### ISSUE TITLE
👑[Enhancement] 解锁锁区/锁偏好游戏的商店页面

### ISSUE THREAD

**Issue by cherinyy** [BeyondDimension/SteamTools#1002]
### 🥰 需求描述(Description)

能够访问锁区/锁偏好游戏的商店页面

### 🧐 解决方案(Solution)

修改 UA 为 `Googlebot/2.1 (+http://www.google.com/bot.html)`
https://keylol.com/t788226-1-1

**Comment by rmbadmin** [comment]
很有用，感谢建议

**Comment by rmbadmin** [comment]
下个版本更新时将支持
