### ISSUE TITLE
🧐[Question] 

### ISSUE THREAD

**Issue by cnbinwang** [BeyondDimension/SteamTools#1003]
### 🧐 问题描述(Description)

已经安装了  dotnet-runtime-6.0.2-win-x64

### 🚑 其他信息(Other Information)

![屏幕截图 2022-02-10 152215](https://user-images.githubusercontent.com/55985430/153358538-a6382b01-b618-43d7-ae29-54765e5d141f.png)

- 程序版本(Program Version):GitHub 2.6.7
- 系统版本号(OS Version):  win11 22000.493
- 是否为应用商店版本(Whether it is a Store version): no

**Comment by AigioL** [comment]
需要安装 ASP.NET Core Runtime 6.0.2
包含以下两项
- .NET Runtime 6.0.2
- ASP.NET Core Runtime 6.0.2

https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.2-windows-x64-installer

**Comment by cnbinwang** [comment]
> Reference

OK
