### ISSUE TITLE
👑[Enhancement] 在网络加速中添加对于电报的支持。

### ISSUE THREAD

**Issue by Fitye** [BeyondDimension/SteamTools#1007]
### 🥰 需求描述(Description)

请问在网络加速中可以添加对于telegram应用的选择么
### 🧐 解决方案(Solution)

辛苦作者惹

**Comment by cherinyy** [comment]
这是不可能的，Telegram 和 Google 是 IP 封禁，无法通过本地反向代理访问这些网站/应用。
