### ISSUE TITLE
🧐[Question] 偶发性出现任务栏图标消失

### ISSUE THREAD

**Issue by Nuit5566** [BeyondDimension/SteamTools#1008]
### 🧐 问题描述(Description)

偶尔会出现任务栏图标消失的情况，软件实际上在运行，重开软件不能解决，重启系统有可能能解决。

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):2.4.12
- 系统版本号(OS Version): Windows 11.22000.493
- 是否为应用商店版本(Whether it is a Store version): no

**Comment by AigioL** [comment]
这个问题应该在当前最新版本 2.6.5~2.6.7 中已修复

**Comment by Nuit5566** [comment]
更新到2.6.7后还是出现消失的情况🤣
