### ISSUE TITLE
🧐[Question] 小白想问一下，程序里反向代理实现直接访问到底是怎么做到的？

### ISSUE THREAD

**Issue by izwb003** [BeyondDimension/SteamTools#1011]
### 🧐 问题描述(Description)

如题，平时的出国旅游工具都很好理解，就是连接到一台能访问这些站点的服务器上，让这些服务器去访问这些站点然后把数据转发回来；
那像Steam++里的反向代理又是什么原理？它是也需要连接到一个外面的服务器上吗？如果不用，那又是怎么做到在本地直接就可以访问到想要的信息的？
而且，为什么采用这种方式就需要信任一个根证书呢？

**Comment by cherinyy** [comment]
根据他人研究，数据跨境安全网关（俗称 GFW）会检测客户端发送至服务器的 TLS 握手请求包中的 SNI 信息。SNI 包含了客户端想要连接的域名，该信息是明文的。因此当数据跨境安全网关检测到相关域名后，会先于服务器返回 RST 包（重置连接），导致连接失败。

因此本地反向代理的目的，是不发送 SNI 信息，或使用其他域名替代（如果服务器不检查 SNI 的话）。
但是这对强制要求 SNI 的网站是无效的，例如 DLsite #907。

**Comment by izwb003** [comment]
> 根据他人研究，数据跨境安全网关（俗称 GFW）会检测客户端发送至服务器的 TLS 握手请求包中的 SNI 信息。SNI 包含了客户端想要连接的域名，该信息是明文的。因此当数据跨境安全网关检测到相关域名后，会先于服务器返回 RST 包（重置连接），导致连接失败。
> 
> 因此本地反向代理的目的，是不发送 SNI 信息，或使用其他域名替代（如果服务器不检查 SNI 的话）。 但是这对强制要求 SNI 的网站是无效的，例如 DLsite #907。

也就是说，Wall的一种拦截方式就是读取明文的SNI并重置连接，而本地反代可以实现删除SNI数据或将其替代，以避免检测？
但仍想请教：
1.为何没听说过用这种方式实现访问Google等站点的？谷歌/FB/推/油管等都是强制要求SNI的吗？
2.为何这样做要信任根证书？是因为代理服务器要充当中间人读取安全连接来修改数据包以改动SNI吗？
3.为何这属于反向代理？是因为像Steam客户端或浏览器这样的程序都是连接到这个本地服务器而相当于未直连到目标服务器吗？

**Comment by cherinyy** [comment]
> > 根据他人研究，数据跨境安全网关（俗称 GFW）会检测客户端发送至服务器的 TLS 握手请求包中的 SNI 信息。SNI 包含了客户端想要连接的域名，该信息是明文的。因此当数据跨境安全网关检测到相关域名后，会先于服务器返回 RST 包（重置连接），导致连接失败。
> > 因此本地反向代理的目的，是不发送 SNI 信息，或使用其他域名替代（如果服务器不检查 SNI 的话）。 但是这对强制要求 SNI 的网站是无效的，例如 DLsite #907。
> 
> 也就是说，Wall的一种拦截方式就是读取明文的SNI并重置连接，而本地反代可以实现删除SNI数据或将其替代，以避免检测？ 但仍想请教： 1.为何没听说过用这种方式实现访问Google等站点的？谷歌/FB/推/油管等都是强制要求SNI的吗？ 2.为何这样做要信任根证书？是因为代理服务器要充当中间人读取安全连接来修改数据包以改动SNI吗？ 3.为何这属于反向代理？是因为像Steam客户端或浏览器这样的程序都是连接到这个本地服务器而相当于未直连到目标服务器吗？

1. 因为它们是被封锁了 IP 地址，IP 地址不可达，而且 Google Chrome 浏览器硬编码了 Google 网站证书，使用非信任的证书可能会出现问题。
2. 我认为跟修改数据包无关，主要是网站本身是 HTTPS 网站，如果本地使用 HTTP 代理 HTTPS 网站，可能会出现媒体文件不可用的情况，因为 HTTP 网站 不能调用 HTTPS 网站上的资源，而 Steam 的媒体文件都是托管于 steamcdn-a.akamaihd.net 等非本域地址。主要受限于浏览器。
3. 正向代理是代理客户端，反向代理是代理服务器。

**Comment by cherinyy** [comment]
没有其他问题的话，建议关闭 issue

**Comment by izwb003** [comment]
> > > 根据他人研究，数据跨境安全网关（俗称 GFW）会检测客户端发送至服务器的 TLS 握手请求包中的 SNI 信息。SNI 包含了客户端想要连接的域名，该信息是明文的。因此当数据跨境安全网关检测到相关域名后，会先于服务器返回 RST 包（重置连接），导致连接失败。
> > > 因此本地反向代理的目的，是不发送 SNI 信息，或使用其他域名替代（如果服务器不检查 SNI 的话）。 但是这对强制要求 SNI 的网站是无效的，例如 DLsite #907。
> > 
> > 
> > 也就是说，Wall的一种拦截方式就是读取明文的SNI并重置连接，而本地反代可以实现删除SNI数据或将其替代，以避免检测？ 但仍想请教： 1.为何没听说过用这种方式实现访问Google等站点的？谷歌/FB/推/油管等都是强制要求SNI的吗？ 2.为何这样做要信任根证书？是因为代理服务器要充当中间人读取安全连接来修改数据包以改动SNI吗？ 3.为何这属于反向代理？是因为像Steam客户端或浏览器这样的程序都是连接到这个本地服务器而相当于未直连到目标服务器吗？
> 
> 1. 因为它们是被封锁了 IP 地址，IP 地址不可达，而且 Google Chrome 浏览器硬编码了 Google 网站证书，使用非信任的证书可能会出现问题。
> 2. 我认为跟修改数据包无关，主要是网站本身是 HTTPS 网站，如果本地使用 HTTP 代理 HTTPS 网站，可能会出现媒体文件不可用的情况，因为 HTTP 网站 不能调用 HTTPS 网站上的资源，而 Steam 的媒体文件都是托管于 steamcdn-a.akamaihd.net 等非本域地址。主要受限于浏览器。
> 3. 正向代理是代理客户端，反向代理是代理服务器。

我还是没能理解第二条。那么证书的作用是什么？

**Comment by cherinyy** [comment]
> 证书的作用是什么？

没有作用，只是对等服务器。

**Comment by izwb003** [comment]
> > 证书的作用是什么？
> 
> 没有作用，只是对等服务器。

那么能否认为：证书的作用就是欺骗浏览器使浏览器认为自己在走正确的https链接，从而保证各种媒体文件等等均可正常传输？

**Comment by cherinyy** [comment]
> 那么能否认为：证书的作用就是欺骗浏览器使浏览器认为自己在走正确的https链接，从而保证各种媒体文件等等均可正常传输？

你可以理解为“欺骗”，但根证书是你自己选择信任后才导入系统/浏览器中的，证书本身没有这个作用。

**Comment by izwb003** [comment]
> > 那么能否认为：证书的作用就是欺骗浏览器使浏览器认为自己在走正确的https链接，从而保证各种媒体文件等等均可正常传输？
> 
> 你可以理解为“欺骗”，但根证书是你自己选择信任后才导入系统/浏览器中的，证书本身没有这个作用。
大概明白了！感谢解答。

**Comment by einsone** [comment]
按上面的说法，对没有封 IP 的网站，只要不发送 SNI ，就能绕过墙吗

**Comment by einsone** [comment]
不发送 SNI
下面的测试代码还是访问不了 steamcommunity.com

```javascript
/* eslint-disable */
const axios = require("axios");
const https = require("https");
const tls = require("tls");
const dns = require("dns");

const httpsAgent = new https.Agent();

function createConnection(port, host, options) {
  if (port !== null && typeof port === 'object') {
    options = port;
  } else if (host !== null && typeof host === 'object') {
    options = { ...host };
  } else if (options === null || typeof options !== 'object') {
    options = {};
  } else {
    options = { ...options };
  }

  if (typeof port === 'number') {
    options.port = port;
  }

  if (typeof host === 'string') {
    options.host = host;
  }

  // 不发送 SNI
  options.server_name = '';
  // 指定解析的 IP
  options.lookup = function(hostname, options, cb) {
    dns.resolve(hostname, function(err, ips) {
      if (err) { return cb(err); }
      console.log(hostname, ips);
      if (hostname === "steamcommunity.com") {
        // ips[0] = "104.104.85.160";
      }
      return cb(null, ips[0], 4);
    }); 
  };

  if (options._agentKey) {
    const session = this._getSession(options._agentKey);
    if (session) {
      debug('reuse session for %j', options._agentKey);
      options = {
        session,
        ...options
      };
    }
  }

  const socket = tls.connect(options);

  if (options._agentKey) {
    // Cache new session for reuse
    socket.on('session', (session) => {
      this._cacheSession(options._agentKey, session);
    });

    // Evict session on error
    socket.once('close', (err) => {
      if (err)
        this._evictSession(options._agentKey);
    });
  }

  return socket;
}

function getCreateConnection() {
  return createConnection;
}

httpsAgent.createConnection = getCreateConnection();

const client = axios.create({
  timeout: 10000,
  httpsAgent,
});

(async function() {
  const url = "https://steamcommunity.com";
  const url2 = "https://httpbin.org/anything";
  try {
    const response = await client.get(url);
    console.log(response.data);
  } catch (e) {
    console.log(e.toString());
  }
})()
```

**Comment by rmbadmin** [comment]
@einsone  你可以抓包检查下数据包sni是否有正确移除，我不确定你使用的方式是否有正常修改生效。

**Comment by einsone** [comment]
1. 代码里这里写错了。改正如下
```javascript
 // 不发送 SNI
  options.servername = '';
```
2. ping steamcommunity.com 找到个可用的 IP。
```bash
PING steamcommunity.com (184.28.13.50) 56(84) bytes of data.
64 bytes from a184-28-13-50.deploy.static.akamaitechnologies.com (184.28.13.50): icmp_seq=1 ttl=54 time=2.30 ms
``` 
修改这里，固定解析到的IP
```javascript
// ips[0] = "184.28.13.50";
```

3. 目前只在这样的情况下成功过： 不发送 SNI，且固定 IP 为 ping 到的 IP（184.28.13.50）

4. 不固定 IP ，每次解析到的 IP 地址不止一种情况（预期情况），但是都请求失败了（全失败，不太应该吧）。
