### ISSUE TITLE
🧐[Question] linux安装包结构问题

### ISSUE THREAD

**Issue by plokid** [BeyondDimension/SteamTools#1017]
### 🧐 问题描述(Description)
请问为什么要把二进制文件放在 /usr/local/bin 目录下，正常来讲所有包管理器安装软件应该放在 /usr 目录下，/usr/local 目录应存放用户自己编译的软件

### 🚑 其他信息(Other Information)
https://blog.csdn.net/aqxin/article/details/48324377

**Comment by AigioL** [comment]
二进制文件应该是在 ```/usr/share/Steam++``` 目录上的

https://github.com/BeyondDimension/SteamTools/blob/develop/src/ST.Tools.Publish/Steam++.desktop

**Comment by plokid** [comment]
但是建立的软链接是在 /usr/local/bin 下的，应该来讲包管理器安装软件不应该安装到 /usr/local 目录下

**Comment by AigioL** [comment]
目前用的是 [dotnet-packaging](https://github.com/quamotion/dotnet-packaging) 这个仓库中的代码进行打包 linux 安装版的

看上去安装目录路径硬编码在 https://github.com/quamotion/dotnet-packaging/blob/master/Packaging.Targets/ArchiveBuilder.cs#L219 上

如果该目录确实不合理，那么应该给这个仓库提交 issue
