### ISSUE TITLE
👑[Enhancement] 希望增加对stackoverflow网站的支持

### ISSUE THREAD

**Issue by GBEYOND0613** [BeyondDimension/SteamTools#1023]
### 🥰 需求描述(Description)

希望增加对stackoverflow网站的支持

原因：访问stackoverflow的速度非常非常慢，有时还不能一次性访问进去，需要跳转，还不一定成功，虽然我找到了用浏览器插件的解决办法，但是steakoverflow网站的一些图片需要访问imgur图床，还需要再打开软件，我希望能集成到一起，让这个软件功能更加强大和方便

### 🧐 解决方案(Solution)

解决方案：替换CDN，我搜索的结果有两种替换方案，一种是换成loli.net（安装插件后感觉访问很快）；另一种是替换成微软的CDN（安装后感觉和第一种差不多）

#### 方案一：cdn 换成 loli.net

这个是我搜到的插件的项目地址：<https://github.com/justjavac/ReplaceGoogleCDN>

原理：将 Google 的 CDN 替换成国内的

#### 方案二：cdn 换成微软cdn

这个是插件的地址：<https://microsoftedge.microsoft.com/addons/detail/%E8%B0%B7%E6%AD%8Ccdn%E4%BA%A4%E6%8D%A2%E5%88%B0%E5%BE%AE%E8%BD%AFcdn/iifjijkgednpbhdbgoopbmikphckgbfj>

这个没找到项目地址

**Comment by rmbadmin** [comment]
下个版本更新时将支持
