### ISSUE TITLE
👑[Enhancement] ASF --encrypt参数

### ISSUE THREAD

**Issue by 1itt1eB0y** [BeyondDimension/SteamTools#1025]
### 🥰 需求描述(Description)
`您正在为 SteamPassword 属性使用 AES 设置，但未提供自定义密钥 --cryptkey。这完全破坏了保护措施，因为 ASF 将使用默认的公开密钥。您应该提供自定义 --cryptkey 参数，来保证此设置提供的安全措施生效。`

### 🧐 解决方案(Solution)

建议添加一个入口用于提供用户自定义的cryptkey值，避免AESkey公开且重复的问题。

**Comment by AigioL** [comment]
https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Command-Line-Arguments-zh-CN#%E5%8F%82%E6%95%B0

可设置环境变量 ASF_CRYPTKEY 自定义值

**Comment by 1itt1eB0y** [comment]
安卓没法加环境变量啊…… :(

**Comment by AigioL** [comment]
![QG3R9_ 8{ PNL 5VBZ95ZM](https://user-images.githubusercontent.com/24450093/155084141-c1b2f2bf-238c-4286-a153-58973c6b102f.png)
已在 ASF 配置 中新增配置项

**Comment by 1itt1eB0y** [comment]
nice大夫！
