### ISSUE TITLE
🐛[BUG] 开启Github.io加速导致名称如“xxx.github.io”的仓库无法操作

### ISSUE THREAD

**Issue by xitieshiz2** [BeyondDimension/SteamTools#1029]
### 🐛 描述(Description)

在软件加速选项卡开启Github.io加速后，会导致所有名称为“xxx.github.io”的github仓库显示为github pages的404界面，同时无法对这个库进行clone/push等操作
关闭Github.io加速，此问题消失
### 📷 复现步骤(Steps to Reproduce)

1. 开启Github.io加速
2. 访问任意名称为“xxx.github.io”的仓库或尝试clone/push
3. 显示github pages 404页面

### 📄 [异常/日志]信息([Exception/Log] Information)
尝试clone/push会显示“The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.”
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.6.7
- 系统版本号(OS Version): Windows 11 22000.527
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/75575551/154811282-a47d4c17-190b-44b7-84ce-f9499cc97305.png)

**Comment by rmbadmin** [comment]
问题与 #952 相同，已热更新修复。
