### ISSUE TITLE
🐛[BUG] manjaro系统无法清除代理

### ISSUE THREAD

**Issue by misaka10843** [BeyondDimension/SteamTools#1046]
### 🐛 描述(Description)

如题，在manjaro系统中，关闭steam++无法清除代理（重启无效），导致不开steam++一些网页会无法加载

并且在更改代理状态时（也就是点击加速/停止加速时）后台输出错误

### 📷 复现步骤(Steps to Reproduce)
1. 开机后打开代理
![image](https://user-images.githubusercontent.com/69132853/154878241-f580ffb4-14d6-4152-8821-13b7fdfd98d0.png)

2. 关闭代理刷新网页
![image](https://user-images.githubusercontent.com/69132853/154878308-e6cd83b1-5cdc-4e71-ba88-a7f3ba772011.png)

### 📄 [异常/日志]信息([Exception/Log] Information)
```bash
(process:9973): dconf-WARNING **: 10:12:01.972: failed to commit changes to dconf: 生成并运行命令行"dbus-launch --autolaunch=596c1ce573b54c828b0762dcf991f249 --binary-syntax --close-stderr"时出错: 子进程已退出, 代码1
```

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.6.7 α for Linux(x64)
- 系统版本号(OS Version):Linux 5.16.7-1-Manjaro
- 是否为应用商店版本(Whether it is a Store version): No

### 🖼 截图(Screenshots)

图1：
![image](https://user-images.githubusercontent.com/69132853/154878241-f580ffb4-14d6-4152-8821-13b7fdfd98d0.png)

图2：
![image](https://user-images.githubusercontent.com/69132853/154878308-e6cd83b1-5cdc-4e71-ba88-a7f3ba772011.png)

图3：
![image](https://user-images.githubusercontent.com/69132853/154878759-81f7195c-47e6-448a-9e48-c09ccf9371fe.png)

**Comment by Mossimos** [comment]
更改代理状态时 启动和关闭 只是命令里面 on 改成 off 去执行了 能正常设置开启 应该关闭也是正常能关闭的
这个日志报错不属于steam++ 的报错 dconf监控的进程ID已经退出了
设置打开logs文件夹看看Steam++自己写的日志

`程序是使用 gsettings 来设置和关闭系统代理的`
gsettings set org.gnome.system.proxy mode 'none'
这个是关闭加速使用的代码你可以自己执行一下看看是否能关闭 能关闭应该是没问题才对 可能是浏览器未断开代理需要重新打开

**Comment by Mossimos** [comment]
可能和不同的系统环境有关也试试
kwriteconfig --file kioslaverc --group 'Proxy Settings' --key Authmode 0
确定哪个命令能关闭代理 可能还有更多的系统环境命令不同

**Comment by z-g-h** [comment]
我获得了相同的错误，archlinux kde桌面，请问现在有您问题解决了吗
