### ISSUE TITLE
🧐[Question] Windows商店版本似乎已下架？

### ISSUE THREAD

**Issue by arenekosreal** [BeyondDimension/SteamTools#1060]
### 🧐 问题描述(Description)
README 给出的 Windows 商店版本[地址](https://www.microsoft.com/store/apps/9MTCFHS560NG)打开后提示无法找到页面
不知道是否为开发团队意料之中的情况

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):N/A
- 系统版本号(OS Version): N/A
- 是否为应用商店版本(Whether it is a Store version): 是

**Comment by AigioL** [comment]
因使用个人账号上架企业应用，被下架了

![FireShot Capture 036 - Steam++ - Review Results - partner microsoft com](https://user-images.githubusercontent.com/24450093/156559043-10545bf4-b417-4d4d-9258-0d9d00916e96.png)

https://docs.microsoft.com/zh-cn/windows/uwp/publish/store-policies#1014-account-type

目前重新注册企业账号发布，在审核中，这部分微软委托第三方机构进行的，且这个第三方机构目前来看效率不高，发工单也问过，支持人员说是帮忙催，但是并没有效果。

![9Q8G05L~9563_ G3HP%) 5](https://user-images.githubusercontent.com/24450093/156559743-1408c7df-6c7e-4ee6-a002-73842cbb2166.png)

后续上架会使用新的 包 ID，包括 URL 地址也需要更换
