### ISSUE TITLE
Artstation 网站无法加速🐛[BUG] 

### ISSUE THREAD

**Issue by ZFT566588** [BeyondDimension/SteamTools#1087]
### 🐛 描述(Description)

Artstation 网站无法加速

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by rmbadmin** [comment]
已热更新修复
