### ISSUE TITLE
🧐[Question] 在linux下使用加速steam出现Invalid SSL Certificate

### ISSUE THREAD

**Issue by ZavierYan** [BeyondDimension/SteamTools#1094]
### 🧐 问题描述(Description)

我在使用arch linux，已经手动在浏览器中安装了证书。
使用加速功能时，无论是host代理模式还是系统代理模式，
进入steam的页面都会报Invalid SSL Certificate

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):2.6.9-2(arch linux user repositry）
- 系统版本号(OS Version): Arch Linux x86_64, 内核: 5.16.12-arch1-1 
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by Mossimos** [comment]
确定是安装到 受信任的颁发机构  且勾选了信任选项吗
也可以尝试将证书导入到 系统根证书
cat xxx.crt >> /etc/pki/tls/certs/ca-bundle.crt
另外确保使用的 chromium 内核的浏览器  因为Steam也是 chromium 内核

**Comment by ZavierYan** [comment]
> 确定是安装到 受信任的颁发机构 且勾选了信任选项吗 也可以尝试将证书导入到 系统根证书 cat xxx.crt >> /etc/pki/tls/certs/ca-bundle.crt 另外确保使用的 chromium 内核的浏览器 因为Steam也是 chromium 内核

我在所有的浏览器都安装了证书，勾选了所有选项。
`cat xxx.crt >> /etc/pki/tls/certs/ca-bundle.crt`这个文件我没有,
我参考了[这个页面](https://wiki.archlinux.org/title/User:Grawity/Adding_a_trusted_CA_certificate#System-wide_%E2%80%93_Arch,_Fedora_(p11-kit))，使用`sudo trust anchor --store xxx.pem`添加了证书，然后仍然有问题。
Chromium浏览器截图：
![Screenshot_20220307_134227](https://user-images.githubusercontent.com/23065733/156975482-7b2eae60-a4fa-49a7-8b6e-219f2775be6c.png)
![Screenshot_20220307_135933](https://user-images.githubusercontent.com/23065733/156976523-9fd40f5a-626b-463b-83fa-b4384da1ea80.png)

**Comment by rmbadmin** [comment]
> > 确定是安装到 受信任的颁发机构 且勾选了信任选项吗 也可以尝试将证书导入到 系统根证书 cat xxx.crt >> /etc/pki/tls/certs/ca-bundle.crt 另外确保使用的 chromium 内核的浏览器 因为Steam也是 chromium 内核
> 
> 我在所有的浏览器都安装了证书，勾选了所有选项。 `cat xxx.crt >> /etc/pki/tls/certs/ca-bundle.crt`这个文件我没有, 我参考了[这个页面](https://wiki.archlinux.org/title/User:Grawity/Adding_a_trusted_CA_certificate#System-wide_%E2%80%93_Arch,_Fedora_(p11-kit))，使用`sudo trust anchor --store xxx.pem`添加了证书，然后仍然有问题。 Chromium浏览器截图： ![Screenshot_20220307_134227](https://user-images.githubusercontent.com/23065733/156975482-7b2eae60-a4fa-49a7-8b6e-219f2775be6c.png) ![Screenshot_20220307_135933](https://user-images.githubusercontent.com/23065733/156976523-9fd40f5a-626b-463b-83fa-b4384da1ea80.png)

检查一下信任的证书的指纹与steam++ appdata内证书的指纹是否一致

**Comment by ginhton** [comment]
下载最新版，然后导入最新版里面的证书就可以了。

**Comment by ZavierYan** [comment]
> 下载最新版，然后导入最新版里面的证书就可以了。

![Screenshot_20220308_122255](https://user-images.githubusercontent.com/23065733/157165878-1a16ef6f-25a0-42ce-8b70-6246acfef7de.png)

我换了github上的2.6.9的版本，还是有一样的问题，信任的证书的指纹与.cer文件是一致的

**Comment by Mossimos** [comment]
要么你试试删了证书然后重新生成一个导入
cat xxx.crt >> /etc/pki/tls/certs/ca-bundle.crt
这个 xxx.crt 是指的
打开 Steam++ > 设置 > 通用设置 > 打开 AppData 文件夹 可以在目录中看见 SteamTools.Certificate 的 cer 或 pfx 格式 的证书 选 cer 的就行

你试试 手动在浏览器设置  隐私与安全 管理证书  切换到授权机构 点击导入 然后选择 AppData 中的 证书文件导入 且在 弹窗中 勾选信任 后再试

**Comment by Mossimos** [comment]
此页面 应该在第一次加速会弹出 才对
https://steampp.net/liunxSetupCer

**Comment by ZavierYan** [comment]
> 要么你试试删了证书然后重新生成一个导入 cat xxx.crt >> /etc/pki/tls/certs/ca-bundle.crt 这个 xxx.crt 是指的 打开 Steam++ > 设置 > 通用设置 > 打开 AppData 文件夹 可以在目录中看见 SteamTools.Certificate 的 cer 或 pfx 格式 的证书 选 cer 的就行
> 
> 你试试 手动在浏览器设置 隐私与安全 管理证书 切换到授权机构 点击导入 然后选择 AppData 中的 证书文件导入 且在 弹窗中 勾选信任 后再试

我没有`/etc/pki/tls/certs/ca-bundle.cr`这个文件，可能这个发行版管理证书的软件不太一样吧，所以我参考了 [arch wiki 上的方法](https://wiki.archlinux.org/title/User:Grawity/Adding_a_trusted_CA_certificate#System-wide_%E2%80%93_Arch,_Fedora_(p11-kit))用`sudo trust anchor --store xxx.crt`添加，不过我不太确定是否是等价的。


> 此页面 应该在第一次加速会弹出 才对 https://steampp.net/liunxSetupCer

然后我就是照着这个页面的步骤做的，`打开 AppData 文件夹`打开的是`~/.local/share/Steam++`目录，
里面没有.pem文件，我把.cer文件转成.pem文件导入，前面那个截图就是该目录下的.cer文件和导入的.pem文件的指纹，是一致的。我把steam++换成2.6.9后把这个目录删了然后重新生成了，所以也不是残留的旧文件。

**Comment by Mossimos** [comment]
证书导入并不需要转换格式啊  cer  是能直接导入浏览器 和 系统使用的

**Comment by ZavierYan** [comment]
> 证书导入并不需要转换格式啊 cer 是能直接导入浏览器 和 系统使用的

这个，chromium导入默认过滤只显示.pem文件的，我没注意可以换。。
不过我感觉不是这个问题，导入的证书的指纹和.cer证书文件的指纹是一样的，
而且我刚试了导入.cer格式的证书，并没有解决问题

**Comment by Mossimos** [comment]
我确定刚刚装的是可以正常用的啊 gsettings 也是正常设置了 
系统都只装了
pacstrap -i /mnt base base-devel linux linux-firmware
sudo pacman -S xorg xorg-server
sudo pacman -S sddm sddm-kcm
sudo pacman -S plasma kde-applications
sudo pacman -S chromium
导入证书是 导入的目录下的 cer 文件 （从下拉框选全部文件就行） 然后弹窗的提示 3个够都勾上
![image](https://user-images.githubusercontent.com/26396340/158025741-e2e536ff-fdea-4cad-9289-751e3b3097c8.png)
![image](https://user-images.githubusercontent.com/26396340/158025771-5127d61f-1a8d-4ee1-966d-cd84ad29da17.png)

**Comment by ZavierYan** [comment]
我目前导入的就是.cer文件，仍有问题
我因为权限的原因在以root身份启动，请问是不是和这个有关呢

**Comment by Mossimos** [comment]
应该没问题 能否找个时间远程下看看具体到底啥问题呢 我多次删除重新生成都是好好的

唯一知道可能有问题的是非root用户 多用户登录桌面环境执行可能 我多次实验后发现 可能和 桌面环境登录多用户有关

gsettings get org.gnome.system.proxy.http host
gsettings get org.gnome.system.proxy.http port
gsettings get org.gnome.system.proxy.https host
gsettings get org.gnome.system.proxy.https port
gsettings get org.gnome.system.proxy mode
和
sudo gsettings get org.gnome.system.proxy.http host
sudo gsettings get org.gnome.system.proxy.http port
sudo gsettings get org.gnome.system.proxy.https host
sudo gsettings get org.gnome.system.proxy.https port
sudo gsettings get org.gnome.system.proxy mode
这命令获取不一致

**Comment by ZavierYan** [comment]
可以，我最近都有时间，要如何操作呢

**Comment by Mossimos** [comment]
加下qq 或者 tg 下个远控软件 anydesk todesk 都行
qq 1798505630

**Comment by Mossimos** [comment]
一直没加是 证书问题解决了吗 ？

**Comment by Rougnt** [comment]
ubuntu同样出现这个问题，该问题并非在浏览器中，而是在steam客户端内提示Invalid SSL Certificate。我已经将cer证书转换成crt并添加到了/usr/local/share/ca-certificates/中，在steam客户端内依旧如此提示

**Comment by rmbadmin** [comment]
> ubuntu同样出现这个问题，该问题并非在浏览器中，而是在steam客户端内提示Invalid SSL Certificate。我已经将cer证书转换成crt并添加到了/usr/local/share/ca-certificates/中，在steam客户端内依旧如此提示

steam在linux中使用的依然是 chromium 内核，所以证书也是独自信任，你可以下载个chrome在chrome中导入信任steam++证书即可在steam的chromium中也生效
