### ISSUE TITLE
🐛[BUG] 🧐[Question] 家庭共享库管理不显示内容，一直为空

### ISSUE THREAD

**Issue by NaiZhiTuDu** [BeyondDimension/SteamTools#1096]
### 🧐 问题描述(Description)
一直正常使用，前段时间想更改共享库顺序时发现无法显示共享库的内容，已经尝试过卸载安装steam++，尝试过加速器，尝试过科学上网，均无法解决

![image](https://user-images.githubusercontent.com/51805661/156922616-c7ab2e27-b7f7-40ba-b21c-b218226f297b.png)

- 程序版本(Program Version):x64 v2.6.7
- 系统版本号(OS Version): Windows 10  19044.1526
- 是否为应用商店版本(Whether it is a Store version): no

**Comment by AigioL** [comment]
更新到 2.6.9 后还能复现吗？

**Comment by NaiZhiTuDu** [comment]
> 更新到2.6.9后能复现吗？

可以了，没有发现有更新，更新后恢复正常
