### ISSUE TITLE
🧐[Question] V2.6.9 一键切换账号功能总是需要重新输入密码和令牌

### ISSUE THREAD

**Issue by wsxyjy** [BeyondDimension/SteamTools#1130]
### 🚑 其他信息(Other Information)

- 程序版本(Program Version):2.6.9
- 系统版本号(OS Version):  Windows 11 21H2 22000.556
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by rmbadmin** [comment]
其实官网是有解答这个问题的
https://steampp.net/faq#ChangeAccount

具体来说就是记住登陆状态失效了，可能与你在其它区域登录过有关，解决方法是下线所有设备重新记住密码登录。
