### ISSUE TITLE
🧐[Question] Firefox浏览出现错误SEC_ERROR_UNKNOWN_ISSUER

### ISSUE THREAD

**Issue by Meatysoda** [BeyondDimension/SteamTools#1133]
### 🧐 问题描述(Description)

启用网络加速后（hosts模式），Firefox在浏览被加速的网页时，总是提示警告：面临潜在的安全风险。接受风险并继续进入网站的话JavaScript等资源不会加载。

Edge浏览器就没有这个问题。我卸载重装了一下证书，问题没有解决。请问是我哪里设置没对吗😂

警告内容：
```
可能有人试图冒充该网站，您不应该继续访问。
 
各个网站通过证书证明自己的身份。Nightly 不信任 steamcommunity.com，因其证书颁发者未知、证书为自签名的，或者服务器未发送正确的中间证书。
 
错误代码：SEC_ERROR_UNKNOWN_ISSUER
```
### 🚑 其他信息(Other Information)

错误代码内容点开后：
```
https://steamcommunity.com/

对等端的证书颁发者不受认可。

HTTP 严格传输安全（HSTS）：false
HTTP 公钥固定：false

证书链：

-----BEGIN CERTIFICATE-----
//
-----END CERTIFICATE-----
```

- 程序版本(Program Version): Windows 11 家庭中文版
- 系统版本号(OS Version): 21H2 22000.556
- 是否为应用商店版本(Whether it is a Store version): 是(Yes)
- Firefox版本：Firefox nightly 100.0a1 & Firefox 98.0

**Comment by rmbadmin** [comment]
https://steampp.net/faq#CommunityAccelerate
