### ISSUE TITLE
🧐[Question] Steam++无法使用，提示重置Hosts文件或编辑Hosts文件并删除多余的Mark，怎么删除多余的Mark

### ISSUE THREAD

**Issue by kuu-an** [BeyondDimension/SteamTools#1145]
### 🚑 其他信息(Other Information)

- 程序版本(Program Version):2.6.9
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by kuu-an** [comment]
怎么问题描述没了……这里补充下

**Comment by kuu-an** [comment]
提示“操作Hosts错误Mark出现多个[#Steam++Start]，请尝试重置Hosts文件或编辑Hosts文件并删除多余的Mark后再尝试一次”
系统版本号是 Win10 专业版 19043.1526

**Comment by rmbadmin** [comment]
记事本打开hosts文件检查内容是否出现重复的#Steam++Start去掉即可，如果看不懂可以直接清空重置hosts内容

**Comment by kuu-an** [comment]
找到解决办法了，原来删掉hosts文件里重复部分的steam++内容就可以，一开始没看懂删除多余的mark是什么意思
