### ISSUE TITLE
在M1的Mac上锁屏后界面消失🐛[BUG] 

### ISSUE THREAD

**Issue by LemonCANDY42** [BeyondDimension/SteamTools#1155]
### 🐛 描述(Description)

在M1的Mac上锁屏后界面消失，关闭后重开依然如此

### 📷 复现步骤(Steps to Reproduce)

1. 并没发现什么触发规律，大概率锁屏后触发
2. 关闭后也会触发

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.6.9
- 系统版本号(OS Version): <--macOS Monterey 12 -->
- 是否为应用商店版本(Whether it is a Store version): <--是(Yes)-->

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/43240832/159192597-0bbbbf3d-c136-4a5c-8e3e-9d028928c742.png)

**Comment by Mossimos** [comment]
你可用在系统托盘找到程序 点击一个菜单打开主界面
我这只要没关闭主程序锁屏不会找不到的 点下面托盘如果窗口已经关闭了是不会再次打开的 暂时只能从系统托盘打开窗口
![image](https://user-images.githubusercontent.com/26396340/159214170-0f1322e4-f0a0-4142-850e-5cc36f41ab70.png)

**Comment by LemonCANDY42** [comment]
thx!果然可以，不过还是希望添加一下swiftui的开发计划，这样性能和效果应该还会有很大的提升~

**Comment by AigioL** [comment]
目前受限于技术以及资金的支持，不太可能使用 Swift UI 重写，性能的提升只能等 UI 框架后续使用 Metal 代替 OpenGL 才能有明显提升

且像 Swift UI 缺少 Xamarin 的官方支持，参考
https://github.com/xamarin/xamarin-macios/issues/6235
https://github.com/chkn/Xamarin.SwiftUI
