### ISSUE TITLE
🧐[Question] 更新2.6.9之后加速无效

### ISSUE THREAD

**Issue by BDLKL** [BeyondDimension/SteamTools#1159]
### 🧐 问题描述(Description)

之前的版本一直可以加速 但是在前两天更新了2.6.9之后怎么加速都没效果 好友也一直连不上 STEAM商店一直-324

[nlog-all-2022-03-22.0.log](https://github.com/BeyondDimension/SteamTools/files/8329513/nlog-all-2022-03-22.0.log)

[nlog-all-2022-03-22.log](https://github.com/BeyondDimension/SteamTools/files/8329500/nlog-all-2022-03-22.log)

[nlog-all-2022-03-23.log](https://github.com/BeyondDimension/SteamTools/files/8329498/nlog-all-2022-03-23.log)

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):2.6.9
- 系统版本号(OS Version):  WIN10  19044.1586
- 是否为应用商店版本(Whether it is a Store version): NO

**Comment by rmbadmin** [comment]
请详细描述问题和贴出日志，否则问题不予处理

**Comment by BDLKL** [comment]
> 请详细描述问题并贴出日志，否则问题不予处理

我更新了几个 这个应该是日志文件吧

**Comment by rmbadmin** [comment]
> > 请详细描述问题并贴出日志，否则问题不予处理
> 
> 我更新了几个 这个应该是日志文件吧

看了，代理设置中，修改下DNS应该可以解决

**Comment by BDLKL** [comment]
> > > 请详细描述问题并贴出日志，否则问题不予处理
> > 
> > 
> > 我更新了几个 这个应该是日志文件吧
> 
> 看了，代理设置中，修改下DNS应该可以解决

感谢 修改DNS之后可以了
