### ISSUE TITLE
🧐[Question] 加速提示324错误

### ISSUE THREAD

**Issue by ghost** [BeyondDimension/SteamTools#1160]
### 🧐 问题描述(Description)
使用 Hosts 模式加速后打开 Steam 等被加速的网站会提示 `ERR_EMPTY_RESPONSE (324)`

### 🚑 其他信息(Other Information)

[日志](https://reechee.lanzouv.com/iJAj001wdz6d)

![](https://s2.loli.net/2022/03/23/qn15EiuLdG6kfPm.png)

![](https://s2.loli.net/2022/03/23/lnkv8JwSQDfL4mh.png)

- 程序版本(Program Version): 2.6.9
- 系统版本号(OS Version):  Windows 11 21H2 22000.556
- 是否为应用商店版本(Whether it is a Store version):  No

**Comment by rmbadmin** [comment]
是否启用了程序加速仅启用脚本功能或者是二级代理开关？

**Comment by ghost** [comment]
Solved，有个程序开了全局代理的锅（……
