### ISSUE TITLE
🐛[BUG] 确认交易一直是没法获取  试了加速器 host 飞机 全局飞机  都是一样的

### ISSUE THREAD

**Issue by SamleTT** [BeyondDimension/SteamTools#1161]
如题

**Comment by rmbadmin** [comment]
请给出详细错误截图和错误信息

**Comment by SamleTT** [comment]
> 

重启之后开全局飞机就好了   没搞懂什么原因   不过软件内的加速好像是没用的

**Comment by rmbadmin** [comment]
> > 
> 
> 重启之后开全局飞机就好了 没搞懂什么原因 不过软件内的加速好像是没用的

软件内的加速与全局飞机同时使用可能会有问题，建议平时只需要开一个就行
