### ISSUE TITLE
👑[Enhancement] 停止软件后移除证书

### ISSUE THREAD

**Issue by simon300000** [BeyondDimension/SteamTools#1162]
### 🥰 需求描述(Description)
软件关闭之后证书似乎依旧是信任状态，这会不会导致一些安全问题？

### 🧐 解决方案(Solution)
提供一个设置，在停止加速的时候关闭/移除证书

**Comment by rmbadmin** [comment]
你可以手动移除，在加速功能里有移除和安装证书选项，至于安全问题，证书在每个设备上都是随机生成，只要你设备信任后的证书文件不泄露给别人就没什么问题。

**Comment by simon300000** [comment]
谢谢
