### ISSUE TITLE
🐛[BUG] windows 8 无法进入Steam++

### ISSUE THREAD

**Issue by LiJunzhen2021** [BeyondDimension/SteamTools#1170]
windows 8 无法进入Steam++

**Comment by rmbadmin** [comment]
⛔ 不受支持的操作系统
Windows 8
[由于微软官方对该产品的支持已结束](https://docs.microsoft.com/zh-cn/lifecycle/products/windows-8)，故本程序无法在此操作系统上运行，[建议升级到 Windows 8.1](https://support.microsoft.com/zh-cn/windows/%E4%BB%8E-windows-8-%E6%9B%B4%E6%96%B0%E5%88%B0-windows-8-1-17fc54a7-a465-6b5a-c1a0-34140afd0669)

**Comment by LiJunzhen2021** [comment]
我不要升级

**Comment by rmbadmin** [comment]
> 我不要升级

那么我们也没有办法，这个问题是取决于微软停止了 .NET 6 在 Windows 8 上的支持。
