### ISSUE TITLE
👑[Enhancement] 加入Microsoft OneDrive加速！！！

### ISSUE THREAD

**Issue by crrashh1542** [BeyondDimension/SteamTools#1171]
### 🥰 需求描述(Description)
国内访问OneDrive网页的话一直转圈进不去......

**Comment by Ra2-IFV** [comment]
![图片](https://user-images.githubusercontent.com/96299096/164125034-f35c2c7a-a7d6-47b1-8383-b16f6b4f9e39.png)
加了

**Comment by crrashh1542** [comment]
![image](https://user-images.githubusercontent.com/33298711/164885547-c89965c3-1a79-4e30-b79e-77ea2c6c3b06.png)

嗯...根本没有用！

**Comment by Ra2-IFV** [comment]
> 嗯...根本没有用！

墙的手段估计上升到Steam++解决不了的地步了...

**Comment by rmbadmin** [comment]
还没更新呢
下个版本更新后会修复
