### ISSUE TITLE
建议增加单独的反代工具👑[Enhancement] 

### ISSUE THREAD

**Issue by Adufun** [BeyondDimension/SteamTools#1173]
### 🥰 需求描述(Description)

建议增加只有反代功能的工具，类似于steamcommunity_302那种，对于喜欢简洁和用不到其他功能的人会很友好。

**Comment by rmbadmin** [comment]
其实如果只有这种需求直接使用steamcommunity_302或者caddy或者nginx自己搭建也行，
steam++不会考虑单独出这种服务，
但后续可能会考虑将所有功能模块化，可以支持移除其它不使用的功能。
