### ISSUE TITLE
🧐[Question] 

### ISSUE THREAD

**Issue by XTsat** [BeyondDimension/SteamTools#1181]
### 🧐 问题描述(Description)

解除 Steam 商店的访问限制怎么没有了

- 程序版本(Program Version):2.6.9
- 系统版本号(OS Version): 
版本	Windows 11 专业版
版本	21H2
安装日期	‎2022/‎2/‎13
操作系统版本	22000.556
体验	Windows 功能体验包 1000.22000.556.0
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by rmbadmin** [comment]
已恢复，刷新下就有了

**Comment by XTsat** [comment]
看到了，谢谢，这个功能感觉还挺方便的，虽然不能入库，但不用换号就能直接进访问限制的游戏还是很方便的

https://github.com/XTsat/SteamTools-Guide
