### ISSUE TITLE
🐛[BUG] window10 HOSTS模式请取消 启动[SteamTools] 加速时占用80端口的设定啊

### ISSUE THREAD

**Issue by gdf159159** [BeyondDimension/SteamTools#1186]
window10 HOSTS模式请取消 启动[SteamTools] 加速时占用80端口的设定啊

[SteamTools] HOSTS模式实际并不需要80端口  
就需要先停止[SteamTools] 加速  先启动apache后在 重新启动[SteamTools] 加速 

所以请取消 启动[SteamTools] 加速时占用80端口的设定啊

**Comment by rmbadmin** [comment]
占用80端口是有用的，目的就是转发普通的http请求到https上，大多数小白用户经常会去开http的链接。

但并不强制，目前的逻辑是80端口如果已经被占用 则放弃监听80端口，如果实在不需要，会考虑在设置中加个选项取消80端口监听。

**Comment by gdf159159** [comment]
添加设置是个好办法
