### ISSUE TITLE
🐛[BUG] win10 打开steam++，报没有安装.NET，已经download并安装好还是不行

### ISSUE THREAD

**Issue by tikaautoman** [BeyondDimension/SteamTools#1188]
### 🐛 描述(Description)

BUG如题，参考下图所示
### 📷 复现步骤(Steps to Reproduce)
![图片](https://user-images.githubusercontent.com/26813034/161170552-913f643c-7904-4c47-b2b9-c4d4e93b97da.png)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): 

### 🖼 截图(Screenshots)
![图片](https://user-images.githubusercontent.com/26813034/161170552-913f643c-7904-4c47-b2b9-c4d4e93b97da.png)

**Comment by AigioL** [comment]
需要安装 [ASP.NET Core 运行时 6.0.3](https://dotnet.microsoft.com/zh-cn/download/dotnet/6.0) 
是 《ASP.NET Core 运行时》 而不是 《.NET 桌面运行时》

**Comment by tikaautoman** [comment]
thx，我重新下载了压缩版的就可以用了，安装版的才会报没安装，我是按照download弹出的页面去下载的，2个x64的都装了，可能还是不对还是怎么回事就不是很清楚




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BeyondDimension/SteamTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月1日(星期五) 上午10:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BeyondDimension/SteamTools] 🐛[BUG] win10 打开steam++，报没有安装.NET，已经download并安装好还是不行 (Issue #1188)





 
需要安装 ASP.NET Core 运行时 6.0.3
 是 《ASP.NET Core 运行时》 而不是 《.NET 桌面运行时》

**Comment by rmbadmin** [comment]
你需要搞清楚自己是否需要使用FDE版本，只有FDE版本是需要自己安装运行环境的。

**Comment by tikaautoman** [comment]
ok,very thx your guide.然后我还有个疑问请教下，如果我用阿根廷账号登录的话steam++能支持加速不同服务器的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BeyondDimension/SteamTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月1日(星期五) 下午4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BeyondDimension/SteamTools] 🐛[BUG] win10 打开steam++，报没有安装.NET，已经download并安装好还是不行 (Issue #1188)





 
你需要搞清楚自己是否需要使用FDE版本，只有FDE版本是需要自己安装运行环境的。

**Comment by AigioL** [comment]
> ok,very thx your guide.然后我还有个疑问请教下，如果我用阿根廷账号登录的话steam++能支持加速不同服务器的吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "BeyondDimension/SteamTools" ***@***.***&gt;; 发送时间:&nbsp;2022年4月1日(星期五) 下午4:55 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [BeyondDimension/SteamTools] 🐛[BUG] win10 打开steam++，报没有安装.NET，已经download并安装好还是不行 (Issue #1188) 你需要搞清楚自己是否需要使用FDE版本，只有FDE版本是需要自己安装运行环境的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

**不支持**

**Comment by tikaautoman** [comment]
Got it. Thx




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BeyondDimension/SteamTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月6日(星期三) 中午1:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BeyondDimension/SteamTools] 🐛[BUG] win10 打开steam++，报没有安装.NET，已经download并安装好还是不行 (Issue #1188)





  
ok,very thx your guide.然后我还有个疑问请教下，如果我用阿根廷账号登录的话steam++能支持加速不同服务器的吗？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "BeyondDimension/SteamTools" @.&gt;; 发送时间:&nbsp;2022年4月1日(星期五) 下午4:55 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [BeyondDimension/SteamTools] 🐛[BUG] win10 打开steam++，报没有安装.NET，已经download并安装好还是不行 (Issue #1188) 你需要搞清楚自己是否需要使用FDE版本，只有FDE版本是需要自己安装运行环境的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
不支持

**Comment by cxh2959540834** [comment]
> ### 🐛 描述(Description)
> BUG如题，参考下图所示
> 
> ### 📷 复现步骤(Steps to Reproduce)
> ![图片](https://user-images.githubusercontent.com/26813034/161170552-913f643c-7904-4c47-b2b9-c4d4e93b97da.png)
> 
> 
> ### 📄 [异常/日志]信息([Exception/Log] Information)
> ### 🚑 基本信息(Basic Information)
> * 程序版本(Program Version):
> * 系统版本号(OS Version):
> * 是否为应用商店版本(Whether it is a Store version):
> 
> ### 🖼 截图(Screenshots)
> ![图片](https://user-images.githubusercontent.com/26813034/161170552-913f643c-7904-4c47-b2b9-c4d4e93b97da.png)
我也是这样，楼主最后咋解决的呀，我按照弹出的下载了都，还是没解决，我也是压缩版
