### ISSUE TITLE
👑[Enhancement] 增加启动后自动加速功能

### ISSUE THREAD

**Issue by Nightingale0504** [BeyondDimension/SteamTools#1191]
### 🥰 需求描述(Description)
可以设置在软件启动后自动开启加速功能，这样可以避免打开软件还要再点一次的麻烦，配合启动时最小化为图标最佳
### 🧐 解决方案(Solution)
增加一个设置选项，勾选后设置在软件启动后自动开启加速功能，这样可以避免打开软件还要再点一次的麻烦，配合启动时最小化为图标最佳
### 🚑 其他信息(Other Information)
无

**Comment by rmbadmin** [comment]
目前代理设置里是有此功能的

**Comment by Nightingale0504** [comment]
谢谢提示，找到了
