### ISSUE TITLE
🧐[Question] steam++使用hosts代理加速失败

### ISSUE THREAD

**Issue by nxz999** [BeyondDimension/SteamTools#1192]
### 🧐 问题描述(Description)

使用hosts代理加速，提示“操作Hosts 错误读取或还原文件时失败，因被其他进程占用，可能是其他不兼容的网络加速程序，请找到占用的进程将其关闭。”我根据官网的帮助通过资源监视器查找"hosts"的关联句柄，但只找到了一个叫“sihost”的程序，结束进程后，仍然提示被占用。求解。

### 🚑 其他信息(Other Information)

![1648727669(1)](https://user-images.githubusercontent.com/102858704/161380754-3d41fc48-c933-46c6-821b-24984d628792.jpg)
![P2XC)03@A55HO2% 4)E~FGA](https://user-images.githubusercontent.com/102858704/161380792-9b93cfee-422c-4ed3-8314-c885010eb546.png)
[nlog-all-2022-04-02.log](https://github.com/BeyondDimension/SteamTools/files/8402404/nlog-all-2022-04-02.log)

- 程序版本(Program Version):x64 v2.6.9
- 系统版本号(OS Version):  Windows 10.19044.1586 
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by rmbadmin** [comment]
请详细描述问题和提供日志

**Comment by nxz999** [comment]
> 请详细描述问题和提供日志

已经添加了

**Comment by rmbadmin** [comment]
日志抛出的异常是The process cannot access the file 'C:\WINDOWS\system32\drivers\etc\hosts' because it is being used by another process.  你实在无法确认是什么程序占用的话，
你可以考虑使用文件解除占用工具强行解除占用或直接尝试自行粉碎删除hosts文件。

**Comment by nxz999** [comment]
> 

好的，谢谢

**Comment by nxz999** [comment]
> 日志抛出的异常是The process cannot access the file 'C:\WINDOWS\system32\drivers\etc\hosts' because it is being used by another process. 你实在无法确认是什么程序占用的话， 你可以考虑使用文件解除占用工具强行解除占用或直接尝试自行粉碎删除hosts文件。

解决了 ，谢谢
