### ISSUE TITLE
🐛[BUG] 网络加速显示异常

### ISSUE THREAD

**Issue by guanjc** [BeyondDimension/SteamTools#1197]
### 🐛 描述(Description)

进入程序后默认是在网络加速界面的，这时候切到其他界面，再切回网络加速，就会出现一堆乱码，希望修复一下。谢谢！
### 📷 复现步骤(Steps to Reproduce)

1. 进入程序，默认为网络加速
2. 切到其他界面
3. 再次返回网络加速界面，就显示了一堆乱码

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.6.9
- 系统版本号(OS Version): Windows 1000.22000.593.0
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)

![Uploading Snipaste_2022-04-04_18-51-17.png…](第1步截图)
![Uploading Snipaste_2022-04-04_18-51-37.png…](第2步截图)
![Uploading Snipaste_2022-04-04_18-51-47.png…](第3步截图)

**Comment by rmbadmin** [comment]
下个版本发布时将会修复
