### ISSUE TITLE
Discord能否支持Support支持页面和Discord支持的Gif网页tenor.com

### ISSUE THREAD

**Issue by RainWill** [BeyondDimension/SteamTools#1224]
我记得之前有一段时间discord加速里多了一个support网页可以加速，但是我当时没用，发现之后几天又下架了，有时候需要support的时候还是比较麻烦，希望恢复支持，还有能否支持加速一下tenor.com，discord的gif表情什么的都在这里，如果不开加速器的话看这些gif都是转圈圈或者加载失败什么的，对于我这些discord重度患者希望还是支持一下，谢谢！

**Comment by AigioL** [comment]
support 的子域名还没适配完成，tenor.com 已被 Google 收购，目前的加速原理上支持不了
