### ISSUE TITLE
Android 证书不信任

### ISSUE THREAD

**Issue by TPAXcc** [BeyondDimension/SteamTools#1225]
LMG710 Android 10 Ver.2.7.0-pre3

把证书删了又重装，就是不信任。是不是要把包也重装一遍才行?

**Comment by AigioL** [comment]
可以在安全设置中清除用户凭证后重新导入一次再试

**Comment by WDNMD957** [comment]
我也是试了好几次都是证书不信任。手机网页可以看，但是chromeos上的chrome就显示证书错误，而且点击高级之后没有继续访问的选项

**Comment by AigioL** [comment]
> 我也是试了好几次都是证书不信任。手机网页可以看，但是chromeos上的chrome就显示证书错误，而且点击高级之后没有继续访问的选项

Chrome OS 上运行 Android 版吗？应该可以直接运行 Linux 版的，可能需要将证书文件导出，并且导入到桌面端上的 Chrome 设置中，可参考 https://steampp.net/liunxSetupCer

**Comment by WDNMD957** [comment]
> 

非常感谢  已经可以访问了     就是速度有点慢
😅

**Comment by TPAXcc** [comment]
@AigioL 我都试过了，还是没用啊

**Comment by TPAXcc** [comment]
难道我得清一遍数据才能用吗

**Comment by AigioL** [comment]
有一些资料显示在 Android 7+ 上 App 不信任用户导入的 CA 证书，这个只能通过 root 后强行导入，或者使用 adb 工具或 Magisk 这类的工具软件将证书导入到系统目录上
https://luoshuijs.vip/install-the-certificate-above-android-7.html
https://www.cnblogs.com/Entr0py/p/9675061.html
https://github.com/XndroidDev/Xndroid/issues/9

但浏览器应该是会信任用户的 CA 证书，例如 Chrome/Edge，其他浏览器未测试
目前在 Android 9 中使用 Edge 与 Android 12 中使用 Chrome 是正常的

可能是因为这些浏览器 App 在清单中声明了信任其他 CA，所以能够正常使用，得逆向 apk 查看清单才知道
https://developer.android.google.cn/training/articles/security-config?hl=zh-cn#TrustingAdditionalCas

**Comment by TPAXcc** [comment]
> 有一些资料显示在 Android 7+ 上 App 不信任用户导入的 CA 证书，这个只能通过 root 后强行导入，或者使用 adb 工具或 Magisk 这类的工具软件将证书导入到系统目录上 https://luoshuijs.vip/install-the-certificate-above-android-7.html https://www.cnblogs.com/Entr0py/p/9675061.html [XndroidDev/Xndroid#9](https://github.com/XndroidDev/Xndroid/issues/9)
> 
> 但浏览器应该是会信任用户的 CA 证书，例如 Chrome/Edge，其他浏览器未测试 目前在 Android 9 中使用 Edge 与 Android 12 中使用 Chrome 是正常的
> 
> 可能是因为这些浏览器 App 在清单中声明了信任其他 CA，所以能够正常使用，得逆向 apk 查看清单才知道 https://developer.android.google.cn/training/articles/security-config?hl=zh-cn#TrustingAdditionalCas

我先试试用 FireFox 和 Edge 行不行吧。实在不行我就用 ADB 导入证书试一下。另外提一嘴，之前用的浏览器是 Via, 这个浏览器似乎并没有自带内核，是使用的系统 WebView 实现 (包仅有 4M)

**Comment by TPAXcc** [comment]
> 有一些资料显示在 Android 7+ 上 App 不信任用户导入的 CA 证书，这个只能通过 root 后强行导入，或者使用 adb 工具或 Magisk 这类的工具软件将证书导入到系统目录上 https://luoshuijs.vip/install-the-certificate-above-android-7.html https://www.cnblogs.com/Entr0py/p/9675061.html [XndroidDev/Xndroid#9](https://github.com/XndroidDev/Xndroid/issues/9)
> 
> 但浏览器应该是会信任用户的 CA 证书，例如 Chrome/Edge，其他浏览器未测试 目前在 Android 9 中使用 Edge 与 Android 12 中使用 Chrome 是正常的
> 
> 可能是因为这些浏览器 App 在清单中声明了信任其他 CA，所以能够正常使用，得逆向 apk 查看清单才知道 https://developer.android.google.cn/training/articles/security-config?hl=zh-cn#TrustingAdditionalCas

我又回来了! 我测试的是 Pixiv.net 这个域名，Edge 似乎确实可用 (证书没问题，但我等了十几秒都没载入完，就没在等)

**Comment by TPAXcc** [comment]
> 

FireFox 同样证书不信任

**Comment by rmbadmin** [comment]
FireFox 在移动端也是要单独添加证书信任的

**Comment by TPAXcc** [comment]
等我早起来用 ADB 导入试下吧。如果 ADB 可行，那就建议在导入证书时候加个提示。另外，在我这个设备上关闭加速很容易卡死，不知道是不是我设备的问题，Soc 是温控贼死的 845，RAM 只有 4G 的 D4L。。。
