### ISSUE TITLE
🧐[Question] steam++在未打开主面板时正常，但打开主面板后就占用gpu，是正常现象吗？

### ISSUE THREAD

**Issue by Dingqiuwu** [BeyondDimension/SteamTools#1232]
### 🧐 问题描述(Description)

steam++在未打开主面板时正常，但打开主面板后就占用gpu，是正常现象吗？
详细地描述需求，让大家都能理解
### 🚑 其他信息(Other Information)

未打开主面板
![image](https://user-images.githubusercontent.com/99721792/162481422-8b131884-16b5-4920-8c21-7f6e391ea3f2.png)
打开主面板（最高可达10%的gpu占用）
![image](https://user-images.githubusercontent.com/99721792/162481686-60d9f1bd-3435-4f85-ad80-828ced1162fe.png)
- 程序版本(Program Version):2.6.3
- 系统版本号(OS Version): 
版本	Windows 11 家庭中文版
版本	21H2
安装日期	‎2021/‎8/‎1
操作系统版本	22000.556
序列号	PF2HN6N4
体验	Windows 功能体验包 1000.22000.556.0

- 是否为应用商店版本(Whether it is a Store version): No

**Comment by rmbadmin** [comment]
设置 通用设置 使用GPU渲染(硬件加速)是默认启用的

因为程序是skia自绘界面不使用GPU渲染会比较卡，你如果不希望有GPU占用关掉硬件加速开关即可。

**Comment by Dingqiuwu** [comment]
> 设置 通用设置 使用GPU渲染(硬件加速)是默认启用的
> 
> 因为程序是skia自绘界面不使用GPU渲染会比较卡，你如果不希望有GPU占用关掉硬件加速开关即可。

谢谢，了解
