### ISSUE TITLE
🧐[Question] 令牌错误 无法登录steam

### ISSUE THREAD

**Issue by ranchen421** [BeyondDimension/SteamTools#1233]
### 🚑 其他信息(Other Information)

- 程序版本(Program Version):忘记了 最新版反正
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by ranchen421** [comment]
问题描述：重装系统后 steam++令牌无法验证steam登录

**Comment by rmbadmin** [comment]
尝试刷新一下令牌同步一下服务器时钟

**Comment by ranchen421** [comment]
尝试过了，只有一个令牌遇到这种情况，但是我把该 UUID以及配置文件导入WinAuth，已经可以用了
