### ISSUE TITLE
👑 添加批量删除凭证功能

### ISSUE THREAD

**Issue by RC1844** [BeyondDimension/SteamTools#124]
### 🥰 需求描述(Description)

我希望【库存游戏】可以添加批量删除凭证功能，我库辣鸡过多🤣🤣

### 🧐 解决方案(Solution)

参考：https://greasyfork.org/zh-CN/scripts/371137

虽然这个基本可以解决问题，但在许可页实在太难认需要保留的游戏了

**Comment by rmbadmin** [comment]
在2.0重做了库存游戏列表之后，可以加入此功能

**Comment by RC1844** [comment]
> 在2.0重做了库存游戏列表之后，可以加入此功能

好的，期待你们的更新
