### ISSUE TITLE
🧐[Question] 配置文件启动时被重置

### ISSUE THREAD

**Issue by FinaFina233** [BeyondDimension/SteamTools#1247]
### 🧐 问题描述(Description)
打开了通用设置中的开机自启动，启动项中并没有出现Steam++，且每次打开Steam++界面设置都会回到默认

### 🚑 其他信息(Other Information)
![image](https://user-images.githubusercontent.com/52440333/162879510-e8ae8e76-0eeb-455a-9fd5-f8e167664405.png)
![image](https://user-images.githubusercontent.com/52440333/162879753-59ca9887-b813-4d28-893e-5952ae80c3b3.png)

- 程序版本(Program Version):
- 系统版本号(OS Version): Windows 11 22000.257 (Windows Insider Beta)
- 是否为应用商店版本(Whether it is a Store version): 否(No)

**Comment by AigioL** [comment]
开机自启是添加在计划任务当中的，不会出现在 ```任务管理器``` 中，只有商店渠道的版本自启项会在这里面

https://steampp.net/faq#NotFoundInTaskmgr

配置文件目录在 ```AppData\Config.mpo```，可在 ```通用设置 - 存储空间 - 打开 AppData 文件夹``` 定位

可能是你的设备上有什么导致在关闭时删除了该文件才会产生每次配置重置
