### ISSUE TITLE
🧐[Question]  微软商店(Microsft Store)版不再更新了吗？

### ISSUE THREAD

**Issue by fuchanghao** [BeyondDimension/SteamTools#1267]
### 🧐 问题描述(Description)

从keylol的帖子：https://keylol.com/t667906-1-1

找到了微软商店版：
https://www.microsoft.com/en-us/p/steam/9mtcfhs560ng

下载下来发现居然是2.6.4的旧版本。

在Github release中也没有看到msix的版本

### 🚑 其他信息(Other Information)

- 程序版本(Program Version): 2.6.4
- 系统版本号(OS Version): Windows 10 IoT LTSC 2021 (19044.1645)
- 是否为应用商店版本(Whether it is a Store version): 是

**Comment by AigioL** [comment]
release 有的 https://github.com/BeyondDimension/SteamTools/releases/download/2.6.9/Steam++_win_x64_msix_v2.6.9.7z
商店渠道审核不给过了，没办法更新了

**Comment by rmbadmin** [comment]
微软商店现在因为名称问题审核无法通过暂时没办法提交更新
