### ISSUE TITLE
⚠️[Bug] [难以复现] Steam++疑似遭到挟持

### ISSUE THREAD

**Issue by Ra2-IFV** [BeyondDimension/SteamTools#1276]
### 🐛 描述(Description)

不多说了，自己看吧...  
![屏幕截图 2022-04-19 232343](https://user-images.githubusercontent.com/96299096/164121842-4374552b-b4c8-4dae-8ec3-028aa8ba5899.png)
用着用着莫名其妙出现轮子的网站，google.com，gmail.com都被挟持了，其他的没试  
当时由于我在干其他事，没怀疑到Steam++的身上，后来我随便看了眼证书(左上角)，居然是Steam++的...  

### 📷 复现步骤(Steps to Reproduce)

我不到啊!  
当时在用虚拟机搞Steam的阿根廷号，开了CF的上网工具+其他上网工具，莫名其妙就这样了，关了也一样，基本能确定是Steam++的问题  
这个应该比较难以复现，给开发者看看我当时开了哪些功能吧，看看能不能诊断出啥  
![屏幕截图 2022-04-19 232511](https://user-images.githubusercontent.com/96299096/164123115-ba7d0775-49c1-4bb2-a98c-ed4cf0f19ff5.png)
![屏幕截图 2022-04-19 232522](https://user-images.githubusercontent.com/96299096/164123117-903c8d16-4f8f-40f8-8432-9fd426daaaaf.png)
![屏幕截图 2022-04-19 232537](https://user-images.githubusercontent.com/96299096/164123118-2219b264-4cfd-487e-95a9-3f726f050893.png)
![屏幕截图 2022-04-19 232546](https://user-images.githubusercontent.com/96299096/164123112-0c83d834-1455-4a23-b1b1-ea1e4db3b5be.png)

### 📄 [异常/日志]信息([Exception/Log] Information)

None.  

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.9.4  
- 系统版本号(OS Version): Windows 10 2004 (19041.1415)  
- 是否为应用商店版本(Whether it is a Store version): No  

### 其他的话
为了防止被重拳出击，表个态  
我反对轮子，因为太™弱智了，骗骗三岁小孩还差不多  
还有轮媒的新闻造假能力堪比你国  
但我坚决反对以任何不正当手段及暴力手段打压轮子  
就那句话：我不同意你的观点，但我誓死捍卫你说话的权利

**Comment by rmbadmin** [comment]
在启用hosts代理时是监听127.0.0.1本机端口进行透明代理的，然后使用hosts设置来保证支持的加速网站能被steam++监听到，你这边出现了代理之外的域名使用steam++按推测只有一个可能，即你本机的google.com和gmail这些被劫持的网站也访问了127.0.0.1所以其流量经过了steam++变成了steam++的证书。但至于其最终劫持到任何网址这个过程，具体还是取决于其域名本身的dns解析地址，这表明google.com和gmail的域名在你的虚拟机中dns解析也被劫持到了这些网站上。

**Comment by Ra2-IFV** [comment]
@rmbadmin 
我是在虚拟机外访问这些网站的
> 即你本机的google.com和gmail这些被劫持的网站也访问了127.0.0.1所以其流量经过了steam++变成了steam++的证书  

确实经过了Steam++，勾选了加速选项后hosts里就有 127.0.0.1 google.com

**Comment by Ra2-IFV** [comment]
DNS大概没有任何问题，我使用了DoH，服务器是Cloudflare，不可能被劫持

**Comment by fuchanghao** [comment]
> DNS大概没有任何问题，我使用了DoH，服务器是Cloudflare，不可能被劫持

你试试改成127.0.0.2再看看问题有没有复现。

**Comment by Ra2-IFV** [comment]
> 你试试改成127.0.0.2再看看问题有没有复现。

改啥？

**Comment by rmbadmin** [comment]
> DNS大概没有任何问题，我使用了DoH，服务器是Cloudflare，不可能被劫持

steam++目前是不支持doh的dns解析的，是走的steam++内的解析，
如果你未设置过dns地址默认取用的就是系统默认的非doh的dns。

勾选加速选项有google.com在hosts是因为谷歌验证码是要靠这个域名来监听的，但是gmail应该是不会有的

**Comment by Ra2-IFV** [comment]
> steam++目前是不支持doh的dns解析的，是走的steam++内的解析， 如果你未设置过dns地址默认取用的就是系统默认的非doh的dns。

DoH是放在我软路由上的，ip地址是192.168.1.1，网络适配器里也设定了...
就很奇怪

**Comment by Ra2-IFV** [comment]
先close了，毕竟概率事件
