### ISSUE TITLE
🐛[BUG]  诡异的内容泄漏问题

### ISSUE THREAD

**Issue by fuchanghao** [BeyondDimension/SteamTools#1277]
### 🐛 描述(Description)

Steam++内存会不断增加且不会释放

### 📷 复现步骤(Steps to Reproduce)

1. 重复反复从任务栏打开Steam++并关闭。
2. 可以看到Steam++内存占用不断升高。
3. 关闭Steam++一段时间后，内存并没有被回收。

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.6.9
- 系统版本号(OS Version): Windows 10 IoT LTSC 2021 (19044.1645) 
- 是否为应用商店版本(Whether it is a Store version):  两者均会复现同样问题

### 🖼 截图(Screenshots)
这是操作之前的内存占用：
[![LrQXLj.png](https://s1.ax1x.com/2022/04/20/LrQXLj.png)](https://imgtu.com/i/LrQXLj)
这是操作大概10次左右的内存占用
[![LrQxwn.png](https://s1.ax1x.com/2022/04/20/LrQxwn.png)](https://imgtu.com/i/LrQxwn)
这是放置了一段时间后的内存占用 (发帖的时候过了差不多10分钟，问题依旧)
[![LrQves.png](https://s1.ax1x.com/2022/04/20/LrQves.png)](https://imgtu.com/i/LrQves)

**Comment by rmbadmin** [comment]
这个其实是一直已知的一个问题，倒也不是内存泄露，
只是因为C#的GC机制和avalonia的窗口关闭时不会及时释放（GC默认释放时间比较久，一般可能要后台待机挺长时间才会自动释放），
导致每次从任务栏唤起时都会new的新窗口一直在吃新的内存，
在以前一直是使用一个窗口不关闭隐藏时倒是没有这个问题，不过这个问题应该可以尝试手动释放window解决。
