### ISSUE TITLE
🧐[Question] 加速失效 脚本也没有效果

### ISSUE THREAD

**Issue by yccshh** [BeyondDimension/SteamTools#1284]
### 🧐 问题描述(Description)
用过一次steam302后steam++加速失效

### 🚑 其他信息(Other Information)

- 是否为应用商店版本
- 否

**Comment by yccshh** [comment]
https://github.com/BeyondDimension/SteamTools/files/8539936/nlog-all-2022-04-22.log

**Comment by Mossimos** [comment]
dns查询失效了 请检查dns设置 尝试刷新dns缓存

**Comment by yccshh** [comment]
更新新版本后已恢复
