### ISSUE TITLE
🧐[Question] steam++存在临时令牌吗 steampy余额交易需要临时令牌

### ISSUE THREAD

**Issue by yccshh** [BeyondDimension/SteamTools#1293]
### 🧐 问题描述(Description)
临时令牌问题
![图片](https://user-images.githubusercontent.com/76168565/165086347-0898961e-ddbe-4f2b-8c50-a8f0cfe9f16e.png)

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by AigioL** [comment]
你可以在 https://store.steampowered.com/twofactor/manage_action 这个页面 获取 Steam 备用令牌码，可以使用短信验证或者令牌验证生成这个 临时令牌

**Comment by yccshh** [comment]
> 你可以在 https://store.steampowered.com/twofactor/manage_action 这个页面 获取 Steam 备用令牌码，可以使用短信验证或者令牌验证生成这个 临时令牌

好的好的谢谢你
