### ISSUE TITLE
🐛[BUG] 新的的内存泄漏问题 

### ISSUE THREAD

**Issue by fuchanghao** [BeyondDimension/SteamTools#1295]
### 🐛 描述(Description)

Steam++内存会不断增加且不会释放。

### 📷 复现步骤(Steps to Reproduce)

1. 打开Steam++
2. 开启网络加速，脚本配置，ASF，并长时间后台挂机运行。
3. 内存以差不多100MB/天的速度增加，且不会减少。
4. 本地hosts代理为了和机场软件不冲突设置为了127.0.0.2。

### 📄 [异常/日志]信息([Exception/Log] Information)

[Uploading Logs.zip…]()

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.6.9
- 系统版本号(OS Version): Windows 10 IoT LTSC 2021 (19044.1645)
- 是否为应用商店版本(Whether it is a Store version): 否
 
### 🖼 截图(Screenshots)

现在现在运行时的内存占用情况：

![屏幕截图 2022-04-26 113748](https://user-images.githubusercontent.com/11471475/165216109-cda88869-9cbd-45cb-9795-11746c56c672.png)

**Comment by rmbadmin** [comment]
可能与 #1277 是相同问题，这期间有重复多次最小化和唤起主窗口吗

**Comment by fuchanghao** [comment]
> 可能与 #1277 是相同问题，这期间有重复多次最小化和唤起主窗口吗

没有，之后我停止运行了，绝大部分时间都挂在后台中，总计不到10次的前台唤醒。

因为使用的功能比较多，不知道是什么原因导致的。

![屏幕截图 2022-04-26 135148](https://user-images.githubusercontent.com/11471475/165231152-b0b05c82-632d-4361-9126-11ecf716fc7d.png)

**Comment by fuchanghao** [comment]
> > 可能与 #1277 是相同问题，这期间有重复多次最小化和唤起主窗口吗
> 
> 没有，之后我停止运行重启了，绝大部分时间都挂在后台中，总计不到10次的前台唤醒。
> 
> 因为使用的功能比较多，不知道是什么原因导致的。
> 
> ![屏幕截图 2022-04-26 135148](https://user-images.githubusercontent.com/11471475/165231152-b0b05c82-632d-4361-9126-11ecf716fc7d.png)

**Comment by rmbadmin** [comment]
可以在测试一下 2.7.0版本 此问题的情况是否依然存在

**Comment by fuchanghao** [comment]
> 可以在测试一下 2.7.0版本 此问题的情况是否依然存在

暂时1日后没遇到内存泄露问题。

但遇到了一个更新Nvidia显卡驱动后，导致steam++界面再次唤醒时卡死的问题。(开了硬件加速，但是更新显卡驱动时已经最小化)

**Comment by fuchanghao** [comment]
> 可以在测试一下 2.7.0版本 此问题的情况是否依然存在

经过整个5/1的连续24小时放置，发现2.7.0依旧有内存泄漏问题，只能说稍微好一点了。

整个5/1几乎没打开Steam++的情况下，这是内存现在的占用：

![屏幕截图 2022-05-05 092347](https://user-images.githubusercontent.com/11471475/166851914-3bfb538d-c2d5-4d65-b88f-22ee9dc8a9b2.png)

而且出现了新的问题，右键在任务栏关闭Steam++之后，Steam++进程并没有直接结束，而是卡在任务管理器中保持占用500多MB的内存后不动了。也无法开启新的Steam++，只能任务管理器手动杀死Steam++进程后才能重开此进程。

![屏幕截图 2022-05-05 092749](https://user-images.githubusercontent.com/11471475/166851975-fa418f50-8454-4759-a6a0-4ac6ee87637a.png)

Log文件如下：
[Logs.zip](https://github.com/BeyondDimension/SteamTools/files/8628286/Logs.zip)


接下来更新2.7.2继续测试。

**Comment by fuchanghao** [comment]
2.7.2看起来基本解决这个问题了。
