### ISSUE TITLE
🐛[BUG] 游戏时长挂机列表无法使用。点击启动游戏没有任何反应

### ISSUE THREAD

**Issue by Maikenene** [BeyondDimension/SteamTools#1303]
### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): 

### 🖼 截图(Screenshots)

![微信图片_20220427102131](https://user-images.githubusercontent.com/38805339/165426155-5e1c40ad-fa0e-435d-9abb-f99fda3b4917.png)
![微信图片_20220427102123](https://user-images.githubusercontent.com/38805339/165426176-5189855c-85fb-4dd9-bf07-4dc9ac2815b6.png)

**Comment by AigioL** [comment]
已在 858af3f8b68c17f8de6375a03ff9c1362e78a028 中修复，可以先使用 [action](https://github.com/BeyondDimension/SteamTools/actions/runs/2230248591) 中编译的二进制文件  [[Release]Steam++_win_x64_858af3f](https://github.com/BeyondDimension/SteamTools/suites/6274467041/artifacts/224205717) 解压替换文件，或等下一个版本修复

**Comment by Maikenene** [comment]
切换账号以后库存游戏刷新列表也会出延迟，必须重启Steam++才能显示切换游戏以及游戏库存正常显示。
![微信图片_20220427102832](https://user-images.githubusercontent.com/38805339/165426902-bc881c30-ecf1-461a-9366-83dce2fe0759.png)
![微信图片_20220427102834](https://user-images.githubusercontent.com/38805339/165426913-06668c7b-3cb1-4ca4-9924-7660e4ec885c.png)
![微信图片_20220427102836](https://user-images.githubusercontent.com/38805339/165426917-6c7fa36e-e43a-4a1b-9a63-669756c7670e.png)

现在还没有发现其他任何BUG

**Comment by rmbadmin** [comment]
于 [97e3ebf](https://github.com/BeyondDimension/SteamTools/commit/97e3ebfc209efb1bcd6b4eaa75ba5f8fc38e341c) 提交修复
等待2.7.1更新

**Comment by Maikenene** [comment]
> 于 [97e3ebf](https://github.com/BeyondDimension/SteamTools/commit/97e3ebfc209efb1bcd6b4eaa75ba5f8fc38e341c) 提交修复 等待2.7.1更新

用[[Release]Steam++_win_x64_858af3f]修好了 挂时长。辛苦了。谢谢  期待2
7.1 版本

**Comment by rmbadmin** [comment]
[2.7.1](https://github.com/BeyondDimension/SteamTools/tree/2.7.1) 已发布并修复
