### ISSUE TITLE
🧐[Question] 

### ISSUE THREAD

**Issue by TNTinMinecraft** [BeyondDimension/SteamTools#1314]
### 🧐 问题描述(Description)

时长挂机没有用

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/48472338/165670796-fe2d1895-09a7-4d23-a6ff-69697a6e0cbe.png)
- 程序版本(Program Version):2.7.0
- 系统版本号(OS Version):Windows 10.19044.1586
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by AigioL** [comment]
今天晚些时候会发布 2.7.1 修复这个问题

**Comment by rmbadmin** [comment]
[2.7.1](https://github.com/BeyondDimension/SteamTools/tree/2.7.1) 已发布并修复
