### ISSUE TITLE
🧐[Question] 

### ISSUE THREAD

**Issue by shangyan11** [BeyondDimension/SteamTools#1318]
### 🧐 问题描述(Description)

安装完成后打开发生错误，下载了.NET还是不行。

### 🚑 其他信息(Other Information)
![1](https://user-images.githubusercontent.com/59022611/166103664-02553eb5-3a78-47b7-9dc5-630843ced7cd.JPG)

- 程序版本(Program Version):Steam++_win_x64_fde_v2.7.2
- 系统版本号(OS Version): 19043.1526

**Comment by Ashetoto** [comment]
这个版本需要自带运行库，选择没有“fde”的版本
