### ISSUE TITLE
🧐[Question] 

### ISSUE THREAD

**Issue by Aeopi** [BeyondDimension/SteamTools#1319]
### 🧐 问题描述(Description)

打开steam++显示要运行此应用程序，必须安装.NET缺少的框架。（To run this application, you must install missing frameworks for.NET.）
我已经安装上需要的框架还是显示需要安装

### 🚑 其他信息(Other Information)

<
![pic - 1](https://user-images.githubusercontent.com/104688033/166112497-79f07006-983f-406d-a1aa-38b565588ad8.jpg)
!--
如截图等其他信息可以贴在这里
Other information such as screenshots can be posted here
-->

- 程序版本(Program Version):V2.7.2
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by AigioL** [comment]
你应该下没有 fde 名字的文件

**Comment by Aeopi** [comment]
> 你应该下没有 fde 名字的文件
 能给个链接吗？

**Comment by AigioL** [comment]
### Steam++_win_x64_v2.7.2.7z
https://github.com/BeyondDimension/SteamTools/releases/download/2.7.2/Steam++_win_x64_v2.7.2.7z

### Steam++_win_x64_v2.7.2.exe
https://github.com/BeyondDimension/SteamTools/releases/download/2.7.2/Steam++_win_x64_v2.7.2.exe

https://cowtransfer.com/s/94ce5dfa928f45
https://www.aliyundrive.com/s/KDCFrongF7F/folder/626cf6256d5ca861ce2a46d2980365fcc6e1a3d2

**Comment by Aeopi** [comment]
> ### Steam++_win_x64_v2.7.2.7z
> https://github.com/BeyondDimension/SteamTools/releases/download/2.7.2/Steam++_win_x64_v2.7.2.7z
> 
> ### Steam++_win_x64_v2.7.2.exe
> https://github.com/BeyondDimension/SteamTools/releases/download/2.7.2/Steam++_win_x64_v2.7.2.exe
> 
> https://cowtransfer.com/s/94ce5dfa928f45 https://www.aliyundrive.com/s/KDCFrongF7F/folder/626cf6256d5ca861ce2a46d2980365fcc6e1a3d2

谢谢，已经可以了
