### ISSUE TITLE
🐛[BUG] 已经安装证书的情况下仍然请求安装证书

### ISSUE THREAD

**Issue by H4M5TER** [BeyondDimension/SteamTools#1320]
### 🐛 描述(Description)

如题，我现在 certmgr 看当前用户证书已经俩 SteamTools Certificate 了

### 📷 复现步骤(Steps to Reproduce)

1. 正常安装证书使用
2. 软件自启、启动时加速
3. 重启电脑
4. 仍然申请安装证书
5. 取消则报错，通过则又增殖

### 📄 [异常/日志]信息([Exception/Log] Information)

[nlog-all-2022-05-01.log](https://github.com/BeyondDimension/SteamTools/files/8598150/nlog-all-2022-05-01.log)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.7.0
- 系统版本号(OS Version): Windows 10.19044.1645
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/21092951/166129168-8442a6f4-5113-4f6a-bfb2-6fd4de6e077c.png)

**Comment by rmbadmin** [comment]
你图中的这个证书安装区域不对，所以程序没法读取到证书已正确安装
证书需要安装进受信任的根证书区域。

**Comment by H4M5TER** [comment]
确认了一边也是有的
![image](https://user-images.githubusercontent.com/21092951/166140499-de5683c7-85f1-4743-aad3-fb6d6f902091.png)

**Comment by AigioL** [comment]
你可以试一下在 certmgr 中删除所有的 SteamTools Certificate，然后使用最新版 2.7.2 启动加速，启动加速时会导入证书

**Comment by H4M5TER** [comment]
把根证书也删掉之后重新加速装上就正常了，虽然不知道什么问题，但是没复现了
