### ISSUE TITLE
🧐[Question] 脚本无法运行

### ISSUE THREAD

**Issue by Ashetoto** [BeyondDimension/SteamTools#1325]
### 🧐 问题描述(Description)

加载脚本并启动加速后，脚本功能（例如历史价格）并没有在steam上体现

· 已加载GM脚本
· 尝试过重启脚本并加速、再启动steam，无效
· 查看过Cache-Scripts文件，有脚本

### 🚑 其他信息(Other Information)

<img width="693" alt="image" src="https://user-images.githubusercontent.com/96050362/166199160-0ee7b498-c942-4561-a78a-0a20200a1d70.png">
已开启脚本，随便选了个游戏查看:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/96050362/166199184-61e195c0-7c21-4eb1-968e-c5adea1942a9.png">

Logs文件如下，但是我看不太懂......
[nlog-all-2022-05-02.log](https://github.com/BeyondDimension/SteamTools/files/8601448/nlog-all-2022-05-02.log)

- 程序版本(Program Version): v2.7.2
- 系统版本号(OS Version): win11
- 是否为应用商店版本(Whether it is a Store version):  否

**Comment by Mossimos** [comment]
https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js | System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (cdn.bootcss.com:443)
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
脚本 需要引用  jquery.min.js 从 cdn.bootcss.com cdn下载绑定失败了
你访问下这url看能打开吗
https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js

**Comment by Mossimos** [comment]
https://cdn.staticfile.org/jquery/1.12.1/jquery.min.js
如实在无法访问可以百度以下公共CDN 找到一个能访问的 
然后编辑脚本找到 https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js
替换这段为 其他cdn的地址

**Comment by Ashetoto** [comment]
> 

“能打开”是指点击这个url后的代码页面吗？
能看到一些很长的、完全看不懂的代码....
和编辑脚本里面的结构完全不一样......所以我不确定这是不是“能访问”的一个状态....
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/96050362/166409403-e25dfa26-f27c-4c84-9780-e593d08a4a25.png">

我发现可能和我使用了梯子有关！
我刚刚关闭梯子后，足迹可以显示了，但是历史最低价并没有成功运转出来，就是下图过后，没有历史最低价
<img width="497" alt="image" src="https://user-images.githubusercontent.com/96050362/166410344-6a70a588-13b5-4b76-9ead-ab7df3810ca9.png">

**Comment by Mossimos** [comment]
最低价也是亲求一个网站返回的结果
https://api.augmentedsteam.com/v01/prices/?bundleids=&subids=478521&appids=1295510&stores=steam&cc=cn&coupon=true
另外貌似确实有点问题我排查下

**Comment by Mossimos** [comment]
发现了 api.augmentedsteam.com  貌似新游戏没有数据
我看这个游戏是有数据的应该是你访问出现了问题
![image](https://user-images.githubusercontent.com/26396340/166417446-2deb7afa-7218-4edd-9e59-cfd6e5f21a77.png)

**Comment by Ashetoto** [comment]
啊！现在已经完全可以运行了~
<img width="496" alt="image" src="https://user-images.githubusercontent.com/96050362/166486222-3893f6ec-8575-4d18-a6b3-ffb221bcff4e.png">
非常感谢！
