### ISSUE TITLE
🐛[BUG] Firefox 证书信任

### ISSUE THREAD

**Issue by jiyizhuo** [BeyondDimension/SteamTools#1327]
### 🐛 描述(Description)

在Github、Steam等加速网站中，使用Firefox Mightly提示HSTS有问题，导致网站无法访问，关闭开发者选项后才能解决(重点就是我十分需要开发者选项)
P.S. 4.30号测评，关闭开发者选项仍然无法访问，Chrome、Edge测试正常

### 📷 复现步骤(Steps to Reproduce)

1. 打开Firefox Mightly浏览器，输入store.steampowered.com
2. 无法访问
3. 打开Steam++加速，重新加载
4. 显示由于HSTS被Mightly拦截

### 📄 [异常/日志]信息([Exception/Log] Information)

`未连接：有潜在的安全问题

Nightly 检测到潜在的安全威胁，并因 pages.github.com 要求安全连接而没有继续。

您可以做什么？

pages.github.com 启用了被称为 HTTP 严格传输安全（HSTS）的安全策略，Nightly 只能与其建立安全连接。您无法为此网站添加例外，以访问此网站。

这个问题大多与网站有关，无法通过您的操作解决。

如果您是在使用公司网络或某些防病毒软件时遇到此问题，可考虑联系客服（技术支持）以寻求帮助。您也可以向网站管理员告知此问题。

可能有人试图冒充该网站，您不应该继续访问。
 
各个网站通过证书证明自己的身份。Nightly 不信任 pages.github.com，因其证书颁发者未知、证书为自签名的，或者服务器未发送正确的中间证书。
 
错误代码：SEC_ERROR_UNKNOWN_ISSUER
 
查看证书`

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):Steam++ x64 v2.6.9 For Windows
- 系统版本号(OS Version): Windows 11 21H2 (OS 内部版本 22000.194)
- 是否为应用商店版本(Whether it is a Store version): 是

### 🖼 截图(Screenshots)

截图工具损坏，暂无截图

**Comment by rmbadmin** [comment]
参考 https://steampp.net/faq#CommunityAccelerate
