### ISSUE TITLE
👑[Enhancement] 

### ISSUE THREAD

**Issue by jiyizhuo** [BeyondDimension/SteamTools#1328]
### 🥰 需求描述(Description)

对以下网站增加加速:
1.NPM
2.Maven
3.Epic
4.Totally Accurate Battle Simulator(TABS的创意工坊)
5.Wikipedia
6.mod.io
7.Google
8.Apple
9.Yahoo
10.Youtube

### 🧐 解决方案(Solution)

没有

### 🚑 其他信息(Other Information)

莫有

**Comment by AigioL** [comment]
NPM 和 Maven 国内应该有镜像可以替代，也不需要加速，mod.io 在适配中，有一些问题没能解决，其他不合法的网站是支持不了的
