### ISSUE TITLE
🐛[BUG] 在2.7.2版本中，Mac arm版发生 软件已损坏，无法打开。

### ISSUE THREAD

**Issue by marc-shen** [BeyondDimension/SteamTools#1333]
# 🐛[BUG] 在2.7.2版本中，Mac arm版发生 软件已损坏，无法打开。

## 问题描述
在macOS（arm架构）安装[Steam++_macos_arm64_v2.7.2.dmg](https://github.com/BeyondDimension/SteamTools/releases/download/2.7.2/Steam++_macos_arm64_v2.7.2.dmg)。在完成安装后运行Steam++会出现软件已损坏的报错提示，无法运行。

## 系统版本
macos Monterey 12.3.1 (21E258)

## 系统架构
ARM64（Apple M1 Pro）

## 建议
重新检查软件封装的过程，可能是在上传过程中出现了问题

**Comment by marc-shen** [comment]
# 补充
## 对安装包进行了 SHA-256 校验
```shell
% shasum -a 256 Steam++_macos_arm64_v2.7.2.dmg
143a42787341bebf849a9ce754ba2758267b399a394adc016d398e7e81120355  Steam++_macos_arm64_v2.7.2.dmg
```
<!DOCTYPE html>

Steam++_macos_arm64_v2.7.2.dmg | 143A42787341BEBF849A9CE754BA2758267B399A394ADC016D398E7E81120355
-- | --

与提供的值相同。

## 综上
应该是打包过程出现问题。

**Comment by Mossimos** [comment]
我这确认是可以正常打开的 重新下载试试呢
![image](https://user-images.githubusercontent.com/26396340/166404732-5fea7ac1-7e80-4513-83f5-604687d1d9e8.png)

**Comment by AigioL** [comment]
系统偏好设置 -> 安全性与隐私 -> 通用 中是否设置为 允许任何来源

https://blog.csdn.net/liuxingyuzaixian/article/details/113727278

**Comment by marc-shen** [comment]
# 解决方案
## 使用x64版本的软件
在安装[Steam++_macos_x64_v2.7.2.dmg](https://github.com/BeyondDimension/SteamTools/releases/download/2.7.2/Steam++_macos_x64_v2.7.2.dmg)后，软件能正常运行。


## 综上
是不是在封装时起名字搞错了？
总之就是非常奇怪。

**Comment by Mossimos** [comment]
并没有搞错啊，SHA-256 校验都是一样的。
可以试试 这里你是有啥提示吗？
![image](https://user-images.githubusercontent.com/26396340/166405125-c1778fa2-6ea9-48c6-bc69-9f16604b368e.png)

**Comment by Mossimos** [comment]
另外你 的图片泄露了你的隐私 注意打码。
还有 用x64版效率其实很低

**Comment by marc-shen** [comment]
> 我这确认是可以正常打开的 重新下载试试呢
> ![image](https://user-images.githubusercontent.com/26396340/166404732-5fea7ac1-7e80-4513-83f5-604687d1d9e8.png)

进行了文件校验，也下载了三遍，应该不是下载的问题。

**Comment by Mossimos** [comment]
看看 系统偏好设置-安全性与隐私-允许从以下位置下载的APP 是什么设置

**Comment by Mossimos** [comment]
也可以尝试从 dmg 托出来 使用中断 CD 进入 Steam++.app  > MacOs 文件夹  运行 ./Steam++ 看看有没有 啥提示

**Comment by marc-shen** [comment]
> 并没有搞错啊，SHA-256 校验都是一样的。
> 可以试试 这里你是有啥提示吗？
> ![image](https://user-images.githubusercontent.com/26396340/166405125-c1778fa2-6ea9-48c6-bc69-9f16604b368e.png)
<img width="372" alt="截屏2022-05-03 12 37 16" src="https://user-images.githubusercontent.com/59384269/166405348-e4222a06-93c7-49d0-8098-6e48ba12133f.png">
 
<img width="306" alt="截屏2022-05-03 12 47 53" src="https://user-images.githubusercontent.com/59384269/166405731-33d00207-fea0-4bd9-886d-b37667527430.png">
不是权限的问题

**Comment by Mossimos** [comment]
这太怪了我重新压缩一个发给你试试

**Comment by marc-shen** [comment]
> 系统偏好设置 -> 安全性与隐私 -> 通用 中是否设置为 允许任何来源
> 
> https://blog.csdn.net/liuxingyuzaixian/article/details/113727278

这个东西在最新版本失效了

To disable Gatekeeper, Use the command: sudo spctl --global-disable
And to re-enable Gatekeep, type this command in terminal: sudo spct; --global-enable.
the old command spctl --master is no longer supported in mac.
This change was introduced in Mac OS 10.15.7 (last version on Catalina) probably because i was last using it just 1 month back and the spctl manpage had the new guidlines. The global command works perfectly on all versions above OS 10.15.7 till Mac OS Montery 12.2.1 (latest stable version).

**Comment by marc-shen** [comment]
> 另外你 的图片泄露了你的隐私 注意打码。
> 还有 用x64版效率其实很低

谢谢谢谢谢谢

**Comment by Mossimos** [comment]
https://pan.mossimo.net:5212/s/b3HD

**Comment by AigioL** [comment]
感觉可能是有抛出未捕获的 托管异常，或非托管异常导致启动时闪退，看看 Logs 文件夹中有没有日志吧 目录在 ```~/Library/Caches/Steam++/Logs```

**Comment by marc-shen** [comment]
目前来看是签名不符。
这个会导致报错，更改安装来源无法解决。

```shell
% xattr -cr /Applications/Steam++.app 
% sudo codesign --force --deep --sign - /Applications/Steam++.app
/Applications/Steam++.app: replacing existing signature
```
这样可以强制更改应用的签名，保证能通过判断。
这个问题应该是最新版本的Mac系统的问题。
有劳二位帮助我解决问题了。

**Comment by Mossimos** [comment]
程序是没有用自证签名的  我系统也是最新的 12.3.1 从网络下载提示也不是损坏 而是在设置需要允许 从互联网下载的Steam++.app 允许一下就OK了这个损坏之前确实没见过

**Comment by Mossimos** [comment]
https://support.apple.com/zh-cn/guide/mac-help/mh40616/12.0/mac/12.0
正常应该 是这样操作 也不会提示损坏
【注】您也可以通过点按“安全性与隐私”偏好设置中“通用”面板上的“仍要打开”按钮来允许被阻止的 App。此按钮在您尝试打开该 App 后一小时内可用。

**Comment by Mossimos** [comment]
也不会提示啥 文件损坏
![image](https://user-images.githubusercontent.com/26396340/166406984-221be86c-8d88-40c2-912c-3ef45fd949a9.png)

**Comment by marc-shen** [comment]
> https://support.apple.com/zh-cn/guide/mac-help/mh40616/12.0/mac/12.0
> 正常应该 是这样操作 也不会提示损坏
> 【注】您也可以通过点按“安全性与隐私”偏好设置中“通用”面板上的“仍要打开”按钮来允许被阻止的 App。此按钮在您尝试打开该 App 后一小时内可用。

没事，已经给它写入了一个签名，现在已经可以开始享受游戏生活了。
自从换了Linux换成了arm架构的Mac，时间都用来找合适的版本的软件了。
非常感谢帮助，真的很有用。

**Comment by livelybone** [comment]
使用这个方法仍然提示损坏怎么破~

> https://support.apple.com/zh-cn/guide/mac-help/mh40616/12.0/mac/12.0 正常应该 是这样操作 也不会提示损坏 【注】您也可以通过点按“安全性与隐私”偏好设置中“通用”面板上的“仍要打开”按钮来允许被阻止的 App。此按钮在您尝试打开该 App 后一小时内可用。

**Comment by Mossimos** [comment]
@livelybone
目前这个不确定是啥错误 ，我也没有多台Mac 来进行测试
你先确定   允许软件安装的来源： 不是仅允许来自 Mac App Store 的 App
或者你有时间可以约定个时间 来远程看看具体什么情况 才好解决这个。

**Comment by livelybone** [comment]
我是 mac M1，会不会是没兼容这个芯片？

**Comment by Mossimos** [comment]
> 我是mac M1，不会是没开发这款芯片？
arm 就是为了 m1 编译的 测试用的机器也是 Mac mini m1 版本

**Comment by marc-shen** [comment]
```shell
% xattr -cr /Applications/Steam++.app
% sudo codesign --force --deep --sign - /Applications/Steam++.app
```
可以解决问题

> 使用这个方法仍然提示损坏怎么破~
> 
> > https://support.apple.com/zh-cn/guide/mac-help/mh40616/12.0/mac/12.0 正常应该 是这样操作 也不会提示损坏 【注】您也可以通过点按“安全性与隐私”偏好设置中“通用”面板上的“仍要打开”按钮来允许被阻止的 App。此按钮在您尝试打开该 App 后一小时内可用。

**Comment by livelybone** [comment]
可以了可以了，牛逼！！

> ```shell
> % xattr -cr /Applications/Steam++.app
> % sudo codesign --force --deep --sign - /Applications/Steam++.app
> ```
> 
> 可以解决问题
> 
> > 使用这个方法仍然提示损坏怎么破~
> > > https://support.apple.com/zh-cn/guide/mac-help/mh40616/12.0/mac/12.0 正常应该 是这样操作 也不会提示损坏 【注】您也可以通过点按“安全性与隐私”偏好设置中“通用”面板上的“仍要打开”按钮来允许被阻止的 App。此按钮在您尝试打开该 App 后一小时内可用。

**Comment by marc-shen** [comment]
@livelybone 
这个方法只能对自己了解的软件使用，强制签名未知软件可能让你的电脑面临病毒等问题。
```ssh
% sudo spctl --global-disable
% sudo spctl --global-enable
```
这两个命令可以在12以上等macOS中开关安装任意软件等权限，可能会安全一些。
使用破解版软件等情况时一定注意计算机安全。

> 可以了可以了，牛逼！！
> 
> > ```shell
> > % xattr -cr /Applications/Steam++.app
> > % sudo codesign --force --deep --sign - /Applications/Steam++.app
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以解决问题
> > > 使用这个方法仍然提示损坏怎么破~
> > > > https://support.apple.com/zh-cn/guide/mac-help/mh40616/12.0/mac/12.0 正常应该 是这样操作 也不会提示损坏 【注】您也可以通过点按“安全性与隐私”偏好设置中“通用”面板上的“仍要打开”按钮来允许被阻止的 App。此按钮在您尝试打开该 App 后一小时内可用。

**Comment by dongruikang** [comment]
> > 系统偏好设置 -> 安全性与隐私 -> 通用 中是否设置为 允许任何来源
> > https://blog.csdn.net/liuxingyuzaixian/article/details/113727278
> 
> 这个东西在最新版本失效了
> 
> To disable Gatekeeper, Use the command: sudo spctl --global-disable And to re-enable Gatekeep, type this command in terminal: sudo spct; --global-enable. the old command spctl --master is no longer supported in mac. This change was introduced in Mac OS 10.15.7 (last version on Catalina) probably because i was last using it just 1 month back and the spctl manpage had the new guidlines. The global command works perfectly on all versions above OS 10.15.7 till Mac OS Montery 12.2.1 (latest stable version).

按照csdn这个链接的方法执行了命令好了：sudo xattr -r -d com.apple.quarantine /Applications/Steam++.app

**Comment by Mossimos** [comment]
可以再帮忙测试下这个还是损坏吗?
@livelybone  @marc-shen  @dongruikang 
https://pan.mossimo.net:5212/s/b3HD

**Comment by marc-shen** [comment]
@Mossimos 
在任何来源开放的情况下还是损坏。

**Comment by Mossimos** [comment]
非常奇怪 Parallels Desktop 创建虚拟机 Macos 12.3.4  ARM 不管怎么运行都是分段错误
但是 x64 就正常 看来只能找人借设备才能找问题了

**Comment by Mossimos** [comment]
@marc-shen
再帮忙试试。
https://pan.mossimo.net:5212/api/v3/file/get/4361/Steam++.app.zip?sign=PG3-6SDYqzNDNxwVZkqTIl8YnpKa2qaQFddYg5uc2VU%3D%3A0

**Comment by marc-shen** [comment]
<img width="418" alt="截屏2022-05-16 18 36 43" src="https://user-images.githubusercontent.com/59384269/168575087-a5148082-e5c4-44e9-8df8-1da9e8acc91f.png">
@Mossimos 不行，很怪

**Comment by Mossimos** [comment]
@marc-shen  
麻烦在帮忙试试  我现在用免费 的xcode给我生成的证书 
和自签了一个证书看看能不能开
https://pan.mossimo.net:5212/s/b3HD

**Comment by Mossimos** [comment]
让一个从来没用过的试了下好像都行
![1](https://user-images.githubusercontent.com/26396340/168987273-c090a97a-2d0e-4b10-971b-82237bb1f29d.jpg)
![2](https://user-images.githubusercontent.com/26396340/168987280-919b4501-b7c5-4091-bc28-c87b9378f241.jpg)

**Comment by marc-shen** [comment]
两个签名版的测试都可以使用，很不错。
