### ISSUE TITLE
🧐[Question]  Mac版本如何解锁成就？

### ISSUE THREAD

**Issue by marc-shen** [BeyondDimension/SteamTools#1335]
# 🧐[Question]  Mac版本如何解锁成就？

**Comment by AigioL** [comment]
解锁成就功能目前是 Windows Only

**Comment by marc-shen** [comment]
了解了

**Comment by AigioL** [comment]
解锁成就功能用的是 Steam Achievement Manager 的代码，最近把里面的 WinAPI 替换成通用函数了，挂时长功能会有点问题，但是可以用 ASF 替代，预计在下个版本中发布。

https://github.com/BeyondDimension/SteamAchievementManager/compare/b6d9278343d113d81fa56a91fb228805dd2f180b..8a274ce89cea436407c0c06c91a085e1a4b98751
