### ISSUE TITLE
🧐[Question] 这个窗口无限放大是什么情况

### ISSUE THREAD

**Issue by 1285626862** [BeyondDimension/SteamTools#1339]
### 🧐 问题描述(Description)

窗口最小化之后再拉出来会放大窗口，直至沾满屏幕

### 🚑 其他信息(Other Information)

https://user-images.githubusercontent.com/101202107/166632466-7811e3c6-6133-4977-b7c6-dfcec6606e41.mp4

- 程序版本(Program Version):2.7.2
- 系统版本号(OS Version): 版本	Windows 11 21H2
- 是否为应用商店版本(Whether it is a Store version): no

**Comment by rmbadmin** [comment]
这是已知问题， 等待FluentAvalonia修复 https://github.com/amwx/FluentAvalonia/issues/115

**Comment by rmbadmin** [comment]
> 这是已知问题， 等待FluentAvalonia修复 https://github.com/amwx/FluentAvalonia/issues/115
