### ISSUE TITLE
🧐[Question] 加速p站pixiv后还是加载不了内容

### ISSUE THREAD

**Issue by mengshanasi** [BeyondDimension/SteamTools#1346]
### 🧐 问题描述(Description)

加速p站pixiv后还是加载不了内容，最好的情况也就图1那样，而且打开p站偶尔会像图2那样，是否和我的浏览器有关？还是需要另外进行一些设置？一般用哪个加速模式？

### 🚑 其他信息(Other Information)

![屏幕截图(659)](https://user-images.githubusercontent.com/62591666/167126258-ff7cac71-6463-452a-9e26-da00d8ca4605.png)
![屏幕截图(661)](https://user-images.githubusercontent.com/62591666/167130002-54b80607-f1a7-453f-95a5-ec7cfa5d200a.png)

- 程序版本(Program Version):V2.7.2
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by rmbadmin** [comment]
https://steampp.net/faq#CommunityAccelerate

**Comment by mengshanasi** [comment]
> https://steampp.net/faq#CommunityAccelerate

谢了大佬，还真得自己手动导入证书。。。
