### ISSUE TITLE
🐛[BUG] 加速时间不动

### ISSUE THREAD

**Issue by Kulahala** [BeyondDimension/SteamTools#1395]
### 🐛 描述(Description)

最小化程序后加速时间不动

### 📷 复现步骤(Steps to Reproduce)

1. steam++加速
2. 关闭变为最小化
3. 加速时间无变化

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.7.2
- 系统版本号(OS Version): winows10.19044.1706
- 是否为应用商店版本(Whether it is a Store version): NO

### 🖼 截图(Screenshots)

![Snipaste_2022-05-14_22-16-06](https://user-images.githubusercontent.com/54696830/168429624-485a0b66-723f-4368-93b7-296d263d9765.png)

**Comment by rmbadmin** [comment]
已在提交中修复
