### ISSUE TITLE
🧐[Question] 

### ISSUE THREAD

**Issue by mwmaacc** [BeyondDimension/SteamTools#1396]
### 🧐 问题描述(Description)
steam启动参数为空，不能一键启动steam

### 🚑 其他信息(Other Information)
<img width="1280" alt="dba5847bfbb0c5046945a48ccfc3c24" src="https://user-images.githubusercontent.com/50987130/168432287-d04bafc4-46f9-4f00-aced-dafa7eeb2e90.png">

- 2.7.3
- win11
- 是(Yes)

**Comment by rmbadmin** [comment]
看这个异常应该是因为steam安装在c盘，
steam++调用的cmd没有权限启动导致的。
尝试将steam文件夹的权限设置授予一下当前系统登录用户权限

**Comment by mwmaacc** [comment]
> 

谢谢 解决了 按照你说的做了 虽然我都不清楚自己设置了什么
