### ISSUE TITLE
🐛[BUG] MacOS无法打开M1版本的Steam++，显示已损坏

### ISSUE THREAD

**Issue by EmptyIrony** [BeyondDimension/SteamTools#1397]
### 🐛 描述(Description)

我是用的设备是MacBookAir M1版，系统版本是12.3.1
安装了Apple版本的Steam++后打开提示软件已损坏，让我放入回收站。
安装Intel版本的Steam++可以正常打开

### 📷 复现步骤(Steps to Reproduce)

1. 安装M1版的Steam++
2. 右键打开

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):12.3.1
- 系统版本号(OS Version):  macOS Monterey 12
- Github 蓝奏云下载方式的dmg文件都试过了

### 🖼 截图(Screenshots)

<img width="260" alt="image" src="https://user-images.githubusercontent.com/43162518/168474155-cf051d93-1978-48a8-816c-eaf02b29cdb9.png">

**Comment by AigioL** [comment]
提示损坏的原因应该是公证的问题，发行的软件包没有使用 Developer ID 证书 进行签名，触发了 macOS 的“门禁”引发的，x64 的版本却又没有触发，也不知道为什么
https://developer.apple.com/cn/developer-id/

Apple Developer Enterprise Program 需要大概 ￥1988/年 的价格，等之后开发 iOS 客户端再考虑购买

解决方案可参考之前的 issue 中的回复
https://github.com/BeyondDimension/SteamTools/issues/1333#issuecomment-1115741718

与 https://github.com/dotnet/runtime/discussions/66574 相关

**Comment by Mossimos** [comment]
试试这个包看看还是损坏吗
https://pan.mossimo.net:5212/api/v3/file/get/4361/Steam++.app.zip?sign=PG3-6SDYqzNDNxwVZkqTIl8YnpKa2qaQFddYg5uc2VU%3D%3A0

**Comment by EmptyIrony** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/43162518/168721963-bf17e212-d5d7-486f-bba2-d2cba562b7d5.png">
可以运行，非常感谢
