### ISSUE TITLE
请问下，Discord的在线语音是否有加入？🧐[Question] 

### ISSUE THREAD

**Issue by juzidefennu** [BeyondDimension/SteamTools#1404]
请问下，Discord的语音是否又加入代理？
因为我在使用的过程中发现，进入语音频道时候走的本地链接。但是这一链接无法保证稳定。
请问这个如何解决？
![image](https://user-images.githubusercontent.com/105665831/168645888-ee5ef297-7aff-4199-8554-c779dc9f6eb4.png)

**Comment by rmbadmin** [comment]
没有办法，steam++并不是加速器，要达到加速这个的目的还是需要借助服务器中转加速。

**Comment by juzidefennu** [comment]
> 没有加速办法，steam++自带，要达到这个加速的目的还是需要借助服务器中转加速。

好的，谢谢。
