### ISSUE TITLE
🐛[BUG] 启动ASF导致Steam++无响应

### ISSUE THREAD

**Issue by Gavin-TnT** [BeyondDimension/SteamTools#1407]
### 🐛 描述(Description)

如果steam开启令牌，ASF加载到发送验证码时无响应，但是如果关闭steam令牌，那么就不会无响应，正常进行挂卡。
### 📷 复现步骤(Steps to Reproduce)

1.打开ASF
2.加载到输入令牌验证码时无响应

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.7.2
- 系统版本号(OS Version): Windows 10.19044.1645
- 是否为应用商店版本(Whether it is a Store version):no 

### 🖼 截图(Screenshots)

![1](https://user-images.githubusercontent.com/80191175/168706216-51c7c539-e3c2-46d1-990a-44e4f5bc9eb2.png)
![2](https://user-images.githubusercontent.com/80191175/168706252-ede2a8d2-64a6-443b-a5fd-d3876743e836.png)

**Comment by rmbadmin** [comment]
这个问题因为我无法复现所以暂时不清楚问题原因，待发现原因后进行修复

**Comment by rmbadmin** [comment]
麻烦测试一下2.8.4是否还有此问题

**Comment by Gavin-TnT** [comment]
> 麻烦测试一下2.8.4是否还有这个问题

还是未响应，但是没有弹出这个
![image](https://user-images.githubusercontent.com/80191175/185781531-36d11314-d3be-4897-92d7-3194c3261565.png)

而是一直卡在这里
![image](https://user-images.githubusercontent.com/80191175/185781567-7f203298-7558-4ebe-926e-5533cdbbc2f0.png)

**Comment by Gavin-TnT** [comment]
如果没有别人和我有同样的问题就不用麻烦您修复了 我使用原版已经挂了

**Comment by XiaokiYolo** [comment]
问题一样，最新版本还未修复，重新下载安装后依然存在，我的是开启ASF后就无响应

**Comment by XiaokiYolo** [comment]
已经通过删除C:\Users\Administrator\AppData\Local\Steam++\ASF\config的所有文件成功启动，ASF.db文件启动会自动生成
