### ISSUE TITLE
🐛[BUG] linux  hosts模式不能使用

### ISSUE THREAD

**Issue by 652436962** [BeyondDimension/SteamTools#1408]
我使用的是deepin 20.05
hosts 模式不能使用，已经按照网页提示执行下列命令
$ sudo chmod a+r /etc/hosts
$ sudo chmod a+w /etc/hosts
![截图_Steam++_20220517131611](https://user-images.githubusercontent.com/34038936/168734387-dda2b04b-f74b-4f39-bfdb-c2fccba817d4.png)
![截图_deepin-terminal_20220517131020](https://user-images.githubusercontent.com/34038936/168734395-36d0c6d3-a6b0-49c8-9383-57b8bb3ecf23.png)

另外 ： control文件的Package字段显示的就是该应用的包名，实际为：Steam++）含有大写英文字母（严格来说这不符合打包规范）

**Comment by Mossimos** [comment]
执行完后需要重新开关加速才会继续修改host文件有重启吗

**Comment by 652436962** [comment]
> 结束后需要重新启动启动将继续执行吗？主机文件有重启

结束后，重启了没用

**Comment by Mossimos** [comment]
日志呢

**Comment by 652436962** [comment]
> 日志呢

 日志  怎么 查看，它提示端口443占用，这个端口能换个吗

![截图_选择区域_20220520094955](https://user-images.githubusercontent.com/34038936/169433846-68441d0b-6620-4c1f-b86b-5021343d5b1a.png)
![截图_选择区域_20220520095643](https://user-images.githubusercontent.com/34038936/169433851-1e374647-48f8-4191-8011-3cd568b381aa.png)

**Comment by AigioL** [comment]
在设置-通用设置-存储空间-打开Logs文件夹中查看日志，443 端口必须占用才能加速

**Comment by Mossimos** [comment]
可能是无权限监听443端口 应该会打开网页提示执行以下命令
sudo setcap cap_net_bind_service=+eip "Steam++程序路径"

**Comment by Mossimos** [comment]
lsof -i:443 也顺便看看有没有程序在占用443端口

**Comment by 652436962** [comment]
这是日志和lsof 的输出
[nlog-all-2022-05-20.log](https://github.com/BeyondDimension/SteamTools/files/8736986/nlog-all-2022-05-20.log)
![截图_选择区域_20220520144059](https://user-images.githubusercontent.com/34038936/169468592-ebe6cc50-e0ac-4000-99d9-77453b3d23a7.png)

**Comment by Mossimos** [comment]
这日志也看不出问题 
系统代理模式应该能正常用吧

**Comment by Xiyou521** [comment]
我有相同的问题，我是ubuntu20，下面是我的日志，请问如何解决呢？ #
![443](https://user-images.githubusercontent.com/109906188/199456325-8c452447-315d-4cc4-9cac-bf44e3550c59.png)

**Comment by Xiyou521** [comment]
我用系统代理模式就会断网

**Comment by chenxiex** [comment]
> 

现在只会弹出这个网页：
https://steampp.net/unixhostaccess?prot=%2Fusr%2Fshare%2FSteam%2B%2B%2FSteam%2B%2B
里面并没有提示执行sudo setcap cap_net_bind_service=+eip "Steam++程序路径"。

**Comment by Mossimos** [comment]
sudo setcap cap_net_bind_service=+eip "Steam++程序路径"。
改行只有在程序检测无法绑定 443 端口时会带参数传入然后网页才会显示该命令的。
另外发现了这个是升级 Antd 5.0 顺便升级了 react router 新版本导致 query 参数失效了谢谢提醒我马上加上。

**Comment by Mossimos** [comment]
现在已经修复了该网页会正常显示此命令了
