### ISSUE TITLE
提示端口占用之后自动弹出的页面无法完成加载，一直卡在加载动画

### ISSUE THREAD

**Issue by TOLIE-OFFICIAL** [BeyondDimension/SteamTools#1414]
平台：arch X86_64
链接地址：https://steampp.net/unixhostaccess?prot=%2Fusr%2Fshare%2FSteam%2B%2B%2FSteam%2B%2B

**Comment by Mossimos** [comment]
应该好了  404.html 加载错误了url了现在修复了

**Comment by TOLIE-OFFICIAL** [comment]
已解决，辛苦
