### ISSUE TITLE
🧐[Question] 实现原理是怎样的

### ISSUE THREAD

**Issue by einsone** [BeyondDimension/SteamTools#1416]
### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): 

1. 程序本地反代了请求， 移除 SNI 信息。这样就可以访问 Steam 了吗？如果是封 IP。还能访问吗

2. 有很多类似 *.rmbgame.net 这样的域名。是不是其实在这些域名上跑了代理的。通过这些代理才访问到诸如 Steam 的？

3. 假设是 2 这样的情况，如果想使用 *.rmbgame.net。要怎么做呢

**Comment by rmbadmin** [comment]
重复 #1011
 
2问题也非服务器反代，仅仅只是使用云端解析
