### ISSUE TITLE
🐛[BUG] 桌面版仍然无法检测更新

### ISSUE THREAD

**Issue by ClementLevi** [BeyondDimension/SteamTools#1419]
### 🐛 描述(Description)

如题，这毛病好久了

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.7.2 exe版
- 系统版本号(OS Version):  Windows 10.19044.1706
- 是否为应用商店版本(Whether it is a Store version): 否(No)

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/35921237/169697901-a2e4d8a2-eb6e-48cf-be4c-241bc6a79c49.png)

**Comment by rmbadmin** [comment]
这是正常状况，目前只有微软商店版发布了2.7.3

**Comment by AigioL** [comment]
2.7.2 版本已经发过 msix 侧载包了，商店版本必须要递增一位，才能覆盖安装，目前功能上是一样的，下个版本会是 2.7.4
