### ISSUE TITLE
🧐[Question] 管理员权限

### ISSUE THREAD

**Issue by szhu25** [BeyondDimension/SteamTools#1424]
### 🧐 问题描述(Description)

目前Windows桌面版启动时仍旧需要UAC/管理员权限， 如果只需要Steam令牌和同步Steam游戏库可不可以不要求管理员权限？ 
### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version):  Windows 11
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by AigioL** [comment]
管理员权限主要是用在加速上修改 hosts 文件，还有一些修改 Steam 的注册表与读取或写入 Steam 安装目录上的配置，这些是库存游戏与账号切换的实现，这个没有试过没有管理员权限能不能写入或修改成功

主要是拆分权限的话代码实现上比较麻烦

**Comment by AigioL** [comment]
管理员权限是在清单文件中声明的
```
<requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
```
https://github.com/BeyondDimension/SteamTools/blob/develop/src/ST.Client.Desktop.Avalonia.App/Properties/app.manifest#L7

将 level 值改为 asInvoker 就没有管理员权限了，这个清单文件编译在 exe 内容上是明文的，这段数据大概在文件末尾部分，可能直接修改 exe 的二进制数据也可以，或者从修改源码重新编译。

**Comment by AigioL** [comment]
看了下权限，```C:\Program Files (x86)``` 这个目录没有写入权限，修改 Steam 安装目录的配置文件，与自动更新程序都是要在这个目录上写入的，安装版目前是装在这个目录上

**Comment by szhu25** [comment]
明白了 谢谢！
