### ISSUE TITLE
🧐[Question] 更新更名为Toolkit之后Steam加速毫无作用?

### ISSUE THREAD

**Issue by QinCaii** [BeyondDimension/SteamTools#1437]
### 🧐 问题描述(Description)

更新之前一直在用Steam++进创意工坊，最近发现不仅创意工坊进不去了，Steam偶尔抽风掉线登录不上的时候开Toolkit也是没有任何作用... 不知道是更新之后服务出问题了还是我自己的设置有错误呢？

### 🚑 其他信息(Other Information)

- 程序版本:2.7.3
- 系统版本号: Windows 10 专业工作站版 21H2
- 是否为应用商店版本: 是

**Comment by rmbadmin** [comment]
加速项目近期没有太大改动，不管是改名前还是改名后的版本我测试都是正常的
