### ISSUE TITLE
🧐[Question] 短信服务

### ISSUE THREAD

**Issue by superHao2000** [BeyondDimension/SteamTools#1438]
### 🧐 问题描述(Description)

无法使用手机号登陆

### 🚑 其他信息(Other Information)

![170291344-e0b9dd72-5d39-4a0a-a7e0-5d7584d559ff](https://user-images.githubusercontent.com/83610194/170291971-4deb3bee-aa4b-4c64-b9f1-06ea8e661600.png)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by AigioL** [comment]
短信服务的用量用完了，不准备续费了，~~下个版本会推出邮箱注册登录~~替代短信，现在可以使用第三方账号快速登录
