### ISSUE TITLE
🧐[Question] 

### ISSUE THREAD

**Issue by DD-Bang** [BeyondDimension/SteamTools#1444]
![image](https://user-images.githubusercontent.com/67574352/170712306-36b74c08-ea23-4c7c-a276-b9de2ebfbf84.png)
网络加速列表为空，打开也会报错

**Comment by Scerendy** [comment]
请问有解决吗？我今天打开也是这样

**Comment by AigioL** [comment]
服务器磁盘写满了，数据库挂了，在修了
#1445 相同

**Comment by AigioL** [comment]
现在应该好了
