### ISSUE TITLE
🧐[Question] 

### ISSUE THREAD

**Issue by puytrf** [BeyondDimension/SteamTools#1445]
### 🧐 问题描述(Description)

客户端错误1006

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/103915558/170719279-b9aa5ae7-d754-4d6f-9877-7f867a5be3f9.png)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by AigioL** [comment]
现在应该好了
