### ISSUE TITLE
🐛[BUG] 加速后steam商店仍然出现-105错误代码与黑屏

### ISSUE THREAD

**Issue by xxxxxxxb** [BeyondDimension/SteamTools#1447]
### 🐛 描述(Description)

在开启对应加速服务后，steam商店仍然出现-105错误，无法连接
host代理显示-105
系统代理显示黑屏

- 程序版本(Program Version):V2.72
- 系统版本号(OS Version):  Windows 7旗舰版
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)
图为开启系统代理后的steam首页
![捕获](https://user-images.githubusercontent.com/96876879/170814173-e8b4b45e-0c45-4d15-ba66-926873ecc705.JPG)

**Comment by rmbadmin** [comment]
请提供程序logs文件夹错误日志

**Comment by xxxxxxxb** [comment]
已经解决，第一次使用程序没有弹出安装证书，卸载重装后就有了安装证书的提示，

**Comment by xxxxxxxb** [comment]
可能是因为第一次打开加速功能时勾选了启用脚本的问题，之前好几次安装也都是勾选了启用脚本后没有安装证书的提示。。。
