### ISSUE TITLE
👑[Enhancement] Windows 标题栏是否能统一？

### ISSUE THREAD

**Issue by elricli** [BeyondDimension/SteamTools#1454]
### 🥰 需求描述(Description)

图片来源：#1419
![image](https://user-images.githubusercontent.com/11224565/171191931-485bb5ea-fc81-4215-8088-1686267cec30.png)

### 🧐 解决方案(Solution)

统一为：`Watt Toolkit`？

不再需要后面的 `x64 v2.7.x for Windows xxx (Administrator）`

**Comment by rmbadmin** [comment]
构建信息加在标题上是为了便于区分大家反馈问题的截图出现在什么版本上，
因为有太多人反馈问题只会给个截图而不说明详细情况和提供版本信息

目前商店版和桌面版也不是同一个版本，所以标题不一样也是正常的

**Comment by elricli** [comment]
> 因为有太多人反馈问题只会给个截图而不说明详细情况和提供版本信息

啊，那就没办法了。
