### ISSUE TITLE
🐛[BUG] Linux 下无法满足构建依赖

### ISSUE THREAD

**Issue by arenekosreal** [BeyondDimension/SteamTools#1456]
### 🐛 描述(Description)

ArchiSteamFarm 这个依赖中包含工作负载 `Microsoft.iOS.Sdk` 的依赖，而这个工作负载在 Linux 下是不可用的。
### 📷 复现步骤(Steps to Reproduce)

1. 安装 `watt-toolkit-git` 这个从源代码构建的 AUR 软件包 
2. 等待错误出现

### 📄 [异常/日志]信息([Exception/Log] Information)
```
/home/zhanghua/.cache/paru/clone/watt-toolkit-git/src/dotnet-sdk/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1178: 此安装文件中任何可用的工作负载中，不存在该项目依赖的以下工作负载包: Microsoft.iOS.Sdk [/home/zhanghua/.cache/paru/clone/watt-toolkit-git/src/SteamTools/references/ArchiSteamFarm/ArchiSteamFarm.Library/ArchiSteamFarm.Library.csproj]
/home/zhanghua/.cache/paru/clone/watt-toolkit-git/src/dotnet-sdk/sdk/6.0.300/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.ImportWorkloads.targets(38,5): error NETSDK1178: 可能需要在另一个操作系统或体系结构上生成项目，或者更新 .NET SDK。 [/home/zhanghua/.cache/paru/clone/watt-toolkit-git/src/SteamTools/references/ArchiSteamFarm/ArchiSteamFarm.Library/ArchiSteamFarm.Library.csproj]
```
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): N/A
- 系统版本号(OS Version): Arch Linux
- 是否为应用商店版本(Whether it is a Store version):  否

### 🖼 截图(Screenshots)

无

**Comment by AigioL** [comment]
TFM net6.0-ios;net6.0-maccatalyst 需要对应的 workload
Xamarin.iOS10 应该不受影响

**Comment by AigioL** [comment]
像 https://github.com/BeyondDimension/ArchiSteamFarm/blob/v5.2.5.5-library/ArchiSteamFarm.Library/ArchiSteamFarm.Library.csproj#L210 这里这些地方路径分隔符用的 ```\``` 可能在 Unix 上也会报错吧，不知道 MSBuild 有转换没有，或许可以换成
```
Condition=" Exists($([System.IO.Path]::Combine('$(MSBuildProjectDirectory)','..','..','InternalsVisibleTo.cs'))) And '$(TargetFramework)' != 'net48'"
```
https://docs.microsoft.com/zh-cn/visualstudio/msbuild/property-functions?view=vs-2022

后续这些子模块的包还是拆分成 nuget 包引用比较合适，也方便构建

**Comment by arenekosreal** [comment]
现在看起来已经没有影响了，不过不确认dalao这边是否还需要这个 issue，所以就先不关闭了。如果不需要的话麻烦dalao们关一下这个 issue 了
