### ISSUE TITLE
🧐[Question] 在host代理模式下，脚本没有效果

### ISSUE THREAD

**Issue by 1394805163** [BeyondDimension/SteamTools#1457]
### 🧐 问题描述(Description)

通过阅读同样问题的issue已经开启了本地socket5代理保证clash 和steam++的共存然后发现脚本全部无效重启以后不开clash，只启动steam++也还是没有效果

对于二级代理和本地socket5的不太理解 如果在clash仅仅使用系统代理情况下是只需要开启本地socket5代理还是 二级代理也要打开，看过了几个cdn好像我都可以打开

![steam++ 1](https://user-images.githubusercontent.com/26848256/171446334-c00a2cf8-38fa-40e0-be5e-9d997aba7e49.png)
![steam++ 2](https://user-images.githubusercontent.com/26848256/171446347-060b81d8-27b9-4b05-a87b-6b4c479e0651.png)
![steam++ 3](https://user-images.githubusercontent.com/26848256/171446350-9d41bb37-722a-4846-a272-7bb88905bfb8.png)

- 程序版本(Program Version):2.72
- 系统版本号(OS Version): Windows 10 21H2
- 是否为应用商店版本(Whether it is a Store version): NO

**Comment by Mossimos** [comment]
开启代理后访问
https://local.steampp.net/?request=https%3A%2F%2Fesapi.isthereanydeal.com%2Fv01%2Fprices%2F%3Fbundleids%3D%26subids%3D631804%2C710689%26appids%3D1761390%26stores%3Dsteam%26cc%3Dcn%26coupon%3Dtrue
如果出现 秒出现 404 代表应该起作用了

**Comment by 1394805163** [comment]
> 

那本地socket5代理和二级代理要同时打开吗 然后就是到底用host模式还是系统代理模式啊
我现在是host模式仅开启本地socket5的情况下 显示的不是404是local.steampp.net 意外终止了连接

**Comment by Mossimos** [comment]
Socket5 代理 是指允许局域网通过 Socket5 连接工具箱的代理
开二级代理就行了  然后要要关闭全局模式 应该就会显示 404 了
 
开全局模式流量到不了工具箱内

**Comment by ACOMilkcoffee** [comment]
> Socket5 代理 是指允许局域网通过 Socket5 连接工具箱的代理 开二级代理就行了 然后要要关闭全局模式 应该就会显示 404 了
> 
> 开全局模式流量到不了工具箱内

我也是同样问题
我开二级代理了，然后点网页里秒出404
但是打开steam任意网页时都显示-324未知错误

**Comment by Mossimos** [comment]
秒出404 是 代理成功了 
324 可能是访问不稳定出现
确保 二级代理 连接的工具能正常访问

**Comment by ACOMilkcoffee** [comment]
> 秒出404 是 代理成功了 324 可能是访问不稳定出现 确保 二级代理 连接的工具能正常访问

我该怎么设置

**Comment by Mossimos** [comment]
确定二级代理设置的 V P N之类工具的IP和端口设置正确 且 能正常使用   否则关闭其他工具且关闭二级代理
 324 可以多次重启加速 和过段时间再试

**Comment by ACOMilkcoffee** [comment]
配置完了我重启steam试试

**Comment by ACOMilkcoffee** [comment]
部分能用，应该是脚本的问题

**Comment by ACOMilkcoffee** [comment]
谢谢了

**Comment by chencl0214** [comment]
> > 秒出404 是 代理成功了 324 可能是访问不稳定出现 确保 二级代理 连接的工具能正常访问
> 
> 我该怎么设置

操作步骤：
1.打开CFW（自己有加速节点），确保端口没改过就是7890
2.选择网络加速里的例如discord，全部启用
3.选择系统代理模式
4.代理设置打开二级代理，确保二级代理ip就是本地ip端口就是7890
5.点一键加速，看到加速成功
6.打开discord正常登录

**Comment by 1394805163** [comment]
> 确定二级代理设置的 V P N之类工具的IP和端口设置正确 且 能正常使用 否则关闭其他工具且关闭二级代理 324 可以多次重启加速 和过段时间再试

为了备战期末跑去图书馆了没看消息 问题是脚本不起作用我现在设置好了能出404 但是脚本没有效果特别是最低价的那个

**Comment by 1394805163** [comment]
> > > 秒出404 是 代理成功了 324 可能是访问不稳定出现 确保 二级代理 连接的工具能正常访问
> > 
> > 
> > 我该怎么设置
> 
> 操作步骤： 1.打开CFW（自己有加速节点），确保端口没改过就是7890 2.选择网络加速里的例如discord，全部启用 3.选择系统代理模式 4.代理设置打开二级代理，确保二级代理ip就是本地ip端口就是7890 5.点一键加速，看到加速成功 6.打开discord正常登录

我按照这个操作步骤做了但是404情况 clash 就没办法用了 端口没变什么都没改

**Comment by Mossimos** [comment]
确保最低价是在Gm脚本后面加载的然后看看Web F12 开发人员控制台有无错误输出
网络请求中筛选 https://local.steampp.net/ 该域名下脚本 确保加载了脚本

**Comment by 1394805163** [comment]
> 确保最低价是在Gm脚本后面加载的然后看看Web F12 开发人员控制台有无错误输出 网络请求中筛选 https://local.steampp.net/ 该域名下脚本 确保加载了脚本

问题好像是2级代理状态 两者冲突了我用的油管做的实验如果开启了2级代理现实了404 这个时候油管就无法访问了，如果这时候我在clash 操作多次开启关闭系统代理油管可以访问 404消失变成拒绝连接

**Comment by Mossimos** [comment]
确定设置的二级代理是  clash  的端口吗

**Comment by 1394805163** [comment]
> 确定设置的二级代理是 clash 的端口吗

确定的

**Comment by 1394805163** [comment]
就如果我用的是路由器负责科学上网要怎么设置啊我现在在学校其实无所谓如果我在家里，家里的路由器已经被我刷好了系统 直接流量走了代理的话 那么steam++要怎么设置 tun模式为 redir-host  但是我依然想要脚本的功能 我对于脚本的功能需求大于哪些网络问题哪些我都没有大问题

**Comment by Mossimos** [comment]
发现了好像是Steam++ 不会转发 没有勾选的请求 导致请求不在列表中的网站没有走二级代理

**Comment by 1394805163** [comment]
> 致请求不在列表中的网站没有走二级代

要怎么解决啊，我上次搜问题的时候我看见B站评论区也有人在问这个问题，我感觉是这个为辅比较好

**Comment by Mossimos** [comment]
在改了 之后测试后告诉你一下 
这个Host模式的特殊性不能生效用脚本
得用系统代理模式才行
