### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by 2623684696** [BeyondDimension/SteamTools#1459]
### 📷 复现步骤(Steps to Reproduce)

1. 打开加速。
2. 发现全部网站连接不上以后关闭加速。
3. 然后崩溃。

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by rmbadmin** [comment]
请提供详细错误信息和程序日志，以及尝试先搜索相似问题查看解决方案

**Comment by 2623684696** [comment]
> 请提供详细错误信息和程序日志，以及尝试先搜索相似问题查看解决方案

呃，日志去哪找？
