### ISSUE TITLE
🐛[BUG] Mac M1 安装显示文件已经损坏

### ISSUE THREAD

**Issue by mitu2** [BeyondDimension/SteamTools#1460]
### 🐛 描述(Description)

Mac M1 安装显示文件已经损坏

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.7.2
- 系统版本号(OS Version):  macOS Monterey 12.2.1 m1
- 是否为应用商店版本(Whether it is a Store version): 

### 🖼 截图(Screenshots)
<img width="376" alt="image" src="https://user-images.githubusercontent.com/71170999/171591420-0fcc5dd2-6b15-440d-8df2-66466c22c8aa.png">

**Comment by rmbadmin** [comment]
重复 #1397 #1333

**Comment by Mossimos** [comment]
@rmbadmin  你把蓝奏云里的安装包替换成
https://pan.mossimo.net:5212/s/4yiQ?path=%2F%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%AC%2FMac%2FARM
用这个打包好的DMG

百度网盘 ，Github , Gitee

**Comment by rmbadmin** [comment]
> @rmbadmin 你把蓝奏云里的安装包替换成 https://pan.mossimo.net:5212/s/4yiQ?path=%2F%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%AC%2FMac%2FARM 用这个打包好的DMG
> 
> 百度网盘 ，Github , Gitee

已经全部更换
