### ISSUE TITLE
🧐[Question] MacOS使用网络加速后网络连接出现异常

### ISSUE THREAD

**Issue by anzhilanxiao1** [BeyondDimension/SteamTools#1461]
### 🧐 问题描述(Description)

MacOS，
第一次使用steam++进行网络加速（host代理模式和系统代理模式都使用过，并且只使用过网络加速-Steam服务这一个功能）并成功在Steam上联机玩了游戏，
之后再打开电脑时发现网络连接出现了异常。
safari、chrome、QQ都无法登录/连接了，微信火狐可以登录/连接。
卸载steam++并重启也没用。
请问有遇到这种情况的吗，这是为什么，怎么解决？
谢谢！

### 🚑 其他信息(Other Information)

无

- 程序版本(Program Version):2.6.9
- 系统版本号(OS Version): 11.6.5
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by Mossimos** [comment]
检查网络设置中的代理设置
可能程序关闭的时候 设置代理关闭没关成功

**Comment by Mossimos** [comment]
尽量去使用Host模式  系统代理模式都有这毛病容易关不掉系统代理

**Comment by Mossimos** [comment]
![image](https://user-images.githubusercontent.com/26396340/171658251-aba8db30-3c8b-4352-b0be-3a13b8630b0e.png)
里面的Https代理和http代理确保是关闭的

**Comment by anzhilanxiao1** [comment]
成功解决了，感谢！
