### ISSUE TITLE
👑[Enhancement] 能否不要自动开启steam社区加速

### ISSUE THREAD

**Issue by whyjxz14** [BeyondDimension/SteamTools#1466]
### 🥰 需求描述(Description)
每次关闭steam社区加速，它下次打开还会自动开启

### 🧐 解决方案(Solution)

不自动开启

**Comment by AigioL** [comment]
在本地加速页面，右上角的 ... 按钮中 取消勾选 **启动时自动启动加速**

**Comment by whyjxz14** [comment]
> 在本地加速页面，右上角的 ... 按钮中 取消勾选 **启动时自动启动加速**

我说的不是自动启动，是取消steam服务里的steam社区以后，下次他又会自动打钩。

**Comment by AigioL** [comment]
> > 在本地加速页面，右上角的 ... 按钮中 取消勾选 **启动时自动启动加速**
> 
> 我说的不是自动启动，是取消steam服务里的steam社区以后，下次他又会自动打钩。

在列表项中取消勾选，然后在右下角托盘中退出程序，再打开，之后应该不会自动打勾了，桌面端的保存配置逻辑在退出时触发，如果直接关机这种操作导致的退出可能不会触发保存逻辑

**Comment by whyjxz14** [comment]
> > > 在本地加速页面，右上角的 ... 按钮中 取消勾选 **启动时自动启动加速**
> > 
> > 
> > 我说的不是自动启动，是取消steam服务里的steam社区以后，下次他又会自动打钩。
> 
> 在列表项中取消勾选，然后在右下角托盘中退出程序，再打开，之后应该不会自动打勾了，桌面端的保存配置逻辑在退出时触发，如果直接关机这种操作导致的退出可能不会触发保存逻辑

并没有，steam服务里的steam社区无论如何启动的时候都会自动打钩的，肯定是特殊设置

**Comment by Mossimos** [comment]
已经关闭 了默认勾选 Steam社区

**Comment by 54145a** [comment]
此问题依然存在或又存在了
插件版本 3.1.0
