### ISSUE TITLE
👑 滚动条相关

### ISSUE THREAD

**Issue by ghost** [BeyondDimension/SteamTools#1467]
### 🥰 需求描述(Description)

新用户, 所以刚开始滚动条根本不知道怎么弄出来, 研究了好久, 很蛋疼

滚动条呼出方式很别扭, 小屏下鼠标悬停和点击的有效宽度太小, 同时又与右侧边框太近了, 不容易触发. 且鼠标悬停呼出的延迟时间太久, 可以说悬停呼出基本用不上. 
即使滚动条出来了, 但与右侧边框距离太近, 拉滚动条也只有那么一小块地方能点到, 非常的难受

### 🧐 解决方案(Solution)

无

### 🚑 其他信息(Other Information)

![Snipaste_2022-06-04_14-15-54](https://user-images.githubusercontent.com/86701862/171987302-560a9321-1583-432f-a482-9b88fe54b67c.png)
只有鼠标尖左侧那么一点地方能操作滚动条, 太窄了

**Comment by rmbadmin** [comment]
嗯..但是win11的滚动条就是这样的，程序使用的fluent设计与win11保持一致
![image](https://user-images.githubusercontent.com/12234359/171987336-2fb4bece-aabb-489c-b884-dcec117401e4.png)

**Comment by nian6** [comment]
这么快
也就是说只是win10有这个问题嘛

**Comment by AigioL** [comment]
现在桌面端(Windows/macOS/Linux)使用的是 [Fluent Design System](https://www.microsoft.com/design/fluent) 
由于使用的是第三方的库实现，与官方的实际上还是有一些差异
你可以在应用商店上下载这个 App [WinUI 3 Gallery](https://apps.microsoft.com/store/detail/winui-3-gallery/9P3JFPWWDZRC) 对比官方的实现
滚动条的设计文档 https://docs.microsoft.com/en-us/windows/apps/design/controls/scroll-controls

光标相对于滚动条过小应该是 DPI 缩放导致的

**Comment by ghost** [comment]
琢磨了一下, 我这个问题出现的情景是: 
我有两个屏幕, 把软件从一个屏幕移动到另一个屏幕后就会出现这个问题
分辨率不同的原因? 我也不懂

好在恢复正常只需要随便拉动一下窗口大小就可以了
...

**Comment by rmbadmin** [comment]
> 琢磨了一下, 我这个问题出现的情景是: 我有两个屏幕, 把软件从一个屏幕移动到另一个屏幕后就会出现这个问题 分辨率不同的原因? 我也不懂
> 
> 好在恢复正常只需要随便拉动一下窗口大小就可以了 ...

这个问题应该会在下个版本发布时修复
