### ISSUE TITLE
🧐[Question] 

### ISSUE THREAD

**Issue by aiyowei126** [BeyondDimension/SteamTools#1469]
### 🧐 问题描述(Description)
Steam++不能绑定Steam账号，是Steam++账号自身登入不
![_ZAICPMBS1T{2JQM@_GCFME](https://user-images.githubusercontent.com/65696447/172033755-8c8cfb56-04c4-49da-9e2c-45398e187764.png)
![J{I EDEHU9MDZFAGM0MHAA6](https://user-images.githubusercontent.com/65696447/172033756-10477e18-99d7-48fd-940b-762fa3b021ed.png)
了

**Comment by AigioL** [comment]
你用的版本似乎已经很老了，在很早之前的版本中，快速登录就改为在浏览器中执行了，而不是在新窗口中，这也导致了与之前版本不兼容

**Comment by aiyowei126** [comment]
新版的加速不了，旧版的却能加速

**Comment by aiyowei126** [comment]
> 你用的版本似乎已经很老了，在很早之前的版本中，快速登录就改为在浏览器中执行了，而不是在新窗口中，这也导致了与之前版本不兼容
新版的加速不了，旧版的却能加速

**Comment by aiyowei126** [comment]
> 你用的版本似乎已经很老了，在很早之前的版本中，快速登录就改为在浏览器中执行了，而不是在新窗口中，这也导致了与之前版本不兼容

新版的我加速不了，旧版的却能加速这是什么情况啊

**Comment by AigioL** [comment]
> > 你用的版本似乎已经很老了，在很早之前的版本中，快速登录就改为在浏览器中执行了，而不是在新窗口中，这也导致了与之前版本不兼容
> 
> 新版的我加速不了，旧版的却能加速这是什么情况啊

旧版能加速是哪个版本？新版加速不了是什么详细错误导致的，有截图或视频吗？

**Comment by aiyowei126** [comment]
> > > 你用的版本似乎已经很老了，在很早之前的版本中，快速登录就改为在浏览器中执行了，而不是在新窗口中，这也导致了与之前版本不兼容
> > 
> > 
> > 新版的我加速不了，旧版的却能加速这是什么情况啊
> 
> 旧版能加速是哪个版本？新版加速不了是什么详细错误导致的，有截图或视频吗？


2.3版的可以正常加速，而最新版2.7.1不能加速，商场页面都打不
![KM7FLX35ED`6C%C{Z)`F3OP](https://user-images.githubusercontent.com/65696447/172047265-37bfecfd-64e9-4600-9a06-ddf1b6cd994a.png)
开

**Comment by AigioL** [comment]
最新版是 2.7.2，你可以在应用商店上直接下载 
https://apps.microsoft.com/store/detail/watt-toolkit/9MTCFHS560NG?hl=zh-cn&gl=CN

**Comment by aiyowei126** [comment]
> 最新版是 2.7.2，你可以在应用商店上直接下载 https://apps.microsoft.com/store/detail/watt-toolkit/9MTCFHS560NG?hl=zh-cn&gl=CN

这是2.7.3版的
![Y8I`8 % (KUQG%)A)8%EUV](https://user-images.githubusercontent.com/65696447/172049942-74764ba2-1f9f-4ea2-883c-1848a06bf62a.png)
2.3.0的可以正常使用

**Comment by rmbadmin** [comment]
提交程序logs文件夹日志可以帮助你更快定位问题，猜测是dns设置相关原因

**Comment by aiyowei126** [comment]
> 提交程序logs文件夹日志可以帮助你更快定位问题，猜测是dns设置相关原因

解决了，谢谢，是需要跟随系统dns代理
