### ISSUE TITLE
🐛[BUG] hosts代理模式开启github代理无法正常推送代码

### ISSUE THREAD

**Issue by Divint3** [BeyondDimension/SteamTools#1470]
### 🐛 描述(Description)

开启了hosts代理模式的github代理全部功能,发现无法推送github仓库

### 📷 复现步骤(Steps to Reproduce)

1.  开启github代理,无法推送github代码
2.  关闭github代理,会走.gitconfig中配置的代理

### 📄 [异常/日志]信息([Exception/Log] Information)

无

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.7.3
- 系统版本号(OS Version):Windows 10 企业版 LTSC 19044.1706
- 是否为应用商店版本(Whether it is a Store version): 是

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/19218225/172042876-04ddc91b-9d24-4139-8bf0-44433d3b024b.png)

**Comment by yzqdev** [comment]
可能原因是nodejs不认反向代理吧,建议使用nodejs相关的git操作时关掉代理;在用git时也不用ssh用https就好

**Comment by Divint3** [comment]
> 可能原因是nodejs不认反向代理吧,建议使用nodejs相关的git操作时关掉代理;在用git时也不用ssh用https就好

这样的话,那这个并不是一个bug咯?

**Comment by yzqdev** [comment]
可以在hexo生成的public文件夹自己手动`git push`,而不是使用`hexo d`

**Comment by Divint3** [comment]
> 可以在hexo生成的public文件夹自己手动`git push`,而不是使用`hexo d`

这个我试了,`public`目录没有`.git`文件夹,在`.git_deploy`执行也是相同的错误

![image](https://user-images.githubusercontent.com/19218225/172044725-955d080a-338e-4283-b074-cb9c8ad7c3b1.png)

**Comment by yzqdev** [comment]
在用git操作时不用ssh用https就好,用ssh会出稀奇古怪的问题

**Comment by Divint3** [comment]
> 在用git操作时不用ssh用https就好,用ssh会出稀奇古怪的问题

好的,确实,使用https确实不会出现问题,
