### ISSUE TITLE
🐛[BUG] 无法加速Google访问，希望加速Google搜索

### ISSUE THREAD

**Issue by hellomdk** [BeyondDimension/SteamTools#1519]
### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by czz404** [comment]
你是想让这个软件在应用商店消失吗。。。

**Comment by natsukiKitano** [comment]
首先这不能算是BUG。
其次Watt Toolkit要是啥都能加速那就没了。
你需要的应该是魔法而非这个软件。

**Comment by AigioL** [comment]
duplicate #1332 #1323 #331 #331
