### ISSUE TITLE
🐛[BUG] Win10 窗口尺寸逐渐变大

### ISSUE THREAD

**Issue by lyzlyslyc** [BeyondDimension/SteamTools#1520]
### 🐛 描述(Description)
在按照下面步骤操作后，UI窗口的尺寸会不断变大

### 📷 复现步骤(Steps to Reproduce)

1. 点击主程序窗口的X按钮，主程序最小化到托盘
2. 点击托盘小图标，主程序窗口重新弹出
3. 此时重复最小化->恢复的操作，主程序窗口的尺寸会逐渐变大

### 📄 [异常/日志]信息([Exception/Log] Information)
无

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.7.2
- 系统版本号(OS Version):Windows 10.19044.1706
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)

![QQ录屏20220610120036 00_00_00-00_00_30](https://user-images.githubusercontent.com/62510112/172988014-18cac2ea-a6d8-40f1-b1cb-8a78511268a1.gif)

**Comment by zxba** [comment]
linux上也有这个bug。

**Comment by lengshuOvO** [comment]
点缩小到任务栏，在点击任务栏窗口，就会一直放大

**Comment by rmbadmin** [comment]
重复 #1339
