### ISSUE TITLE
🐛[BUG] 编译代码异常

### ISSUE THREAD

**Issue by invokerw** [BeyondDimension/SteamTools#1522]
### 🐛 描述(Description)

编译代码异常

### 📷 复现步骤(Steps to Reproduce)

1.安装好 vs2022 preview 之后，编译启动报错 

### 📄 [异常/日志]信息([Exception/Log] Information)
Package.Current.Id.Name 找不到所导致的
“System.InvalidOperationException”(位于 WinRT.Runtime.dll 中)
详情见截图

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): github 最新代码
- 系统版本号(OS Version): Windows 10.19042.844(see winver)
- 是否为应用商店版本(Whether it is a Store version): 否(No)

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/20391001/173210839-6380fde7-3e1b-49d0-af4b-820bc1d7c1a8.png)

**Comment by AigioL** [comment]
桌面版的启动项目是 ```ST.Client.Avalonia.App```
DesktopBridge 的启动项目是 ```ST.Client.Avalonia.App.Bridge.Package```

Package.Current.Id.Name 这个 API 必须在打包的应用中调用，启动项目不应该设为 ```Steam++```

**Comment by invokerw** [comment]
> 

好的。万分感谢。
