### ISSUE TITLE
系统代理下不关闭加速重启电脑后访问网页报代理服务器有问题

### ISSUE THREAD

**Issue by ghost** [BeyondDimension/SteamTools#1523]
### 系统代理下直接重启电脑后访问网页报代理服务器有问题 (Hosts代理没有)

只加速了github

#### 重启电脑后访问网页
![Snipaste_2022-06-12_11-29-43](https://user-images.githubusercontent.com/86701862/173213589-6ab4cb29-d91e-4738-8977-db2520e382d3.png)

#### 其他
最近正常访问github有这个问题, 会不会和这个有关?
![Snipaste_2022-06-12_11-48-38](https://user-images.githubusercontent.com/86701862/173213544-fd466c72-c638-4ac3-9e1f-c19c33e8b76e.png)

### 📷 复现步骤(Steps to Reproduce)

1.  开启系统代理
2.  重启电脑
3. 访问web网站

### 📄 [异常/日志]信息([Exception/Log] Information)
重启电脑后首次打开软件
![Snipaste_2022-06-12_11-29-32](https://user-images.githubusercontent.com/86701862/173213423-d6f9334c-e332-4c7f-83e3-57ea961aa28c.png)

日志
![Snipaste_2022-06-12_11-39-33](https://user-images.githubusercontent.com/86701862/173213429-09a6a941-468c-481b-904b-ef8b8a73db83.png)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): v2.7.3
- 系统版本号(OS Version): Windows 10.19044.1706  
- 是否为应用商店版本(Whether it is a Store version):  是

**Comment by Mossimos** [comment]
关闭 系统设置 网络 代理 中的使用代理服务器 
这是程序未正常关闭导致没有取消使用代理服务器

**Comment by ghost** [comment]
因为用的时候开启加速就挂后台不管了, 关机的时候也没必要专门去关一下代理
hosts模式用的443端口经常被其他程序占用, 懒得每次都去停止进程

有没有办法可以在关机前自动关闭这个代理
把软件调成开机自启动能不能解决这个问题

**Comment by Mossimos** [comment]
这个一般直接开启加速应该就正常了
软件开机启动 然后自动开启加速应该可以
