### ISSUE TITLE
🐛[BUG] 手机版登录不了QQ，无论是用TIM还是普通QQ都试过了，都不行

### ISSUE THREAD

**Issue by cxtznb** [BeyondDimension/SteamTools#1556]
### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): 

### 🖼 截图(Screenshots)

![efdf475539a7be9143a4d7bf74c5fe9](https://user-images.githubusercontent.com/107716226/174387041-af9e75e5-f279-4f17-8449-1314ab5cbd66.jpg)
![f49a8e4bf84fec9bebd6ff83577e3ce](https://user-images.githubusercontent.com/107716226/174387064-01f28251-9503-4b14-b57c-7db46b231f64.jpg)

**Comment by AigioL** [comment]
Android 版本现在没有账号相关的功能，可以不用登录
