### ISSUE TITLE
🧐[Question] 存在其它代理软件情况下脚本无法正确使用

### ISSUE THREAD

**Issue by TABRIS1412** [BeyondDimension/SteamTools#1559]
### 🧐 问题描述(Description)

在有使用其它代理软件的情况下，即使对steam加速域名添加例外任然无法启用脚本。具体表现：

1.Steam++启用Host模式，Clash开启系统代理——无法使用脚本，梯子正常

2.Steam++后启用Host模式，Clash先开启系统代理——无法使用脚本，梯子正常

3.Steam++先启用系统代理模式，Clash后开启系统代理——无法使用脚本，梯子正常

4.Steam++后启用系统代理模式，Clash先开启系统代理——脚本使用正常，但梯子无法打开除Steam++已加速外的网址。

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):  2.7.3
- 系统版本号(OS Version): Windows 10.19044.1566
- 是否为应用商店版本(Whether it is a Store version): 是

**Comment by rmbadmin** [comment]
使用其他代理时，请使用代理设置的二级代理功能，
其他代理会与Steam++系统代理模式冲突，
至于hosts模式优先级是比系统代理低的，不管是开了什么系统代理，当代理生效时hosts就不会在生效

**Comment by TABRIS1412** [comment]
求教有关二级代理功能如何设置。
使用HTTP模式填写地址端口号后启动二级代理模式后是否还需要启动设置外面的一键加速功能？
不胜感谢
