### ISSUE TITLE
🧐[Question] 

### ISSUE THREAD

**Issue by drsongs** [BeyondDimension/SteamTools#1571]
### 🧐 问题描述(Description)
用steam++加速的时候，个人卡牌库存打不开，换了302和uu都可以

### 🚑 其他信息(Other Information)

这是截图
![image](https://user-images.githubusercontent.com/101931122/174830687-cb1c033f-58bc-4256-8001-63a5cb76e7a5.png)

**Comment by rmbadmin** [comment]
我测试并没有此问题
