### ISSUE TITLE
🧐[Question] Watt Toolkit微软商店版本使用卡顿严重

### ISSUE THREAD

**Issue by lsyanling** [BeyondDimension/SteamTools#1572]
### 🧐 问题描述(Description)

左侧菜单栏的切换卡顿严重，例如，从“网络加速”切换至“脚本配置”平均需要等待4秒，反之平均需要等待7秒，有时窗口标题还出现“未响应”字样。
即使是同一个大菜单下也有卡顿，例如，从“网络加速”下的“Steam服务”切换至“Origin”时有约2秒的卡顿，勾选复选框大约延迟0.3秒。
从最小化状态切换至前台时窗口界面会黑屏约1秒，任务管理器显示，应用位于前台时的CPU占用经常超过30%。
我想知道是否仅有我出现这样的情况，应该如何解决。

### 🚑 其他信息(Other Information)

我的CPU是i5 9300H，16G内存，无独立显卡。
无论是否启用硬件加速，以及使用或不使用任何透明材质，卡顿都相当严重。

- 程序版本(Program Version): 2.7.3
- 系统版本号(OS Version):  Windows 11 22621.105
- 是否为应用商店版本(Whether it is a Store version):  是

**Comment by rmbadmin** [comment]
可能是没有独显所以无法硬件加速的原因吧，avalonia的UI性能确实比较拉胯，或许得等到之后更换到MAUI在看能不能好些了

**Comment by AigioL** [comment]
i5 9300H 是有核显 英特尔® 超核芯显卡 630 的
https://www.intel.cn/content/www/cn/zh/products/sku/191075/intel-core-i59300h-processor-8m-cache-up-to-4-10-ghz/specifications.html

你是否安装了最新版的显卡驱动？
[Intel® Graphics – Windows* DCH Drivers](https://downloadmirror.intel.com/732078/igfx_win_101.1994.exe)

非应用商店版本也卡顿吗？

**Comment by Mossimos** [comment]
我在同为630核显的 i7 4700mq下测试 只发现启动比较慢 切换窗口没有说卡几秒的情况 CPU是确实超过20%

**Comment by lsyanling** [comment]
> i5 9300H 是有核显 英特尔® 超核芯显卡 630 的 https://www.intel.cn/content/www/cn/zh/products/sku/191075/intel-core-i59300h-processor-8m-cache-up-to-4-10-ghz/specifications.html
> 
> 你是否安装了最新版的显卡驱动？ [Intel® Graphics – Windows* DCH Drivers](https://downloadmirror.intel.com/732078/igfx_win_101.1994.exe)
> 
> 非应用商店版本也卡顿吗？

下面是我的UHD630显卡驱动版本，它的大版本号比网站上的更高，甚至比beta的版本号更高，我不清楚这是为什么，但我想应当是最新版的。
如果确有必要，我可以试试重新安装显卡驱动，但目前来说，它对其它所有的应用程序都支持得很好。

![image](https://user-images.githubusercontent.com/65443331/174943531-5167035c-7b59-424b-94d0-c90ed33e466d.png)

我刚刚测试了非应用商店版本，也是一样的卡顿。

**Comment by lsyanling** [comment]
> 我在同为630核显的 i7 4700mq下测试 只发现启动比较慢 切换窗口没有说卡几秒的情况 CPU是确实超过20%

因为启动时间并不是很影响使用，所以我没有关注，实际上我这里启动大约需要20多秒。启动时，它保持一个透明边框长达10秒，然后才能显示窗口界面。
不仅是切换窗口卡，鼠标滚轮操作滚动条、勾选复选框也有明显卡顿。

**Comment by lsyanling** [comment]
> 可能是没有独显所以无法硬件加速的原因吧，avalonia的UI性能确实比较拉胯，或许得等到之后更换到MAUI在看能不能好些了

实际上，我使用的Windows 11的新任务管理器在切换菜单时也有卡顿，但表现得没有这么明显，卡顿不会超过1秒。

**Comment by AigioL** [comment]
> > i5 9300H 是有核显 英特尔® 超核芯显卡 630 的 https://www.intel.cn/content/www/cn/zh/products/sku/191075/intel-core-i59300h-processor-8m-cache-up-to-4-10-ghz/specifications.html
> > 你是否安装了最新版的显卡驱动？ [Intel® Graphics – Windows* DCH Drivers](https://downloadmirror.intel.com/732078/igfx_win_101.1994.exe)
> > 非应用商店版本也卡顿吗？
> 
> 下面是我的UHD630显卡驱动版本，它的大版本号比网站上的更高，甚至比beta的版本号更高，我不清楚这是为什么，但我想应当是最新版的。 如果确有必要，我可以试试重新安装显卡驱动，但目前来说，它对其它所有的应用程序都支持得很好。
> 
> ![image](https://user-images.githubusercontent.com/65443331/174943531-5167035c-7b59-424b-94d0-c90ed33e466d.png)
> 
> 我刚刚测试了非应用商店版本，也是一样的卡顿。

驱动的版本号更高应该是因为更高的版本驱动是 OEM 的定制版，Intel 官网上的是通用版本的驱动
https://www.intel.cn/content/www/cn/zh/download/19344/intel-graphics-windows-dch-drivers.html
```
详细说明
注： 安装此英特尔通用显卡驱动程序将覆盖您的计算机制造商 （OEM） 自定义的驱动程序。
OEM 驱动程序是精心挑选的，包括针对特定于平台的问题的定制功能和解决方案。
通用英特尔驱动程序为用户提供了 OEM 可能尚未定制的最新、最强大的功能增强和错误修复，以满足平台特定的需求。
用户可以在 OEM 网站查看是否与 OEM 版本匹配。
```

@Mossimos i7 4700MQ 的核显不是这款

大概率可能是 ```Xe 专用、第六代至第十二代智能英特尔® 酷睿™处理器显卡``` 与 [SkiaSharp](https://github.com/mono/SkiaSharp) 的兼容问题

~~但 Chromium 内核的浏览器，包括 Chrome/Edge 以及 [electron](https://www.electronjs.org/) 也是用到的 Skia，表现效果通常都比 SkiaSharp 要好，比如在 Avalonia.Skia 以及 Uno 上。~~

**你可以在应用商店上下载这两款应用，观察一下是否同样卡顿**
- [Lunacy-图形设计软件](https://apps.microsoft.com/store/detail/lunacy%E5%9B%BE%E5%BD%A2%E8%AE%BE%E8%AE%A1%E8%BD%AF%E4%BB%B6/9PNLMKKPCLJJ?hl=zh-cn&gl=CN)
- [Avalonia Control Gallery](https://apps.microsoft.com/store/detail/avalonia-control-gallery/9PGHN6QNJ3RP?hl=zh-cn&gl=CN)

如果还是有卡顿可以试下安装通用的显卡驱动覆盖 OEM 版的

**Comment by Mossimos** [comment]
确实我记错了 是 hd 4600 但是比 630性能更低 没有这切换卡顿几秒的现象

**Comment by AigioL** [comment]
> 确实我记错了 是 hd 4600 但是比 630性能更低 没有这切换卡顿几秒的现象

UHD Graphics 630 不如 HD Graphics 4600 肯定是驱动开倒车了，搞不好 Xe 的独显 锐炬®  也会有这个问题

**Comment by AigioL** [comment]
刚在一台 [i3-1115G4](https://www.intel.cn/content/www/cn/zh/products/sku/208652/intel-core-i31115g4-processor-6m-cache-up-to-4-10-ghz/specifications.html?wapkw=i3%201115g4) 的机器上测试了 显卡是 ```Intel® UHD Graphics```，没有卡顿
不过是 Win10 驱动为 30.0.101.1660，所以这应该是驱动或者 Win11 的问题

**Comment by lsyanling** [comment]
> > > i5 9300H 是有核显 英特尔® 超核芯显卡 630 的 https://www.intel.cn/content/www/cn/zh/products/sku/191075/intel-core-i59300h-processor-8m-cache-up-to-4-10-ghz/specifications.html
> > > 你是否安装了最新版的显卡驱动？ [Intel® Graphics – Windows* DCH Drivers](https://downloadmirror.intel.com/732078/igfx_win_101.1994.exe)
> > > 非应用商店版本也卡顿吗？
> > 
> > 
> > 下面是我的UHD630显卡驱动版本，它的大版本号比网站上的更高，甚至比beta的版本号更高，我不清楚这是为什么，但我想应当是最新版的。 如果确有必要，我可以试试重新安装显卡驱动，但目前来说，它对其它所有的应用程序都支持得很好。
> > ![image](https://user-images.githubusercontent.com/65443331/174943531-5167035c-7b59-424b-94d0-c90ed33e466d.png)
> > 我刚刚测试了非应用商店版本，也是一样的卡顿。
> 
> 驱动的版本号更高应该是因为更高的版本驱动是 OEM 的定制版，Intel 官网上的是通用版本的驱动 https://www.intel.cn/content/www/cn/zh/download/19344/intel-graphics-windows-dch-drivers.html
> 
> ```
> 详细说明
> 注： 安装此英特尔通用显卡驱动程序将覆盖您的计算机制造商 （OEM） 自定义的驱动程序。
> OEM 驱动程序是精心挑选的，包括针对特定于平台的问题的定制功能和解决方案。
> 通用英特尔驱动程序为用户提供了 OEM 可能尚未定制的最新、最强大的功能增强和错误修复，以满足平台特定的需求。
> 用户可以在 OEM 网站查看是否与 OEM 版本匹配。
> ```
> 
> @Mossimos i7 4700MQ 的核显不是这款
> 
> 大概率可能是 `Xe 专用、第六代至第十二代智能英特尔® 酷睿™处理器显卡` 与 [SkiaSharp](https://github.com/mono/SkiaSharp) 的兼容问题
> 
> ~但 Chromium 内核的浏览器，包括 Chrome/Edge 以及 [electron](https://www.electronjs.org/) 也是用到的 Skia，表现效果通常都比 SkiaSharp 要好，比如在 Avalonia.Skia 以及 Uno 上。~
> 
> **你可以在应用商店上下载这两款应用，观察一下是否同样卡顿**
> 
> * [Lunacy-图形设计软件](https://apps.microsoft.com/store/detail/lunacy%E5%9B%BE%E5%BD%A2%E8%AE%BE%E8%AE%A1%E8%BD%AF%E4%BB%B6/9PNLMKKPCLJJ?hl=zh-cn&gl=CN)
> * [Avalonia Control Gallery](https://apps.microsoft.com/store/detail/avalonia-control-gallery/9PGHN6QNJ3RP?hl=zh-cn&gl=CN)
> 
> 如果还是有卡顿可以试下安装通用的显卡驱动覆盖 OEM 版的

我尝试了这两款应用，均有卡顿，第一款应用与Watt Toolkit如出一辙，第二款卡顿感轻得多，不超过0.5秒。
我已经安装了Intel UHD630的最新通用驱动30.0.101.1994，但不起作用。
实际上，UHD630的驱动安装程序也一样卡顿，软件许可协议的滚动条难以拖动。

**Comment by AigioL** [comment]
你用的是 Win11 22H2 的预览版是吧？
可能是 Win 11 的问题，更新到最新的 ```22621.160``` 试试

如果还是不行可以在 [反馈中心](https://aka.ms/WIPFeedbackHub) 上提交问题给微软

**Comment by lsyanling** [comment]
> 你用的是 Win11 22H2 的预览版是吧？ 可能是 Win 11 的问题，更新到最新的 `Windows 11 Insider Preview Build 22621.160` 试试
> 
> 如果还是不行可以在 [反馈中心](https://aka.ms/WIPFeedbackHub) 上提交问题给微软

是的，beta通道的预览版。
可能因为是联想笔记本，我并未收到22621.160的推送，我已经提交了关于未收到推送的反馈，暂未得到回复。
我正准备向微软反馈该问题，如果22621.160能够解决的话更好，但我感觉不太可能。

谢谢您的建议！

**Comment by Lwll-6** [comment]
我也遇到了和你一样相同的问题

**Comment by Steve-337** [comment]
我是刚刚突然卡了……之前好好的，系统更新是暂停状态（AMD处理器，英伟达独显，显卡混合模式）

**Comment by lsyanling** [comment]
> 我也遇到了和你一样相同的问题

你也是`Windows 11 22H2`且只有 Intel 的核显吗

**Comment by Steve-337** [comment]
刚刚打开，在系统没有关键更新的情况下不再卡顿，变正常了（唯一一个更新是硬盘驱动更新）

**Comment by AigioL** [comment]
应该与 https://www.ithome.com/0/626/040.htm 相关
```
现有大量用户反馈称，最近的 Windows 11 内部版本包括 22H2 RTM 版本 22621 都受到了影响。
从用户反馈来看，大多数 CPU 占用率过高（90-100%)，从而导致整个系统变慢，进而导致应用程序无法正常使用。
```

**Comment by lsyanling** [comment]
> 应该与 https://www.ithome.com/0/626/040.htm 相关
> 
> ```
> 现有大量用户反馈称，最近的 Windows 11 内部版本包括 22H2 RTM 版本 22621 都受到了影响。
> 从用户反馈来看，大多数 CPU 占用率过高（90-100%)，从而导致整个系统变慢，进而导致应用程序无法正常使用。
> ```

Visual Studio 似乎是变慢了，我也认为 Watt Toolkit 的 CPU 占用率不应该经常超过 30% ，但我同时运行着多个 .NET 程序，CPU 占用率没有 90% 那么夸张。可能一部分 .NET 框架受到的冲击更大？

联想笔记本仍未收到更新推送。

**Comment by AigioL** [comment]
> 



> > 应该与 https://www.ithome.com/0/626/040.htm 相关
> > ```
> > 现有大量用户反馈称，最近的 Windows 11 内部版本包括 22H2 RTM 版本 22621 都受到了影响。
> > 从用户反馈来看，大多数 CPU 占用率过高（90-100%)，从而导致整个系统变慢，进而导致应用程序无法正常使用。
> > ```
> 
> Visual Studio 似乎是变慢了，我也认为 Watt Toolkit 的 CPU 占用率不应该经常超过 30% ，但我同时运行着多个 .NET 程序，CPU 占用率没有 90% 那么夸张。可能一部分 .NET 框架受到的冲击更大？
> 
> 联想笔记本仍未收到更新推送。

现在 .NET 6+ 的程序不多吧，像 Blazor、JetBrains Rider 是肯定用，Visual Studio 主要还是在旧的 .Net Framework 4.8 上，应该对 .Net Framework 的影响较小，毕竟这个是 Windows 系统组件，像 IIS 计算机管理，等组件还是跑在这个上面的

**Comment by lsyanling** [comment]
我通过转到 `Release Preview 通道` 更新到了 `22621.169` ，`Watt Toolkit` 的卡顿有了明显改善，启动耗时约 5~10 秒，菜单项的切换也降低到了 4 秒以下。相比于之前，至少算是可以使用的状态了。

对于目前正位于 `Beta 通道` 的联想电脑，切换到 `Release Preview 通道` 也许是此问题的一个临时的解决方案。在更新完毕后，可以切换回 `Beta 通道` 。

但该版本对 Visual Studio、任务管理器等应用还未做优化。

悲报，我的Microsoft Office也变得卡卡的了。

**Comment by lsyanling** [comment]
我跑路了，直接上 `dev` 通道，现在极其流畅。

除了右下角的水印，我应该早就这样做的。

如果还处于 `22621` 版本且仍受这个问题的困扰，跑路前往 `dev` 通道是一个选择。
