### ISSUE TITLE
🧐[Question] windows文件夹里面无法正常创建快捷方式，打开后发现里面文件都带黄色小锁头，请问该如何去除

### ISSUE THREAD

**Issue by 8260105** [BeyondDimension/SteamTools#1573]
### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): yes

**Comment by rmbadmin** [comment]
要给微软商店的应用程序添加快捷方式，你需要执行以下操作来添加
开始 -  运行  输入 shell:appsfolder 回车执行 - 再打开的应用列表中找到 Watt Toolkit 右键创建快捷方式
