### ISSUE TITLE
🧐[Question] 支持的操作系统问题，实测下来不确定为何这么写。

### ISSUE THREAD

**Issue by fuchanghao** [BeyondDimension/SteamTools#1576]
### 🧐 问题描述(Description)

官方声称不支持Windows Server 2008 R2 SP1

> Windows Server 2008 R2 SP1
> 仅可使用 1.X 版本，2.X 开始不受支持，建议升级到更高版本

我像Windows 7一样打了ESU补丁，测试运行，Windows 7遇到的设置小窗口显示不了边框的问题，一样存在。

所以想了解不兼容的问题到底出在哪里，Windows Server 2008 R2 SP1不行？(两者共用同一个ESU更新补丁)

况且使用的依赖[FluentAvalonia](https://github.com/amwx/FluentAvalonia)已经不再支持Windows 7和8.1。(不过我测试8.1目前UI没有问题)

### 🚑 其他信息(Other Information)

Windows 7
![屏幕截图 2022-06-23 150515](https://user-images.githubusercontent.com/11471475/175238156-7ebb37e7-8382-4ee2-9791-b1e9050c45fb.png)

Windows Server 2008 R2 SP1
![屏幕截图 2022-06-23 140847](https://user-images.githubusercontent.com/11471475/175227773-17ce73d2-f2c8-465c-8ceb-8b7b8648d893.png)

![屏幕截图 2022-06-23 150604](https://user-images.githubusercontent.com/11471475/175238097-6ea5c9fc-489a-437e-a6a1-0cacd216c1e9.png)

- 程序版本(Program Version): 2.7.2
- 系统版本号(OS Version): Windows Server 2008 R2 SP1 (7601.25983)  /  Windows 7 Ultimate (7601.25983)
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by AigioL** [comment]
因为 Windows Server 2008 R2 SP1 不在 [.NET 6 - Supported OS versions](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md#windows) 列表中

FluentAvalonia 用了一些 win8 开始有的 API，比如获取主题色之类的颜色相关，早期版本是直接调用的，后来加了不兼容的系统上给予默认颜色，应该是兼容其他系统了，只是 README 上没改

**Comment by rmbadmin** [comment]
我们并不会特意去支持和测试这些过时的操作系统了，所以不保证可用，
在过不久也可能会抛弃对win7的支持，因为在这上面徒费精力并不划算。

**Comment by AigioL** [comment]
.NET 7.0 预计于今年 11 月发布，迁移后应该将不再支持 Windows 7 和 8.1 以及对应的 Server 版本。
https://github.com/dotnet/core/blob/main/roadmap.md#upcoming-ship-dates
https://github.com/dotnet/core/issues/7556

**Comment by fuchanghao** [comment]
> .NET 7.0 预计于今年 11 月发布，迁移后应该将不再支持 Windows 7 和 8.1 以及对应的 Server 版本。 https://github.com/dotnet/core/blob/main/roadmap.md#upcoming-ship-dates [dotnet/core#7556](https://github.com/dotnet/core/issues/7556)

[Windows Server 2012/R2 ESU](https://docs.microsoft.com/en-us/lifecycle/faq/extended-security-updates) will start mid-way through the .NET 7 lifecycle, in October 2023. We will offer support for Windows Server 2012/R2 throughout .NET 7 and .NET 8

从这里来看，Windows 8.1应该还可以继续支持.NET 7和8，从之前的操作来看，是可以像Windows 7那样安装的Server版的补丁继续兼容Windows 8.1的。

**Comment by fuchanghao** [comment]
> 因为 Windows Server 2008 R2 SP1 不在 [.NET 6 - Supported OS versions](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md#windows) 列表中
> 
> FluentAvalonia 用了一些 win8 开始有的 API，比如获取主题色之类的颜色相关，早期版本是直接调用的，后来加了不兼容的系统上给予默认颜色，应该是兼容其他系统了，只是 README 上没改

我实测目前.NET 6运行库像Windows 7一样正常安装。

![屏幕截图 2022-06-23 172402](https://user-images.githubusercontent.com/11471475/175265672-9748780d-7f87-4c1c-b16a-225d93ab1d30.png)

**Comment by AigioL** [comment]
Windows 8.1 没有出现在 Lifecycle FAQ - Extended Security Updates 的表格中，不见得能装 Server 版本的 ESU 补丁
你可以在 生命周期页面上看到 Win 8.1 是没有 ESU 的数据
https://docs.microsoft.com/en-us/lifecycle/products/windows-81
https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2012-r2

.NET 6 现在虽然能够运行在 Windows 7 / Windows Server 2008 R2 SP1，但根据该公告 https://github.com/dotnet/announcements/issues/226
很明显将在 2023/01 时不能再安装上或正常运行，按现在每个月一个小版本发行周期，大概是 6.0.13 时将结束支持

.NET 7 在公告中明确不支持 Windows 7 / Windows 8.1，虽然没写 Windows Server 2008 R2 SP1 但应该也包含在内

.NET 8 中应该会直接删除这些系统的兼容代码，可能更早，也许在 .NET 7 中就删了，这样就算有 ESU 也跑不了了

已更新了 README 中 Windows Server 2008 R2 SP1 条目

**Comment by fuchanghao** [comment]
> Windows 8.1 没有出现在 Lifecycle FAQ - Extended Security Updates 的表格中，不见得能装 Server 版本的 ESU 补丁 你可以在 生命周期页面上看到 Win 8.1 是没有 ESU 的数据 https://docs.microsoft.com/en-us/lifecycle/products/windows-81 https://docs.microsoft.com/en-us/lifecycle/products/windows-server-2012-r2
> 
> .NET 6 现在虽然能够运行在 Windows 7 / Windows Server 2008 R2 SP1，但根据该公告 [dotnet/announcements#226](https://github.com/dotnet/announcements/issues/226) 很明显将在 2023/01 时不能再安装上或正常运行，按现在每个月一个小版本发行周期，大概是 6.0.13 时将结束支持
> 
> .NET 7 在公告中明确不支持 Windows 7 / Windows 8.1，虽然没写 Windows Server 2008 R2 SP1 但应该也包含在内
> 
> .NET 8 中应该会直接删除这些系统的兼容代码，可能更早，也许在 .NET 7 中就删了，这样就算有 ESU 也跑不了了
> 
> 已更新了 README 中 Windows Server 2008 R2 SP1 条目

能装 Server 版本的 ESU 补丁这个是一定能装的，甚至现在早就停止更新的Windows Vista/Windows 8都可以通过Windows Server 2008/Windows Server 2012的补丁续命。至于怎么让补丁装上就要看[abbodi1406](https://github.com/abbodi1406)的工具了。

而且微软的支持(support)和兼容(能运行)不是一个意思。很多情况下支持是指：“你是一个Windows 8.1用户，遇到了这个.NET bug提交之后微软不理会，你是一个Windows Server 2012 R2的用户，提交了这个.NET Bug微软才理会”。
