### ISSUE TITLE
🐛[BUG]Github加速后vscode和jetbrains的Github copilot无法使用 

### ISSUE THREAD

**Issue by mendax1234** [BeyondDimension/SteamTools#1579]
### 🐛 描述(Description)

使用github加速后，vscode和jetbrains软件里的github copilot无法使用，报错如下
![image](https://user-images.githubusercontent.com/62934294/175446808-fe7cabd8-4c7e-47f0-8c9d-baeeacc7eae7.png)

### 📷 复现步骤(Steps to Reproduce)

1. 开启软件中的github加速
2. 打开vscode，并安装github copilot
3. 登录github账号，发现无法登录

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):最新的版本
- 系统版本号(OS Version): Windows10 21H2
- 是否为应用商店版本(Whether it is a Store version): Yes

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/62934294/175446886-e636c5de-53fb-4b2e-b013-3cfa607865a5.png)

**Comment by rmbadmin** [comment]
这个报错是证书信任的问题，得看看有没有办法让Github Copilot插件信任第三方证书

**Comment by mendax1234** [comment]
不知道啊，大佬能帮忙看一下吗？

**Comment by mendax1234** [comment]
> 这个报错是证书信任的问题，得看看有没有办法让Github Copilot插件信任第三方证书

请问这个软件有iOS版吗？还有就是为什么Windows端的内存占用达300多MB，好大。

**Comment by rmbadmin** [comment]
> > 这个报错是证书信任的问题，得看看有没有办法让Github Copilot插件信任第三方证书
> 
> 请问这个软件有iOS版吗？还有就是为什么Windows端的内存占用达300多MB，好大。

大部分内存都是程序UI和steam游戏库存占用的

**Comment by rmbadmin** [comment]
> > > 这个报错是证书信任的问题，得看看有没有办法让Github Copilot插件信任第三方证书
> > 
> > 
> > 请问这个软件有iOS版吗？还有就是为什么Windows端的内存占用达300多MB，好大。
>
大部分内存都是程序UI和steam游戏库存占用的，ios版正在开发，
至于Github Copilot插件证书信任问题的解决方案我暂时没有时间

**Comment by mendax1234** [comment]
> > > > 这个报错是证书信任的问题，得看看有没有办法让Github Copilot插件信任第三方证书
> > > 
> > > 
> > > 请问这个软件有iOS版吗？还有就是为什么Windows端的内存占用达300多MB，好大。
> 
> 大部分内存都是程序UI和steam游戏库存占用的，ios版正在开发， 至于Github Copilot插件证书信任问题的解决方案我暂时没有时间

好吧，还有我发现开系统代理，证书信任的问题就没有了。
还有就是因为我不玩steam，只是对github，discord等加速有需求，所以有什么办法能关掉steam游戏库占用的内存吗？

**Comment by AigioL** [comment]
> > > > > 这个报错是证书信任的问题，得看看有没有办法让Github Copilot插件信任第三方证书
> > > > 
> > > > 
> > > > 请问这个软件有iOS版吗？还有就是为什么Windows端的内存占用达300多MB，好大。
> > 
> > 
> > 大部分内存都是程序UI和steam游戏库存占用的，ios版正在开发， 至于Github Copilot插件证书信任问题的解决方案我暂时没有时间
> 
> 好吧，还有我发现开系统代理，证书信任的问题就没有了。 还有就是因为我不玩steam，只是对github，discord等加速有需求，所以有什么办法能关掉steam游戏库占用的内存吗？

关掉主窗口后内存占用应该在 90 MB 以内，这是最低的值了

**Comment by mendax1234** [comment]
> 关掉主窗口后内存占用应该在 90 MB 以内，这是最低的值了

可是我观点主窗口，就缩小到任务栏里，还是占用300MB内存。。。

**Comment by AigioL** [comment]
> 



> > 关掉主窗口后内存占用应该在 90 MB 以内，这是最低的值了
> 
> 可是我观点主窗口，就缩小到任务栏里，还是占用300MB内存。。。

提供截图看看

**Comment by mendax1234** [comment]
> > 
> 
> > > 关掉主窗口后内存占用应该在 90 MB 以内，这是最低的值了
> > 
> > 
> > 可是我观点主窗口，就缩小到任务栏里，还是占用300MB内存。。。
> 
> 提供截图看看


![image](https://user-images.githubusercontent.com/62934294/175471646-49c76626-06eb-4d69-84ce-b23d47a3f2ce.png)
@AigioL 现在200多，感觉其实差不太多。。

**Comment by mendax1234** [comment]
所以怎么说，为什么内存占用这么大？

**Comment by rmbadmin** [comment]
一个avalonia的空窗口也会至少占用100MB左右内存，这是正常占用

**Comment by mendax1234** [comment]
emmm，啊这，所以这对只想加速github和discord，twitch来说不是特别友好。。。

**Comment by rmbadmin** [comment]
> emmm，啊这，所以这对只想加速github和discord，twitch来说不是特别友好。。。

你可以直接用科学上网工具或者其他反代工具，steam++的反代功能并不是steam++的主要功能

**Comment by mendax1234** [comment]
反代工具的话vscode和jetbrains的github copilot无法使用。。。

**Comment by mendax1234** [comment]
我也是把所有github加速的工具都试了一遍，才用steam++的

**Comment by rmbadmin** [comment]
> 我也是把所有github加速的工具都试了一遍，才用steam++的

会考虑之后做一个不加载UI的仅运行加速服务的启动参数，这样应该能最小占用仅运行反代功能

**Comment by mendax1234** [comment]
> > 我也是把所有github加速的工具都试了一遍，才用steam++的
> 
> 会考虑之后做一个不加载UI的仅运行加速服务的启动参数，这样应该能最小占用仅运行反代功能

太好了，希望能早日做出来，感谢大佬！

**Comment by mendax1234** [comment]
还有，好奇的问一下大佬的discord加速功能是如何做的，能否介绍一下 @rmbadmin
