### ISSUE TITLE
窗口自动变大🐛[BUG] 

### ISSUE THREAD

**Issue by Herboct** [BeyondDimension/SteamTools#1582]
### 🐛 描述(Description)

窗口大小在每次最小化或关闭之后，再次打开会变大一圈，每次重复操作都是这样，需要每次手动调整大小很不方便

### 📷 复现步骤(Steps to Reproduce)

1. 最小化或关闭窗口
2. 在任务栏或右下角角标点击软件
3. 弹出的视窗会自动放大

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.7.3
- 系统版本号(OS Version):  Windows 11 专业工作站版 21H2
- 是否为应用商店版本(Whether it is a Store version):  是

**Comment by rmbadmin** [comment]
重复 #1339 #1520
