### ISSUE TITLE
👑[Enhancement] 希望改进代理时所用的证书

### ISSUE THREAD

**Issue by wjr050430** [BeyondDimension/SteamTools#1585]
### 🥰 需求描述(Description)
如题，代理时使用的证书不被firefox信任，也无法在firefox中正常导入。

### 🧐 解决方案(Solution)
也许可以试试改进下证书，自签证书颁发机构证书解决？这块不是非常了解，但我知道的是data.stats.gov.cn的证书也未被firefox信任，但是其根证书可以导入firefox从而信任

### 🚑 其他信息(Other Information)
![图片](https://user-images.githubusercontent.com/53849228/175779475-f476a044-36c7-4b61-bbbc-baa66d1245af.png)
![图片](https://user-images.githubusercontent.com/53849228/175779531-6d1b3481-5595-447b-bbfa-f4b0bc5252ce.png)

**Comment by rmbadmin** [comment]
建议提出问题时先搜索一下issues有没有相关问题
#856 #490 #8
你需要导入的是证书cer文件 不是pfx
