### ISSUE TITLE
安卓版加速问题

### ISSUE THREAD

**Issue by Snowfly-Guo** [BeyondDimension/SteamTools#1586]
![Screenshot_20220626_154129_net.steampp.app.jpg](https://user-images.githubusercontent.com/79904577/175804953-d7e6fa87-1458-45aa-86ed-05b7ed0a132d.jpg)![Screenshot_20220626_155105_tv.twitch.android.app.jpg](https://user-images.githubusercontent.com/79904577/175804981-027d0cf4-db40-419e-bbde-2e185dc88cbe.jpg)
显示已连接还是无法使用twitch

**Comment by rmbadmin** [comment]
安卓版目前因为android系统安全政策原因，所以本地反代没有办法正常使用，请等待后续更新

**Comment by Snowfly-Guo** [comment]
> 安卓版目前因为android系统安全政策原因，所以本地反代没有办法正常使用，请等待后续更新

好的👌
