### ISSUE TITLE
🐛[BUG] 修改游戏名称后无法改回去了

### ISSUE THREAD

**Issue by Heporis** [BeyondDimension/SteamTools#1587]
可以修改成别的名字，但是就是不能改回原来的名字，必须要和原始名字不一样。
比如我Dota 2可已改成Dota 2太好玩了，Dota，Dota 22，Dota 2太好玩了啊啊啊，但是一旦改过名字就改不回Dota 2了。。。。

**Comment by Mossimos** [comment]
我这是可以改成 Dota 23  然后再改回来没有问题啊

**Comment by Heporis** [comment]
> 我这是可以改成 Dota 23 然后再改回来没有问题啊

今天自己正常了，我又试了一下，发现原因了，改回原来的名字之后必须要启动一次游戏，它才会生效，但是改成别的名字就不需要启动游戏，重启steam之后立马就能生效。
![GIF 2022-6-27 23-08-58](https://user-images.githubusercontent.com/51895154/175973677-e0210b2b-69ec-4987-a278-c6b03cd1f3ad.gif)
虽然steam上的名字今天变成Dota 2了，但是steam++里的还是Dota
![image](https://user-images.githubusercontent.com/51895154/175972056-99a5819b-1dcc-4e5d-a161-e81f57ea23e4.png)
![image](https://user-images.githubusercontent.com/51895154/175972086-9d647b4c-a9f3-4835-8365-36f84f8f3377.png)
