### ISSUE TITLE
[Question] 软件下来，脚本安不上是什么原因🧐

### ISSUE THREAD

**Issue by maya970** [BeyondDimension/SteamTools#1596]
### 🧐 问题描述(Description)

软件下来，脚本安不上是什么原因
点击安装插件 转了一下 回到原来的图标 返回 啥也没有

### 🚑 其他信息(Other Information)

![无标题](https://user-images.githubusercontent.com/85286329/175895582-bc51010b-57ab-4ee9-93c8-818820dfe61a.png)

- 程序版本(Program Version):最新版本
- 系统版本号(OS Version):win7
- 是否为应用商店版本(Whether it is a Store version): 官网下载

**Comment by rmbadmin** [comment]
提供下程序错误日志

**Comment by maya970** [comment]
> 程序错误日志
[steam++.zip](https://github.com/BeyondDimension/SteamTools/files/8991968/steam%2B%2B.zip)
感谢管理员大大
已经安装 Windows 7 安全更新程序 (KB2813430)，但仍未好用

**Comment by Mossimos** [comment]
是程序 设置  通用设置 打开logs文件夹中的日志文件

**Comment by maya970** [comment]
> 是程序 设置 通用设置 打开logs文件夹中的日志文件
[nlog-all-2022-06-27.log](https://github.com/BeyondDimension/SteamTools/files/8992023/nlog-all-2022-06-27.log)
好的

**Comment by Mossimos** [comment]
请检查你电脑的时间是否是最新的 
与服务器验证SSL证书时间无效

**Comment by maya970** [comment]
> 请检查你电脑的时间是否是最新的 与服务器验证SSL证书时间无效

好的，解决了，万万没想到的错误
谢谢
