### ISSUE TITLE
👑[Enhancement] 希望增加对Parsec的支持

### ISSUE THREAD

**Issue by supply9243** [BeyondDimension/SteamTools#1605]
### 🥰 需求描述(Description)

https://parsec.app/
Parsec是一款低延迟高画质的免费串流软件，最近不知道为何被移动运营商屏蔽了域名，无法连接服务器。

### 🧐 解决方案(Solution)

kessel-ws.parsec.app
kessel-api.parsec.app
仅仅加速此两个域名就可以解决问题，而且不会消耗什么流量，您可以实际测试下。

### 🚑 其他信息(Other Information)

个人也可以通过内置的代理解决问题，但大部分用户并没有这个技能。

**Comment by ListenV** [comment]
支持

**Comment by Ra2-IFV** [comment]
最新版已支持Parsec加速，建议升级

**Comment by Ra2-IFV** [comment]
最新版已支持Parsec加速，建议升级
