### ISSUE TITLE
[Steam++ on Linux] Discord加速不成功

### ISSUE THREAD

**Issue by 0xarch** [BeyondDimension/SteamTools#1606]
问题：
**在Arch  Linux上使用Steam++时，Discord加速不成功（卡在更新检查）（未测试其他网站）**
系统代理和HOSTS代理都尝试过，按照443占用问题修改后仍然不成功

### **日志（$HOME/.cache/Steam++/Logs/nlog-all-2022-06-29.log)：**

> 2022-06-29 14:50:12.5753|Error|Startup|ActiveUserPost | System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Application.Startup.ActiveUserPost(ActiveUserType type)
> 2022-06-29 17:17:51.3116|Error|Startup|ActiveUserPost | System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Application.Startup.ActiveUserPost(ActiveUserType type)
> 2022-06-29 17:21:06.3930|Error|Startup|ActiveUserPost | System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Application.Startup.ActiveUserPost(ActiveUserType type)
> 2022-06-29 17:21:35.3477|Error|Startup|ActiveUserPost | System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Application.Startup.ActiveUserPost(ActiveUserType type)
> 2022-06-29 17:23:15.3354|Error|Startup|ActiveUserPost | System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Application.Startup.ActiveUserPost(ActiveUserType type)
> 2022-06-29 17:23:38.7562|Error|Startup|ActiveUserPost | System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Application.Startup.ActiveUserPost(ActiveUserType type)
> 2022-06-29 17:23:45.5385|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyConnectException: Couldn't authenticate host 'discord.com' with certificate 'discord.com'.
>  ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
>  ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
>  ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
>    --- End of inner exception stack trace ---
>    at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
>    at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
>    --- End of inner exception stack trace ---
>    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
>    at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
> 2022-06-29 17:23:51.2568|Error|HttpProxyS|ProxyServer ExceptionFunc | Titanium.Web.Proxy.Exceptions.ProxyConnectException: Couldn't authenticate host 'discord.com' with certificate 'discord.com'.
>  ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
>  ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
>  ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
>    --- End of inner exception stack trace ---
>    at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
>    at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
>    --- End of inner exception stack trace ---
>    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
>    at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
>    --- End of inner exception stack trace ---
>    at Titanium.Web.Proxy.ProxyServer.handleClient(TransparentBaseProxyEndPoint endPoint, TcpClientConnection clientConnection, Int32 port, CancellationTokenSource cancellationTokenSource, CancellationToken cancellationToken)
> 2022-06-29 17:38:17.6038|Error|Startup|ActiveUserPost | System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Application.Startup.ActiveUserPost(ActiveUserType type)

程序版本(Program Version):**2.7.2-2(AUR)**
系统版本号(OS Version): **Arch Linux x86_64 5.18.7-arch1-1**

**Comment by rmbadmin** [comment]
根据错误提示来看应该是证书信任问题，尝试将appdata内的cer证书文件添加系统信任

**Comment by 0xarch** [comment]
已解决，感谢
