### ISSUE TITLE
🧐[Question] 客户端错误1006咋办，怎么解决

### ISSUE THREAD

**Issue by allestic** [BeyondDimension/SteamTools#1609]
### 🧐 问题描述(Description)

客户端错误1006：以一种权限访问不允许的方式做了一个访问套接字的程序
### 🚑 其他信息(Other Information)

![屏幕截图(277)](https://user-images.githubusercontent.com/82659177/176514881-509be7ba-2582-4e88-af77-4f7ef2d2c3cf.png)

- 程序版本(Program Version):2.7.2
- 系统版本号(OS Version): windows 11.22000.739
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by rmbadmin** [comment]
程序的联网请求被防火墙或者杀毒软件拦截了
