### ISSUE TITLE
🐛[BUG] 用挂时长挂没有下载的游戏后steam库存中显示游戏已下载且之后无法卸载 点启动无反应

### ISSUE THREAD

**Issue by Nefelibataaaa** [BeyondDimension/SteamTools#1621]
### 🐛 描述(Description)
在steamapps中没有这个游戏 而且在steam内无法卸载游戏也无法重新下载  

### 📷 复现步骤(Steps to Reproduce)

1. 在steam++挂时长里加入没有下载的游戏 开启挂时长
2. steam里出现没有下载的游戏在运行
3. 关掉挂时长游戏留在库存里不能卸载也无法运行
4. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.7.2 for Windows（x64）
- 系统版本号(OS Version): Windows 10.19043.1766
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)
![steamwebhelper_ah5Ocj8tPv](https://user-images.githubusercontent.com/108726124/177293664-6da5986a-7cb7-4c36-a4c0-09366f23ce82.png)

**Comment by Nefelibataaaa** [comment]
怎么办啊qwq 现在想玩这个游戏却玩不了:-(((((((((

**Comment by Mossimos** [comment]
重启Steam呢

**Comment by rmbadmin** [comment]
退出Steam
删除Steam目录下的  \Steam\appcache\appinfo.vdf
重启Steam

**Comment by Nefelibataaaa** [comment]
解决了 谢谢大佬！！！！！！
