### ISSUE TITLE
🐛[BUG] 最小化窗口后打开，界面尺寸会变大

### ISSUE THREAD

**Issue by YXTong17** [BeyondDimension/SteamTools#1623]
### 🐛 描述(Description)
最小化Steam++的窗口后，再次打开时窗户尺寸变大，横纵都有变化。经过测试应该是按比例增大了，类似每次打开横纵都变大为之前的120%。

### 📷 复现步骤(Steps to Reproduce)
1. 最小化Steam++窗口
2. 通过任务栏再次打开
也可以通过反复点击任务栏中已打开的Steam++实现

### 📄 [异常/日志]信息([Exception/Log] Information)
无

### 🚑 基本信息(Basic Information)
- 程序版本(Program Version): 2.7.2 for Windows (x64)
- 系统版本号(OS Version): Windows 10.19044.1766
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/48703739/177468981-e5d5b1b5-ae7c-4a5f-ac6e-fa43bf1cef45.png)
![image](https://user-images.githubusercontent.com/48703739/177469001-ff45d755-425b-44c6-be59-36ebc628a34a.png)
![image](https://user-images.githubusercontent.com/48703739/177469029-f3d55f2e-86e1-4f79-9936-43205d7f7eff.png)
![image](https://user-images.githubusercontent.com/48703739/177469049-1382200a-7f64-4300-9ff2-a84e7f8fc5cd.png)
![image](https://user-images.githubusercontent.com/48703739/177469073-45a525a0-b7a8-40ac-be49-12e1305c301b.png)

**Comment by rmbadmin** [comment]
重复 #1582
这个问题已经被修复，请等待下个版本发布
