### ISSUE TITLE
希望启动时能增加自动启动网络加速

### ISSUE THREAD

**Issue by WiZ33rd** [BeyondDimension/SteamTools#1624]
RT，希望程序启动时能自动开始网络加速。
并且开机时有没有方法能添加管理员权限，不用每次手动点

**Comment by rmbadmin** [comment]
使用任务计划设置开机自启，并且勾选管理权限运行即可不弹UAC提示，或者直接关闭系统UAC警告。
开启程序自动加速是已有功能
![image](https://user-images.githubusercontent.com/12234359/177685925-be42a169-8115-4fea-a7fc-8a44c92e1baf.png)

**Comment by WiZ33rd** [comment]
> 使用任务计划设置开机自启，并且勾选管理权限运行即可不弹UAC提示，或者直接关闭系统UAC警告。 开启程序自动加速是已有功能 ![image](https://user-images.githubusercontent.com/12234359/177685925-be42a169-8115-4fea-a7fc-8a44c92e1baf.png)

感谢
