### ISSUE TITLE
👑[Enhancement] 导出已编辑的游戏信息

### ISSUE THREAD

**Issue by ww460160885** [BeyondDimension/SteamTools#1635]
### 🥰 需求描述(Description)

对于有多个账号/设备，且大量编辑了游戏信息的用户，在每个账号/设备上重新编辑过于繁琐，体验不佳。

### 🧐 解决方案(Solution)

新增一个按钮（必要时增加相应弹出页面），可以一键 导出/导入 编辑后的信息，方便其他账号/设备同步更改。

（非必要）也可增加”一键同步本地已修改内容到所有已保存的账号“功能。
### 🚑 其他信息(Other Information)

无

**Comment by rmbadmin** [comment]
#1634 这两个功能是计划中的，只是因为上线匆忙所以暂时未完善，建议将两个问题合并到一个来

**Comment by ww460160885** [comment]
关闭了 #1635 ，合并内容到 #1634
