### ISSUE TITLE
👑[Enhancement] 一个小小建议(拜托了)

### ISSUE THREAD

**Issue by Sobfy** [BeyondDimension/SteamTools#1637]
希望这个软件窗口不要自动调整大小
强迫症有点难受
其次希望可以增加一个关闭直接退出，而不是留在后台(每次退出比较麻烦)

**Comment by rmbadmin** [comment]
这是一个已经修复的问题直接关闭退出也是已经做好的功能，请等待新版本发布。
重复 #1623 #970
