### ISSUE TITLE
🐛[BUG] 库存游戏功能显示大量账户中没有的不知名小游戏

### ISSUE THREAD

**Issue by wslwslwsl1** [BeyondDimension/SteamTools#1645]
### 🐛 描述(Description)
在库存游戏界面中显示**大量**并未我的Steam账户拥有的游戏，多为不知名小游戏。

### 📷 复现步骤(Steps to Reproduce)
打开应用就是这样，无需复现

### 📄 [异常/日志]信息([Exception/Log] Information)
https://pastebin.ubuntu.com/p/DpZYvsHBwz/

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): v2.7.2 alpha for Linux
- 系统版本号(OS Version): Manjaro Linux
- 是否为应用商店版本(Whether it is a Store version): No
- P.S. Windows 版也有同样问题

### 🖼 截图(Screenshots)
![图片](https://user-images.githubusercontent.com/109137382/178444415-75a9fb29-9340-4564-a1d0-69645c0b3102.png)

**Comment by Mossimos** [comment]
可能是在你机器上登录过的其他Steam账号的游戏 ， Linux目前没有判断是登录的哪个账号筛选该账号的游戏

**Comment by wslwslwsl1** [comment]
我自己的三个帐号的游戏的确全部包含在内，但是多出来的游戏不属于我系统中曾登录过的任何帐号，甚至有的游戏连steam商店界面都打不开，而且这个系统中确实只登录过我自己的帐号，能大概讲一下这个库存功能的工作原理吗？

**Comment by rmbadmin** [comment]
因为目前linux和mac并没有连接steam做账号所有权筛选，所以多出来游戏是正常现象，
数据来自steam缓存过的游戏，不管这游戏是否属于你，只要steam缓存了都会读取并展示。
这并不是bug所以也不需要修复。
