### ISSUE TITLE
🧐[Question] steam++可以加载到需要确认的交易，但无法确认或取消.

### ISSUE THREAD

**Issue by lulouislu** [BeyondDimension/SteamTools#1659]
### 🧐 问题描述(Description)

Steam++ 可以加载到需要确认的交易，但无法确认或取消；换了steam++的商店版和手机版,都无法确认

程序版本(Program Version):2.7.3
系统版本号(OS Version): Windows 10.19044.1826(专业版)
是否为应用商店版本(Whether it is a Store version): 否(No)

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/33508165/178656766-9bb01248-502e-452b-8bee-46726d0d96c5.png)

![Snipaste_2022-07-13_13-06-00](https://user-images.githubusercontent.com/33508165/178654988-fdc15282-486b-458f-a765-d2679924836e.png)

**Comment by mlch911** [comment]
+1，是 steam 改接口了吗

**Comment by AigioL** [comment]
今早开始出现的这个问题，可能是 Steam 改了接口或者在维护中，目前 Steam 官方的手机 App 也不能确认与取消交易。

**Comment by lulouislu** [comment]
这样啊,希望官方快点修好吧

**Comment by rmbadmin** [comment]
现在应该都正常了，steam服务恢复了
