### ISSUE TITLE
👑求增加国外框架

### ISSUE THREAD

**Issue by azhango** [BeyondDimension/SteamTools#1660]
### 🥰 需求描述(Description)

求增加类似于Spring，方便阅读，国内不好打开

**Comment by AigioL** [comment]
https://spring.io 使用 CloudFlare CDN
从 https://www.vsping.com 以及 https://www.itdog.cn/http 的测试结果上看到，在国内少部分运营商提供的网络上访问较慢，也许你可以换一个 DNS 试试
或者使用国内的镜像站例如
https://docs.gitcode.net/spring/guide/spring/why-spring.html
https://www.docs4dev.com

Spring 与我们的业务范围不相关，也与我们所使用的技术栈不相关
支持一个加速项目需要很大的时间成本，尤其是在一直维护上，所以不会考虑添加此类网站
