### ISSUE TITLE
🧐[有办法和clash等代理共存吗] 

### ISSUE THREAD

**Issue by Null-Bot9875** [BeyondDimension/SteamTools#1661]
clash的端口和steam++似乎有冲突 每次启动了一个另一个就失败

**Comment by Null-Bot9875** [comment]
![image](https://user-images.githubusercontent.com/52150648/178744488-e59f610c-7f62-4d91-aaa8-8f1d15f8cb3a.png)

**Comment by Null-Bot9875** [comment]
![image](https://user-images.githubusercontent.com/52150648/178744488-e59f610c-7f62-4d91-aaa8-8f1d15f8cb3a.png)

**Comment by Mossimos** [comment]
用系统代理模式的话  请在程序内配置二级代理  然后clash 允许局域网连接再开加速

**Comment by EvilWuZhi** [comment]
都用上Clash了 还要加速吗（

**Comment by Alexius66** [comment]
> 都用上Clash了 还要加速吗（

这不是为了用脚本嘛
