### ISSUE TITLE
👑[Enhancement] 能不能加个启动时自动加速选项

### ISSUE THREAD

**Issue by idadwind1** [BeyondDimension/SteamTools#1666]
### 🥰 需求描述(Description)

> 因为经常使用，所以设了个开机自动启动，可是还是需要手动加速，每次都这样就觉得有点麻烦  

***所以可不可以加个启动时自动加速？***

### 🧐 解决方案(Solution)

**解决方法其实很简单！希望能优先处理**  
就***改一下参数和菜单***

**Comment by rmbadmin** [comment]
这是已有功能 #1624 
同时这也是重复问题.
