### ISSUE TITLE
🧐[Question] 加速无效 WindowsCryptographicException: 不支持请求的操作

### ISSUE THREAD

**Issue by yingmiait** [BeyondDimension/SteamTools#1677]
### 🧐 问题描述(Description)

在我这台电脑上，UHE加速有效，steamconmunity302有效，其他加速器有效，只有steam++无效
不明白为什么在我这台电脑上使用steam++host模式会出现地址前面全是127.0.0.1，具体如图，与其他加速器完全不一样
百度过了，必应过了，Google过了，也在csdn上搜过了，也看了其他的Issue，没有得到解决

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/89168964/179790168-9f6002ff-675f-46e2-9159-eb5c6bf2275c.png)

- 程序版本(Program Version): steam++ x64 v2.7.2 for windows
- 系统版本号(OS Version): Windows 10.19044.1826（21H2）
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by rmbadmin** [comment]
提供程序错误日志，127.0.0.1是正常的，steamconmunity302也是同样的方式

**Comment by yingmiait** [comment]
[nlog-all-2022-07-19.log](https://github.com/BeyondDimension/SteamTools/files/9142730/nlog-all-2022-07-19.log)

**Comment by rmbadmin** [comment]
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: 不支持请求的操作。
错误问题在于在你的设备上无法调用系统组件创建证书，尝试修复或重装系统吧

**Comment by yingmiait** [comment]
![image](https://user-images.githubusercontent.com/89168964/179797407-9401451c-d287-42cc-982c-db150bfd978f.png)
解决了，如图为原因，更改权限后移除证书后再安装一次就可以正常加速了

**Comment by rmbadmin** [comment]
很好，谢谢，能自行找到解决方案更好，这也为以后遇到相同问题的其它人提供了帮助，
同时如果没有其他问题我将关闭此问题了。
