### ISSUE TITLE
请问下能增加Mod.io的访问加速吗？谢谢👑[Enhancement] 

### ISSUE THREAD

**Issue by shoucanLi** [BeyondDimension/SteamTools#1689]
### 🥰 需求描述(Description)

想要增加Mod.io网站的访问加速功能，这是个和创意工坊类似的Mod订阅网站。如果可行的话麻烦大佬了，谢谢！

**Comment by AigioL** [comment]
mod.io 的支持还没弄好，与 #327 重复
