### ISSUE TITLE
🐛[BUG] 软件手机令牌的加密有时（比如崩溃后）会丢失，导致不用输密钥就能访问

### ISSUE THREAD

**Issue by shiquda** [BeyondDimension/SteamTools#1705]
1. 崩溃后或者强制关机后软件手机令牌加密有时会丢失，导致不用密钥也能访问令牌信息
2. 还有就是手机令牌交易确认要求输本地令牌密钥时点击取消，也能进行交易确认（图2）
3.”需要解密才能继续“在图3版面选择取消后，重新输入密钥，即使正确也会无限制弹出输入密钥的窗口，然而再选择取消或输入错误的密码后却可以继续（图4）

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.7.3
- 系统版本号(OS Version): Windows 10.19042.685
- 是否为应用商店版本(Whether it is a Store version): 是

### 🖼 截图(Screenshots)
图2![image](https://user-images.githubusercontent.com/104683621/180337659-ee962a2e-c5cf-408e-b6d9-25b6316ff119.png)
图3![image](https://user-images.githubusercontent.com/104683621/180338484-07f4ff16-0f3f-4eae-ba52-c8112c4580ee.png)
图4![image](https://user-images.githubusercontent.com/104683621/180338920-094d56fb-039e-41e2-95e9-b8b9751af6ac.png)

<!--

**Comment by rmbadmin** [comment]
除第一个问题暂时无法确定原因外，23问题已经修复，1问题程序非正常退出也应该不会去有写入令牌的操作才对，我这边暂时无法复现

**Comment by shiquda** [comment]
> Reference in



> 除第一个问题暂时无法确定原因外，23问题已经修复，1问题程序非正常退出也应该不会去有写入令牌的操作才对，我这边暂时无法复现

好的，谢谢！

**Comment by shiquda** [comment]
您好，昨天令牌加密再次丢失，好像不是原来以为的崩溃导致的，而是多次执行类似2和3的操作导致的，具体原因不明

**Comment by rmbadmin** [comment]
等2.8.0发布后在测试下新版本是否问题依旧吧

**Comment by shiquda** [comment]
> 等2.8.0发布后在测试下新版本是否问题依旧吧

好的，谢谢，辛苦了！

**Comment by rmbadmin** [comment]
1问题原因已经找到了，因为令牌交易中会异步保存令牌的一些登录状态数据，在这个过程执行之前如果恰好输入过错误密码或取消输入密码，那么可能会将当前令牌数据保存成无密码数据，然后因为通用的判断数据是否有密码保护的方法取得是第一条数据是否有密码，导致了这个原因。2.8中将会修复。
