### ISSUE TITLE
🧐[Question] WinStore 版本更新显示更早版本提示

### ISSUE THREAD

**Issue by indescribableQB** [BeyondDimension/SteamTools#1708]
### 🧐 问题描述(Description)
在windonws stroe安装的2.72，弹出了更新2.64的更新。点击版本更新，ws没反应。是哪里出问题了吗？
![QQ截图20220722182753](https://user-images.githubusercontent.com/42056610/180421290-58d985c6-16c0-4139-82f1-11a70ba1e717.png)

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): <!--是(Yes)/否(No)--

>

**Comment by AigioL** [comment]
服务端有一些错误，正在排查，现在应该是收不到旧版本的更新提示了，需重启程序后生效
