### ISSUE TITLE
👑[Enhancement] 增加本地令牌用户手动排序功能

### ISSUE THREAD

**Issue by ghost** [BeyondDimension/SteamTools#1709]
### 🥰 需求描述(Description)

![image](https://user-images.githubusercontent.com/26181512/180600706-817d717a-bf4a-4701-8e7f-14a2820de8f5.png)
如图所示，当有多个本地令牌时，令牌之间的显示顺序是程序自动决定的并且不能调整，所以希望可以增加令牌手动排序的功能。

### 🧐 解决方案(Solution)
增加手动排序的功能和选项。

### 🚑 其他信息(Other Information)

无

**Comment by AigioL** [comment]
你可以在令牌上右键菜单中上移下移

**Comment by rmbadmin** [comment]
你可以右键令牌，可以调整顺序

**Comment by ghost** [comment]
好的，多谢解答，非常抱歉因为对软件功能了解不足所以提出了多余的请求。
