### ISSUE TITLE
🧐[Question] 新版本2.8.0网络加速启动失败

### ISSUE THREAD

**Issue by shiquda** [BeyondDimension/SteamTools#1710]
### 🧐 问题描述(Description)
如图1，加速启动失败。
log:
2022-07-23 18:15:41.8853|Error|ReverseProxyS|ProxyServer ExceptionFunc | System.ArgumentException: An item with the same key has already been added. Key: [/^https://store\.steampowered\.com/.*$, System.Application.Models.ScriptDTO]
   at System.Collections.Generic.TreeSet`1.AddIfNotPresent(T item)
   at System.Collections.Generic.SortedDictionary`2.Add(TKey key, TValue value)
   at System.Application.Models.ReverseProxyConfig.AddScriptConfigs(IDictionary`2 dict, IEnumerable`1 scripts)
   at System.Application.Models.ReverseProxyConfig..ctor(YarpReverseProxyServiceImpl reverseProxyService)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddConfiguration(IServiceCollection services, YarpReverseProxyServiceImpl reverseProxyService)
   at System.Application.Services.Implementation.YarpReverseProxyServiceImpl.StartupConfigureServices(IServiceCollection services)
   at System.Application.Services.Implementation.YarpReverseProxyServiceImpl.StartProxyCore()

### 🚑 其他信息(Other Information)
![image](https://user-images.githubusercontent.com/104683621/180600943-bc97b900-c2da-4103-b97e-a594e6a98a8f.png)

- 程序版本(Program Version):2.8.0
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by Mossimos** [comment]
截图下脚本列表看看

**Comment by rmbadmin** [comment]
可以截图看下启用了哪些脚本吗

**Comment by shiquda** [comment]
![image](https://user-images.githubusercontent.com/104683621/180601082-1cb04f26-7c7b-4d7e-a527-2bb950e41220.png)
![image](https://user-images.githubusercontent.com/104683621/180601085-c4973ecc-fabd-4e7b-9aa5-0125efd6fd39.png)
![image](https://user-images.githubusercontent.com/104683621/180601095-672004a3-4b69-4cd1-8169-4a3793f396e1.png)
![image](https://user-images.githubusercontent.com/104683621/180601094-2b54cd8d-47b8-4efe-9be9-c9b953d728af.png)
![image](https://user-images.githubusercontent.com/104683621/180601096-a7fca9ff-6b84-4d9e-980e-9e8c7dcc9ff9.png)
关闭脚本后可正常启动加速

**Comment by shiquda** [comment]
![image](https://user-images.githubusercontent.com/104683621/180601269-67d61992-c87e-4b66-977a-358a33f916b1.png)
这个关了好像就可以了

脚本代码：
// ==UserScript==
// @name         Steam便捷加入购物车
// @namespace    Steam便捷加入购物车
// @version      0.4
// @description  Steam便捷加入购物车，不自动跳转购物车页面。
// @author       HCLonely
// @match        https://store.steampowered.com/*
// @require      https://cdn.bootcss.com/sweetalert/2.1.2/sweetalert.min.js
// @supportURL   https://blog.hclonely.com/posts/578f9be7/
// @homepage     https://blog.hclonely.com/posts/578f9be7/
// @grant        GM_addStyle
// @run-at       document-end
// ==/UserScript==

(function($) {
    'use strict';
    function addToCart(appid){
        swal({
            title: "Steam便捷加入购物车",
            text: "正在获取游戏信息...",
            icon: "info",
        });
        $.ajax({
            url:'https://store.steampowered.com/app/'+appid,
            type:'get',
            success:(data)=>{
                try{
                    let addToCart=data.match(/\<form name\=\"add\_to\_cart[\w\W]*?\<\/form\>/gim);
                    if(addToCart){
                        swal({
                            title: "Steam便捷加入购物车",
                            text: "获取游戏信息成功！ \n正在处理游戏信息...",
                            icon: "info",
                        });
                        let inputArr=addToCart[0].match(/\<input type\=\"hidden\".*?\>/gim);
                        let postData={};
                        for(let i=0;i<inputArr.length;i++){
                            let input=$(inputArr[i]);
                            let key=input.attr('name');
                            let value=input.attr('value');
                            postData[key]=value;
                        }
                        swal({
                            title: "Steam便捷加入购物车",
                            text: "获取游戏信息成功！ \n处理游戏信息完成！ \n正在加入购物车...",
                            icon: "info",
                        });
                        $.ajax({
                            url:'https://store.steampowered.com/cart/',
                            type:'post',
                            data:postData,
                            success:(data)=>{
                                try{
                                    let test=new RegExp('\<div class\=\"cart_row.*?data\-ds\-appid\=\"'+appid+'\"','g');
                                    if(test.test(data)){
                                        swal({
                                            title: "Steam便捷加入购物车",
                                            text: "获取游戏信息成功！ \n处理游戏信息完成！ \n加入购物车成功！",
                                            icon: "success",
                                        });
                                    }else{
                                        swal({
                                            title: "Steam便捷加入购物车",
                                            text: "获取游戏信息成功！ \n处理游戏信息完成！ \n加入购物车失败！",
                                            icon: "error",
                                        });
                                    }
                                }catch(e){
                                    swal({
                                        title: "Steam便捷加入购物车",
                                        text: "获取游戏信息成功！ \n处理游戏信息完成！ \n加入购物车失败！",
                                        icon: "error",
                                    });
                                }
                            },
                            error:()=>{
                                swal({
                                    title: "Steam便捷加入购物车",
                                    text: "获取游戏信息成功！ \n处理游戏信息完成！ \n加入购物车失败！",
                                    icon: "error",
                                });
                            },
                        });
                    }else{
                        swal({
                            title: "Steam便捷加入购物车",
                            text: "获取游戏信息成功！ \n没有找到添加购物车按钮，请手动添加！",
                            icon: "warning",
                            buttons: {
                                cancel: "关闭",
                                手动添加: true,
                            },
                        })
                            .then((value) => {
                            if(value) window.open('https://store.steampowered.com/app/'+appid,'_blank')
                        });
                    }
                }catch(e){
                    swal({
                        title: "Steam便捷加入购物车",
                        text: "脚本出错！",
                        icon: "error",
                    });
                    console.error(e);
                }
            },
            error:e=>{
                swal({
                    title: "Steam便捷加入购物车",
                    text: "获取游戏信息失败！",
                    icon: "error",
                });
                console.error(e);
            },
        });
    }
    function addBtn(){
        $('.ds_options').parent().not(':contains("添加至购物车")').append(`<div class="ds_options hclonely btnv6_green_white_innerfade"><span>添加至购物车</span></div>`);
        $('.ds_options.hclonely').click(function(e){
            e.preventDefault();
            addToCart($(this).parent().attr('data-ds-appid'));
        });
    }

    addBtn();

    setInterval(()=>{
        if($('.ds_options').parent().not(':contains("添加至购物车")').length>0) addBtn();
    },1500);

    GM_addStyle(`.hclonely{position: absolute;right: 0;top: 25px;z-index: 999999;padding: 0 !important;}`);

})(jQuery);

**Comment by rmbadmin** [comment]
已经定位原因修复

**Comment by shiquda** [comment]
（需要再开一个issue吗）
对了，还有一个问题，选择加速模式时，使用PAC代理和系统代理无法正常加速
PAC:非必须加速网站（原本不使用加速可打开的）可打开，加速网站不可打开，流量显示为0：
![image](https://user-images.githubusercontent.com/104683621/180602123-d2229b95-281f-4129-a463-f1e84c7fcd23.png)

系统代理：使用加速功能的网站（即使不加速也能访问）无法访问，别的网站可访问。流量显示为0：
![image](https://user-images.githubusercontent.com/104683621/180602218-b8bc550a-3951-4c00-9598-22c71539f606.png)
其他代理模式正常。

**Comment by rmbadmin** [comment]
> （需要再开一个issue吗） 对了，还有一个问题，选择加速模式时，使用PAC代理和系统代理无法正常加速 PAC:非必须加速网站（原本不使用加速可打开的）可打开，加速网站不可打开，流量显示为0： ![image](https://user-images.githubusercontent.com/104683621/180602123-d2229b95-281f-4129-a463-f1e84c7fcd23.png)
> 
> 系统代理：使用加速功能的网站（即使不加速也能访问）无法访问，别的网站可访问。流量显示为0： ![image](https://user-images.githubusercontent.com/104683621/180602218-b8bc550a-3951-4c00-9598-22c71539f606.png) 其他代理模式正常。

问题原因应该与默认设置监听ip为0.0.0.0有关，改到127.0.0.1在测试下看看

**Comment by shiquda** [comment]
好的，更改后已解决，四种代理模式均可使用了。
（现在关闭广告功能还没开启吗，本人已赞助但是无法改成关闭广告，但是好像也没看到广告）

**Comment by rmbadmin** [comment]
> 好的，更改后已解决，四种代理模式均可使用了。 （现在关闭广告功能还没开启吗，本人已赞助但是无法改成关闭广告，但是好像也没看到广告）

嗯，暂时还没有接到广告，所以并未开启，赞助关闭广告功能等待服务端之后更新下，就应该都可以设置了

**Comment by shiquda** [comment]
> 

好的，谢谢！（虽然有了也会开广告，加油！）
（话说大佬闲下来的时候能给个steam好友位吗😀）

**Comment by rmbadmin** [comment]
> > 
> 
> 好的，谢谢！（虽然有了也会开广告，加油！） （话说大佬闲下来的时候能给个steam好友位吗😀）

你可以申请steam好友后到我steam主页给个留言给我，直接申请的话我没法区分是谁所以一般不会通过

**Comment by shiquda** [comment]
> > > 
> > 
> > 
> > 好的，谢谢！（虽然有了也会开广告，加油！） （话说大佬闲下来的时候能给个steam好友位吗😀）
> 
> 你可以申请steam好友后到我steam主页给个留言给我，直接申请的话我没法区分是谁所以一般不会通过

好的，已经留言啦，谢谢！（送你一个小点数）
