### ISSUE TITLE
🧐[Question] FDE版本中RemovebinPath未能正确执行

### ISSUE THREAD

**Issue by ElemenTP** [BeyondDimension/SteamTools#1711]
### 🧐 问题描述(Description)

从2.7.2升级到2.8.0，安装程序没有把2.7.2的程序文件彻底删除。我使用的是fde版，其他版本情况未知

### 🚑 其他信息(Other Information)

![屏幕截图 2022-07-23 184113](https://user-images.githubusercontent.com/57991536/180601761-5e5461f1-13a2-415a-b3dc-5e9bf2d8d452.png)
图中的Bin文件夹为2.7.2版本残留

- 程序版本(Program Version): 2.8.0
- 系统版本号(OS Version): 10.0.22621.0
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by AigioL** [comment]
在 设置 - 通用设置 - 存储空间 - 打开Logs文件夹，当天的日志中是否有 ```RemovebinPath``` 相关的内容？

删除 Bin 文件夹的代码位于
https://github.com/BeyondDimension/SteamTools/blob/2.8.0/src/ST.Client/Migrations.cs#L41-L56

之前测试过是正常的

**Comment by ElemenTP** [comment]
> 在 设置 - 通用设置 - 存储空间 - 打开Logs文件夹，当天的日志中是否有 `RemovebinPath` 相关的内容？
> 
> 删除 Bin 文件夹的代码位于 https://github.com/BeyondDimension/SteamTools/blob/2.8.0/src/ST.Client/Migrations.cs#L41-L56
> 
> 之前测试过是正常的

原来删除旧版文件的逻辑不是用安装器完成的，我升级后还没有启动过软件，先去看了眼文件夹。

启动软件试了一下，确实是正常的。
