### ISSUE TITLE
🐛[BUG] 提出一种对于界面异常放大的问题原因设想

### ISSUE THREAD

**Issue by XTsat** [BeyondDimension/SteamTools#1712]
### 🐛 描述(Description)

图中这种情况的一种可能解决设想

![8~{ }SUNRL@041QY0V3W`WI](https://user-images.githubusercontent.com/44708609/180605582-4668d46e-9669-4d84-b4dd-1d571c588373.jpg)

### 🚑 基本信息(Basic Information)

我曾经在别的项目中看到过类似的问题，可以试着收集遇到异常的电脑是否有以下软件导致的冲突

![OJVUW)9_C$E~~AYFK%3%W5N](https://user-images.githubusercontent.com/44708609/180605634-1f1408cc-5a5e-4d5b-ba85-4e739f70badb.png)

![BU{)EI0E129}NMZ%T_MIFCO](https://user-images.githubusercontent.com/44708609/180605637-5224b136-5901-45b9-a629-a22a2bd8df2a.png)

- 程序版本(Program Version):2.8.0

**Comment by rmbadmin** [comment]
问题已经解决，修复的2.8.1版本已经在编译中了

**Comment by XTsat** [comment]
切换的问题和这个异常放大的问题定位为同一个问题吗

**Comment by rmbadmin** [comment]
不是，切换的UI错位问题与用户电脑字体有关

**Comment by XTsat** [comment]
说到字体，可以实现默认选择几个系统默认会有的字体，然后加个选择自定义吗，之前用的有个电脑有几十个GB的字体，一点字体就卡死，想换回默认我都重开了好几次

**Comment by rmbadmin** [comment]
> 说到字体，可以实现默认选择几个系统默认会有的字体，然后加个选择自定义吗，之前用的有个电脑有几十个GB的字体，一点字体就卡死，想换回默认我都重开了好几次

现在就是这样的，这里的UI切换问题是字体图标的问题，不是显示文字的字体

**Comment by AigioL** [comment]
这个问题在 https://github.com/BeyondDimension/FluentAvalonia/compare/54af6d847ce9e88619befe09b7edd2ff436745f6...8098c1c22abf9e8861bef2bc8d61a00bfa05d8b0 中修复了

主要原因是 FluentAvalonia 的 FontIcon 中 ```new Typeface(```，FontFamily 在 Avalonia 的字体解析中找不到对应的值会抛出异常，从而中断了整个布局的渲染，导致布局错乱
