### ISSUE TITLE
🧐[Question] 2.8里ASF无法正常显示日志；选择启动时最小化到托盘开启时不会自动加速网络

### ISSUE THREAD

**Issue by shiquda** [BeyondDimension/SteamTools#1713]
### 🧐 问题描述(Description)
（辛苦了，又有一个问题）
1.asf日志怎么显示不了了（或显示很少）：
![image](https://user-images.githubusercontent.com/104683621/180606425-c8e923d2-e1f1-40ba-bbe8-2cceb1c746a6.png)

之前版本的点击启动ASF之后马上就会显示一些日志，然而新版本不会显示，有时一段时间后显示这个
![image](https://user-images.githubusercontent.com/104683621/180606438-cf8754d8-261f-4852-bab6-b7caa32522a7.png)
之前输令牌直接在软件的控制台里输入即可，但是前面去手动导入授权文件才登进去。
![image](https://user-images.githubusercontent.com/104683621/180606688-5f5b8a8b-921b-4b7f-9246-0e176530036e.png)

但是这里显示可以挂卡

2.若选择开启时缩小到托盘，则网络加速不会自动打开（已勾选自动开启网络加速），需要手动点击托盘图标后才会开始加速（这么说如果开了asf自动启动也不会自动开始吧）
### 🚑 其他信息(Other Information)

- 程序版本(Program Version):2.8.0
- 系统版本号(OS Version):
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by rmbadmin** [comment]
感谢反馈的这些问题了，已经修复并开始编译新版本

**Comment by shiquda** [comment]
> 感谢反馈的这些问题了，已经修复并开始编译新版本
谢谢，辛苦了，也要注意休息
