### ISSUE TITLE
🐛[BUG] PAC代理不能正常工作

### ISSUE THREAD

**Issue by ElemenTP** [BeyondDimension/SteamTools#1714]
### 🐛 描述(Description)

PAC代理模式不能正常工作

### 📷 复现步骤(Steps to Reproduce)

举例
在网络加速界面，选中“Github”，全部启用，开启加速。  
访问github.com，仍然和未开启加速时的情况一致，要么是超时，要么正常访问，但证书仍然是Github原版证书，说明github.com没有经过本地代理。  
![屏幕截图 2022-07-23 234632](https://user-images.githubusercontent.com/57991536/180612447-273359af-c32e-421d-b006-7d7722aa82c9.png)
访问gist.github.com，可以稳定的顺利访问，证书变为自签证书，说明gist.github.com经过本地代理  
![屏幕截图 2022-07-23 235301](https://user-images.githubusercontent.com/57991536/180612644-771df051-e8cc-49c8-a4f4-11bb8eb6bfb3.png)

使用curl获取pac脚本内容，如下：
```js
function FindProxyForURL(url, host){
    var pac = 'PROXY 127.0.0.1:26501';
    if (shExpMatch(host, 'api.github.com')) return pac;
    if (shExpMatch(host, 'gist.github.com')) return pac;
    if (shExpMatch(host, 'githubusercontent.com;raw.github.com')) return pac;
    if (shExpMatch(host, 'githubapp.com')) return pac;
    if (shExpMatch(host, 'github.io')) return pac;
    if (shExpMatch(host, 'github.com;*.github.com')) return pac;
    return 'DIRECT';
}
```
根据[代理自动配置文件（PAC）文件 - HTTP | MDN](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Proxy_servers_and_tunneling/Proxy_Auto-Configuration_PAC_file#shexpmatch(str,%20shexp))中对shExpMatch函数的描述，其第二个参数接收 shell glob 表达式，所以自动生成的pac脚本中诸如`githubusercontent.com;raw.github.com`和`github.com;*.github.com`不能匹配到对应domain，而`gist.github.com`可以匹配到，造成上文所述的没有代理github.com却正确代理gist.github.com的行为。  

使用[pierrecoll/autoprox](https://github.com/pierrecoll/autoprox)工具进行测试，结果相同。
```
.\autoprox.exe -u:http://github.com -p:http://127.0.0.1:26501/pac
Searching proxy for url : http://github.com
File located on an http server: downloading http://127.0.0.1:26501/pac to C:\Users\ElemenTP\AppData\Local\Temp\E2D.tmp
Searching proxy using file : C:\Users\ElemenTP\AppData\Local\Temp\E2D.tmp
Trying to load jsproxylegacy.dll from current directory (Windows 11)
The Winsock 2.2 dll was found okay
Calling InternetInitializeAutoProxyDll with C:\Users\ElemenTP\AppData\Local\Temp\E2D.tmp
        Calling InternetGetProxyInfo for url http://github.com and host github.com
        Proxy returned for url http://github.com is:
DIRECT

        Deleting the autoproxy script temporary file :
C:\Users\ElemenTP\AppData\Local\Temp\E2D.tmp

.\autoprox.exe -u:http://gist.github.com -p:http://127.0.0.1:26501/pac
Searching proxy for url : http://gist.github.com
File located on an http server: downloading http://127.0.0.1:26501/pac to C:\Users\ElemenTP\AppData\Local\Temp\384A.tmp
Searching proxy using file : C:\Users\ElemenTP\AppData\Local\Temp\384A.tmp
Trying to load jsproxylegacy.dll from current directory (Windows 11)
The Winsock 2.2 dll was found okay
Calling InternetInitializeAutoProxyDll with C:\Users\ElemenTP\AppData\Local\Temp\384A.tmp
        Calling InternetGetProxyInfo for url http://gist.github.com and host gist.github.com
        Proxy returned for url http://gist.github.com is:
PROXY 127.0.0.1:26501

        Deleting the autoproxy script temporary file :
C:\Users\ElemenTP\AppData\Local\Temp\384A.tmp
```
### 📄 [异常/日志]信息([Exception/Log] Information)

日志里基本都是System.OperationCanceledException和Microsoft.AspNetCore.Connections.ConnectionAbortedException，粗略看了一下没有相关的

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 10.0.22621.0
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by ElemenTP** [comment]
试了一下修复后的版本(4826939668dbd318e2a4614be3adec497b0643de)，pac脚本生成是正确的，但是代理的domain和host模式比少了不少，pac模式下mega（没有代理g.api.mega.co.nz，无法进入“我的文件”界面）和pixiv（没有代理i.pximg.net，大量图片挂）都是不正常的。

**Comment by rmbadmin** [comment]
这个问题后续服务端更新改进即可
