### ISSUE TITLE
🐛[BUG] 在windows 10专业工作站版本中无法启动

### ISSUE THREAD

**Issue by xiangfa-test** [BeyondDimension/SteamTools#1716]
### 🐛 描述(Description)

如题，在windows 10专业工作站版本中被识别为windows 8

### 📷 复现步骤(Steps to Reproduce)

1. 打开watt toolkit
2. 错误出现
3. 

### 📄 [异常/日志]信息([Exception/Log] Information)
暂无
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.1
- 系统版本号(OS Version): Windows 10 专业工作站版 19044.1862
- 是否为应用商店版本(Whether it is a Store version): no

### 🖼 截图(Screenshots)

![QQ截图20220724092637](https://user-images.githubusercontent.com/106453502/180628468-089fb937-b0d0-44aa-9d37-286c114ceb34.png)
![QQ截图20220724093200](https://user-images.githubusercontent.com/106453502/180628516-65ae7615-60b6-4225-8737-2a93c8f0321c.png)

**Comment by AigioL** [comment]
直接运行 ```Steam++.exe``` 而不是 ```Steam++.Launcher.exe``` 或者下载
https://github.com/BeyondDimension/SteamTools/raw/develop/references/Steam%2B%2B.Launcher.exe.bin
重命名替换 ```Steam++.Launcher.exe``` 即可
