### ISSUE TITLE
🐛[BUG] win11系统识别为win8

### ISSUE THREAD

**Issue by GodGun968** [BeyondDimension/SteamTools#1718]
### 🐛 描述(Description)
win11系统识别为win8
### 📷 复现步骤(Steps to Reproduce)

1. 安装完成
2. 点击立即启动运行Steam++.Launcher.exe
3. 提示:
---------------------------
Watt Toolkit
---------------------------
由于微软官方对 Windows 8 的支持已结束，故本程序无法在此操作系统上运行，建议升级到 Windows 8.1 或 Windows 10/11
---------------------------
确定   
---------------------------

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):Steam++_win_x64_fde_v2.8.1
- 系统版本号(OS Version): Windows 11
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/67826085/180629563-340c0efa-63a9-4383-a66b-2ae61a5f9668.png)

**Comment by AigioL** [comment]
与 https://github.com/BeyondDimension/SteamTools/issues/1716#issuecomment-1193226676 重复
