### ISSUE TITLE
🧐[Question] 新版本重构加速服务后，似乎Steam图片这项加速功能失效

### ISSUE THREAD

**Issue by Nepchico** [BeyondDimension/SteamTools#1722]
### 🧐 问题描述(Description)

RT，新版本更新后，Steam图片加速功能失效，Steam客户端中自己的头像、游戏中覆盖的好友头像以及成就都无法成功刷新，回滚2.7.2后此功能仍然有效

### 🚑 其他信息(Other Information)
![image](https://user-images.githubusercontent.com/85654042/180631910-0b8c1ab0-0340-4783-aae8-17438e1e9230.png)
![image](https://user-images.githubusercontent.com/85654042/180631955-a5ea394f-118a-4d08-9de9-9dfa804293f5.png)

- 程序版本(Program Version):2.8.1
- 系统版本号(OS Version): Windows11.22000.795
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by Nepchico** [comment]
[nlog-all-2022-07-24.log](https://github.com/BeyondDimension/SteamTools/files/9175127/nlog-all-2022-07-24.log)
附上此次运行的log
在此次运行中，有过几次成功刷新，但稳定性非常低

**Comment by rmbadmin** [comment]
看起来日志里并没有与steam图片加速相关的记录，问题应该是其它个例问题，大部分用户都正常使用

**Comment by Nepchico** [comment]
![image](https://user-images.githubusercontent.com/85654042/180632328-041bff2b-f914-4efe-a08a-b72a1c7bf51f.png)
我觉得这一条应该是对应Steam图片加速的🤔

**Comment by rmbadmin** [comment]
> ![image](https://user-images.githubusercontent.com/85654042/180632328-041bff2b-f914-4efe-a08a-b72a1c7bf51f.png) 我觉得这一条应该是对应Steam图片加速的🤔

但是这一条是旧版本的，新版本不会有这个

**Comment by AigioL** [comment]
> ![image](https://user-images.githubusercontent.com/85654042/180632328-041bff2b-f914-4efe-a08a-b72a1c7bf51f.png) 我觉得这一条应该是对应Steam图片加速的🤔

这条应该是 2.7.x 中出现的，在 2.8.x 中使用 Yarp 替换了 Titanium-Web-Proxy

**Comment by Mossimos** [comment]
而且头像是这个地址
https://avatars.akamai.steamstatic.com/01e32179008648cd2f1ddcfa80b14343a8ca62ca_medium.jpg

**Comment by SeYingSi** [comment]
我也遇到了这个问题，加速选项里把steam图片加速去掉就可以正常显示头像了

**Comment by Nepchico** [comment]
> 我也遇到了这个问题，加速选项里把steam图片加速去掉就可以正常显示头像了

我的网络是移动的，不挂加速就是无法加载的
这个东西的加速就是我提的建议，用来修复我这种网络不加速无法加载的情况
不过现在无法使用了就有点心烦。。。☹️回滚2.7.2倒是正常的

**Comment by rmbadmin** [comment]
> > 我也遇到了这个问题，加速选项里把steam图片加速去掉就可以正常显示头像了
> 
> 我的网络是移动的，不挂加速就是无法加载的 这个东西的加速就是我提的建议，用来修复我这种网络不加速无法加载的情况 不过现在无法使用了就有点心烦。。。☹️回滚2.7.2倒是正常的

所以你这里是无法访问这个地址吗https://avatars.akamai.steamstatic.com/01e32179008648cd2f1ddcfa80b14343a8ca62ca_medium.jpg

**Comment by MemoryFoam6694** [comment]
> > > 我也遇到了这个问题，加速选项里把steam图片加速去掉就可以正常显示头像了
> > 
> > 
> > 我的网络是移动的，不挂加速就是无法加载的 这个东西的加速就是我提的建议，用来修复我这种网络不加速无法加载的情况 不过现在无法使用了就有点心烦。。。☹️回滚2.7.2倒是正常的
> 
> 所以你这里是无法访问这个地址吗 https://avatars.akamai.steamstatic.com/01e32179008648cd2f1ddcfa80b14343a8ca62ca_medium.jpg

我也是这个问题，
![2SU0YVQ~KPV5ZKO{H)6_{~F](https://user-images.githubusercontent.com/63762873/181174235-ff5fb744-bb86-4758-8506-0959a958706e.png)
右上角头像不显示，CSGO里个人头像也是不显示

**Comment by rmbadmin** [comment]
> > > > 我也遇到了这个问题，加速选项里把steam图片加速去掉就可以正常显示头像了
> > > 
> > > 
> > > 我的网络是移动的，不挂加速就是无法加载的 这个东西的加速就是我提的建议，用来修复我这种网络不加速无法加载的情况 不过现在无法使用了就有点心烦。。。☹️回滚2.7.2倒是正常的
> > 
> > 
> > 所以你这里是无法访问这个地址吗 https://avatars.akamai.steamstatic.com/01e32179008648cd2f1ddcfa80b14343a8ca62ca_medium.jpg
> 
> 我也是这个问题， ![2SU0YVQ~KPV5ZKO{H)6_{~F](https://user-images.githubusercontent.com/63762873/181174235-ff5fb744-bb86-4758-8506-0959a958706e.png) 右上角头像不显示，CSGO里个人头像也是不显示

所以能回答我一下开启steam图片加速后访问https://avatars.akamai.steamstatic.com/01e32179008648cd2f1ddcfa80b14343a8ca62ca_medium.jpg
这个地址的结果吗

**Comment by Nepchico** [comment]
> > > > > 我也遇到了这个问题，加速选项里把steam图片加速去掉就可以正常显示头像了
> > > > 
> > > > 
> > > > 我的网络是移动的，不挂加速就是无法加载的 这个东西的加速就是我提的建议，用来修复我这种网络不加速无法加载的情况 不过现在无法使用了就有点心烦。。。☹️回滚2.7.2倒是正常的
> > > 
> > > 
> > > 所以你这里是无法访问这个地址吗 https://avatars.akamai.steamstatic.com/01e32179008648cd2f1ddcfa80b14343a8ca62ca_medium.jpg
> > 
> > 
> > 我也是这个问题， ![2SU0YVQ~KPV5ZKO{H)6_{~F](https://user-images.githubusercontent.com/63762873/181174235-ff5fb744-bb86-4758-8506-0959a958706e.png) 右上角头像不显示，CSGO里个人头像也是不显示
> 
> 所以能回答我一下开启steam图片加速后访问https://avatars.akamai.steamstatic.com/01e32179008648cd2f1ddcfa80b14343a8ca62ca_medium.jpg 这个地址的结果吗

![image](https://user-images.githubusercontent.com/85654042/181264024-37813e04-42ee-4758-ad09-b2c2e41c61c7.png)
正常，steam内部应该不是使用这个头像的CDN

**Comment by rmbadmin** [comment]
@Nepchico 但根据抓包结果显示，steam客户端就是根据这个地址来展示头像图片的，能正常访问那steam客户端内也应该正常才对，而且据用户反馈来看，貌似只有移动网用户有这样的问题，你们出现这个问题的都是移动网络吗？

**Comment by Nepchico** [comment]
> @Nepchico 但根据抓包结果显示，steam客户端就是根据这个地址来展示头像图片的

那奇怪了🤔
不过根据hosts加速的结果看，你们没有把这个地址加到服务里
![image](https://user-images.githubusercontent.com/85654042/181265393-330d7067-4ed9-4923-befc-02cdcbdf10ed.png)
是的，我是移动网络的用户，如果没有加速，这个问题是一直存在的
而且2.7.2以前加速就没有这个问题，就挺迷的

**Comment by rmbadmin** [comment]
> > @Nepchico 但根据抓包结果显示，steam客户端就是根据这个地址来展示头像图片的
> 
> 那奇怪了🤔 不过根据hosts加速的结果看，你们没有把这个地址加到服务里 ![image](https://user-images.githubusercontent.com/85654042/181265393-330d7067-4ed9-4923-befc-02cdcbdf10ed.png) 是的，我是移动网络的用户，如果没有加速，这个问题是一直存在的 而且2.7.2以前加速就没有这个问题，就挺迷的

你这张图第28行不就是这个地址么

**Comment by MemoryFoam6694** [comment]
> > > @Nepchico 但根据抓包结果显示，steam客户端就是根据这个地址来展示头像图片的
> > 
> > 
> > 那奇怪了🤔 不过根据hosts加速的结果看，你们没有把这个地址加到服务里 ![image](https://user-images.githubusercontent.com/85654042/181265393-330d7067-4ed9-4923-befc-02cdcbdf10ed.png) 是的，我是移动网络的用户，如果没有加速，这个问题是一直存在的 而且2.7.2以前加速就没有这个问题，就挺迷的
> 
> 你这张图第28行不就是这个地址么

       我已经回退到2.7.2了，网址是显示头像的，我是移动的网络。在2.7.2是正常的

**Comment by rmbadmin** [comment]
> > > > @Nepchico 但根据抓包结果显示，steam客户端就是根据这个地址来展示头像图片的
> > > 
> > > 
> > > 那奇怪了🤔 不过根据hosts加速的结果看，你们没有把这个地址加到服务里 ![image](https://user-images.githubusercontent.com/85654042/181265393-330d7067-4ed9-4923-befc-02cdcbdf10ed.png) 是的，我是移动网络的用户，如果没有加速，这个问题是一直存在的 而且2.7.2以前加速就没有这个问题，就挺迷的
> > 
> > 
> > 你这张图第28行不就是这个地址么
> 
> ```
>    我已经回退到2.7.2了，网址是显示头像的，我是移动的网络。在2.7.2是正常的
> ```

我需要的是有问题的人帮忙测试 2.8版本，2.7.2没问题的情况我已经知道了，但我因为不能复现问题所以只能靠你们测试2.8版本

**Comment by rmbadmin** [comment]
> > > > @Nepchico 但根据抓包结果显示，steam客户端就是根据这个地址来展示头像图片的
> > > 
> > > 
> > > 那奇怪了🤔 不过根据hosts加速的结果看，你们没有把这个地址加到服务里 ![image](https://user-images.githubusercontent.com/85654042/181265393-330d7067-4ed9-4923-befc-02cdcbdf10ed.png) 是的，我是移动网络的用户，如果没有加速，这个问题是一直存在的 而且2.7.2以前加速就没有这个问题，就挺迷的
> > 
> > 
> > 你这张图第28行不就是这个地址么
> 
> ```
>    我已经回退到2.7.2了，网址是显示头像的，我是移动的网络。在2.7.2是正常的
> ```

我需要的是有问题的人帮忙测试 2.8版本，2.7.2没问题的情况我已经知道了，但我因为不能复现问题所以只能靠你们测试2.8版本

**Comment by Nepchico** [comment]
> > > > > @Nepchico 但根据抓包结果显示，steam客户端就是根据这个地址来展示头像图片的
> > > > 
> > > > 
> > > > 那奇怪了🤔 不过根据hosts加速的结果看，你们没有把这个地址加到服务里 ![image](https://user-images.githubusercontent.com/85654042/181265393-330d7067-4ed9-4923-befc-02cdcbdf10ed.png) 是的，我是移动网络的用户，如果没有加速，这个问题是一直存在的 而且2.7.2以前加速就没有这个问题，就挺迷的
> > > 
> > > 
> > > 你这张图第28行不就是这个地址么
> > 
> > 
> > ```
> >    我已经回退到2.7.2了，网址是显示头像的，我是移动的网络。在2.7.2是正常的
> > ```
> 
> 我需要的是有问题的人帮忙测试 2.8版本，2.7.2没问题的情况我已经知道了，但我因为不能复现问题所以只能靠你们测试2.8版本

好的，回车没按，人已经瞎了☹️

**Comment by SeYingSi** [comment]
> 

移动确实惨了，我电信，前段时间也突然加载不了就开着了，现在关了又可以加载了

**Comment by Nepchico** [comment]
2.8.2更新后问题已修复👌
