### ISSUE TITLE
🧐[Question]  加速twitch没有聊天室消息.

### ISSUE THREAD

**Issue by lwj528** [BeyondDimension/SteamTools#1723]
### 🧐 问题描述(Description)

2.7.2 和 v2.8.1  加速twitch没有聊天室消息.前2天都有,本人用的联通, 
### 🚑 其他信息(Other Information)
![捕获](https://user-images.githubusercontent.com/67459448/180634144-b20aacd1-ccf5-4ec0-bda9-6cf4132cb55d.JPG)

**Comment by rmbadmin** [comment]
服务端热更新修复了，等待半小时缓存刷新后在重开软件加速即可

**Comment by lwj528** [comment]
> 服务端热更新修复了，等待半小时缓存刷新后在重开软件加速即可

现在又加速不了了
