### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by a44a14** [BeyondDimension/SteamTools#1727]
### 📷 复现步骤(Steps to Reproduce)

1. 打开
2. 加速
3. 闪退

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.1
- 系统版本号(OS Version): win7sp1
- 是否为应用商店版本(Whether it is a Store version): no

**Comment by AigioL** [comment]
#1726 重复
