### ISSUE TITLE
👑[Enhancement] 请求加速steam客服页面

### ISSUE THREAD

**Issue by Wildwizard404** [BeyondDimension/SteamTools#1733]
### 🥰 需求描述(Description)
无法对steam客服页面进行加速，使用host模式并查看host文件，发现并没有help.steampowered.com的记录。
### 🧐 解决方案(Solution)

NAN

### 🚑 其他信息(Other Information)

NAN

**Comment by rmbadmin** [comment]
已在新版本添加
