### ISSUE TITLE
🐛[BUG] 一个老问题，部分网站加速失效

### ISSUE THREAD

**Issue by lx20000904** [BeyondDimension/SteamTools#1760]
### 🐛 描述(Description)
window10，从2.7.2版本开始就出现twitch登录加速无效，V2EX网站加速失败，无法进入官网，twitch观看直播和聊天都正常，点登录直接转圈，然后转一会就会停留在登录界面，一直点登录一直转圈。v2ex则是根本没加速，直接404。
### 🚑 基本信息(Basic Information)
- 程序版本(Program Version):2.8.1
- 系统版本号(OS Version): window 10 21H2
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by rmbadmin** [comment]
v2ex我测试正常，twitch登录问题目前已发现，还在处理

**Comment by lx20000904** [comment]
> 

我测试了一下发现，v2ex的问题还是存在，加速模式选择DNS和host模式的话，如果启用脚本的话，会直接提示“该网页无法正常运作www.v2ex.com 目前无法处理此请求。HTTP ERROR 502”，不启用脚本显示“{"error":"Request","message":"Because https://www.v2ex.com/ actually points to WattToolkit itself, WattToolkit has interrupted this forwarding"}”，PAC模式无论开不开启脚本会提示“网址为 https://www.v2ex.com/# 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。”换到系统代理模式的话无论开不开启脚本过一会都能成功进入官网。

以上结果只针对v2ex网站，其他网站暂时没有测试，浏览器是谷歌版本 103.0.5060.66（正式版本）（64 位）

**Comment by rmbadmin** [comment]
v2ex的问题已经发现，下个版本更新后修复

**Comment by lx20000904** [comment]
2.8.2版本v2ex在DNS模式开启脚本状态能打开，偶尔有加载卡顿连接不上的情况，twitch登录问题依旧存在。

**Comment by rmbadmin** [comment]
twitch登录已经热更新修复
