### ISSUE TITLE
我windows 10 误判成windows 8

### ISSUE THREAD

**Issue by RightFS** [BeyondDimension/SteamTools#1761]
![image](https://user-images.githubusercontent.com/12915306/180980540-411706c3-0e16-4f24-88a0-a922336df18a.png)

![image](https://user-images.githubusercontent.com/12915306/180980583-694403ae-f7bd-4c60-a5a2-253b68643b83.png)

**Comment by AigioL** [comment]
在 2.8.1 中已修复

**Comment by RightFS** [comment]
我下的就是2.8.1

![image](https://user-images.githubusercontent.com/12915306/180982738-599409c2-687b-49f5-8841-f2d2efe223d4.png)

**Comment by RightFS** [comment]
@AigioL

**Comment by AigioL** [comment]
https://github.com/BeyondDimension/SteamTools/issues/1716#issuecomment-1193226676
