### ISSUE TITLE
🐛[BUG] 无法加速bug

### ISSUE THREAD

**Issue by beeyeefox** [BeyondDimension/SteamTools#1762]
[nlog-all-2022-07-26.log](https://github.com/BeyondDimension/SteamTools/files/9190466/nlog-all-2022-07-26.log)

**Comment by rmbadmin** [comment]
你可以在当前提问里上传的，没必要新开问题

**Comment by beeyeefox** [comment]
> 你可以在当前提问里上传的，没必要新开问题

原来如此吗

**Comment by beeyeefox** [comment]
> 你可以在当前提问里上传的，没必要新开问题

希望大佬早日解决问题
