### ISSUE TITLE
书接上回，这个测试触发了更多的bug

### ISSUE THREAD

**Issue by lx20000904** [BeyondDimension/SteamTools#1765]
> 

我测试了一下发现，v2ex的问题还是存在，加速模式选择DNS和host模式的话，如果启用脚本的话，会直接提示“该网页无法正常运作www.v2ex.com 目前无法处理此请求。HTTP ERROR 502”，不启用脚本显示“{"error":"Request","message":"Because https://www.v2ex.com/ actually points to WattToolkit itself, WattToolkit has interrupted this forwarding"}”，PAC模式无论开不开启脚本会提示“网址为 https://www.v2ex.com/# 的网页可能暂时无法连接，或者它已永久性地移动到了新网址。”换到系统代理模式的话无论开不开启脚本过一会都能成功进入官网。

以上结果只针对v2ex网站，其他网站暂时没有测试，浏览器是谷歌版本 103.0.5060.66（正式版本）（64 位）

_Originally posted by @lx20000904 in https://github.com/BeyondDimension/SteamTools/issues/1760#issuecomment-1196154535_

**Comment by lx20000904** [comment]
使用系统代理模式一段时间后会陷入所有加速均失效的状态，不知道是到了一定的流量还是加速了一定的时间触发的bug，其他三种加速模式，如果从开机自启算的话，大体加速没问题，也很稳定，只是v2ex和twitch登录出现问题。目前总结出来的问题就这些，有新发现会跟进更新。

**Comment by rmbadmin** [comment]
嗯其实没必要开新问题，问题确实存在，我正在尝试修复

**Comment by lx20000904** [comment]
> 嗯其实没必要开新问题，问题确实存在，我正在尝试修复

好的，下回注意，可能是节点不稳定，下午我用DNS模式测试v2ex又能打开了。
