### ISSUE TITLE
🐛[BUG] 没有在您的电脑上读取到任何Steam帐户数据。

### ISSUE THREAD

**Issue by Petalses** [BeyondDimension/SteamTools#1767]
之前有十二个账号，今天开机突然没了捏，昨天还好好的，再登录账号里面也不显示记录了
![image](https://user-images.githubusercontent.com/104431661/181148548-66fd4f28-d056-4dff-a809-b3c3bb184efb.png)

**Comment by rmbadmin** [comment]
覆盖安装一遍steam然后重开steam++

**Comment by Petalses** [comment]
没重安装，下午开机自己就好了，不过是steam++缓存问题，还是steam用户数据的问题呢

**Comment by rmbadmin** [comment]
> 没重安装，下午开机自己就好了，不过是steam++缓存问题，还是steam用户数据的问题呢

steam++只从steam读取该数据，自身并不会缓存，既然问题已解决那么我会关闭这个问题
