### ISSUE TITLE
我的电脑是window 10家庭版的，但是在安装了watt toolkit之后无法运行，显示软件已经停止对window 8的支持🐛[BUG] 

### ISSUE THREAD

**Issue by ghost** [BeyondDimension/SteamTools#1768]
### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by rmbadmin** [comment]
重新下载非fde版本运行steam++.exe
