### ISSUE TITLE
🐛[BUG] 最新版watt toolkit只有在系统代理模式下出现使用http协议的网站大概率无法访问的情况

### ISSUE THREAD

**Issue by zse4t7i** [BeyondDimension/SteamTools#1772]
### 🐛 描述(Description)

只有在使用系统代理模式时，通过浏览器（edge、火狐）访问使用http协议的网站（如 http://immersivemath.com ）时无法访问，具体表现为浏览器地址栏中出现原网址不断复制以至于超过浏览器限制的超长网址字符串，而相关网站可ping通，具体详见第一个gif动图。

顺便反馈一个小问题，在我的电脑上使用DNS驱动拦截模式和hosts代理模式时无法使用github的ssh，但pac代理和系统代理模式则可以，具体详见#1108 中的对话。

### 📷 复现步骤(Steps to Reproduce)

1. 打开watt toolkit并使用系统代理模式
2. 访问http网站

### 📄 日志信息(Log Information)

日志文件：
[nlog-all-2022-07-28.log](https://github.com/BeyondDimension/SteamTools/files/9203003/nlog-all-2022-07-28.log)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):**2.8.1**
- 系统版本号(OS Version): **Windows 10.0.22000**
- 是否为应用商店版本(Whether it is a Store version): **Yes**

### 🖼 截图(Screenshots)
![动画1](https://user-images.githubusercontent.com/51823222/181351279-7b48fa2e-2381-4406-8c88-a16bc2ee492e.gif)

**Comment by beiming42** [comment]
这是日志文件：
[nlog-all-2022-07-28.log](https://github.com/BeyondDimension/SteamTools/files/9202999/nlog-all-2022-07-28.log)

**Comment by rmbadmin** [comment]
这个问题已经修复，在下个版本发布时会解决

**Comment by beiming42** [comment]
嗯好谢谢

**Comment by zse4t7i** [comment]
好耶！谢谢大大❤️

**Comment by zse4t7i** [comment]
请问“下个版本”是指2.8.2吗，今天这版试了一下，条件不变，访问http网站会自动改成https协议导致访问失败

**Comment by rmbadmin** [comment]
> 请问“下个版本”是指2.8.2吗，今天这版试了一下，条件不变，访问http网站会自动改成https协议导致访问失败

默认就是http自动转http这么处理的，你如果不希望可以在代理设置中关闭
![image](https://user-images.githubusercontent.com/12234359/181478529-d4547078-67d9-47d1-8a3b-2d1fb551d10f.png)

**Comment by zse4t7i** [comment]
关掉这个选项可以访问了，辛苦大大了💕
