### ISSUE TITLE
👑[Enhancement] 请求添加对imgur图床的支持

### ISSUE THREAD

**Issue by jalaxy33** [BeyondDimension/SteamTools#1774]
### 🥰 需求描述(Description)

请求添加对imgur图床的支持。我目前正在使用一些markdown笔记软件，有将图片上传到图床的需求，imgur图床免费且无上传上限，因此选择使用imgur作为主力图床，但是目前国内访问imgur需要挂代理，所以希望你们能增加对于imgur图床的支持。

非常感谢你们带来的这么好用的工具！

**Comment by rmbadmin** [comment]
目前是有imgur加速选项的，在其它网站中

**Comment by jadada** [comment]
> 目前是有imgur加速选项的，在其它网站中

确实有，感谢回答！
