### ISSUE TITLE
👑[Enhancement] 添加对Minecraft国际版的加速支持

### ISSUE THREAD

**Issue by Nightingale0504** [BeyondDimension/SteamTools#1776]
### 🥰 需求描述(Description)
如题，添加对Minecraft国际版的加速支持，因为Minecraft的服务器在国外，更新速度极慢，会耗费大量时间，而网上又没有几个能用的方案，所以想让Watt Toolkit包含此功能，以加速Minecraft的更新

### 🧐 解决方案(Solution)
添加对Minecraft国际版的加速支持

**Comment by guihongwong** [comment]
转对面dogfilght360的host 如果是基岩版 
&有点不理解

**Comment by Nightingale0504** [comment]
> 转对面dogfilght360的host 如果是基岩版 &有点不理解

是对Minecraft Launcher的加速支持，没说清楚，抱歉

**Comment by GuihongWang** [comment]
> > 转对面dogfilght360的host 如果是基岩版 &有点不理解
> 
> 是对Minecraft Launcher的加速支持，没说清楚，抱歉

大号 那就可以用那个dogfilght360的那个host工具  那个有对应的加速

**Comment by Nightingale0504** [comment]
Xbox的加速吗？没找到minecraft之类的选项

**Comment by GuihongWang** [comment]
> Xbox的加速吗？没找到minecraft之类的选项

游戏内相关
我的世界启动器更新

**Comment by GuihongWang** [comment]
如果可以的话 建议关闭issue
这样可以给社区的工作人员减少负担
~~让issue数量比较好看一点~~
