### ISSUE TITLE
🧐[Question] steam++打不开

### ISSUE THREAD

**Issue by wwem** [BeyondDimension/SteamTools#1779]
打开了s

### 🧐 问题描述(Description)

2.8.1自动更新的2.8.2，更新完后打开就显示要NET6.0.7，我就按照他说的去NET官网下载安装了，但是安装完了还是打不开，重启电脑重装软件都试过了,都是显示要NET

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/110185933/181577662-d4711e6d-1c3a-42a0-99de-5e9961ce16bd.png)
![image](https://user-images.githubusercontent.com/110185933/181578101-d537e6ca-bb5a-471a-8673-8e54e8208273.png)

- 程序版本(Program Version):2.8.2
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by Mossimos** [comment]
因为ASF的需要 ASP.NET Core 运行时
而且你不了解这个的情况请不要下载FDE版本 直接下载完整版就行了 
![image](https://user-images.githubusercontent.com/26396340/181581501-37ccc9b1-36f9-44a6-9dc3-6731846166d7.png)

**Comment by AigioL** [comment]
https://download.visualstudio.microsoft.com/download/pr/175ea216-cfde-4fab-8184-c19ce4c1e349/05f550b728c9f53e3e14ec54f40f42aa/dotnet-runtime-6.0.7-win-x64.exe

https://download.visualstudio.microsoft.com/download/pr/c4c86d02-a47b-4bd4-b73d-ec3be19e5245/76c673e22a120464c95f85bef342a361/aspnetcore-runtime-6.0.7-win-x64.exe

装这两个或者用非 FDE 的版本
