### ISSUE TITLE
🐛[BUG] 2.8.1 自动更新模块版本识别问题

### ISSUE THREAD

**Issue by DCxDESIGN** [BeyondDimension/SteamTools#1781]
### 🐛 描述(Description)

【可能可以作为 #1779 的补充？】
2.8.1 自动更新模块会将非 FDE 版识别为 FDE 版，从而在自动更新时只下载 FDE 版，导致没有安装 .NET 和 ASP 运行时的机器在自动更新后报错无法打开

### 🖼 截图(Screenshots)

![SShot-20220729-030734-Steam++](https://user-images.githubusercontent.com/48208459/181623683-57d9431e-e6f9-482f-a3f9-aab9e56ffbb5.png)

**Comment by AigioL** [comment]
这个问题是个客户端错误，存在于现在已发行的版本，从 2.8.2 升级至下一个版本也会存在问题
好在服务端现已禁用 FDE 版本的自动更新下载，应该会跳转官网引导手动下载
