### ISSUE TITLE
🧐[Question] 2.8.2没有MSIX版本吗？

### ISSUE THREAD

**Issue by fuchanghao** [BeyondDimension/SteamTools#1783]
### 🧐 问题描述(Description)
不知道什么原因我用Microsoft Store 检查不到2.8.2的更新。

于是打算下载msix版手动更新，发现无论是github还是gitee，以及各种网盘分流，都没有MSIX的版本。

是取消了2.8.2的msix版本发布计划了？

### 🚑 其他信息(Other Information)

- 程序版本(Program Version): 2.8.1
- 系统版本号(OS Version): Windows 10 21H2 19044.1826
- 是否为应用商店版本(Whether it is a Store version): 是

**Comment by rmbadmin** [comment]
微软商店需要审核，审核时间最短数小时最长三天，审核通过后还需要最长24小时才能给用户发更新推送
![image](https://user-images.githubusercontent.com/12234359/181670452-88d514aa-3bbe-4eda-b3f6-b5e36112511d.png)
