### ISSUE TITLE
### 🐛 描述(Description)

### ISSUE THREAD

**Issue by jadeteen989** [BeyondDimension/SteamTools#1787]
### 🐛 描述(Description)
window10，从2.7.2版本开始就出现twitch登录加速无效，V2EX网站加速失败，无法进入官网，twitch观看直播和聊天都正常，点登录直接转圈，然后转一会就会停留在登录界面，一直点登录一直转圈。v2ex则是根本没加速，直接404。
### 🚑 基本信息(Basic Information)
- 程序版本(Program Version):2.8.1
- 系统版本号(OS Version): window 10 21H2
- 是否为应用商店版本(Whether it is a Store version): No

__Originally posted by @lx20000904 in https://github.com/BeyondDimension/SteamTools/issues/1760__

**Comment by rmbadmin** [comment]
重复 #1760
