### ISSUE TITLE
👑[Enhancement] 建议增加mc加速

### ISSUE THREAD

**Issue by littlekan233** [BeyondDimension/SteamTools#1790]
### 🥰 需求描述(Description)

在mc游玩外国服务器较慢（如动作定格），有时候连不上，建议开发者对于mc进行加速

**Comment by GuihongWang** [comment]
建议自己搞中转服务器 这个工具是针对HTTP加速的 不是mc服务器的UDP TCP加速

**Comment by littlekan233** [comment]
> 建议自己搞中转服务器 这个工具是针对HTTP加速的 不是mc服务器的UDP TCP加速

好的 谢谢回答

**Comment by GuihongWang** [comment]
建议下次把github的邮箱提醒打开
