### ISSUE TITLE
<!--

### ISSUE THREAD

**Issue by jadeteen989** [BeyondDimension/SteamTools#1793]
### 🥰 需求描述(Description)

在mc游玩外国服务器较慢（如动作定格），有时候连不上，建议开发者对于mc进行加速

### 🚑 其他信息(Other Information)

__Originally posted by @littlekan233 in https://github.com/BeyondDimension/SteamTools/issues/1790__

**Comment by rmbadmin** [comment]
重复问题就不要反复开issues了#1790
