### ISSUE TITLE
🧐[Question] 安装之后缺少vpn加速和脚本配置菜单

### ISSUE THREAD

**Issue by buuu9** [BeyondDimension/SteamTools#1799]
[

### 🧐 问题描述(Description)

从微软商店和官网下载后均无法正常显示本地加速和脚本配置。有尝试过删除本地文件并重新安装，但是没有作用

### 🚑 其他信息(Other Information)

![Screenshot 2022-07-31 170957](https://user-images.githubusercontent.com/77175765/182020468-33fa82f3-62f7-456c-8ed0-f2cae04039ca.png)

- 程序版本(Program Version): Windows 2.8.2
- 系统版本号(OS Version):  Windows 11
- 是否为应用商店版本(Whether it is a Store version):  否

**Comment by rmbadmin** [comment]
注意更新公告，非简中语言不再显示加速和脚本功能 重复#1791

**Comment by buuu9** [comment]
> 哦谢谢，我没注意这一点。我再去试试
