### ISSUE TITLE
🐛[BUG] 史低价格脚本某些游戏匹配错误

### ISSUE THREAD

**Issue by slightin** [BeyondDimension/SteamTools#1811]
### 🐛 描述(Description)
史低脚本在查询某些游戏的史低价格时会返回的其他游戏的价格

### 📷 复现步骤(Steps to Reproduce)

1. 打开“steam历史最低价格查询”脚本并运行加速
2. 打开 https://store.steampowered.com/app/242760/The_Forest/
3. 点击下图红框内链接
![image](https://user-images.githubusercontent.com/67229521/182271649-5c4a7a1e-bd7e-4b12-a35c-5070d3535429.png)
4. 可以看到返回的是其他游戏 (https://store.steampowered.com/app/1859730/) 的链接

### 🚑 基本信息(Basic Information)

- 脚本版本(Script Version): 1.1
- 程序版本(Program Version): 2.8.2
- 系统版本号(OS Version): windows11 21H2
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by Mossimos** [comment]
这属于 api.augmentedsteam.com 数据返回的错误 ， 我们也修复不了
