### ISSUE TITLE
👑[Enhancement] 请问加速服务支持单独启动吗

### ISSUE THREAD

**Issue by mendax1234** [BeyondDimension/SteamTools#1812]
### 🥰 需求描述(Description)

比如我只想加速discord服务，有没有方法能够只开机自启动这个discord服务，而不启动steam++的图形界面？

**Comment by Ra2-IFV** [comment]
跟我想法一样 #1809 
解决办法就是加个CLI版本的

**Comment by mendax1234** [comment]
> 跟我想法一样 #1809 解决办法就是加个CLI版本的

所以，这个问题解决了吗？

**Comment by rmbadmin** [comment]
重复问题就关闭了 转 #1809
