### ISSUE TITLE
🐛[BUG] 流量统计页面出现内存泄漏

### ISSUE THREAD

**Issue by smallg0at** [BeyondDimension/SteamTools#1814]
### 🐛 描述(Description)

流量统计页面会导致内存占用严重超出正常范围，最高会到达 3GB

### 📷 复现步骤(Steps to Reproduce)

1. 打开 Watt Toolkit 和 任务管理器。由于本机设置，会自动开始加速。
2. 等待几秒，打开 GitHub 首页等任何能在监控表上呈现为流量数据的网站
3. 返回 Watt Toolkit，发现占用 RAM 来到了 1 GB 左右，并会发现内存量还在增加
4. 最小化程序，点击其他窗口，等待几秒，回到 Watt Toolkit，内存量小幅突增

### 📄 日志信息(Log Information)

Log 在复现过程中没有生成任何内容。

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.8。2
- 系统版本号(OS Version): Windows 11 Build 25169.1000
- 是否为应用商店版本(Whether it is a Store version): No

### 🖼 截图(Screenshots)

此为记录到的内存峰值（是在未刻意测试的情况下），甚至比 Edge 还多
![image](https://user-images.githubusercontent.com/30719670/182319783-6a882e76-daf0-4a4e-8816-026f446c450f.png)

**Comment by rmbadmin** [comment]
确定为流量统计造成的吗？，我这边测试无法复现此问题。

这个问题确实有部分用户反馈了，但具体原因因为无法复现还在寻找，
也有用户有两台设备，但问题只会在其中一个设备上出现的情况。

**Comment by smallg0at** [comment]
> 确定为流量统计造成的吗？，我这边测试无法复现此问题。
> 
> 这个问题确实有部分用户反馈了，但具体原因因为无法复现还在寻找， 也有用户有两台设备，但问题只会在其中一个设备上出现的情况。

确认了，只有在流量统计在前台时才会有明显的内存增长。

**Comment by reamger** [comment]
同样的问题，Microsoft应用商店版本v2.8.6，系统Windows 10 专业版 22H2 19045.2486
只要流量统计在前台且窗口没有被最小化，在taskmgr里查看内存占用会以约每秒25M的速度增长，最高似乎没有上限（经测试可占用 6G+ 内存） 
但只要窗口没有在绘制流量统计图，内存增长马上停止，占用波动恢复正常（已占用内存仍未释放）

**Comment by rmbadmin** [comment]
关联至 #2708，3.0版本中应该被修复

**Comment by OutKeal** [comment]
最新版本仍然有此问题.我关闭了GPU硬件加速问题消失了

**Comment by Damdamgi** [comment]
还存在问题
版本是最新的3.0.0-rc.8
以下是日志
2024-05-29 08:30:59.9590|Error|SteamworksWebApiS|SendAsync fail由于目标计算机积极拒绝，无法连接。 (steam-chat.com:443)
 ---> System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
8:37截图
![8点37](https://github.com/BeyondDimension/SteamTools/assets/101446262/29984f1a-67fa-4a9d-b660-70422388ad8b)
8:39截图
![8点39](https://github.com/BeyondDimension/SteamTools/assets/101446262/bb8f5c97-ed0e-4baa-a998-82c22ed03817)
最大峰值为1246M

windows  10专业版22H2
访问steam时产生流量消耗,能够让其占用内存速度加快

**Comment by Damdamgi** [comment]
![image](https://github.com/BeyondDimension/SteamTools/assets/101446262/c1f79af2-ea1a-4639-be7f-8fbd1367fe3b)
@rmbadmin
