### ISSUE TITLE
👑可不可以加一个Youtube的进入host代理(Can you add a Youtube entry host proxy)

### ISSUE THREAD

**Issue by Appleyoubi** [BeyondDimension/SteamTools#1820]
可不可以添加一个Youtube的网络Hosts代理，让中国人可以在Youtube里发售视频。也可以让中国人看Youtube中的视频，实现外交，谢谢
Can you add a Youtube web Hosts proxy so that Chinese can sell videos on Youtube? You can also let Chinese watch the video in Youtube and achieve diplomacy, thank you

**Comment by AigioL** [comment]
#479 #685 #847 #898 #1246 #1328 #1332 重复

**Comment by buiawpkgew1** [comment]
这个可能添加不了

**Comment by Appleyoubi** [comment]
Why，是因为要跳网吗？

**Comment by Appleyoubi** [comment]
@buiawpkgew1 问一下是因为要跳网的问题吗？我相信你们Watt Tookit Awo..

**Comment by buiawpkgew1** [comment]
> @buiawpkgew1 问一下是因为要跳网的问题吗？我相信你们Watt Tookit Awo..

我不知道,我又不是作者 建议挂VPN上网
