### ISSUE TITLE
🧐[Question] 没找到加速功能

### ISSUE THREAD

**Issue by xiaopangju** [BeyondDimension/SteamTools#1823]
### 🧐 问题描述(Description)

我从Aur安装了watt-toolkit-bin包，但是无法找到加速页面
### 🚑 其他信息(Other Information)
![image](https://user-images.githubusercontent.com/56964531/182757971-7617c92f-9f8a-43ab-a27e-847c46bacdc8.png)
![image](https://user-images.githubusercontent.com/56964531/182758170-49e0d48b-a45f-4be7-a5ed-817287d51b5a.png)

- 程序版本(Program Version):V2.8.2
- 系统版本号(OS Version): Manjaro 21.3.6 Ruah
- 是否为应用商店版本(Whether it is a Store version): 否(No)

**Comment by ElemenTP** [comment]
https://github.com/BeyondDimension/SteamTools/releases/tag/2.8.0

steam++语言改为简体中文并重启steam++即可

**Comment by xiaopangju** [comment]
@ElemenTP 设置是点不开的

**Comment by ElemenTP** [comment]
> @ElemenTP 设置是点不开的

确实，忘了linux和macos上设置点不开这个事。。。那你可能需要把系统语言改为简体中文

**Comment by AigioL** [comment]
## 📁 存储空间
- AppData
    - Microsoft Store ```%USERPROFILE%\AppData\Local\Packages\4651ED44255E.47979655102CE_k6txddmbb6c52\LocalState```
    - Windows ```\AppData``` or ```%LocalAppData%\Steam++```
    - macOS ```~/Library/Steam++```
    - Linux ```$XDG_DATA_HOME/Steam++``` or ```$HOME/.local/share/Steam++```
    - Android ```/data/data/net.steampp.app/files```
- Cache
    - Microsoft Store ```%USERPROFILE%\AppData\Local\Packages\4651ED44255E.47979655102CE_k6txddmbb6c52\LocalCache```
    - Windows ```\Cache``` or ```%Tmp%\Steam++```
    - macOS ```~/Library/Caches/Steam++```
    - Linux ```$XDG_CACHE_HOME/Steam++``` or ```$HOME/.cache/Steam++```
    - Android ```/data/data/net.steampp.app/cache```
- Logs
    - Microsoft Store ```%USERPROFILE%\AppData\Local\Packages\4651ED44255E.47979655102CE_k6txddmbb6c52\LocalCache\Logs```
    - Windows ```\Logs``` or ```%Tmp%\Steam++\Logs```
    - macOS ```~/Library/Caches/Steam++/Logs```
    - Linux ```$XDG_CACHE_HOME/Steam++/Logs``` or ```$HOME/.cache/Steam++/Logs```
    - Android ```/data/data/net.steampp.app/cache/Logs```

**Comment by AigioL** [comment]
Unix 上 语言与区域好像没有跟随系统，可以在 Windows 上将语言设置为中文，再将 AppData 目录上的 Config.mpo 文件替换

**Comment by AigioL** [comment]
在 Unix 上设置页面打不开的问题在 https://github.com/BeyondDimension/SteamTools/commit/33c6f0d5f9408a2cdd1ba554e344eeb4da6c6e99 中修复

Unix 上程序检测系统语言会是 en-US，这个问题暂时也没办法
下个版本会 ```非简中默认隐藏加速与脚本仅在 Windows 上生效```

可以在目前的 action 上下载编译的版本测试
https://github.com/BeyondDimension/SteamTools/actions/runs/2826909792

**Comment by xiaopangju** [comment]
> 在 Unix 上设置页面打不开的问题在 [33c6f0d](https://github.com/BeyondDimension/SteamTools/commit/33c6f0d5f9408a2cdd1ba554e344eeb4da6c6e99) 中修复
> 
> Unix 上程序检测系统语言会是 en-US，这个问题暂时也没办法 下个版本会 `非简中默认隐藏加速与脚本仅在 Windows 上生效`
> 
> 可以在目前的 action 上下载编译的版本测试 https://github.com/BeyondDimension/SteamTools/actions/runs/2826909792

谢谢，我有时间试试看
