### ISSUE TITLE
🐛[BUG] linux 2.8.2版本无法打开设置界面

### ISSUE THREAD

**Issue by ngdngdc** [BeyondDimension/SteamTools#1824]
### 🐛 描述(Description)

从AUR安装的watt-toolkit-bin2.8.2-1启动后点击设置无反应。

### 📷 复现步骤(Steps to Reproduce)

1. 从AUR安装的watt-toolkit-bin
2. 启动程序
3. 打开设置

### 📄 日志信息(Log Information)

[nlog-all-2022-08-04.log](https://github.com/BeyondDimension/SteamTools/files/9257000/nlog-all-2022-08-04.log)
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.2-1(AUR)
- 系统版本号(OS Version): 5.18.14-1-Manjaro-Cinnamon
- 是否为应用商店版本(Whether it is a Store version): No

### 🖼 截图(Screenshots)
![图片](https://user-images.githubusercontent.com/61965178/182774112-631043b7-b51a-404f-9cff-318b3c7c4b1c.png)

**Comment by iforgetmyname** [comment]
OS：macOS Monterey 12.5 arm64
软件版本：2.8.2 beta for macOS (arm64)， 2.8.2 beta for macOS (x64) rosetta转译

经过测试也无法正常打开设置页面

**Comment by David-Xian66** [comment]
对 Mac也打不开

**Comment by AigioL** [comment]
在 Unix 上设置页面打不开的问题在 https://github.com/BeyondDimension/SteamTools/commit/33c6f0d5f9408a2cdd1ba554e344eeb4da6c6e99 中修复

可以在目前的 action 上下载编译的版本测试
https://github.com/BeyondDimension/SteamTools/actions/runs/2826909792

**Comment by YuzhenQin** [comment]
> 在 Unix 上设置页面打不开的问题在 [33c6f0d](https://github.com/BeyondDimension/SteamTools/commit/33c6f0d5f9408a2cdd1ba554e344eeb4da6c6e99) 中修复
> 
> 可以在目前的 action 上下载编译的版本测试 https://github.com/BeyondDimension/SteamTools/actions/runs/2826909792

~~Actions 不会编译 Linux 版本？~~  
使用 AUR 上的 watt-toolkit-git 解决了

**Comment by AigioL** [comment]
> > 在 Unix 上设置页面打不开的问题在 [33c6f0d](https://github.com/BeyondDimension/SteamTools/commit/33c6f0d5f9408a2cdd1ba554e344eeb4da6c6e99) 中修复
> > 可以在目前的 action 上下载编译的版本测试 https://github.com/BeyondDimension/SteamTools/actions/runs/2826909792
> 
> Actions 不会编译 Linux 版本？

[Release]Steam++_linux_x64_e369c6a
https://github.com/BeyondDimension/SteamTools/suites/7737426888/artifacts/324551390
