### ISSUE TITLE
🐛[BUG] 未知原因的交易页面出现502的问题。

### ISSUE THREAD

**Issue by fuchanghao** [BeyondDimension/SteamTools#1825]
### 🐛 描述(Description)

部分浏览器使用加速方式访问交易页面时会报错。

### 📷 复现步骤(Steps to Reproduce)

1. 使用系统自带的edge浏览器，或者360极速浏览器X(最新版)。
2. 关闭所有扩展。
3. 开启网络加速，选择Hosts模式。
4. 访问一个好友的Steam主页，选择交易。
5. 弹出的交易窗口显示502错误。

即访问如下链接时出现了502错误：
https://steamcommunity.com/tradeoffer/new/?partner=349033330

额外测试：
1.Firefox和Steam客户端自带浏览器正常。
2.使用steamcommunity_302_V12.1.4进行Hosts代理正常。
3.使用代理服务器访问正常。

### 📄 日志信息(Log Information)

[nlog-all-2022-08-04.log](https://github.com/BeyondDimension/SteamTools/files/9258236/nlog-all-2022-08-04.log)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): v2.8.2
- 系统版本号(OS Version): Windows 10 IoT LTSC 2021 x64 19044.1865 
- 是否为应用商店版本(Whether it is a Store version): 是

### 🖼 截图(Screenshots)

![屏幕截图 2022-08-04 165251](https://user-images.githubusercontent.com/11471475/182806424-444fa5a1-1b05-4478-b6ab-bf39c6e3dd47.png)
![屏幕截图 2022-08-04 165548](https://user-images.githubusercontent.com/11471475/182808006-46e3272b-6afc-4eec-b0ad-375839d8ef6e.png)
![屏幕截图 2022-08-04 165727](https://user-images.githubusercontent.com/11471475/182808036-cf0a4adf-9604-4f1e-a78b-0a33391a9dcd.png)

**Comment by fuchanghao** [comment]
今天更新了2.8.3，测试问题依旧。

不得不换成steamcommunity_302_V12.1.5，进行steam相关代理。

依旧有：Request headers must contain only ASCII characters. 的问题。

[nlog-all-2022-08-15.log](https://github.com/BeyondDimension/SteamTools/files/9334799/nlog-all-2022-08-15.log)

**Comment by rmbadmin** [comment]
我这里测试一切正常 无法复现问题，所以并没有处理该问题。
异常原因是指请求的header中包含了非ASCII字符，但反代并没有添加过这样的字符header，有点谜

**Comment by fuchanghao** [comment]
> 我这里测试一切正常 无法复现问题，所以并没有处理该问题。 异常原因是指请求的header中包含了非ASCII字符，但反代并没有添加过这样的字符header，有点谜


抓包出来的请求头信息，我也看不懂哪里触犯了非ASCII字符：

```
请求 URL: https://steamcommunity.com/tradeoffer/new/?partner=349033330
请求方法: GET
状态代码: 502 
远程地址: 127.0.0.3:443
引用站点策略: strict-origin-when-cross-origin
content-length: 0
content-type: application/json; charset=utf-8
date: Mon, 15 Aug 2022 06:45:40 GMT
server: Kestrel
:authority: steamcommunity.com
:method: GET
:path: /tradeoffer/new/?partner=349033330
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,ja;q=0.5,mt;q=0.4
cache-control: max-age=0
cookie: lastCategoryCount=ç¨€æœ‰åº¦; bCompletedTradeOfferTutorial=true; lastext_440=0; strTradeLastInventoryContext=440_2; timezoneOffset=28800,0; sessionid=4c7182996c8417dfff55bfa4; steamMachineAuth76561198309299058=9CF1001705130277ECEC5207133866AFD1069408; webTradeEligibility=%7B%22allowed%22%3A1%2C%22allowed_at_time%22%3A0%2C%22steamguard_required_days%22%3A15%2C%22new_device_cooldown_days%22%3A7%2C%22time_checked%22%3A1635552606%7D; Steam_Language=schinese; browserid=2475306690174673341; app_impressions=970830@2_100400_100401_|979070@2_100400_100401_|550470@2_100400_100401_|1150080@2_9_100015_100202|730310@2_100100_100101_100102|730310@2_100100_100101_100102|730310@2_100100_100101_100102|223850@2_100300_300_|223850@2_9_100000_|223850@2_9_100009_|223850@2_100100_100101_100106|223850@2_9_100009_|223850@2_100100_100101_100106|223850@2_100100_100101_100106|636570@2_100300_100500__100503|743280@2_100300_100500__100503|1846630@2_100300_100500__100503|1959900@2_100300_100500__100503|446530@2_100300_100500__100503|1854250@2_100300_100500__100503|1954640@2_100300_100500__100503|1987370@2_100300_100500__100503|1653050@2_100300_100500__100503|2060100@2_100300_100500__100503|446530@2_100300_100500__100503|1854250@2_100300_100500__100503|1954640@2_100300_100500__100503|1987370@2_100300_100500__100503|1854250@2_100300_100500__100503|1954640@2_100300_100500__100503|1987370@2_100300_100500__100503|1653050@2_100300_100500__100503|2060100@2_100300_100500__100503|446530@2_100300_100500__100503; steamCurrencyId=34; steamCountry=CN%7Cc78d3f2fa90fb05f24f12644263033c1; steamRememberLogin=76561198985936203%7C%7C0e2617442f7bd727321d6ce52cff79e3; steamLoginSecure=76561198985936203%7C%7C509090A5A920BEA4B6C85083F68812A0C5673C62; strInventoryLastContext=440_2; steamMachineAuth76561198985936203=; tsTradeOffersLastRead=1660527699
dnt: 1
sec-ch-ua: "Chromium";v="104", " Not A;Brand";v="99", "Microsoft Edge";v="104"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: none
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54
```

**Comment by rmbadmin** [comment]
看起来可能是cookie中的 ```lastCategoryCount=ç¨€æœ‰åº¦```
不太理解这是什么东西

**Comment by fuchanghao** [comment]
> 看起来可能是cookie中的 `lastCategoryCount=ç¨€æœ‰åº¦` 不太理解这是什么东西

这应该是“稀有度”的意思。

那个是windows-1252下识别UTF-8编码的结果。

还有一个账户是“品质”，看起来应该是交易时候对于不同类型物品的计数。

进一步查了一下这个cookie，这个比较奇怪，这个不是steam的cookie，是著名steam交易用插件的：Steam Inventory Helper

https://steaminventoryhelper.com/

**Comment by rmbadmin** [comment]
你可以试试关闭这个插件看看问题是否依旧

**Comment by fuchanghao** [comment]
> 你可以试试关闭这个插件看看问题是否依旧

我测试过禁用这个插件并清除steam网站的cookie后问题不再发生。

一旦开启这个插件就有这个问题，只能用其它支持非ASCII的反代工具，例如Watt Toolkit v2.7.2、Steamcommunity 302 v12.1.5等。

**Comment by rmbadmin** [comment]
> > 你可以试试关闭这个插件看看问题是否依旧
> 
> 我测试过禁用这个插件并清除steam网站的cookie后问题不再发生。
> 
> 一旦开启这个插件就有这个问题，只能用其它支持非ASCII的反代工具，例如Watt Toolkit v2.7.2、Steamcommunity 302 v12.1.5等。

知道问题原因倒是有办法解决了，我会处理一下转义这些非ascii字符，等下次更新吧
