### ISSUE TITLE
🧐[Question] ArchLinux证书导入等问题

### ISSUE THREAD

**Issue by ngdngdc** [BeyondDimension/SteamTools#1829]
### 🧐 问题描述(Description)
* Arch系的用户可能需要使用`sudo trust anchor --store SteamTools.Certificate.cer`导入证书才能正常加速Steam[#1094](https://github.com/BeyondDimension/SteamTools/issues/1094),但目前程序不会提示这一点.
* 使用QQ登录时第一次必然登录失败(至少我这边是这样的),点击网页上的重试后可成功登录.
* wiki、readme等页面需要更新.

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):2.8.2-1(AUR)
- 系统版本号(OS Version): 5.18.14-1-Manjaro-Gnome
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by Mossimos** [comment]
我之前测试的时候  Arch  是在 Chrome  安装证书后 Steam 也就都信任了 之前添加到系统证书里面也不被识别 。如果这个命令可用之后我会加上个提示的。得等之后试试
