### ISSUE TITLE
每次电脑重启需要重新输入密码和令牌🐛[BUG] 

### ISSUE THREAD

**Issue by FHfanshu** [BeyondDimension/SteamTools#1835]
现在每次重启电脑都需要重新输入steam密码和令牌了
即使选择了记住密码下一次重启也是这样
卸载重装steam问题依旧存在
真的很不方便

**Comment by FHfanshu** [comment]
应该是账户凭证出问题了

**Comment by FHfanshu** [comment]
虽然现在通过steamtool的账号切换功能 现在可以自动登陆了 但是软件里显示没有在我的电脑上读取到任何steam账户数据
![image](https://user-images.githubusercontent.com/88384345/183254168-29ea3fe3-b2cc-4c40-9586-9a0abbd0b0cf.png)

**Comment by rmbadmin** [comment]
覆盖重装steam即可

**Comment by FHfanshu** [comment]
好的我试试
&nbsp;


3357264605
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月6日(星期六) 晚上11:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BeyondDimension/SteamTools] 每次电脑重启需要重新输入密码和令牌🐛[BUG]  (Issue #1835)





 
覆盖重装steam即可
