### ISSUE TITLE
🐛[BUG] 启用加速后会禁用网卡IPV6，关闭后不会自动恢复

### ISSUE THREAD

**Issue by kylyzhh** [BeyondDimension/SteamTools#1836]
### 🐛 描述(Description)

启用加速后会禁用网卡IPV6，关闭后不会自动恢复

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/53763846/183255683-198e021a-f5aa-493e-a6bc-a856bc0a676a.png)

**Comment by rmbadmin** [comment]
steam++并不会做这样的事情，没有任何代码与这相关，据我所知某NN加速器是会有这样的行为的，建议你检查一下
