### ISSUE TITLE
👑[Enhancement] .NET MAUI/VS17.3 GA

### ISSUE THREAD

**Issue by wuliangtdi** [BeyondDimension/SteamTools#1861]
### 🥰 需求描述(Description)
vs 17.3.0正式版已更新，正式支持maui，是不是有计划迁移到微软官方的ui框架？

**Comment by AigioL** [comment]
之前有一个 XamarinForms 项目，这个项目内的部分内容应该会迁移到 MAUI
https://github.com/BeyondDimension/SteamTools/tree/develop/src/ST.Client.XamarinForms

MAUI 预计用于移动端上，Android 与 iOS，桌面端目前用的 AvaloniaUI 不会更改

之前尝试用 MAUI 的时候，Windows 上他是渲染到的 WinUI 3 上的，而且自带的导航组件渲染到 NavigationView 上，默认的渲染层还不支持一些功能，比如 ```PaneDisplayMode="Left/LeftCompact/LeftMinimal"```，强行改这个模式，也有问题

而且也没有保持 Fluent 的风格，反而像是 Material Design 的部分风格

WinUI 3 相比 WinUI 2(UWP) 实际上也有一些倒退，比如启动速度更慢、RAM 使用量和安装大小更大，在文档中也有提到这点
https://docs.microsoft.com/zh-cn/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/what-is-supported#performance-considerations

相比较而言在 Win 10 上比 AvaloniaUI 好一点，但是差距并不是很大，除非解决上面这些问题

VS 17.3 中 .NET MAUI 开发工具的 GA 中的 workload macos 支持没问题的话
现在的 macOS 版本应该改为这个 TFM，调用 Apple 平台的 API，要实现 Dock 栏，自定义协议 等一些平台功能

**Comment by AigioL** [comment]
close by #2339
