### ISSUE TITLE
库存游戏里有许多我不曾拥有的游戏

### ISSUE THREAD

**Issue by Chen-11111** [BeyondDimension/SteamTools#1873]
库存游戏里有许多我不曾拥有的游戏

### 🧐 问题描述(Description)

库存游戏里有许多我不曾拥有的游戏
是因为以前可能不小心登陆过其他账号吗？该如何清除

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/66070662/184049513-853e2b66-b8d3-42ce-958c-179ddb963ed9.png)

- 程序版本(Program Version):2.82（不同版本一直拥有）
- 系统版本号(OS Version): win10
- 是否为应用商店版本(Whether it is a Store version): no

**Comment by rmbadmin** [comment]
这一般是正常情况，游戏信息读取自steam缓存，并不一定会是拥有的。

**Comment by Chen-11111** [comment]
好的，了解了

**Comment by Chen-11111** [comment]
好的，了解了。希望开发者继续加油！
