### ISSUE TITLE
🧐[Question] 登陆账号登不上去，开不开加速都登不上去，浏览器报错504

### ISSUE THREAD

**Issue by muyueyuan** [BeyondDimension/SteamTools#1876]
### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by flyygph** [comment]
我的也是这样，微软商店的和官网下的2.8.2都试过了，还是504，用的是win10企业版21H2

**Comment by Liziyu352** [comment]
我也是，只要使用第三方服务登录watt toolbox就会蹦504错误

**Comment by rmbadmin** [comment]
目前已知是服务端问题，与客户端无关

**Comment by Liziyu352** [comment]
那就好，别搞个客户端大bug，然后就和wallpaper engine一样不修了

**Comment by Kal-tsit63** [comment]
问题相同,没法登录steam账号,网页能打开，点击登录后一直转圈，随后报504

**Comment by AigioL** [comment]
已修复
