### ISSUE TITLE
🐛[BUG] 多账号登录需要重新输入密码

### ISSUE THREAD

**Issue by Lcyeah096** [BeyondDimension/SteamTools#1878]
我有个阿根廷账号和我弟弟有时候会使用我的电脑，之前账户录入比较少的时候是可以正常切换账号不需要重新输入密码的，账号多起来之后切换账号每次都需要重新输入密码和steam令牌。软件上是有显示已记住登录状态的。。

**Comment by rmbadmin** [comment]
软件上显示的记住状态不是实时有效的，请检查steam登录状态是否已经失效。
https://steampp.net/faq#ChangeAccount
