### ISSUE TITLE
🧐[Question] watt toolkit的网页上标明了有steam和epic，但为什么当前下载的程序只是steam++的换名，并不支持epic？

### ISSUE THREAD

**Issue by Liziyu352** [BeyondDimension/SteamTools#1880]
截图----→
![image](https://user-images.githubusercontent.com/72553634/184352633-d3e5fe13-3c53-45c6-b733-def85d3a1d32.png)

- 程序版本(Program Version):Watt Toolkit v2.8.2
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): 是

**Comment by rmbadmin** [comment]
之前有支持，但效果不太理想所以暂时下掉了，steam++的加速主要是steam，其它加速项目都会视情况随时调整，官网图片不便于改动所以保持不变
