### ISSUE TITLE
每次开机无法自启动

### ISSUE THREAD

**Issue by RedarlingY** [BeyondDimension/SteamTools#1881]
开机后无法自启动且不能打开，只能重新下载，steam登录也失效了

**Comment by esirprus** [comment]
同样的问题：开机后无法自启动且无法打开。并且重新下载其他版本也不行。

**Comment by cEvolve05** [comment]
[#1862 (comment)](https://github.com/BeyondDimension/SteamTools/issues/1862#issuecomment-1210423305)
你可以试试这个方法

**Comment by rmbadmin** [comment]
重复 #1875  下个版本更新后会修复
