### ISSUE TITLE
🐛[BUG] 快捷登录中的Steam登录无法正常登录

### ISSUE THREAD

**Issue by ChocolaVanilla0305** [BeyondDimension/SteamTools#1884]
### 🐛 描述(Description)
快捷登录中的Steam登录,在网页浏览器中填写完信息跳转时显示"504 Gateway Time-out"
api.steampp.net Ping全红
https://ping.chinaz.com/api.steampp.net

### 📷 复现步骤(Steps to Reproduce)

使用快捷登陆中的Steam登录并填写完毕信息

### 🚑 基本信息(Basic Information)
 
- 程序版本(Program Version): v2.8.2
- 系统版本号(OS Version):  Windows 10 21H2
- 是否为应用商店版本(Whether it is a Store version):  否

### 🖼 截图(Screenshots)

![图片](https://user-images.githubusercontent.com/106427708/184496933-421ad1ab-ff6f-486f-ba4b-e630daf66367.png)

**Comment by AigioL** [comment]
与 #1876 相同，因为服务器在上海，Steam 登录接口是在社区上的，服务器也需要网络加速才能访问
之前的方案在服务器上不稳定，连不上就会这样超时，最近在改成现在客户端用的这套 Yarp 的代理方式，还没改好

**Comment by AigioL** [comment]
与 #1876 重复，现已修复
