### ISSUE TITLE
Android Watt 无法加速discord APP🧐[Question] 

### ISSUE THREAD

**Issue by Ignis-hoyee** [BeyondDimension/SteamTools#1885]
### 🧐 问题描述(Description)
根据软件指导在设置-安全重导入证书，导入CA证书后刷新该板块可以看到discord的加速选项，但选中后打开discord app没有加速效果依旧提醒“连接中”

### 🚑 其他信息(Other Information)

- 程序版本(Program Version): 2.8.2
- 系统版本号(OS Version): Android 12 MIUI 13.0.5稳定版
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by rmbadmin** [comment]
注意软件公告提示， 其它app是默认不信任用户证书的，这是android高版本安全机制，目前没什么好办法解决。

**Comment by Ignis-hoyee** [comment]
got it，十分感谢
