### ISSUE TITLE
🐛[BUG] An error occurred while sending the request

### ISSUE THREAD

**Issue by FoliageOwO** [BeyondDimension/SteamTools#1887]
### 🐛 描述(Description)

访问 Github，时不时会出现以下错误：
```json
{"error":"Request","message":"An error occurred while sending the request."}
```

除此之外，我在复现的过程中还时不时出现了 #1769 #1760 的问题：
```java
{"error":"Request","message":"Because https://github.com/topics/admin-dashboard actually points to WattToolkit itself, WattToolkit has interrupted this forwarding"}
```

有时候正常访问，有时候便出现以上 **两种错误**。

我尝试切换加速模式，`PAC 代理` 和 `系统代理` 直接无法连接，提示拒绝连接。

`Hosts 代理模式` 会出现上述第一个错误，`DNS 驱动拦截模式` 会出现上述第二个错误。

### 📷 复现步骤(Steps to Reproduce)

1. 访问 Github
2. 报错，无法正常访问

### 📄 日志信息(Log Information)

日志：[Pastbin](https://pastebin.ubuntu.com/p/GFDqPWvtTs/)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): v2.8.2
- 系统版本号(OS Version): Windows 7 SP1
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by rmbadmin** [comment]
更新刚刚发布的2.8.3，在观察一段时间问题是否依旧
