### ISSUE TITLE
无法启动🧐[Question] 

### ISSUE THREAD

**Issue by mayuhui123** [BeyondDimension/SteamTools#1888]
### 🧐 问题描述(Description)
在2.8.2尝试无法登录discird后，我尝试下载2.8.3并使用，但是安装完成后无法打开软件，之前的2.8.2和2.8.1可以正常打开

- 程序版本(Program Version):2.8.3
- 系统版本号(OS Version): win10
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by Azincc** [comment]
我是应用商店版的也有此问题 下载2.8.2安装包版也是不行

**Comment by rmbadmin** [comment]
提供下logs日志

**Comment by mayuhui123** [comment]
> 提供下logs日志

我没有在2.8.3里找到logs文
![I9`7(6VA@@LTW@$O479S L3](https://user-images.githubusercontent.com/111242759/184569641-b6e3781a-af65-4d72-a4d9-d3a54dbccfe8.png)
件

**Comment by rmbadmin** [comment]
> > 提供下logs日志
> 
> 我没有在2.8.3里找到logs文 ![I9`7(6VA@@LTW@$O479S L3](https://user-images.githubusercontent.com/111242759/184569641-b6e3781a-af65-4d72-a4d9-d3a54dbccfe8.png) 件

win+r 运行输入  %Tmp%\Steam++\Logs

**Comment by mayuhui123** [comment]
> > > 提供下logs日志
> > 
> > 
> > 我没有在2.8.3里找到logs文 ![I9`7(6VA@@LTW@$O479S L3](https://user-images.githubusercontent.com/111242759/184569641-b6e3781a-af65-4d72-a4d9-d3a54dbccfe8.png) 件
> 
> win+r 运行输入 %Tmp%\Steam++\Logs

2022-08-15 11:17:21.0422|Error|ViaFactory|(App)Close exception when OnExitRestoreHosts | System.Exception: DI.Get* fail, serviceType: System.Application.Services.IReverseProxyService
   at System.DI.Get_Nullable[T]()
   at System.Application.UI.Program.GlobalExceptionHelpers.Handler(Exception ex, String name, Nullable`1 isTerminating)

**Comment by rmbadmin** [comment]
> > > > 提供下logs日志
> > > 
> > > 
> > > 我没有在2.8.3里找到logs文 ![I9`7(6VA@@LTW@$O479S L3](https://user-images.githubusercontent.com/111242759/184569641-b6e3781a-af65-4d72-a4d9-d3a54dbccfe8.png) 件
> > 
> > 
> > win+r 运行输入 %Tmp%\Steam++\Logs
> 
> 2022-08-15 11:17:21.0422|Error|ViaFactory|(App)Close exception when OnExitRestoreHosts | System.Exception: DI.Get* fail, serviceType: System.Application.Services.IReverseProxyService at System.DI.Get_NullableT at System.Application.UI.Program.GlobalExceptionHelpers.Handler(Exception ex, String name, Nullable`1 isTerminating)

看看 %LocalAppData%\Steam++ 内的config.mpo是什么状况 以及删除再打开试试看

**Comment by mayuhui123** [comment]
> > > > > 提供下logs日志
> > > > 
> > > > 
> > > > 我没有在2.8.3里找到logs文 ![I9`7(6VA@@LTW@$O479S L3](https://user-images.githubusercontent.com/111242759/184569641-b6e3781a-af65-4d72-a4d9-d3a54dbccfe8.png) 件
> > > 
> > > 
> > > win+r 运行输入 %Tmp%\Steam++\Logs
> > 
> > 
> > 2022-08-15 11:17:21.0422|Error|ViaFactory|(App)Close exception when OnExitRestoreHosts | System.Exception: DI.Get* fail, serviceType: System.Application.Services.IReverseProxyService at System.DI.Get_NullableT at System.Application.UI.Program.GlobalExceptionHelpers.Handler(Exception ex, String name, Nullable`1 isTerminating)
> 
> 看看 %LocalAppData%\Steam++ 内的config.mpo是什么状况 以及删除再打开试试看

我没找到config.mpo

**Comment by rmbadmin** [comment]
@mayuhui123 能提供下截图看看appdata中有哪些文件么

**Comment by mayuhui123** [comment]
> 
![_PGCPM5Q19J8}}Z2WF5HI(F](https://user-images.githubusercontent.com/111242759/184574017-a40e8605-b926-4971-88ec-9071cccf95a8.png)

**Comment by mayuhui123** [comment]
> @mayuhui123 能提供下截图看看appdata中有哪些文件么
![_PGCPM5Q19J8}}Z2WF5HI(F](https://user-images.githubusercontent.com/111242759/184574057-4503b9a1-a898-48e8-96e4-6e5519de42c6.png)

**Comment by rmbadmin** [comment]
> > @mayuhui123 能提供下截图看看appdata中有哪些文件么
> > ![_PGCPM5Q19J8}}Z2WF5HI(F](https://user-images.githubusercontent.com/111242759/184574057-4503b9a1-a898-48e8-96e4-6e5519de42c6.png)

指的是 %LocalAppData%\Steam++

**Comment by mayuhui123** [comment]
> > > @mayuhui123 能提供下截图看看appdata中有哪些文件么
> > > ![_PGCPM5Q19J8}}Z2WF5HI(F](https://user-images.githubusercontent.com/111242759/184574057-4503b9a1-a898-48e8-96e4-6e5519de42c6.png)
> 
> 指的是 %LocalAppData%\Steam++

抱歉啊，我有点电脑白痴
![`G99NYSSAV ~LJ0JG{9A)P9](https://user-images.githubusercontent.com/111242759/184574440-a9bba555-197a-4842-8968-fe576632d782.png)
![I1UN8JBZ945O6G66${I`$F9](https://user-images.githubusercontent.com/111242759/184574446-a79b2298-313b-4e35-9819-18cdebe548e7.png)
![NPW}UIO9WH DJWL6 T_(N(C](https://user-images.githubusercontent.com/111242759/184574451-71f9caa0-df3a-43a5-845c-36f2651432e4.png)
![QH_QCQCIQPPPXK4 JRD6NQ6](https://user-images.githubusercontent.com/111242759/184574457-d3598032-fa45-45c4-9257-9c4314009f25.png)

**Comment by rmbadmin** [comment]
Win+R 输入 %LocalAppData%\Steam++  打不开吗？

**Comment by mayuhui123** [comment]
> Win+R 输入 %LocalAppData%\Steam++ 打不开吗？

对的，我这是没有这个的

**Comment by liuxiang2123** [comment]
兄弟 我知道怎么解决了 在AppData/Local 里面新建一个Steam++文件夹就可以打开了

**Comment by liuxiang2123** [comment]
估计是作者忘记把这个新建文件夹的程序写进去了

**Comment by mayuhui123** [comment]
> 估计是作者忘记把这个新建文件夹的程序写进去了

我草，你好强大....

**Comment by liuxiang2123** [comment]
> 

可以用了吧

**Comment by mayuhui123** [comment]
> > 
> 
> 可以用了吧

可以了

**Comment by mayuhui123** [comment]
虽然可以用了，但是我discord还是进不去.

**Comment by liuxiang2123** [comment]
> 虽然可以用了，但是我discord还是进不去.

我可以进去 刚加速的时候会让你安装个证书

**Comment by mayuhui123** [comment]
> 
刚下载玩启动都要安装证书的

**Comment by liuxiang2123** [comment]
> > 
> 
> 刚下载玩启动都要安装证书的

那不清楚了 我确实可以进dis

**Comment by mayuhui123** [comment]
> > > 
> > 
> > 
> > 刚下载玩启动都要安装证书的
> 
> 那不清楚了 我确实可以进dis

你用的什么加速模式

**Comment by AigioL** [comment]
已在 2.8.3.1 中修复
