### ISSUE TITLE
🧐[绑定steam账号失败] 

### ISSUE THREAD

**Issue by Randark-JMT** [BeyondDimension/SteamTools#1896]
### 🧐 绑定steam账号失败

在尝试绑定steam账号的时候，返回“绑定失败，此账号已被其他用户绑定”

### 🚑 其他信息(Other Information)

![图片](https://user-images.githubusercontent.com/56223739/184562044-5c943fc9-678b-40dc-bb0e-d43c720c3b45.png)

- 程序版本(Program Version):2.8.2
- 系统版本号(OS Version): Windows 10.19044.1889
- 是否为应用商店版本(Whether it is a Store version): 是

**Comment by rmbadmin** [comment]
字面意思，自行去关于注销其他账号
