### ISSUE TITLE
无法启动steam++ 点了一点反应没有

### ISSUE THREAD

**Issue by liuxiang2123** [BeyondDimension/SteamTools#1897]
无法启动steam++ 点了一点反应没有  刚刚还在用 然后下载了个向日葵远程 和我朋友通了下 steam++就打不开了 怎么点都没有如何反应.....然后我把向日葵卸载了 还是不行 没有反应
[internal-nlog.txt](https://github.com/BeyondDimension/SteamTools/files/9335039/internal-nlog.txt)
[nlog-all-2022-08-15.log](https://github.com/BeyondDimension/SteamTools/files/9335040/nlog-all-2022-08-15.log)

**Comment by rmbadmin** [comment]
这是安装版的一个问题，已经在处理了，你可以下免安装版或者等安装版重新发包一下

**Comment by liuxiang2123** [comment]
> 这是安装版的一个问题，已经在处理了，你可以下免安装版或者等安装版重新发包一下

我知道怎么解决了 在appdata/local里面新建个Steam++文件夹就可以解决了

**Comment by AigioL** [comment]
已在 2.8.3.1 中修复
