### ISSUE TITLE
🧐[Question] 内存占用问题

### ISSUE THREAD

**Issue by pengyirui** [BeyondDimension/SteamTools#1898]
### 🧐 问题描述(Description)

启动加速后内存就被吃了3个G了，这不正常吧。是BUG？
### 🚑 其他信息(Other Information)

![图片](https://user-images.githubusercontent.com/50801805/184587172-12aa7ba8-85c7-41ff-bf45-6a0e6b829478.png)

- 程序版本(Program Version):2.8.3
- 系统版本号(OS Version): win11
- 是否为应用商店版本(Whether it is a Store version): no

**Comment by rmbadmin** [comment]
目前有部分用户有这个问题，但我无法复现问题，具体原因暂时还未知，
推测可能是本地有其它非支持的加速项网络被解析到127.0.0.1导致了代理无限循环，你可以观察一下是否是此问题导致

**Comment by AigioL** [comment]
看上去可能与 #1814 相关

目前这个问题在我们的设备上没办法复现，所以比较难解决

如果有条件的话可以使用 [JetBrains dotMemory](https://www.jetbrains.com.cn/dotmemory/) 进行观察
使用方法可参考以下文章
https://blog.jetbrains.com/zh-hans/dotnet/2022/06/08/how-we-used-dotmemory-to-optimize-dotmemory/
https://www.cnblogs.com/qinhuan/p/13913460.html

**Comment by rmbadmin** [comment]
重复 #2708
