### ISSUE TITLE
🐛[BUG] 2.8.3便携版更新2.8.3.1会导致设置被重置

### ISSUE THREAD

**Issue by fuchanghao** [BeyondDimension/SteamTools#1911]
### 🐛 描述(Description)

2.8.3版本无法检测到修复版的2.8.3.1，从Github上下载7z包覆盖会导致所有设置被重置。

### 📷 复现步骤(Steps to Reproduce)

1. 下载之前的2.8.3旧版压缩包。
2. 检测更新，无法检测到2.8.3.1修正版进行自动升级。
3. 进行一些设置操作，例如导入令牌等。
4. 下载2.8.3.1版本压缩包覆盖升级，例如"Steam++_win_x64_v2.8.3.1.7z"，之前所有设置全部被初始化，令牌全部丢失，仅有ASF还在。

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.8.3.1
- 系统版本号(OS Version):  Windows 10 19044.1889 x64
- 是否为应用商店版本(Whether it is a Store version):  否

**Comment by fuchanghao** [comment]
怀疑是“修复 首次使用 Windows 安装版(非应用商店版) 可能导致程序无法正常启动”这个修复问题不操作有点问题。

通常绿色版版本。一般是首次运行时触发一段代码生成默认的配置文件，这样升级的时候不会影响已有的配置文件。

而不是软件包集成一个默认的配置文件，升级的时候覆盖原有的配置文件。

**Comment by AigioL** [comment]
确实是7z的包中包含了 AppData 文件夹与相关配置，导致解压覆盖了

**Comment by fuchanghao** [comment]
> 确实是7z的包中包含了 AppData 文件夹与相关配置，导致解压覆盖了

这个是打包的时候忘记忽略这些文件还是写更新说明的时候忘记提示了？

**Comment by AigioL** [comment]
> > 确实是7z的包中包含了 AppData 文件夹与相关配置，导致解压覆盖了
> 
> 这个是打包的时候忘记忽略这些文件还是写更新说明的时候忘记提示了？

应该是要忽略 AppData 与 Cache 目录的

**Comment by rmbadmin** [comment]
这个问题确实很严重，这里道个歉。
本来版本都是由CI自动化部署打包发布，不可能出现这种问题的，
但因为2.8.3发布前有疏忽导致了2.8.3 Windows安装版可能有配置文件出现异常无法打开的严重问题
所以临时修复计划发布了2.8.3.1，因为2.8.3的发布已经存在所以由 @AigioL  临时手动打包发布导致了这个严重问题，目前已经撤掉了所有有问题的包，并计划重新由CI发布 2.8.4 版本。

**Comment by fuchanghao** [comment]
> 这个问题确实很严重，这里道个歉。 本来版本都是由CI自动化部署打包发布，不可能出现这种问题的， 但因为2.8.3发布前有疏忽导致了2.8.3 Windows安装版可能有配置文件出现异常无法打开的严重问题 所以临时修复计划发布了2.8.3.1，因为2.8.3的发布已经存在所以由 @AigioL 临时手动打包发布导致了这个严重问题，目前已经撤掉了所有有问题的包，并计划重新由CI发布 2.8.4 版本。

了解了。
