### ISSUE TITLE
无法登录Twitch

### ISSUE THREAD

**Issue by Anivia-ad** [BeyondDimension/SteamTools#1912]
使用前已安装证书。网络是正常的，能够看Twitch直播，也勾选Twitch登录加速，但就是不能登录账户.点击登录后仍然显示这个界面。
![1](https://user-images.githubusercontent.com/70047326/184911397-f30193a0-91cb-4efa-a1a2-3ec0c13d3748.png)
。

**Comment by rmbadmin** [comment]
已经热更新修复
