### ISSUE TITLE
🐛[BUG] Trojan:Win32/Wacatac.B!ml 已从此设备中删除威胁或应用。

### ISSUE THREAD

**Issue by ddzzkunye** [BeyondDimension/SteamTools#1917]
### 🐛 描述(Description)

Trojan:Win32/Wacatac.B!ml
已从此设备中删除威胁或应用。

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):  Steam++_win_x64_v2.8.4.exe
- 系统版本号(OS Version):  Win10Edu  19044.1889  Windows Feature Experience Pack 120.2212.4180.0
- 是否为应用商店版本(Whether it is a Store version):  No

**Comment by Mossimos** [comment]
请问从哪里下载的呢

**Comment by AigioL** [comment]
NSIS 这个打包误报率还是挺高的
https://www.virustotal.com/gui/file/b0a3a6ef2156c007af0fa311ab1470524f0bf94f5e1d4420772320f13680dfd4?nocache=1

7z 包是没有这个问题的
https://www.virustotal.com/gui/file/e797cb455740de75eef5eea0433d7f37551e75a2061c62c3e7670333598c7281?nocache=1

**Comment by ddzzkunye** [comment]
Github上的链接 @Mossimos
