### ISSUE TITLE
🧐[Question] 看不到加速功能

### ISSUE THREAD

**Issue by JohnKeyes** [BeyondDimension/SteamTools#1918]
语言切换成简中之后还是看不到加速和脚本功能
![image](https://user-images.githubusercontent.com/68500572/185057300-18b7309f-e0e5-4303-80e2-97862c62ef38.png)
![image](https://user-images.githubusercontent.com/68500572/185057379-d7b1599b-f138-4e92-8160-631044978649.png)

**Comment by Mossimos** [comment]
切换语言后是否又重启 Steam++

**Comment by JohnKeyes** [comment]
重启好几遍了

**Comment by Mossimos** [comment]
确定是托盘退出的程序吗？  我在 3台电脑上测试了都是正常的, 切换托盘退出然后重启 Steam++ 就正常显示了

**Comment by JohnKeyes** [comment]
哦，还在托盘里，现在好了，但为什么之前没完全退出的时候每次打开它windows defender都要问我一遍

**Comment by Mossimos** [comment]
windows 要问你是因为 UAC 权限控制 Steam++ 是以管理员身份启动的所以会弹窗
关闭按钮并不是退出只是关闭窗口
