### ISSUE TITLE
🧐[Question] 证书安装成功没反应

### ISSUE THREAD

**Issue by MooerMax** [BeyondDimension/SteamTools#1941]
### 🧐 问题描述(Description)
按照提示把证书安装了 但是一直在这个界面。
按了确定按钮结果又弹出终端要求输入密码，一直循环，试了好多次了QwQ

- 程序版本(Program Version):2.8.4beta
- 系统版本号(OS Version): macOS Catalina 10.15.7

**Comment by MooerMax** [comment]
<img width="874" alt="截屏2022-08-24 下午2 40 04" src="https://user-images.githubusercontent.com/111956853/186348977-2784e2eb-ac04-49f8-aa94-c43fad436d38.png">

**Comment by MooerMax** [comment]
<img width="572" alt="截屏2022-08-24 下午2 39 57" src="https://user-images.githubusercontent.com/111956853/186349042-1795cd62-5215-4e53-8e7f-9dee259411a5.png">

**Comment by Mossimos** [comment]
能否打开钥匙串   登录选项   证书里面看看是否信任了SteamTools证书呢

**Comment by MooerMax** [comment]
是这个吗
![Uploading 截屏2022-08-24 下午5.18.15.png…]()

**Comment by MooerMax** [comment]
是这个吗
<img width="481" alt="截屏2022-08-24 下午5 19 31" src="https://user-images.githubusercontent.com/111956853/186381371-7767a144-d58a-4f02-97ba-f77720f5a434.png">

**Comment by Mossimos** [comment]
是这个 如果是已经信任了不应该会继续弹窗才对。
security verify-cert -c  "证书路径"
看看执行结果 证书路径是 /users/apple/library/steam++ 那一串

**Comment by MooerMax** [comment]
🧐
<img width="313" alt="截屏2022-08-25 上午9 53 18" src="https://user-images.githubusercontent.com/111956853/186556426-a5bc7f8c-4bc4-4e13-8526-a1e9eb48a412.png">

**Comment by Mossimos** [comment]
这个就是为信任这个证书的错误啊...
你是之前用过旧版本的把。 试试手动删除钥匙串里面的这个旧证书重新安装下试试。
如果好了的话我去按这条件看看是什么问题

**Comment by MooerMax** [comment]
还是不行诶QwQ

**Comment by MooerMax** [comment]
之前没有用过旧版本 最近才下载的

**Comment by Mossimos** [comment]
那我目前也无法复现这个问题。
你试试删除这个钥匙串中的证书 ， 然后重新打开AppData文件夹 删除里面的证书。然后再开Steam++试试呢。
还不行的话你发下日志  
程序内打开Logs文件夹压缩下发过来看看日志

**Comment by MooerMax** [comment]
<img width="645" alt="截屏2022-08-25 下午2 51 26" src="https://user-images.githubusercontent.com/111956853/186595315-cec95b26-22ac-438f-8322-d37f3eabd4a3.png">

**Comment by MooerMax** [comment]
还是不行QwQ
[Logs.zip](https://github.com/BeyondDimension/SteamTools/files/9422271/Logs.zip)

**Comment by MooerMax** [comment]
SteamTools.Certificate.pfx
这个好像一直导入不了钥匙串

**Comment by Mossimos** [comment]
你钥匙串中的证书是安装在这个登录下面的吗

![image](https://user-images.githubusercontent.com/26396340/186599392-01dad199-82b3-4b49-9309-d009d5e69683.png)

**Comment by MooerMax** [comment]
嗯对

**Comment by Mossimos** [comment]
输入密码确认后会有系统弹窗需要 允许信任证书
![image](https://user-images.githubusercontent.com/26396340/186599804-d62daa98-aa93-4878-9b04-2d057aebf4b0.png)
信任完后去程序点击确定 
![image](https://user-images.githubusercontent.com/26396340/186600016-1f7c343c-f273-4670-88e6-6006cc6eeaa2.png)
我这就加速成功了

**Comment by MooerMax** [comment]
嘶 我这里证书一直都是信任

**Comment by Mossimos** [comment]
不清楚是不是 macOS Catalina 10.15.7 有额外操作 我这也没有实机 无法复现。
估计只能远程帮你看才行

**Comment by MooerMax** [comment]
麻了 切系统代理成功了
<img width="759" alt="截屏2022-08-25 下午3 22 42" src="https://user-images.githubusercontent.com/111956853/186601840-eccc408e-f4aa-4dfb-a510-f854fc545463.png">

**Comment by MooerMax** [comment]
钥匙串里面给给证书更改了设置再改回来成功了额

**Comment by Mossimos** [comment]
。。。。那这问题就很迷惑了啊

**Comment by MooerMax** [comment]
挺玄学的就。。。
先close了 感谢解答♪(･ω･)ﾉ

**Comment by MooerMax** [comment]
挺玄学的就。。。
先close了 感谢解答♪(･ω･)ﾉ

**Comment by MooerMax** [comment]
.

**Comment by Mossimos** [comment]
行吧 , 这个问题我到时候找人去借台机器试试看
