### ISSUE TITLE
🧐[Question] macos要求在弹出窗口输入密码安装证书，但弹出的终端shell窗口无输入密码项

### ISSUE THREAD

**Issue by januar10513** [BeyondDimension/SteamTools#1953]
### 🧐 问题描述(Description)
各位大神电脑白痴求教～安装之后点选一键加速后要求“请在弹出的控制台窗口输入系统密码以安装信任证书。信任完成后点击确定按钮继续。”，请问需要输入何种指令才能让我输入密码然后安装证书呢？
已单独在钥匙串中添加证书认证但还是不行，先谢谢！

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by Mossimos** [comment]
弹出的窗口直接输入密码就行了

在 Password： 后面输入就好了 
输入密码 不显示字符是正常的
输入完直接回车就行了

**Comment by januar10513** [comment]
> 弹出的窗口直接输入密码就行了
> 
> 在 Password： 后面输入就好了 输入密码 不显示字符是正常的 输入完直接回车就行了

今天在办公室的windows系统上装畅通无阻，macos还是不行，都没有password，具体劳烦您看一眼我新补充的图，先谢谢！

**Comment by januar10513** [comment]
> 弹出的窗口直接输入密码就行了
> 
> 在 Password： 后面输入就好了 输入密码 不显示字符是正常的 输入完直接回车就行了

今天在办公室windows系统下载使用畅通无阻，macos没有输入password的地方，只显示：
Last login: Mon Aug 29 17:37:30 on ttys000
MacBook-Pro ~ % 
 这样，不知道是不是安装的时候哪里错，卸载重装也还是一样，占用您时间啦，谢谢！

**Comment by Mossimos** [comment]
这不是截图啊 弹出的窗口中 应该是带命令行的
#1941 
你可以参考这里的图

**Comment by AyanoZhou** [comment]
同样的问题，弹出的终端shell窗口没有命令行
我的解决办法：在钥匙串访问中找到**SteamTools Certificate**，右键**显示简介**，在信任里改成始终信任

**Comment by AyanoZhou** [comment]
同样的问题，弹出的终端shell窗口没有命令行（或者说它把终端打开了，但是不弹出窗口）

我的解决方法：在钥匙串访问中找到 SteamTools Certificate  ，右键点击 显示简介 ，在信任里选择 始终信任，
然后又参照弹出的https://steampp.net/unixhostaccess
在终端执行`sudo chmod +a 'user:此处请修改为您当前的用户名:allow write' /etc/hosts` 
加速成功

**Comment by januar10513** [comment]
> 这不是截图啊 弹出的窗口中 应该是带命令行的 #1941 你可以参考这里的图



> 同样的问题，弹出的终端shell窗口没有命令行（或者说它把终端打开了，但是不弹出窗口）
> 
> 我的解决方法：在钥匙串访问中找到 SteamTools Certificate ，右键点击 显示简介 ，在信任里选择 始终信任， 然后又参照弹出的https://steampp.net/unixhostaccess 在终端执行`sudo chmod +a 'user:此处请修改为您当前的用户名:allow write' /etc/hosts` 加速成功

按照这个方法输入代码之后输入密码，出现
“usage:	chmod [-fhv] [-R [-H | -L | -P]] [-a | +a | =a  [i][# [ n]]] mode|entry file ...
	chmod [-fhv] [-R [-H | -L | -P]] [-E | -C | -N | -i | -I] file ...” 后关闭窗口，还是不行，多谢解答，我再试试！

**Comment by januar10513** [comment]
> 这不是截图啊 弹出的窗口中 应该是带命令行的 #1941 你可以参考这里的图

和这个情况应该蛮像的，不过玄学失败，我明日再卸载干净重装试试！十分感谢
