### ISSUE TITLE
通过hosts加速github，在进行push命令的时候，会有SSL报错🐛[BUG] 

### ISSUE THREAD

**Issue by ghost** [BeyondDimension/SteamTools#1960]
### 🐛 描述(Description)

通过hosts加速github，在进行push命令的时候，会有SSL报错 
SSL certificate problem: unable to get local issuer certificate
前两天好像还没这个问题，具体我也不是很清楚。昨晚提交的过程中，就发生了这个问题。
DNS加速模式 好像没有作用，加速流量一直为零。

### 📷 复现步骤(Steps to Reproduce)

1. 选择hosts加速github
2. 然后在本地的项目中 通过git push 命令，就会发生ssl报错。
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.2 for Windows(x64)
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): yes

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/99951952/187389668-cc03afa8-21c1-43f6-8b93-8a292724c81c.png)

**Comment by rmbadmin** [comment]
你需要让git信任本地证书 参考 https://github.com/BeyondDimension/SteamTools/discussions/234#discussion-3362834

``git config --global http.sslBackend schannel``
