### ISSUE TITLE
👑[Enhancement] 安卓APP功能建议

### ISSUE THREAD

**Issue by Nighting0518** [BeyondDimension/SteamTools#1975]
### 🥰 需求描述(Description)
官方app有小组件功能 在桌面上就可以看到令牌输入 但是网络环境不好的时候容易卡死 而且绑定双账号的话还是要进到app界面里面选择 希望在app里可以添加2*2滑动或者2*4的小组件可以更方便的查看令牌信息

**Comment by AigioL** [comment]
与 #445 #1738 重复

**Comment by Nighting0518** [comment]
抱歉 只搜索了小组件关键词
