### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by BlameTwo** [BeyondDimension/SteamTools#1976]
![image](https://user-images.githubusercontent.com/65759143/188249473-65fea3bb-f5f5-44cb-ba44-fc06d9236d14.png)

内存泄漏？？

我加速了一下游戏就变成这样了捏，还有就是渲染的加速图表太占用GPU了，20%+。

目前版本是最新版。

**Comment by Janet-Baker** [comment]
复现：
工具箱在前台，启动网络加速，在图表界面，GPU在25%到50%之间波动（透明设为NONE也是一样的），内存占用量不断上涨。
工具箱在前台，离开图表界面，GPU**较少**占用，内存上涨停止。
关闭工具箱的窗口，GPU无占用。
