### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by zhilong-12138** [BeyondDimension/SteamTools#1977]
### 🐛 描述(Description)
当我启动Watt Toolkit之后，一款游戏无法启动COD16(战网平台)，直接闪退

### 📷 复现步骤(Steps to Reproduce)

1. 启动Watt Toolkit，加速steam
2. 启动战网
3. 启动COD16
4. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.8.2
- 系统版本号(OS Version): Windows Feature Experience Pack 120.2212.4180.0
- 是否为应用商店版本(Whether it is a Store version): no

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/46955133/188251061-acf0af1b-ab3b-4296-aa6f-a9f222faf1c3.png)

**Comment by Mossimos** [comment]
这部分在很早前发过公告的 要么升级要么  管理员权限运行CMD 输入 sc stop WinDivert1.4 停掉驱动或者重启电脑在进行游戏。
https://steampp.net/noticeInfo?id=a646433e-f36b-1410-8893-00e23e1d515d
