### ISSUE TITLE
🧐[Question] 现在的网页翻译助手为什么不能翻译steam了？

### ISSUE THREAD

**Issue by sxic** [BeyondDimension/SteamTools#1980]
### 🚑 其他信息(Other Information)
2.8.4版本

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by Mossimos** [comment]
需要更新脚本插件 在脚本市场有新适配的脚本,gm脚本也顺便更新下 更新到最新的 0.32

**Comment by Mossimos** [comment]
已经更换了百度翻译了 测试也正常了更新就能使用了
