### ISSUE TITLE
🐛[BUG] Mac系统下信任证书问题

### ISSUE THREAD

**Issue by teanxo** [BeyondDimension/SteamTools#1982]
版本号：v2.8.4
操作系统：MACOS Catalina 10.15.7
复现问题：在Mac系统下第一次打开使用加速时，会在终端弹出输入密码来信任证书操作，输入密码后点击确定仍会重复打开终端窗口
在钥匙串内已查看到SteamTools Certificate证书已被信任
Keychains/login.keychain-db文件也已被创建

**Comment by Mossimos** [comment]
请参考下这个 可能是 MACOS Catalina 10.15.7 需要单独手动操作 其他 11-12目前都是可以正常使用的

#1941

**Comment by teanxo** [comment]
我试着操作了一下  把密钥删除重新安装也不太好使，是我操作步骤不对吗

**Comment by Mossimos** [comment]
是手动在证书  改成不信任 然后再次信任
