### ISSUE TITLE
🧐[Question] 2.8.4如何使clash与steam++反代加速共存？

### ISSUE THREAD

**Issue by Alexius66** [BeyondDimension/SteamTools#1987]
### 🧐 问题描述(Description)
看之前的回答都是说开启应用的二级代理，但是2.8.4版本的应用似乎并无二级代理这一设置，该如何设置能使clash与程序的反代加速共存？

### 🚑 其他信息(Other Information)

- 程序版本(Program Version): 2.8.4
- 系统版本号(OS Version): Windows 11.22622.590
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by Dradows** [comment]
steam++我用的hosts代理，两个没冲突
