### ISSUE TITLE
🐛[BUG] Steam 启动参数无效

### ISSUE THREAD

**Issue by Mishasama** [BeyondDimension/SteamTools#1992]
### 🐛 描述(Description)

输入了启动参数后在++里通过保存共享库启动的 Steam 没有应用启动参数。

### 📷 复现步骤(Steps to Reproduce)

1. 在++里加入启动参数
2. 在++里调整家庭共享库顺序并保存
3. 在++弹出的重启提示里点击重启
4. 登入后发现没有载入启动参数

### 📄 日志信息(Log Information)

[nlog-all-2022-09-09.log](https://github.com/BeyondDimension/SteamTools/files/9528170/nlog-all-2022-09-09.log)
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.8.4
- 系统版本号(OS Version): Windows 10.19042.1645
- 是否为应用商店版本(Whether it is a Store version): Yes

**Comment by AigioL** [comment]
https://github.com/BeyondDimension/SteamTools/pull/1995 @rmbadmin

**Comment by AigioL** [comment]
预计于下一个版本中修复
