### ISSUE TITLE
🧐[Question] Archlinux证书导入后依旧提示“你的连接不是专用连接”

### ISSUE THREAD

**Issue by YouLanjie** [BeyondDimension/SteamTools#2007]
### 🧐 问题描述(Description)

我尝试以各种方法导入了"xxx.cer"文件后，虽然浏览器（edge）的“隐私->管理证书->颁发机构”显示已经安装了证书，但是在打开加速后仍旧提示“你的连接不是专用连接”。

### 🚑 其他信息(Other Information)

错误截图：

![image](https://user-images.githubusercontent.com/66255345/189465118-bc442ee0-1a1c-4dd8-99bd-1bd08ba1f324.png)

- 运行使用的用户: root
- 桌面环境: i3-wm

- 程序版本(Program Version): v2.8.4 b
- 系统版本号(OS Version): Arch Linux（软件均为最新）
- 是否为应用商店版本(Whether it is a Store version): AUR的watt-toolkit-bin

**Comment by Mossimos** [comment]
请提供下 管理证书->颁发机构 里面SteamTools 证书的详细截图

**Comment by YouLanjie** [comment]
截图：
![image](https://user-images.githubusercontent.com/66255345/189489754-91e96ac3-1c71-4ba8-91e4-21f2c72c5aed.png)

**Comment by immccn123** [comment]
同问。重试安装证书依然无效。

不过裸连上GitHub之后利用证书缓存可以做到避开HSTS（并显示安全连接）。（亲测Edge浏览器有效）

系统信息：
- OS: Manjaro Linux (Linux 5.15.60)（软件均为最新）
- DE: Plasma 5.24.6
- 图形平台: X11
- 软件版本: watt-toolkit-bin 2.8.4-4 （最新AUR版本）
- 非root用户

~~而且gcr-viewer有个一年多的bug 害得我搞了半天~~

**Comment by Mossimos** [comment]
确定在安装时是否勾选了信任，我在机器上测试是可以的啊
![image](https://user-images.githubusercontent.com/26396340/189552754-e80ed41c-b7e4-43a8-953a-2b0befe403da.png)

**Comment by YouLanjie** [comment]
我在安装时确实是勾选了信任，但就是会报错
![image](https://user-images.githubusercontent.com/66255345/189574382-fe945dc7-b57f-4df2-9e15-7cb1c2664e8f.png)

**Comment by Mossimos** [comment]
Linux  Edge Chrome Firefox 我都试过了没问题  只能要么你开远程我看看到底啥问题了
![image](https://user-images.githubusercontent.com/26396340/189578873-c7c40502-1a6e-42ae-a4cf-f8330ca2191e.png)

**Comment by yingziyu-llt** [comment]
请在firefox浏览器中再次安装证书，浏览器证书不走系统证书

**Comment by ngdngdc** [comment]
这样可能会有用#1829

**Comment by Mossimos** [comment]
如还有问题请再打开。
