### ISSUE TITLE
👑[Enhancement] 关于加速vercel.app的功能

### ISSUE THREAD

**Issue by Yang-qwq** [BeyondDimension/SteamTools#2014]
### 🥰 需求描述(Description)

如题，可否添加一个加速vercel.app的功能？

### 🧐 解决方案(Solution)

我查询到了没有污染的域名ip地址（第一行），如下：
|Domain|IP|Country|ISP|
|---|---|---|---|
|vercel.app|76.76.21.164|USA|S16509 Amazon.com, Inc.|
|vercel.app（已污染）|159.69.71.100|Unknown|Unknown|

**Comment by Yang-qwq** [comment]
问题目前已解决，感谢修复
测试内容：https://github-readme-stats.vercel.app/api?username=Yang-qwq&locale=cn&show_icons=true&theme=vue&count_private=true

**Comment by elarbor** [comment]
> 问题目前已解决，感谢修复 测试内容：https://github-readme-stats.vercel.app/api?username=Yang-qwq&locale=cn&show_icons=true&theme=vue&count_private=true

![image](https://github.com/user-attachments/assets/cd1d68d0-4f70-423c-8cdf-9217d66b4441)
