### ISSUE TITLE
🧐[Question] 系统语言不是中文不能使用加速功能吗？

### ISSUE THREAD

**Issue by maxshiro** [BeyondDimension/SteamTools#2048]
### 🧐 问题描述(Description)
Windows下高分屏显示中文字体模糊，把系统语言改成英文会舒适些。
然后打开toolkit就发现没有网络加速的选项。
所以程序是根据系统语言决定是否允许使用加速功能吗？
如果是的话个人认为改成读取系统时区或许会更合理些（？）

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):v2.8.4
- 系统版本号(OS Version): Windows 11.22622.601
- 是否为应用商店版本(Whether it is a Store version): 是

**Comment by rmbadmin** [comment]
公告里已经说明过了，非简中隐藏加速和脚本功能，关于中文字体模糊你可以尝试再程序UI设置中手动更换其它字体试试，之所以靠语言设置区分而不是读取系统时区是因为， 加速功能里有大量未翻译文本，这会导致切换成其它语言会让程序使用体验变得比较割裂，但目前因为服务端并未支持多语言，所以暂时只能这样了。

**Comment by maxshiro** [comment]
> 公告里已经说明过了，非简中隐藏加速和脚本功能，关于中文字体模糊你可以尝试再程序UI设置中手动更换其它字体试试，之所以靠语言设置区分而不是读取系统时区是因为， 加速功能里有大量未翻译文本，这会导致切换成其它语言会让程序使用体验变得比较割裂，但目前因为服务端并未支持多语言，所以暂时只能这样了。

抱歉，没有注意到公告有写明。我会尝试解决系统字体的问题。
