### ISSUE TITLE
🧐[Question] steam++原理是什么

### ISSUE THREAD

**Issue by eyihsil** [BeyondDimension/SteamTools#2057]
### 🧐 问题描述(Description)
steam++原理是什么？我用的校园网会不会被检测异常

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by David-Xian66** [comment]
自己看代码（

**Comment by eyihsil** [comment]
> 自己看代码（

看不懂，我不是程序员

**Comment by rmbadmin** [comment]
这种问题，你应该学会搜索再提问，已经再issues里有过解答了
#1011 #1416
