### ISSUE TITLE
🧐[Question] macOS12.6无法打开Steam++（新下载）

### ISSUE THREAD

**Issue by cky008** [BeyondDimension/SteamTools#2062]
### 🧐 问题描述(Description)

无法运行，提示“因为Apple无法检查其是否包含恶意软件” “此软件需要更新，请联系开发者了解更多信息”。设备是14寸macbook pro丐版，在issue里搜了下mac好像没看到相关问题..不知是bug还是我没搞对呢...

### 🚑 其他信息(Other Information)

<img width="372" alt="image" src="https://user-images.githubusercontent.com/56156916/193416685-37259685-3d13-4bd8-832b-736d15007864.png">

- 程序版本(Program Version):2.8.4
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): No github release是下载的版本

**Comment by David-Xian66** [comment]
。。。。。。。

**Comment by David-Xian66** [comment]
（我很好奇你用了多长时间的Mac

**Comment by David-Xian66** [comment]
重新打开steam++
然后
系统偏好设置-> 安全性与隐私-> 通用 下面有个仍然打开 点下（可能需要输入锁屏密码

**Comment by David-Xian66** [comment]
（然后记得回来关闭这个issue

**Comment by cky008** [comment]
好的 可以了 谢谢 才开始用（

**Comment by David-Xian66** [comment]
> 好的 可以了 谢谢 才开始用（

没事
