### ISSUE TITLE
[BUG]macos10.15无限循环安装证书

### ISSUE THREAD

**Issue by sdfwss** [BeyondDimension/SteamTools#2063]
macos10.15在开启加速是无限循环安装证书步骤

**Comment by Mossimos** [comment]
参考该问题尝试下 #1941

**Comment by Mossimos** [comment]
如果 终端没有自动弹出也可以手动打开终端试试 ，今天遇到个手动打开终端 命令直接显示在终端了，但是终端没有自动打开。

**Comment by sdfwss** [comment]
终端可以正常使用，但输入完命令后会弹出一个一样的终端

**Comment by Mossimos** [comment]
macos10.15 请手动在”钥匙串访问“中手动取消信任再信任证书
