### ISSUE TITLE
🐛[BUG] 系统代理模式导致火狐浏览器页面乱码

### ISSUE THREAD

**Issue by wold9168** [BeyondDimension/SteamTools#2072]
### 🐛 描述(Description)

注意到，当开启Steam++的网络加速时，若使用的加速模式为“系统代理模式”，则火狐浏览器（国际版）中所有的未被代理的页面（即便为局域网网关的登录页面）变为单行乱码，无法正常加载，而被代理的页面（如：github.com）不受影响。
打开火狐浏览器的排障模式不影响此BUG的复现。
通过控制变量法得知，Chromium不受此BUG影响。

### 📷 复现步骤(Steps to Reproduce)

1. 打开Steam++（Watt Toolkit）
2. 开启网络加速
3. 打开火狐浏览器，浏览未被代理（加速）的页面

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.4 for linux，安装自AUR的`watt-toolkit-bin`。
- 系统版本号(OS Version):Arch Linux x86_64(Kernel Version:5.19.12-arch1-1) 
- 是否为应用商店版本(Whether it is a Store version):No 

火狐浏览器的版本为105.0.1（64位），国际版。
我使用Arch Linux系统，桌面环境是KDE Plasma。
在我的电脑上运行`neofetch`的输出如下：
```
                   -`                    shinonome@shinonome-82l5 
                  .o+`                   ------------------------ 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: 82L5 Lenovo XiaoXinPro 16ACH 2021 
               `+oooooo:                 Kernel: 5.19.12-arch1-1 
               -+oooooo+:                Uptime: 1 hour, 20 mins 
             `/:-:++oooo+:               Packages: 1865 (pacman) 
            `/++++/+++++++:              Shell: zsh 5.9 
           `/++++++++++++++:             Resolution: 2560x1600 
          `/+++ooooooooooooo/`           DE: Plasma 5.25.5 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         WM Theme: Breeze 微风 
       -osssssso.      :ssssssso.        Theme: [Plasma], Breeze [GTK2/3] 
      :osssssss/        osssso+++.       Icons: [Plasma], breeze [GTK2/3] 
     /ossssssss/        +ssssooo/-       Terminal: yakuake 
   `/ossssso+/:-        -:/+osssso+-     CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 3.200GHz 
  `+sso+:-`                 `.-/+oso:    GPU: AMD ATI 05:00.0 Cezanne 
 `++:.                           `-/+/   Memory: 7860MiB / 13850MiB 
 .`                                 `/
```
### 🖼 截图(Screenshots)
![深度截图_选择区域_20221003175111](https://user-images.githubusercontent.com/48375098/193549732-31ff7c96-f066-48e9-80d0-c7272965e705.png)

**Comment by Enaium** [comment]
fedora是除GitHub页面外就乱码，估计是除加速页面外就乱码，Linux  Mint是所有页面都乱码

**Comment by wold9168** [comment]
> fedora是除GitHub页面外就乱码，估计是除加速页面外就乱码，Linux Mint是所有页面都乱码

有尝试过Chromium吗？我这边是浏览器用Chromium不会乱码，可能只有火狐会出这个bug。
我回头测测Thunderbird会不会出这个bug。

**Comment by Enaium** [comment]
> > fedora是除GitHub页面外就乱码，估计是除加速页面外就乱码，Linux Mint是所有页面都乱码
> 
> 有尝试过Chromium吗？我这边是浏览器用Chromium不会乱码，可能只有火狐会出这个bug。
> 我回头测测Thunderbird会不会出这个bug。

我用chromium和edge测试了，也这样

**Comment by lazyfreeman** [comment]
Firefox (Windows, Fedora) 和 Edge (Windows 10) 均出现此问题.

**Comment by rmbadmin** [comment]
#2174  已提交相关修复

**Comment by shuifa** [comment]
> #2174 已提交相关修复

要等下一个版本才能不出现这个bug了吗？

**Comment by rmbadmin** [comment]
> > #2174 已提交相关修复
> 
> 要等下一个版本才能不出现这个bug了吗？

是的，你也可以自行去github actions中下载最新提交的CI自动化部署版本先用着

**Comment by shuifa** [comment]
> > > #2174 已提交相关修复
> > 
> > 
> > 要等下一个版本才能不出现这个bug了吗？
> 
> 是的，你也可以自行去github actions中下载最新提交的CI自动化部署版本先用着

steam内图片没有展示，以及我在提交github issue的时候上传图片一直提示failed。换了个其他的github加速软件才成功。。这个也修复了吗

**Comment by rmbadmin** [comment]
> > > > #2174 已提交相关修复
> > > 
> > > 
> > > 要等下一个版本才能不出现这个bug了吗？
> > 
> > 
> > 是的，你也可以自行去github actions中下载最新提交的CI自动化部署版本先用着
> 
> steam内图片没有展示，以及我在提交github issue的时候上传图片一直提示failed。换了个其他的github加速软件才成功。。这个也修复了吗

我这边测试没有此问题
