### ISSUE TITLE
🧐[Question] 启动加速后内存占用很高

### ISSUE THREAD

**Issue by batu1579** [BeyondDimension/SteamTools#2091]
### 🧐 问题描述(Description)

启动加速以后内存占用会变得很高，这正常嘛？

一般在 1.7GB 左右，有时候甚至能达到 3GB ，VSCode 的占用都比不上他。导致我的笔记本经常什么工作都没有的时候也像起飞了一样QAQ

我开了历史最低价格查询的脚本，不知道有没有影响。

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/51915056/194618331-0a9f4bfd-8ec4-4dbd-bdc1-dfe3ed6131ed.png)

- 程序版本(Program Version): 2.8.2
- 系统版本号(OS Version): Windows 11 22000.978
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by rmbadmin** [comment]
更新到2.8.4在观察一段时间

**Comment by batu1579** [comment]
好的这就更新！

**Comment by batu1579** [comment]
我试了几天，现在没有问题了。

谢谢大大！！！Orz
