### ISSUE TITLE
🧐[Question] Steam更新新版客户端后Steam++不起作用了

### ISSUE THREAD

**Issue by PVWXX** [BeyondDimension/SteamTools#2093]
Steam更新新版客户端后Steam++不能用了
### 🧐 问题描述(Description)
不仅仅是客户端进不了，Steam官网也打不开了，另一台电脑一开始能打开Steam官网，用了Steam++之后也打不开了，并且停止加速或者退出之后仍然不行

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):2.8.4
- 系统版本号(OS Version): Windows 11 专业版 64-bit (10.0, Build 22621) / Windows 10 专业版 64-bit (10.0, Build 19044)
- 是否为应用商店版本(Whether it is a Store version): 否 / 是

**Comment by rmbadmin** [comment]
提供程序错误日志

**Comment by PVWXX** [comment]
> 提供程序错误日志

[nlog-all-2022-10-09.log](https://github.com/BeyondDimension/SteamTools/files/9741750/nlog-all-2022-10-09.log)
这个吗

**Comment by rmbadmin** [comment]
更换下代理设置得dns即可

**Comment by PVWXX** [comment]
> 更换下代理设置得dns即可
好了，多谢大佬
