### ISSUE TITLE
🧐[Question] 脚本无法下载

### ISSUE THREAD

**Issue by 894wlp** [BeyondDimension/SteamTools#2100]
![eefb4b15ebe7125a](https://user-images.githubusercontent.com/115552796/195088382-7e1ab247-92be-4373-8268-1b15ce202efd.png)

系统:win10
[Uploading nlog-all-2022-10-11.log…]()

**Comment by Mossimos** [comment]
麻烦请重新上传下日志 你这个日志还没上传正确

**Comment by 894wlp** [comment]
[nlog-all-2022-10-13.log](https://github.com/BeyondDimension/SteamTools/files/9770072/nlog-all-2022-10-13.log)

**Comment by Mossimos** [comment]
https://steampp.net/uploads/js/00000000000000000000000000000001/0.32.js
看情况是无法链接我们官网下载JS 
以及日志中有 223.5.5.5 无法解析域名错误。

**Comment by 894wlp** [comment]
可能是校园网的问题，切换手机热点就可以了。请问有方法解决吗？

**Comment by 894wlp** [comment]
改dns会导致无法连接网络

**Comment by Mossimos** [comment]
网络问题无法连接 Github Pages 。现在用了国内 CDN
