### ISSUE TITLE
👑[Enhancement] 希望加入谷歌浏览器网页翻译加速功能

### ISSUE THREAD

**Issue by CrazyZhang666** [BeyondDimension/SteamTools#2115]
### 🥰 需求描述(Description)

由于谷歌翻译前段时间退出中国，导致谷歌浏览器网页翻译功能无法使用，希望可以加入一个谷歌浏览器网页翻译加速功能

### 🧐 解决方案(Solution)

目前是使用修改host方式在使用网页翻译功能
203.208.40.66 translate.googleapis.com

其实就是这个api无法访问了，translate.googleapis.com，只需要加速这个即可
> 上面的ip地址是百度获取的，不一定完全有效

**Comment by ghost** [comment]
nslookup  translate.googleapis.com 得出的ip地址再写进hosts就可以了
