### ISSUE TITLE
🐛[BUG] Linux版Watt Toolkit无论使用系统代理还是hosts代理都无法加速Steam

### ISSUE THREAD

**Issue by Jiedi847** [BeyondDimension/SteamTools#2123]
### 🐛 描述(Description)
Linux版Watt Toolkit无论使用hosts代理还是系统代理都无法加速Steam，Steam会提示CONNECTION PROBLEM。浏览器页面使用hosts加速正常，使用系统代理会排版异常。

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):Watt Toolkit x64 v.2.8.4 β for linux
- 系统版本号(OS Version): Ubuntu 20.04 LTS
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by Mossimos** [comment]
用的是 Chrome 内核的浏览器吗？ 如果不是尝试下载 Chrome 浏览器导入下证书 Steam 应该就好了

**Comment by Jiedi847** [comment]
如何安装证书？在管理证书界面导入Steam++的pfx证书提示证书不可信
________________________________
发件人: Mossimo ***@***.***>
发送时间: 2022年10月15日 15:08
收件人: BeyondDimension/SteamTools ***@***.***>
抄送: Jiedi847 ***@***.***>; Author ***@***.***>
主题: Re: [BeyondDimension/SteamTools] 🐛[BUG] Linux版Watt Toolkit无论使用系统代理还是hosts代理都无法加速Steam (Issue #2123)


用的是 Chrome 内核的浏览器吗？ 如果不是尝试下载 Chrome 浏览器导入下证书 Steam 应该就好了

**Comment by Mossimos** [comment]
Linux 下导入的是 Cer 格式的证书  pfx是 windows 使用的证书

**Comment by Jiedi847** [comment]
用的就是chrome，导入证书那里提示不可信，红色的，导入的fpx格式的证书

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月15日 15:08
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [BeyondDimension/SteamTools] 🐛[BUG] Linux版Watt Toolkit无论使用系统代理还是hosts代理都无法加速Steam (Issue #2123)


用的是 Chrome 内核的浏览器吗？ 如果不是尝试下载 Chrome 浏览器导入下证书 Steam 应该就好了

**Comment by Jiedi847** [comment]
> Linux 下导入的是 Cer 格式的证书 pfx是 windows 使用的证书

谢谢，问题已经解决了，Chrome没法把Cer导入进Chromium内核证书列表里，用openssl命令把cer证书转换成crt证书就能导入了，Steam能正常工作了，浏览器也不会提示证书错误。
