### ISSUE TITLE
👑[Enhancement] 功能需求：二维码登录

### ISSUE THREAD

**Issue by kurisucat** [BeyondDimension/SteamTools#2125]
### 🥰 需求描述(Description)

支持 Steam 手机新客户端的二维码登录。

### 🧐 解决方案(Solution)

工具箱电脑端可以整那种 Bandicam 那种的录屏框框来截取二维码。

工具箱手机端直接扫码。

### 🚑 其他信息(Other Information)

无。

**Comment by rmbadmin** [comment]
这是计划内的功能，后续会支持
