### ISSUE TITLE
🧐[Question] steamdeck的linux系统加速失败

### ISSUE THREAD

**Issue by Ladjic** [BeyondDimension/SteamTools#2136]
我使用的是steamdeck的linux系统，之前也看了B站上的教程

使用host模式有流量，但会出现证书问题，尝试了
sudo cp /home/deck/.local/share/Steam++/SteamTools.Certificate.cer /etc/ca-certificates/trust-source/anchors
sudo trust extract-compat
不过没用，还是显示证书问题。

换系统代理模式就完全没反应了
请问有什么解决方法吗。

**Comment by rmbadmin** [comment]
linux的 steam 浏览器内置证书需要在 chrome 设置中添加下证书信任 之后会对所有 chromium 系浏览器都生效

**Comment by Ladjic** [comment]
> linux的 steam 浏览器内置证书需要在 chrome 设置中添加下证书信任 之后会对所有 chromium 系浏览器都生效

谢谢，我一开始用的是火狐，换chrome没有导入就能用了
另外火狐的话要专门导入一下证书，导入完了也能用，谢谢回答

**Comment by ngdngdc** [comment]
提一点：在Arch系发行版中若不使用chrome则可能需要导入到系统根证书才能正常加速steam(native)runtime #1829
这点我在五分钟之前于endeavouros中测试通过（未测试edge等chromium）.

**Comment by LRW-Adolph** [comment]
> 我使用的是steamdeck的linux系统，之前也看了B站上的教程
> 
> 使用host模式有流量，但会出现证书问题，尝试了 sudo cp /home/deck/.local/share/Steam++/SteamTools.Certificate.cer /etc/ca-certificates/trust-source/anchors sudo trust extract-compat 不过没用，还是显示证书问题。
> 
> 换系统代理模式就完全没反应了 请问有什么解决方法吗。

[把证书复制到了/etc/ca-certificates/trust-source/谷歌浏览器提示Certificate Import Error The Private Key for this Client Cricate is missing or invald不让导

**Comment by huhuime** [comment]
用certutil导入证书就行
