### ISSUE TITLE
🧐[Question] 如何使steam++与V2rayn系统代理共存？

### ISSUE THREAD

**Issue by HRxiaohu** [BeyondDimension/SteamTools#2138]
### 🧐 问题描述(Description)

如何使steam++与V2rayn系统代理共存？应当选择哪种模式？
### 🚑 其他信息(Other Information)

- 程序版本(Program Version): 2.8.4
- 系统版本号(OS Version): Windows 11 22H222623.746 
- 是否为应用商店版本(Whether it is a Store version):  yes

**Comment by sceic** [comment]
你在v2里面把steam，github，epic之类的域名和ip跳过一下呗

**Comment by xinghui233** [comment]
可是clash这种自带DNS的怎么去和steam++同时使用

**Comment by TaoRone** [comment]
同问这个问题
