### ISSUE TITLE
使用工具加速discord卡在检查更新后的启动界面🧐[Question] 

### ISSUE THREAD

**Issue by 1024TzKi** [BeyondDimension/SteamTools#2146]
### 🧐 问题描述(Description)
大约今天早上开始出现使用加速工具pass检查更新界面后卡在loading界面

### 🚑 其他信息(Other Information)

![捕获](https://user-images.githubusercontent.com/45119955/197727717-0283aebb-e36e-4a29-87f2-cc1cbb6fa99d.PNG)

- 程序版本(Program Version): 2.8.4
- 系统版本号(OS Version):  windows10 22H2 19045.2130
- 是否为应用商店版本(Whether it is a Store version):  是

**Comment by veifun** [comment]
+1同样的问题，求急需解决QAQ

**Comment by Tian9511** [comment]
+1同样的问题，求急需解决QAQ

**Comment by mxancl** [comment]
+1同样的问题，求急需解决QAQ

**Comment by wcy6457** [comment]
同问题，急需解决！

**Comment by Keith-Haruki** [comment]
我也有这个问题，是从官网提供的蓝奏云下载的。
Discord更新可以顺利进行，但是之后会卡在加载界面。
可以用浏览器正常打开Discord官网，但是尝试使用网页版仍然会卡在加载界面。

    程序版本(Program Version): 2.8.4
    系统版本号(OS Version): windows10 21H1 19043.2130
    是否为应用商店版本(Whether it is a Store version): 否
![截图](https://user-images.githubusercontent.com/30818183/197780736-ce89d398-7b2c-43f2-a5b1-cac27b906913.jpg)

**Comment by giegie12** [comment]
+1同样的问题，求急需解决QAQ

**Comment by giegie12** [comment]
> 我也有这个问题，是从官网提供的蓝奏云下载的。
> Discord更新可以顺利进行，但是之后会卡在加载界面。
> 可以用浏览器正常打开Discord官网，但是尝试使用网页版仍然会卡在加载界面。
> 
>     程序版本(Program Version): 2.8.4
>     系统版本号(OS Version): windows10 21H1 19043.2130
>     是否为应用商店版本(Whether it is a Store version): 否
> ![截图](https://user-images.githubusercontent.com/30818183/197780736-ce89d398-7b2c-43f2-a5b1-cac27b906913.jpg)
> 

我的加载速度极慢，情况和上面的兄弟一样

**Comment by Keith-Haruki** [comment]
更新：试了试羽翼城（dogfight360）的steamcommunity_302工具，可以正常使用Discord。可以暂时逃难过去，等待Watt Toolkit更新
![截图](https://user-images.githubusercontent.com/30818183/197926034-2f531697-b81c-4d22-8942-08d021cfa382.jpg)

**Comment by wcy6457** [comment]
> 

emmm ,你这样不太好吧。。。在这里宣传别的软件hhh，至少在我熟悉的minecraft的开源社区是很忌讳的。。。这里不了解了就

**Comment by wcy6457** [comment]
> 更新：试了试羽翼城（dogfight360）的steamcommunity_302工具，可以正常使用Discord。可以暂时逃难过去，等待Watt Toolkit更新 ![截图](https://user-images.githubusercontent.com/30818183/197926034-2f531697-b81c-4d22-8942-08d021cfa382.jpg)


emmm ,你这样不太好吧。。。在这里宣传别的软件hhh，至少在我熟悉的minecraft的开源社区是很忌讳的。。。这里不了解了就

**Comment by Keith-Haruki** [comment]
> > 
> 
> emmm ,你这样不太好吧。。。在这里宣传别的软件hhh，至少在我熟悉的minecraft的开源社区是很忌讳的。。。这里不了解了就

非常抱歉，只是想给楼里急用的人一个临时解决方案，就没有多想，是我做的不对。
Watt Toolkit是非常好用的工具，也是我大多数时候的第一选择，绝无借机捧踩的意思。
我会立刻删除这涉及其他类似软件的回帖，在这里就我的不适宜行为，再次向Watt Toolkit团队和其他相关人士道歉。
~~至于已经被引用的我所发出的不适宜内容，希望您能够协助消除，谢谢。~~
感谢您指出我的错误并协助我消除影响。

**Comment by veifun** [comment]
> > > 
> > 
> > 
> > emmm ,你这样不太好吧。。。在这里宣传别的软件hhh，至少在我熟悉的minecraft的开源社区是很忌讳的。。。这里不了解了就
> 
> 非常抱歉，只是想给楼里急用的人一个临时解决方案，就没有多想，是我做的不对。 Watt Toolkit是非常好用的工具，也是我大多数时候的第一选择，绝无借机捧踩的意思。 我会立刻删除这涉及其他类似软件的回帖，在这里就我的不适宜行为，再次向Watt Toolkit团队和其他相关人士道歉。 至于已经被引用的我所发出的不适宜内容，希望您能够协助消除，谢谢。

大佬可以加我QQ1071287603吗，我也用了steamcommunity上discord，但我上不去。希望得到帮助和指导QAQ

**Comment by veifun** [comment]
> > > 
> > 
> > 
> > emmm ,你这样不太好吧。。。在这里宣传别的软件hhh，至少在我熟悉的minecraft的开源社区是很忌讳的。。。这里不了解了就
> 
> 非常抱歉，只是想给楼里急用的人一个临时解决方案，就没有多想，是我做的不对。 Watt Toolkit是非常好用的工具，也是我大多数时候的第一选择，绝无借机捧踩的意思。 我会立刻删除这涉及其他类似软件的回帖，在这里就我的不适宜行为，再次向Watt Toolkit团队和其他相关人士道歉。 至于已经被引用的我所发出的不适宜内容，希望您能够协助消除，谢谢。



> > > 
> > 
> > 
> > emmm ,你这样不太好吧。。。在这里宣传别的软件hhh，至少在我熟悉的minecraft的开源社区是很忌讳的。。。这里不了解了就
> 
> 非常抱歉，只是想给楼里急用的人一个临时解决方案，就没有多想，是我做的不对。 Watt Toolkit是非常好用的工具，也是我大多数时候的第一选择，绝无借机捧踩的意思。 我会立刻删除这涉及其他类似软件的回帖，在这里就我的不适宜行为，再次向Watt Toolkit团队和其他相关人士道歉。 至于已经被引用的我所发出的不适宜内容，希望您能够协助消除，谢谢。

大佬可以加我QQ1071287603吗，我还是上不去。希望能得到临时解决的帮助和指导QAQ

**Comment by veifun** [comment]
> > > 
> > 
> > 
> > emmm ,你这样不太好吧。。。在这里宣传别的软件hhh，至少在我熟悉的minecraft的开源社区是很忌讳的。。。这里不了解了就
> 
> 非常抱歉，只是想给楼里急用的人一个临时解决方案，就没有多想，是我做的不对。 Watt Toolkit是非常好用的工具，也是我大多数时候的第一选择，绝无借机捧踩的意思。 我会立刻删除这涉及其他类似软件的回帖，在这里就我的不适宜行为，再次向Watt Toolkit团队和其他相关人士道歉。 至于已经被引用的我所发出的不适宜内容，希望您能够协助消除，谢谢。

大佬可以加我QQ1071287603吗，我还是上不去。希望能得到临时解决的帮助和指导QAQ

**Comment by rmbadmin** [comment]
已经修复，等待缓存刷新后获取到新的Discord加速项勾选加速即可

**Comment by giegie12** [comment]
大佬，进是能进了，但特别卡，还会把dc卡掉线。@rmbadmin

**Comment by giegie12** [comment]
而且是一直卡@rmbadmin

**Comment by wcy6457** [comment]
> 大佬，进是能进了，但特别卡，还会把dc卡掉线。@rmbadmin

我这里一切正常的。。。对了，discord加速里新增了一个选项，你看下是不是没有勾的原因？（瞎猜ing）

**Comment by wcy6457** [comment]
> 大佬，进是能进了，但特别卡，还会把dc卡掉线。@rmbadmin

是discord加速里多了个选项

**Comment by giegie12** [comment]
@wcy6457 大佬，全勾了

**Comment by wcy6457** [comment]
> @wcy6457 大佬，全勾了

这就不知道了，试试换换代理dns（加速模式的右边的代理设置里面）还有加速模式？

**Comment by iMoeAriaCG** [comment]
Discord版本是不是PTB或者Canary，要是的话，建议换Stable版，至少我这里换Stable版就没有这个问题了

**Comment by giegie12** [comment]
什么什么版我不懂，大佬能细说吗？@ArtistMatsuri

**Comment by iMoeAriaCG** [comment]
从微软商店下的Discord然后开Watt Toolkit就没这个问题

**Comment by giegie12** [comment]
谢谢大佬，早点休息@ArtistMatsuri
