### ISSUE TITLE
👑[Enhancement] 希望可以注销非必要登录方式关联的账户，比如QQ登录，方便重新绑定登录方式。

### ISSUE THREAD

**Issue by toopen-top** [BeyondDimension/SteamTools#2183]
### 🥰 需求描述(Description)

用QQ登录的时候忘记绑定手机号了，后来又用手机号登录，再想绑定我的QQ号就提示账户已存在之类的信息。

### 🧐 解决方案(Solution)

希望可以注销不必要登录方式关联的账号，方便该登录方式再次绑定到主账号上。

**Comment by rmbadmin** [comment]
软件关于内支持自己注销账号
