### ISSUE TITLE
🐛[BUG] 脚本Steam economy enhancer 无法正常使用

### ISSUE THREAD

**Issue by nyxgy18** [BeyondDimension/SteamTools#2184]
### 🐛 描述(Description)

在之前这个脚本可以自动出售卡片，并且在市场处显示价格是否合理，但是现在它完全无效了，刷新这个脚本会导致卡顿甚至导致steam++闪退，并且这个问题时好时坏，已经尝试重装脚本，重启steam商店和重装steam++均不能解决问题

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): 
- 版本：x64 v2.8.4 for windows，直接在github上下载的

**Comment by tsuiihan** [comment]
[我也遇到了这个问题，社区商店内当前价格无法读取，更换加速器加速后可以[](url)](![1](https://user-images.githubusercontent.com/85303015/198821029-4c053f61-47ed-4fc5-969d-0381627c87ea.jpg))

**Comment by Mossimos** [comment]
目前是 Steam 库存接口加上了 请求频率限制 SEE 插件频率太快被 限制请求了.
只能等待新方法，或者 Steam 放宽限制了.
改成排队请求的话太慢了

**Comment by XCXXCXXCX11** [comment]
> 现在是库存接口加了 请求频率限制 看到频率太快被限制 请求 了

什么时候能修复呀

**Comment by XCXXCXXCX11** [comment]
> ### 🐛描述（描述）
> 在此之前这个脚本可以在自动售票上打折，并且在该处显示的价格是否合理，但现在它完全无效了，市场尝试这个脚本会导致触发甚至导致团队++闪退，并且这个问题时好时，已经重装脚本，重启steam商店和重装steam++均不能解决问题
> 
> ### 📷复现步骤(Steps to Reproduce)
> 
> ### 📄日志信息（日志信息）
> ### 🚑基本信息(基本信息)
> * 程序版本（程序版本）：
> * 系统版本号（OS版本）：
> * 是否为应用商店版本（是否为Store版本）：
> * 版本：x64 v2.8.4 for windows，直接在github上下载的
> 
> ### 🖼截图（截图）

什么时候能修复呀

**Comment by Mossimos** [comment]
更新 see v6.8.6
