### ISSUE TITLE
🧐[Question] steam服务加速后没有效果

### ISSUE THREAD

**Issue by LeeZ1Q** [BeyondDimension/SteamTools#2185]
### 🧐 steam服务加速后没有效果

尝试过换代理DNS地址\重装证书\代理模式均没有效果

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/64735802/198813025-a2592867-3d93-4903-b06b-d82a6a84fad8.png)
log如下
[internal-nlog.txt](https://github.com/BeyondDimension/SteamTools/files/9892949/internal-nlog.txt)
[nlog-all-2022-10-29.log](https://github.com/BeyondDimension/SteamTools/files/9892950/nlog-all-2022-10-29.log)
- 程序版本(Program Version):2.8.4
- 系统版本号(OS Version): Win10](url)
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by CDmking** [comment]
看日志你这是用了IPv6地址吧，试着把软件代理设置的DNS改为SystemDefault (系统默认) 试试？

**Comment by CDmking** [comment]
与此设备同一网络的其他设备是否可以正常联网，若可以，则是设备本身的设置问题（如：Windows 10 中，是否在“网络设置”中启用“手动代理设置”等）；若不可以，请排查路由器、网关等设备是否正常运行。

**Comment by LeeZ1Q** [comment]
网络是校园网，之前未开启**使用代理服务器**，开启后使用**Host\PAC代理模式**商店显示**错误代码130**，**系统代理模式**商店为**黑屏**

> 与此设备同一网络的其他设备是否可以正常联网，若可以，则是设备本身的设置问题（如：Windows 10 中，是否在“网络设置”中启用“手动代理设置”等）；若不可以，请排查路由器、网关等设备是否正常运行。

**Comment by CDmking** [comment]
> 网络是校园网，之前未开启**使用代理服务器**，开启后使用**Host\PAC代理模式**商店显示**错误代码130**，**系统代理模式**商店为**黑屏**
> 
> > 与此设备同一网络的其他设备是否可以正常联网，若可以，则是设备本身的设置问题（如：Windows 10 中，是否在“网络设置”中启用“手动代理设置”等）；若不可以，请排查路由器、网关等设备是否正常运行。

那就是校园网本身的问题，跟设备和软件没关系，换个网络试试。
