### ISSUE TITLE
🐛[BUG] Linux下不显示广告

### ISSUE THREAD

**Issue by ngdngdc** [BeyondDimension/SteamTools#2186]
### 🐛 描述(Description)

Windows下程序可正常显示广告但Linux下不显示

### 📄 日志信息(Log Information)

近几日程序似乎未创建日志
[nlog-all-2022-10-26.log](https://github.com/BeyondDimension/SteamTools/files/9893565/nlog-all-2022-10-26.log)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.4-4(AUR-bin)
- 系统版本号(OS Version): EndeavourOS Linux x86_64
- 是否为应用商店版本(Whether it is a Store version): No

### 🖼 截图(Screenshots)

Windows:
![屏幕截图 2022-10-28 232352](https://user-images.githubusercontent.com/61965178/198828976-41865486-6328-44e4-85ad-90dbe94169a2.jpg)
![屏幕截图 2022-10-29 143123](https://user-images.githubusercontent.com/61965178/198828982-bfb3c8f3-1219-400a-904d-6e4a38099a64.jpg)
Linux:
![Screenshot_20221029_192104](https://user-images.githubusercontent.com/61965178/198829023-9cf0b482-c9eb-4dc3-83d2-69a2d8815621.png)
![Screenshot_20221029_192037](https://user-images.githubusercontent.com/61965178/198829021-cb100f99-73d2-4a34-aa78-8bc7b62fb40b.png)

**Comment by rmbadmin** [comment]
因为接的广告只在windows推广啊，所以其他平台当然没有🤣
