### ISSUE TITLE
🧐[Question] 

### ISSUE THREAD

**Issue by yisusheng** [BeyondDimension/SteamTools#2187]
### 🧐 问题描述(Description)
当steam++运行后，库里有一款游戏（Unrailed）会自动显示“正在运行”，但实际上是未运行的，没有游戏画面。
即使游戏未安装，打开steam++后，同样会显示游戏正在运行。

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by Mossimos** [comment]
请检查是否添加到了 游戏挂时长列表中

**Comment by yisusheng** [comment]
检查了一下，是的，不会用的时候乱点的。感谢。
