### ISSUE TITLE
🐛[BUG] discord无法打开

### ISSUE THREAD

**Issue by EricKK** [BeyondDimension/SteamTools#2197]
### 🐛 描述(Description)

discord无法打开，流量统计界面没流量

### 📷 复现步骤(Steps to Reproduce)

1. 加速模式选host
2. 打开discord
3. 浏览器提示超时

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.8.4
- 系统版本号(OS Version):  Windows 10 21H2
- 是否为应用商店版本(Whether it is a Store version): No

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/4104606/199200126-edcf2097-c6ba-46cb-9610-b3bddb79b965.png)

**Comment by CDmking** [comment]
换成DNS拦截模式可以正常打开。

**Comment by EricKK** [comment]
> 换成DNS拦截模式可以正常打开。

还是不行，流量统计0kb和另外一个issue还是有点不同的。

**Comment by CDmking** [comment]
请您提供一下日志文件，谢谢。

**Comment by rmbadmin** [comment]
discord.gg域名没有走加速（我之后加上），你可以直接开discord.com或者discordapp.net

**Comment by EricKK** [comment]
> 请您提供一下日志文件，谢谢。

日志文件并没有相关信息，显示日志时间点是很早之前的，并不是我后面打开discord时的日至。

**Comment by EricKK** [comment]
> discord.gg域名没有走加速（我之后加上），你可以直接开discord.com或者discordapp.net

好的，怪不得不行了，谢谢。
