### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by null0x0f** [BeyondDimension/SteamTools#2205]
### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): 

### 🖼 截图(Screenshots)

<img width="691" alt="image" src="https://user-images.githubusercontent.com/95173705/199701081-f50754a4-ef78-4f52-ac8e-4b208b54dc55.png">

**Comment by null0x0f** [comment]
没有github加速了

**Comment by rmbadmin** [comment]
程序语言改为简中，然后重启程序
