### ISSUE TITLE
[Question] 能否实现非线性动画？

### ISSUE THREAD

**Issue by SherkeyXD** [BeyondDimension/SteamTools#225]
### 🧐 问题描述(Description)

目前使用的UI框架能否实现滚动页面时的非线性动画效果？

### 🚑 其他信息(Other Information)

大概做到像edge的网页平滑滚动的效果就好

**Comment by AigioL** [comment]
理论上当然能实现，毕竟底层都是 Skia，只是成本问题

最简单的实现方式 是用 [Edge WebView2](https://docs.microsoft.com/zh-cn/microsoft-edge/webview2) 与 Web UI 实现相关的页面

可惜 WebView2 目前只能在 Windows 上工作，且没有 AvaloniaUI 上的官方支持，也没有看到社区上有支持

之后如果有支持的解决方案，就吧目前用到 CEF 上的地方换掉也就实现了

**Comment by AigioL** [comment]
AvaloniaUI 上的滚动条 要实现这个较难，而且目前在 Windows 上也有一个问题 https://github.com/AvaloniaUI/Avalonia/issues/5640

之后有时间可以尝试搞一下，目前来看成本太高

**Comment by S-t-e-v-e-e** [comment]
> 理论上当然能实现，毕竟底层都是 Skia，只是成本问题
> 
> 最简单的实现方式 是用 [Edge WebView2](https://docs.microsoft.com/zh-cn/microsoft-edge/webview2) 与 Web UI 实现相关的页面
> 
> 可惜 WebView2 目前只能在 Windows 上工作，且没有 AvaloniaUI 上的官方支持，也没有看到社区上有支持
> 
> 之后如果有支持的解决方案，就吧目前用到 CEF 上的地方换掉也就实现了

https://docs.avaloniaui.net/zh-Hans/xpf/embedding/web-view
