### ISSUE TITLE
🐛[BUG]访问github,谷歌浏览器页面提示“您的连接不是私密连接”。

### ISSUE THREAD

**Issue by xjown** [BeyondDimension/SteamTools#2250]
### 🐛 描述(Description)

开启软件后，打开github。谷歌浏览器提示“您的连接不是私密连接，攻击者可能会试图从 github.com 窃取您的信息”。

**Comment by rmbadmin** [comment]
信任steam++生成的证书即可

**Comment by xjown** [comment]
> 信任steam++生成的证书即可
我在钥匙串里面看到已经信任，并且之前都是好的，只有最近才出现这种情况

**Comment by rmbadmin** [comment]
> > 信任steam++生成的证书即可
> > 我在钥匙串里面看到已经信任，并且之前都是好的，只有最近才出现这种情况

检查下是不是证书过期了，或者重新生成过证书，这样需要重新信任新的证书

**Comment by xjown** [comment]
> > > 信任steam++生成的证书即可
> > > 我在钥匙串里面看到已经信任，并且之前都是好的，只有最近才出现这种情况
> 
> 检查下是不是证书过期了，或者重新生成过证书，这样需要重新信任新的证书

我看证书过期是2023年，然后我先删除证书，再把软件卸载。在重新下载、安装了一次证书。重启浏览器后还是之前那样。safari是正常的

**Comment by rmbadmin** [comment]
> > > > 信任steam++生成的证书即可
> > > > 我在钥匙串里面看到已经信任，并且之前都是好的，只有最近才出现这种情况
> > 
> > 
> > 检查下是不是证书过期了，或者重新生成过证书，这样需要重新信任新的证书
> 
> 我看证书过期是2023年，然后我先删除证书，再把软件卸载。在重新下载、安装了一次证书。重启浏览器后还是之前那样。safari是正常的

mac上的 chrome可能需要再浏览器里单独添加证书信任，检查一下

**Comment by xjown** [comment]
> > > > > 信任steam++生成的证书即可
> > > > > 我在钥匙串里面看到已经信任，并且之前都是好的，只有最近才出现这种情况
> > > 
> > > 
> > > 检查下是不是证书过期了，或者重新生成过证书，这样需要重新信任新的证书
> > 
> > 
> > 我看证书过期是2023年，然后我先删除证书，再把软件卸载。在重新下载、安装了一次证书。重启浏览器后还是之前那样。safari是正常的
> 
> mac上的 chrome可能需要再浏览器里单独添加证书信任，检查一下
好的,感谢

**Comment by yin-qiyu** [comment]
请问解决了吗  我也遇到了同样的问题

**Comment by xjown** [comment]
> 请问解决了吗 我也遇到了同样的问题
没！

**Comment by ghost** [comment]
请问解决了吗 我也遇到了同样的问题
