### ISSUE TITLE
🧐[Question] hosts模式下部分谷歌网站也在hosts名单中

### ISSUE THREAD

**Issue by Pr0pHesyer** [BeyondDimension/SteamTools#2253]
### 🧐 问题描述(Description)

我使用的是路由器透明代理，在不使用Watt toolkit的情况下能正常连接谷歌。但是在启用开启hosts模式加速后访问google.com会404，查看hosts后发现是被hosts重定向了，也就是被Watt toolkit接管并禁止连接。
作者声称不会加速谷歌，我表示理解。但是为什么要干扰正常的访问？

- 程序版本(Program Version):2.8.4
- 系统版本号(OS Version): 版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2022/‎10/‎13
操作系统版本	22621.674
体验	Windows Feature Experience Pack 1000.22634.1000.0

- 是否为应用商店版本(Whether it is a Store version): Y

**Comment by rmbadmin** [comment]
这是因为你勾选了谷歌验证码加速，所以需要修改hosts监听谷歌域名来跳转谷歌验证码，如果你有其他方式访问谷歌，则不需要开谷歌验证码加速即可。
