### ISSUE TITLE
👑[Enhancement] epic目前需要加速器来加速

### ISSUE THREAD

**Issue by HamsterYrc** [BeyondDimension/SteamTools#2261]
真的需要epic，而且官网显示有这个功能

### 🥰 需求描述(Description)

客户端商城一直无法连接，很烦，官网却可以
### 🧐 解决方案(Solution)

1.用其他加速器
2.用v**
### 🚑 其他信息(Other Information)

虽然已经提过，但觉得还需要再提一遍
<img width="977" alt="image" src="https://user-images.githubusercontent.com/109511472/201308766-aa5b6085-2504-496a-af93-4e94cd058ac7.png">
<img width="818" alt="image" src="https://user-images.githubusercontent.com/109511472/201309018-aa657d29-1d4b-499d-94b7-dc137e794d44.png">

**Comment by HamsterYrc** [comment]
补充：即使实装后效果不好也能接受

**Comment by HamsterYrc** [comment]
ps
运气问题

**Comment by HamsterYrc** [comment]
ps：运气问题，不用加了

**Comment by Louaq** [comment]
还是用加速器

**Comment by AigioL** [comment]
#318 duplicate
