### ISSUE TITLE
更新到2.8.4版本后發現缺少網絡加速和脚本配置功能

### ISSUE THREAD

**Issue by yishi048** [BeyondDimension/SteamTools#2264]
### 🧐 问题描述(Description)

-->之前使用的是2.6.9版本，今天下載更新2.8.4版本以後發現沒有網絡加速和脚本配置的功能。嘗試過下載2.8.4版本的EXE和7Z都是沒有這兩個功能的，登錄了以後也沒有。

截圖

-->
![image](https://user-images.githubusercontent.com/115603988/201461154-38775e20-3e2d-4790-a0d9-e0c6e97ca07c.png)

- 程序版本(Program Version):2.8.4
- 系统版本号(OS Version): <!-- Windows 10 
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by rmbadmin** [comment]
语言设置简中，重启软件就有了，公告里已经说过了
