### ISSUE TITLE
是赞助用户却没有去广告🧐[Question] 

### ISSUE THREAD

**Issue by 894wlp** [BeyondDimension/SteamTools#2266]
### 🧐 问题描述(Description)
是赞助用户却没有去广告
如截图等其他信息可以贴在这里
![屏幕截图 2022-11-13 134056](https://user-images.githubusercontent.com/115552796/201507998-4f54f872-30b1-4ade-b490-0960f8a76796.png)

- 程序版本(Program Version):2.8.4
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): 否(No)

**Comment by rmbadmin** [comment]
UI设置里自己关一下..

**Comment by 894wlp** [comment]
谢谢
