### ISSUE TITLE
🧐[Question] Macos上安装信任证书时反复弹出控制台窗口

### ISSUE THREAD

**Issue by sundaylover** [BeyondDimension/SteamTools#2267]
请在弹出的控制台窗口输入系统密码以安装信任证书，点击确定后可以弹出控制台窗口，但是输完密码返回点确定后依然弹出控制台窗口，一直反复这样

<img width="1675" alt="Snipaste_2022-11-13_14-23-47" src="https://user-images.githubusercontent.com/8598259/201508957-3364ead2-8401-4e6b-98d0-f0d43f32bdc5.png">
<img width="900" alt="Snipaste_2022-11-13_14-24-08" src="https://user-images.githubusercontent.com/8598259/201508968-51448f2a-1651-4778-99d1-71b550cd0aae.png">
<img width="586" alt="Snipaste_2022-11-13_14-23-58" src="https://user-images.githubusercontent.com/8598259/201508973-7198d449-e394-48e1-98a4-265c06268049.png">
<img width="900" alt="Snipaste_2022-11-13_14-24-18" src="https://user-images.githubusercontent.com/8598259/201508977-7624f52d-8707-4666-b107-e0e63d562dc4.png">
<img width="1143" alt="Snipaste_2022-11-13_14-31-37" src="https://user-images.githubusercontent.com/8598259/201509030-433579ea-c5ba-4a8d-99c2-c745243a1cf1.png">

- 程序版本(Program Version):2.8.4
- 系统版本号(OS Version): macOS Catalina 10.15.7
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by Mossimos** [comment]
10.15.x 可能有问题。
参考下 #1941
这个问题可能手动重新信任下证书就行了

**Comment by sundaylover** [comment]
解决了，先把证书手动设置成用不信任，然后再一键加速输入密码就可以了，多谢

**Comment by sundaylover** [comment]
解决了，先把证书手动设置成用不信任，然后再一键加速输入密码就可以了，多谢
