### ISSUE TITLE
👑[Enhancement] 希望增加Sandboxie沙盒内多开和HLTV的加速支持

### ISSUE THREAD

**Issue by LeeBA4IHW** [BeyondDimension/SteamTools#2268]
### 🥰 需求描述(Description)

如题，1.希望增加sandboxie的多开支持性，因为某些包括我在内的人需要多开steam挂时长，而steam是可以用sandboxie等工具多开的但是steam++不行(会闪退).
2.希望可以加速HLTV. HLTV是CSGO的著名比赛网站，在国内打开加速会很慢有些时候会打不开，包括下载Demo也是慢的离谱.
最后谢谢大佬的工具!
### 🧐 解决方案(Solution)
/

### 🚑 其他信息(Other Information)
![Issue1](https://user-images.githubusercontent.com/55200366/201652294-b699a06f-1342-484c-a0fe-9f413b1daab1.png)

**Comment by AigioL** [comment]
#318 duplicate
