### ISSUE TITLE
🧐[Question] 官网上有暴雪加速，以前的版本也有，请问现在为什么没了？

### ISSUE THREAD

**Issue by Xiuyuan121** [BeyondDimension/SteamTools#2272]
- 程序版本(Program Version):2.8.4
- 系统版本号(OS Version):Windows11 22H2 22621.819
- 是否为应用商店版本(Whether it is a Store version): 
否

**Comment by rmbadmin** [comment]
加速项目会根据加速支持效果实时调整，如果效果不行且短时间没有好办法解决我会暂时移除对应加速项等待能解决时在启用

**Comment by Y1NXu** [comment]
大概多久能够重新支持呢
