### ISSUE TITLE
Matt Toolkit window 64版本 下载后菜单里没有网页加速和脚本配置，第一个可选菜单是账号切换🧐[Question] 

### ISSUE THREAD

**Issue by Moksi00** [BeyondDimension/SteamTools#2280]
尝试下载了许多次Matt toolkit，无论是从商店下载还是网页下载，下载安装打开后，菜单栏都是从账号切换功能开始往下的。
比一般的缺失了前两个“网页加速”和“脚本配置”功能。
请问应该要如何修复才可以使用网页加速功能？感谢大家指导！

### 🧐 问题描述(Description)

![image](https://user-images.githubusercontent.com/118732014/203034593-aeedd497-f0c4-4d81-bb03-a7e3c77cf2eb.png)

### 🚑 其他信息(Other Information)

windows版本如图

![image](https://user-images.githubusercontent.com/118732014/203035050-565ea429-ce84-4013-8a58-1923b4036ff3.png)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): yes

**Comment by rmbadmin** [comment]
软件语言切换为简中，重启软件

**Comment by Moksi00** [comment]
> 软件语言切换为简中，重启软件

感恩！！！！！！！！！！！！
