### ISSUE TITLE
🧐[Question] 请问在mac下如何运行源码及开发

### ISSUE THREAD

**Issue by jimersylee** [BeyondDimension/SteamTools#2290]
### 🧐 问题描述(Description)

在Mac下使用Rider和Visual Studio For Mac 尝试运行，都没有成功，是否有开发运行，及如何编译的文档

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by AigioL** [comment]
Rider 和 VS for Mac 应该因为一些 Xamarin 相关的 TFM 导致没法编译，现在最新版的 VS 2022 Win 也有这个问题
但是好像还有一些其他什么问题不记得了，导致也编译不了

现在只能在 VS 2022 Win 上，先注释了 Xamarin 相关的 TFM 才能编译调试

下个月预计要重构下客户端这一片，重构之后应该才能用其他 IDE 了

**Comment by shuifa** [comment]
> Rider 和 VS for Mac 应该因为一些 Xamarin 相关的 TFM 导致没法编译，现在最新版的 VS 2022 Win 也有这个问题
> 
> 但是好像还有一些其他什么问题不记得了，导致也编译不了
> 
> 
> 
> 现在只能在 VS 2022 Win 上，先注释了 Xamarin 相关的 TFM 才能编译调试
> 
> 
> 
> 下个月预计要重构下客户端这一片，重构之后应该才能用其他 IDE 了

请问下，下一个版本啥时候发布啊，距离上次发布4个月了快要？

**Comment by rmbadmin** [comment]
> > Rider 和 VS for Mac 应该因为一些 Xamarin 相关的 TFM 导致没法编译，现在最新版的 VS 2022 Win 也有这个问题
> > 但是好像还有一些其他什么问题不记得了，导致也编译不了
> > 现在只能在 VS 2022 Win 上，先注释了 Xamarin 相关的 TFM 才能编译调试
> > 下个月预计要重构下客户端这一片，重构之后应该才能用其他 IDE 了
> 
> 请问下，下一个版本啥时候发布啊，距离上次发布4个月了快要？

预计是1月份吧

**Comment by shuifa** [comment]
> > > Rider 和 VS for Mac 应该因为一些 Xamarin 相关的 TFM 导致没法编译，现在最新版的 VS 2022 Win 也有这个问题
> 
> > > 但是好像还有一些其他什么问题不记得了，导致也编译不了
> 
> > > 现在只能在 VS 2022 Win 上，先注释了 Xamarin 相关的 TFM 才能编译调试
> 
> > > 下个月预计要重构下客户端这一片，重构之后应该才能用其他 IDE 了
> 
> > 
> 
> > 请问下，下一个版本啥时候发布啊，距离上次发布4个月了快要？
> 
> 
> 
> 预计是1月份吧

这次是有巨大的改动吗，半年出一个版本

**Comment by rmbadmin** [comment]
> > > > Rider 和 VS for Mac 应该因为一些 Xamarin 相关的 TFM 导致没法编译，现在最新版的 VS 2022 Win 也有这个问题
> > 
> > 
> > > > 但是好像还有一些其他什么问题不记得了，导致也编译不了
> > 
> > 
> > > > 现在只能在 VS 2022 Win 上，先注释了 Xamarin 相关的 TFM 才能编译调试
> > 
> > 
> > > > 下个月预计要重构下客户端这一片，重构之后应该才能用其他 IDE 了
> > 
> > 
> > > 
> > 
> > 
> > > 请问下，下一个版本啥时候发布啊，距离上次发布4个月了快要？
> > 
> > 
> > 预计是1月份吧
> 
> 这次是有巨大的改动吗，半年出一个版本

 .NET 7及 MAUI的尝试以及服务端重构花费较多时间把，也有很多其他挖坑到一半的新功能构想和尝试可能暂时无法更新进来，所以耽误了许多时间。
