### ISSUE TITLE
加速后访问被加速网站，浏览器断开连接

### ISSUE THREAD

**Issue by zcm2005** [BeyondDimension/SteamTools#2291]
例如：

你的连接不是专用连接
攻击者可能试图从 onedrive.live.com 窃取你的信息(例如，密码、消息或信用卡)。
NET::ERR_CERT_AUTHORITY_INVALID
onedrive.live.com 使用加密来保护你的信息。这次，当 Microsoft Edge 尝试连接到 onedrive.live.com 时，网站发回了不正常和不正确的凭据。如果攻击者尝试假冒 onedrive.live.com，或者 WLAN 登录屏幕已中断连接，则可能会发生这种情况。你的信息仍然安全，因为在交换任何数据之前，Microsoft Edge 停止了连接。

你现在无法访问 onedrive.live.com，因为网站使用的是 HSTS。网络错误和攻击通常是暂时的，因此该页面以后可能会恢复正常。

**Comment by zcm2005** [comment]
似乎不论用哪种加速模式，都有这个问题

**Comment by zcm2005** [comment]
系统：Windows Server 2022 Datacenter
浏览器：Edge
软件版本：2.8.4
如果需要更多信息，我还可以提供

**Comment by zcm2005** [comment]
补充：经过一些测试，这个问题看起来与账户有关。
使用普通用户打开软件，会要求管理员权限，输入管理员密码并允许允许，然后进行加速。
此时，打开edge，访问网页，会出现上述问题。
但是，右键edge并用管理员账户运行，问题消失，可以正常访问。

在安装软件时，安装程序运行在管理员账户下，并提示安装证书，是否与此有关？证书的存储是否有误？

**Comment by rmbadmin** [comment]
确保steam++证书正确安装

**Comment by zcm2005** [comment]
经检查，Steam证书安装在了Administrator账户的“受信任的根证书颁发机构”下，这是不合适的。为了修正这个问题，我将该证书导出，并重新导入到"本地计算机\受信任的根证书颁发机构"中，该问题消失。
推测导致此问题的原因：系统中有一普通用户以及Administrator，登录普通用户并运行安装程序，此时要求管理员权限。输入密码，安装程序以管理员身份运行，并将证书安装到其运行的账户（Administrator）中。完成后，运行软件，此时普通用户正确安装证书，无法正常登录网站；利用管理员权限运行edge，edge获取到Administrator下的证书，可以正常登陆网站；将证书导入“本地计算机”，所有用户均可访问，此时普通用户可以正常登录网站。

**Comment by rmbadmin** [comment]
证书现在默认确实是安装再当前用户上，而不是本地计算机上

**Comment by zcm2005** [comment]
如果可以的话，希望可以优化一下证书的默认存储，或者在安装时提供其他选项。
