### ISSUE TITLE
🧐[Question]操作 Hosts 错误文件访问被拒绝，没有权限

### ISSUE THREAD

**Issue by Thhhhhhhh** [BeyondDimension/SteamTools#2307]
### 🧐 问题描述(Description)
操作 Hosts 错误文件访问被拒绝，没有权限

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by CDmking** [comment]
没有其他信息了吗？

**Comment by Hyumtaro** [comment]
我也存在相同的问题,此外查询443端口为发展其他进程占用

**Comment by CDmking** [comment]
是否使用了管理员权限运行程序？

**Comment by Hyumtaro** [comment]
> 是否使用了管理员权限运行程序？

感谢！已经可以了。因为是在Ubuntu系统下，所以没法像Windows下那样方便的以管理员权限运行。我是通过查看deb包文件结构找到可执行文件位置，然后sudo执行的。对于其他linux用户，可以考虑相同的解决办法。
```bash
sudo /usr/share/Steam++/Steam++
```

**Comment by Hyumtaro** [comment]
> > 是否使用了管理员权限运行程序？
> 
> 感谢！已经可以了。因为是在Ubuntu系统下，所以没法像Windows下那样方便的以管理员权限运行。我是通过查看deb包文件结构找到可执行文件位置，然后sudo执行的。对于其他linux用户，可以考虑相同的解决办法。
> 
> ```shell
> sudo /usr/share/Steam++/Steam++
> ```

emmm,又仔细看了一下,好像官方已经列出解决办法了.
https://steampp.net/liunxSetupCer

**Comment by cygauss** [comment]
> > > 是否使用了管理员权限运行程序？
> > 
> > 
> > 感谢！已经可以了。因为是在Ubuntu系统下，所以没法像Windows下那样方便的以管理员权限运行。我是通过查看deb包文件结构找到可执行文件位置，然后sudo执行的。对于其他linux用户，可以考虑相同的解决办法。
> > ```shell
> > sudo /usr/share/Steam++/Steam++
> > ```
> 
> emmm,又仔细看了一下,好像官方已经列出解决办法了. https://steampp.net/liunxSetupCer

你这个给出的是linux浏览器证书问题，我认为无法修改hosts文件，如你之前所说，是用户权限问题，导入证书真能解决吗？
经过尝试，无法自动创建一个有权限的hosts，（可能与我的archlinux的权限设置有关），实际上用root给一般帐号一个write权限就可以了
