### ISSUE TITLE
🐛[BUG] 没有网络加速功能，和介绍里的不一样

### ISSUE THREAD

**Issue by B-lovedHunter** [BeyondDimension/SteamTools#2308]
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): v2.8.4
- 系统版本号(OS Version): Windows 11
- 是否为应用商店版本(Whether it is a Store version): No

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/26589791/204462508-1e888449-c814-4fe6-a5d1-523ec86389d8.png)

**Comment by B-lovedHunter** [comment]
重启就可以了

**Comment by FloodLin** [comment]
> 重启就可以了
重起之后仍不可以。这个和7z版和exe安装版有区别么？
win11，启动之后显示【账号切换】，没有【网络加速】和【脚本配置】这两个项目

**Comment by FloodLin** [comment]
> > 重启就可以了
> > 重起之后仍不可以。这个和7z版和exe安装版有区别么？
> > win11，启动之后显示【账号切换】，没有【网络加速】和【脚本配置】这两个项目

已解决了。
win11系统设置为了英文版。默认隐藏了。将程序语言设置成【中文】后重启程序即可以出现上述项目了。
