### ISSUE TITLE
希望可以加入[SteamDB]的网络加速👑[Enhancement] 

### ISSUE THREAD

**Issue by beizhi233** [BeyondDimension/SteamTools#2311]
### 🥰 需求描述(Description)
希望在网络加速选项里加入Steam DB的加速选项，某些地区的宽带（比如我）在90%的情况下是无法直接访问的，查询游戏史低价，一键入库等功能的使用都十分的不方便，感谢大佬做出这么简单易用的软件，希望以后能越来越好！

**Comment by AigioL** [comment]
#318 duplicate
