### ISSUE TITLE
👑[Enhancement] 我发现使用加速和脚本时会出现库存访问次数过多然后不能访问的问题

### ISSUE THREAD

**Issue by milkmikVC** [BeyondDimension/SteamTools#2313]
### 🥰 需求描述(Description)
就是说 我在使用steam++加速和脚本的时候访问库存，会如此提示
![image](https://user-images.githubusercontent.com/89504131/205262243-0de01c83-e8b1-4982-81be-960cf2f727e8.png)
我询问了steam客服，他说是因为使用了浏览器拓展所导致的，关闭拓展即可
但这个时间不会马上好 一般需要等一整天才能再次使用 
现在我无法访问库存 很难受

**Comment by rmbadmin** [comment]
这一般是用了快速扫描库存价格插件，导致你的IP频繁调度接口被屏蔽了，等待解除或者更换IP

**Comment by milkmikVC** [comment]
> 这一般是用了快速扫描库存价格插件，导致你的IP频繁调度接口被屏蔽了，等待解除或者更换IP

但我好像没有用这类插件  或者是buff这样的软件会造成这种情况吗
