### ISSUE TITLE
🧐[Question] GitHub 代理不包括 github.githubassets.com

### ISSUE THREAD

**Issue by pan3793** [BeyondDimension/SteamTools#2316]
### 🧐 问题描述(Description)

代理不包括 github.githubassets.com，GitHub Web 界面还是不能打开

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by AigioL** [comment]
#318 duplicate
