### ISSUE TITLE
steam打开之后steam++闪退.开着steam打不开steam++咋整啊没steam++没法活了

### ISSUE THREAD

**Issue by zyf3130517039** [BeyondDimension/SteamTools#2327]
steam打开之后steam++闪退.开着steam打不开steam++咋整啊没steam++没法活了

https://user-images.githubusercontent.com/89716385/206214976-fe92d2b8-45ef-4f00-a00f-04ec162cd323.mp4

**Comment by rmbadmin** [comment]
更新一下最新版本2.8.4，然后也覆盖重装一下steam

**Comment by zyf3130517039** [comment]
谢谢啊。大神辛苦了，刚看完你视频，看哭了。太不容易了，我再去试一下，我已经试过好多遍了还是不行


痣多猩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BeyondDimension/SteamTools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月7日(星期三) 晚上11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BeyondDimension/SteamTools] steam打开之后steam++闪退.开着steam打不开steam++咋整啊没steam++没法活了 (Issue #2327)





 
更新一下最新版本2.8.4，然后也覆盖重装一下steam

**Comment by zyf3130517039** [comment]
没有效果，我按照您说的过程做的，steam++还是闪退

**Comment by rmbadmin** [comment]
提供一下steam++ logs文件夹得日志文件看看

**Comment by zyf3130517039** [comment]
[nlog-all-2022-12-07.log](https://github.com/BeyondDimension/SteamTools/files/10177358/nlog-all-2022-12-07.log)

**Comment by zyf3130517039** [comment]
启不启动加速都一样，开steam之后++卡一下就闪退了。昨天还好好地，不知道怎么就这样了。

**Comment by zyf3130517039** [comment]
我刚才虚拟机试了一下，虚拟机正常。应该是我电脑问题，我重装系统先，不好意思啊
