### ISSUE TITLE
👑[Enhancement] 希望可以加入启动后自动开启加速功能

### ISSUE THREAD

**Issue by seventeenST** [BeyondDimension/SteamTools#2331]
希望可以加入启动后自动开启加速功能。
现在虽然有启动后自动启动steam功能，但因为加速未开启，经常导致因为网络问题启动失败，希望可以加入启动后自动加速功能

**Comment by ngdngdc** [comment]
你是说这个？
![屏幕截图 2022-12-09 160830](https://user-images.githubusercontent.com/61965178/206655067-e7be0258-70c6-498b-9bf3-d7eeeea8abdb.jpeg)

**Comment by AigioL** [comment]
这个自启的功能确实放的太深入了，之后会考虑下放在显眼的位置，或首次使用时引导
