### ISSUE TITLE
库存无法显示🧐[Question] 

### ISSUE THREAD

**Issue by llkklkhj** [BeyondDimension/SteamTools#2332]
如图，库存无法显示，一直显示为加载状态

### 🚑 其他信息(Other Information)

![_AXP~G9_M 41 N~5Y3IJDUQ](https://user-images.githubusercontent.com/120175089/206677337-6d6e2ae8-7d01-45a6-ab32-3cd8bc42ff71.png)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by nenevva** [comment]
我也遇到了这个问题
-------
我的环境：WIn11 Steam测试分支的最新build Dec 9 2022
看了下log，错误信息如下：Error|GetAppInfos|"appinfo.vdf" magic code is not supported: 0x07564428

**Comment by sxjn023** [comment]
请问你有没有解决这个问题，

**Comment by llkklkhj** [comment]
> 

没有

**Comment by rmbadmin** [comment]
该问题与steam最近的更新有关，要等修复后发布个新版本解决

**Comment by G-lory** [comment]
有没有更新呢现在



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月12日(周一) 下午3:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BeyondDimension/SteamTools] 库存无法显示🧐[Question]  (Issue #2332)




 
Closed #2332 as completed.
