### ISSUE TITLE
🧐[Question] Macos 安装新任证书时遇到问题

### ISSUE THREAD

**Issue by PlumTree1995** [BeyondDimension/SteamTools#2333]
### 🧐 问题描述(Description)
点击一键加速后自动运行终端但没有弹出窗口，点开终端后无钥匙形提示

### 🚑 其他信息(Other Information)
![截屏2022-12-09 下午10 26 52](https://user-images.githubusercontent.com/120192049/206724020-591833c5-4446-4456-a840-bbd872196aa5.png)
![截屏2022-12-09 下午10 28 15](https://user-images.githubusercontent.com/120192049/206724488-211872aa-5e32-402c-ac6a-b9921a0b96bc.png)

- 程序版本(Program Version):2.8.4 x64
- 系统版本号(OS Version): macOS Catalina 10.15.7
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by Mossimos** [comment]
10.15 版本目前有问题 [参考该连接](https://steampp.net/macosSetupCer) 安装好证书后
手动取消信任再信任一次

**Comment by PlumTree1995** [comment]
输入密码后报错了
![截屏2022-12-10 上午8 48 23](https://user-images.githubusercontent.com/120192049/206819985-e788c042-7506-41f7-b576-b55507d9f9b7.png)

**Comment by PlumTree1995** [comment]
> 10.15 版本目前有问题 [参考该连接](https://steampp.net/macosSetupCer) 安装好证书后 手动取消信任再信任一次
输入密码后报错了
![截屏2022-12-10 上午8 48 23](https://user-images.githubusercontent.com/120192049/206820473-242dcd0b-8d01-4fc1-8419-1b2985b7f5a7.png)

**Comment by Mossimos** [comment]
路径给短了不好意思这是完整的
sudo security add-trusted-cert -d -r trustRoot -k /Users/此处修改成您的用户名/Library/Steam++/SteamTools.Certificate.cer /Library/Keychains/login.keychain-db

**Comment by Mossimos** [comment]
![image](https://user-images.githubusercontent.com/26396340/206851688-2a29faa7-7cb7-4b85-a7ce-35b17d969271.png)
先走这里手动导入吧
/Users/此处修改成您的用户名/Library/Steam++/SteamTools.Certificate.cer
这个证书然后信任。

**Comment by Mossimos** [comment]
sudo -S security add-trusted-cert -d -r trustRoot -k /Users/修改成你的用户名/Library/Keychains/login.keychain-db" /Users/修改成你的用户名/Library/Steam++/SteamTools.Certificate.cer"

**Comment by PlumTree1995** [comment]
证书倒是没问题了，输完获取host权限的命令又报错了，遭不住😂
![截屏2022-12-10 下午7 45 49](https://user-images.githubusercontent.com/120192049/206853429-70b6a32d-1e6e-4485-a019-56da5b21bf7c.png)



> sudo -S security add-trusted-cert -d -r trustRoot -k /Users/修改成你的用户名/Library/Keychains/login.keychain-db" /Users/修改成你的用户名/Library/Steam++/SteamTools.Certificate.cer"

**Comment by Mossimos** [comment]
这个是没有这个文件？
那你尝试
cd /etc
touch hosts

**Comment by Mossimos** [comment]
实在不行可以尝试系统代理模式

**Comment by PlumTree1995** [comment]
已经手动赋予etc权限了，还是不行（哭
![截屏2022-12-10 下午10 51 56](https://user-images.githubusercontent.com/120192049/206861237-c888480c-7791-4e9e-b819-dcf01f954681.png)

试了一下，系统代理确实可以用，那感谢大佬的耐心解答，辛苦了（鞠躬

**Comment by Mossimos** [comment]
sudo touch hosts 呢

**Comment by Mossimos** [comment]
而且你不要 给 /etc 目录修改权限 会有安全问题 其实 host 文件修改权限也会有安全问题

**Comment by PlumTree1995** [comment]
呃。。。那要怎么补救呢

**Comment by Mossimos** [comment]
你实际是没给成功的  chmod 设置权限后面是要跟文件夹路径的你没加所有指令完全都没执行
