### ISSUE TITLE
👑[Enhancement] 请添加fandom的反代支持

### ISSUE THREAD

**Issue by mike-brown8** [BeyondDimension/SteamTools#2335]
### 🥰 需求描述(Description)
我需要访问位于Fandom的Minecraft Wiki，可是由于直连访问缓慢，甚至会丢失页面排版，我无法正常使用此Wiki。

### 🧐 解决方案(Solution)
添加Fandom、Fandom图片、Fandom网页的支持

**Comment by AigioL** [comment]
#318 duplicate
