### ISSUE TITLE
🧐[Question] 加速Discord后仍无法打开其他人分享的加入频道网页链接

### ISSUE THREAD

**Issue by Husomeone** [BeyondDimension/SteamTools#2336]
### 🧐 问题描述(Description)

加速Discord后一切都正常使用，但是当我试图点击他人分享的 加入频道链接 的时候，网页加载失败，无法访问discord.gg
是否是需要再添加一个关于discord.gg的加速

### 🚑 其他信息(Other Information)

- 程序版本(Program Version): 2.8.4
- 系统版本号(OS Version): 版本	Windows 10 专业版19044.2251
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by rmbadmin** [comment]
之前整了一直忘记更新到正式了，现在已经更新了，等缓存刷新后重开下加速应该就正常了
