### ISSUE TITLE
🐛[BUG] Watt Toolkit 无法正确识别通过 `Steam.exe` 加上启动参数 `-steamchina` 而启动的蒸汽平台客户端

### ISSUE THREAD

**Issue by cherinyy** [BeyondDimension/SteamTools#2346]
### 🐛 描述(Description)

可以通过启动参数 `-steamchina` 将 Steam 客户端“转换”为蒸汽平台客户端，而 Watt Toolkit 仍然将其视为 Steam。

### 📷 复现步骤(Steps to Reproduce)

1. 运行带有参数 `-steamchina` 的 `Steam.exe`。

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.8.4
- 系统版本号(OS Version): Windows 11 Pro for Workstations Version 22H2 (Build 22621.900)
- 是否为应用商店版本(Whether it is a Store version): 是

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/9050713/207233230-72ddbffc-3147-4484-9a93-97b4fc8d26e5.png)

**Comment by rmbadmin** [comment]
我测试是正常的，这应该与已经修复的steam传参启动的bug有关，新版本发布后会修复，你可以测试下https://github.com/BeyondDimension/SteamTools/actions/runs/3677559295
构建的包是否正常修复

**Comment by cherinyy** [comment]
> 我测试是正常的，这应该与已经修复的steam传参启动的bug有关，新版本发布后会修复，你可以测试下https://github.com/BeyondDimension/SteamTools/actions/runs/3677559295 构建的包是否正常修复

![image](https://user-images.githubusercontent.com/9050713/207309584-4fe18257-99f4-4e2f-afb1-b528b787a7f5.png)

无

![image](https://user-images.githubusercontent.com/9050713/207309612-142a384e-3504-43ea-bd22-2c96cbb234b3.png)
