### ISSUE TITLE
🐛[BUG] mega的加速有问题 会一直转圈圈 有几个域名没有写入到hosts

### ISSUE THREAD

**Issue by gdf159159** [BeyondDimension/SteamTools#2370]
比如 eu.static.mega.co.nz

g.api.mega.co.nz

**Comment by littlekan233** [comment]
确实 资源（eu.static.mega.co.nz）得需要关掉加速才能出来 api（g.api.mega.co.nz）无论开没开加速都访问不了

**Comment by AHKR-y** [comment]
所以是咋解决的
