### ISSUE TITLE
🐛[BUG] 2.8.5版本，在设置中添加任何启动项会导致无法用一键登陆启动steam

### ISSUE THREAD

**Issue by c1ha0x00** [BeyondDimension/SteamTools#2373]
### 🐛 描述(Description)

2.8.5 版本，在设置->Steam 设置->Steam 启动参数 一栏里填入任何启动项（如-websocket , -tcp , -console 等）之后，使用一键登陆功能会失效。经测试2.8.4版本没有问题，在steam快捷方式中添加任何合法启动项也能如期运行。
### 📷 复现步骤(Steps to Reproduce)

1. 2.8.5版本中，Steam 启动参数内填入 `-websockt` 
2. 点击“帐号切换”中的“一键登录 Steam“ （此时一闪而过Windows Terminal，之后无任何steam程序启动迹象，无steam.exe进程）

### 📄 日志信息(Log Information)

在执行上述步骤后程序没有产生日志文件。
不添加启动参数的日志：
```
2023-12-17 00:32:23.0357|Error|SteamworksLocalApiS|Initialize Fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at System.Application.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()
```

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.8.5
- 系统版本号(OS Version): Windows 11 Version 22H2 (OS Build 22621.963)
- 是否为应用商店版本(Whether it is a Store version): 是

### 🖼 截图(Screenshots)

![图片](https://user-images.githubusercontent.com/108121639/208145837-7d418bf8-7d16-4035-9885-52027124ddc7.png)
![图片](https://user-images.githubusercontent.com/108121639/208145928-130a3da0-b30b-46c6-82d1-136cccd13260.png)

**Comment by rmbadmin** [comment]
这是一个已知的问题，目前解决方案是 尝试勾选 以管理员身份启动Steam选项 即可

**Comment by c1ha0x00** [comment]
> 这是一个已知的问题，目前解决方案是 尝试勾选 以管理员身份启动Steam选项 即可

可用，感谢
