### ISSUE TITLE
最新版本2.8.5的成就管理无法弹出管理实操窗口🧐[Question] 

### ISSUE THREAD

**Issue by ArKenNNN** [BeyondDimension/SteamTools#2374]
### 🧐 问题描述(Description)
无法打开成就管理窗口，点击管理成就后会弹出加载，随后会秒弹一个窗口消失然后就没有任何反应，没有成就管理的窗口弹出。

### 🚑 其他信息(Other Information)
对于2.8.4版本我并无此情况，且在此问题发生后我重新使用2.8.4能正常使用此功能初步判断与本人设备无关
下为日志内容
![报错日志](https://user-images.githubusercontent.com/120783211/208239894-9e15c663-ed0d-4091-9939-88a024b39230.png)

- 程序版本(Program Version):2.8.5 for Windows (x64)
- 系统版本号(OS Version): 
![系统版本](https://user-images.githubusercontent.com/120783211/208240053-9a2ffa01-8eb2-42ed-beec-cd9392fe4066.png)

- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by rmbadmin** [comment]
fix on 5509004c649082003a0ad97cae028e5be1fac8f2

**Comment by ArKenNNN** [comment]
> fix on [5509004](https://github.com/BeyondDimension/SteamTools/commit/5509004c649082003a0ad97cae028e5be1fac8f2)

THX

**Comment by ArKenNNN** [comment]
> fix on [5509004](https://github.com/BeyondDimension/SteamTools/commit/5509004c649082003a0ad97cae028e5be1fac8f2)

这不是很会实操啊。。。。。

**Comment by ArKenNNN** [comment]
这些东西该如何使用呢。。。。。
