### ISSUE TITLE
🐛[BUG] 2.8.5版本的成就管理功能无法使用！

### ISSUE THREAD

**Issue by Scz3oX** [BeyondDimension/SteamTools#2375]
### 🐛 描述(Description)

新版本的成就管理无法使用，点击后直接闪退。2.8.4版本使用正常！

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.8.5
- 系统版本号(OS Version): Windows10  (系统版本 19045.2364)
- 非应用商店版本

**Comment by rmbadmin** [comment]
fix on 5509004c649082003a0ad97cae028e5be1fac8f2
