### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by ghost** [BeyondDimension/SteamTools#2381]
### 🐛 描述(Description)

解锁成就无法使用

### 📷 复现步骤(Steps to Reproduce)

1. 点击解锁
2. 闪出窗口
3. 自动关闭

### 📄 日志信息(Log Information)

[internal-nlog.txt](https://github.com/BeyondDimension/SteamTools/files/10255638/internal-nlog.txt)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.5
- 系统版本号(OS Version): win11专业版，版本21H2(OS内部版本220001219)
- 是否为应用商店版本(Whether it is a Store version): NO

### 🖼 截图(Screenshots)

https://user-images.githubusercontent.com/96985911/208341378-9e40e8e7-0f12-4bb8-94db-d0822498efcc.mp4

**Comment by rmbadmin** [comment]
fix on 5509004c649082003a0ad97cae028e5be1fac8f2
