### ISSUE TITLE
🐛[BUG] 开启steam++加速后Chrome浏览器无法打开steam官网及社区

### ISSUE THREAD

**Issue by RoyFata** [BeyondDimension/SteamTools#2382]
### 🐛 描述(Description)

开启steam++加速后Chrome浏览器无法打开steam官网及社区

### 📷 复现步骤(Steps to Reproduce)

1. 
<img width="1378" alt="截屏2022-12-19 13 34 53" src="https://user-images.githubusercontent.com/95155210/208355464-b1d65dfd-0a93-4a36-b72b-52f1b627fec1.png">

2. 
<img width="1016" alt="截屏2022-12-19 13 37 04" src="https://user-images.githubusercontent.com/95155210/208355869-6fd7440d-b0d1-4a08-9563-790e4b3f744b.png">
<img width="1378" alt="截屏2022-12-19 13 35 17" src="https://user-images.githubusercontent.com/95155210/208355902-c6789618-4af6-4cde-815a-6f5f84077b16.png">

3. 
<img width="580" alt="截屏2022-12-19 13 36 51" src="https://user-images.githubusercontent.com/95155210/208355583-d3ebda47-e0e3-4ef0-983f-eb02ddd2f1bb.png">
<img width="759" alt="截屏2022-12-19 13 36 08" src="https://user-images.githubusercontent.com/95155210/208355616-5b48b0a0-b67a-4cfe-8210-d00b062ffd4c.png">
<img width="405" alt="截屏2022-12-19 13 35 28" src="https://user-images.githubusercontent.com/95155210/208355629-ae572bf3-cc7e-4203-82da-c9f1e94e3d82.png">

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.4
- 系统版本号(OS Version): macOS Ventura 13.0.1
- 是否为应用商店版本(Whether it is a Store version): NO

**Comment by RoyFata** [comment]
找到原因了，启动系统代理可以访问steam官网及其社区，但是也只能访问steam官网其他的网页全部不可用，但是启动hosts代理是反过来的，其他网页正常可用，只有steam官网及其社区网页不可用，头大

**Comment by RoyFata** [comment]
找到原因了，启动系统代理可以访问steam官网及其社区，但是也只能访问steam官网其他的网页全部不可用，但是启动hosts代理是反过来的，其他网页正常可用，只有steam官网及其社区网页不可用，头大

**Comment by rmbadmin** [comment]
> 找到原因了，启动系统代理可以访问steam官网及其社区，但是也只能访问steam官网其他的网页全部不可用，但是启动hosts代理是反过来的，其他网页正常可用，只有steam官网及其社区网页不可用，头大

更新到2.8.5再测一下看看

**Comment by RoyFata** [comment]
> > 找到原因了，启动系统代理可以访问steam官网及其社区，但是也只能访问steam官网其他的网页全部不可用，但是启动hosts代理是反过来的，其他网页正常可用，只有steam官网及其社区网页不可用，头大
> 
> 更新到2.8.5再测一下看看

okok了版本问题更新就ok了谢谢！！
