### ISSUE TITLE
🐛[BUG] 2.8.5版本下无法管理成就

### ISSUE THREAD

**Issue by CubicSalt** [BeyondDimension/SteamTools#2383]
库存游戏-右键管理成就后，下方显示启动中，然后快速弹出一个窗口后消失。Steam界面游戏显示运行中，然后立刻变为关闭状态。
回滚2.8.4版本后恢复正常。系统为Window11。

**Comment by rmbadmin** [comment]
fix on 5509004c649082003a0ad97cae028e5be1fac8f2
