### ISSUE TITLE
🐛[BUG] 此程序与COD19冲突

### ISSUE THREAD

**Issue by SakMura** [BeyondDimension/SteamTools#2386]
### 🐛 描述(Description)

Watt Toolkit与COD19冲突，关了Watt，COD19可以启动，应该是反作弊和Watt冲突。

### 📷 复现步骤(Steps to Reproduce)

开了Watt Toolkit，Steam启动COD19，过一会COD19进程自动结束。

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.8.5 for Windows (x64)
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by rmbadmin** [comment]
公告里已经说明过了，不开启dns加速即可
