### ISSUE TITLE
🐛[BUG] 在创意工坊中无法评论

### ISSUE THREAD

**Issue by YanSGod** [BeyondDimension/SteamTools#2398]
### 🐛 描述(Description)
在创意工坊中无法评论

### 📷 复现步骤(Steps to Reproduce)
1 进工坊
2 对某一项目进行评论

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.5
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): <!--是(Yes)

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/99068464/209558929-a5aab661-1d82-4bb0-9f58-2ae615d534d0.png)
### 日志
[nlog-all-2022-12-26.log](https://github.com/BeyondDimension/SteamTools/files/10303836/nlog-all-2022-12-26.log)

**Comment by YanSGod** [comment]
用小黑盒加速器就可以，steam++不行，应该是steam++本身问题

**Comment by rmbadmin** [comment]
目前仅支持自己有IPV6地址后 开启 Steam讨论/留言(IPV6) 加速项后 即可正常留言和访问讨论组，否则无法留言是正常状况。
