### ISSUE TITLE
🧐[Question] 提示“服务端错误：5002” 且 加速界面没有可选的加速项目

### ISSUE THREAD

**Issue by Ethy0** [BeyondDimension/SteamTools#2402]
### 🧐 问题描述(Description)

如题

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):2.8.6
- 系统版本号(OS Version): Linux Mint 21.1 Cinnamon （Linux内核：5.15.0-56-generic）
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by Ethy0** [comment]
![2022-12-30 21-37-54屏幕截图](https://user-images.githubusercontent.com/41030966/210076496-ea7c8b5e-f5f4-4461-9121-cd9e18c77583.png)
截图如上

**Comment by Mossimos** [comment]
![image](https://user-images.githubusercontent.com/26396340/210076773-024fe203-d785-4ee1-b4fa-d81153538438.png)
5002的定义是请求被取消了你点右手边3个点 里面的刷新试试

**Comment by Ethy0** [comment]
> ![image](https://user-images.githubusercontent.com/26396340/210076773-024fe203-d785-4ee1-b4fa-d81153538438.png) 5002的定义是请求被取消了你点右手边3个点 里面的刷新试试

![2022-12-30 21-45-55屏幕截图](https://user-images.githubusercontent.com/41030966/210076890-992800d0-b999-402b-9cfb-3840eb767586.png)
没有反应...

**Comment by Mossimos** [comment]
https://api.steampp.net/ 这个地址你能正常打开吗

**Comment by Ethy0** [comment]
> https://api.steampp.net/ 这个地址你能正常打开吗

![2022-12-30 21-49-29屏幕截图](https://user-images.githubusercontent.com/41030966/210077126-eb3ac902-5baf-4307-b983-af7a2303dba0.png)
可以的

**Comment by Mossimos** [comment]
程序的日志发下。另外 @AigioL  看看

**Comment by Ethy0** [comment]
> 程序的日志发下。另外 @AigioL 看看

[nlog-all-2022-12-30.log](https://github.com/BeyondDimension/SteamTools/files/10324977/nlog-all-2022-12-30.log)
@AigioL

**Comment by harris-hao** [comment]
我也有同样的问题，我是win10系统 22H2版本号，目前还未解决，不知道你是如何解决的呢？

**Comment by Ethy0** [comment]
> 

之后再打开软件过一会就加载出来了，我也不清楚是什么问题

**Comment by Ethy0** [comment]
> 我也有同样的问题，我是win10系统 22H2版本号，目前还未解决，不知道你是如何解决的呢？

之后再打开软件过一会就加载出来了，我也不清楚是什么问题
