### ISSUE TITLE
🐛[BUG] macOS Ventura 无法导出本地令牌

### ISSUE THREAD

**Issue by iforgetmyname** [BeyondDimension/SteamTools#2403]
### 🐛 描述(Description)

macOS Watt Toolkit在本地令牌页面点击导出后，arm版本无响应，x64版本直接crash

### 📷 复现步骤(Steps to Reproduce)

1. 侧边栏进入本地令牌页面
2. 在有本地令牌的情况下，点击上方导出按键
3. arm版本进入无限转圈圈，x64软件直接退出

### 📄 日志信息(Log Information)

无相关日志内容

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.8.4-2.8.6 arm及x64(rosetta转译) 共六个版本全部测试过
- 系统版本号(OS Version):  macOS Ventura 13.1 (22C65)
- 是否为应用商店版本(Whether it is a Store version):  否

### 🖼 截图(Screenshots)

<img width="1267" alt="截屏2022-12-30 21 45 38" src="https://user-images.githubusercontent.com/14368888/210076825-4a39227a-d39c-4743-8103-31699ae14186.png">

**Comment by Mossimos** [comment]
这个是已知问题 ，包括加密窗口 也会闪退目前得等待重构一起解决。

**Comment by iforgetmyname** [comment]
啊这，有大概时间么？我想转移一下令牌到另外一台电脑现在束手无策

**Comment by Mossimos** [comment]
打开Appdata复制里面全部内容到另一台机器应该可以

**Comment by iforgetmyname** [comment]
哦哦好的我试一下，谢谢！
