### ISSUE TITLE
🧐[Question] MacOS 13.0.1 (22A400) 报错 "应用程序“Steam++”无法打开。"

### ISSUE THREAD

**Issue by ShadowWaIker** [BeyondDimension/SteamTools#2414]
### 🧐 问题描述(Description)

MacOS 13.0.1 (22A400) 报错 "应用程序“Steam++”无法打开。"

已经尝试过 ARM 版、X64 版，报错一样。

已经尝试过 `sudo spctl --master-disable` 禁用安全设置，禁用后依旧报错。

已经尝试过 `sudo chmod +x /Applications/Steam++.app/Contents/MacOS/Steam++` 修复权限，修复后依旧报错。

### 🚑 其他信息(Other Information)

![WX20230105-104031@2x](https://user-images.githubusercontent.com/10329893/210691374-28045cfa-e152-4146-8d11-1861db924e46.png)

- 程序版本(Program Version): Steam++_macos_arm64_v2.8.6.dmg、Steam++_macos_x64_v2.8.6.dmg
- 系统版本号(OS Version): MacOS 13.0.1 
- 是否为应用商店版本(Whether it is a Store version): 否(No)

**Comment by David-Xian66** [comment]
确认下载文件完整吗？

**Comment by ShadowWaIker** [comment]
文件是完整的，可以正常打开dmg，Checksum也是正确的

我获取到的是
`shasum -a 256 Steam++_macos_arm64_v2.8.6.dmg
772cfb10035f5dc290aa6a1e6f373826db4f45e8bd65e4d06083e4973b576dad`

Release 页面贴的 Checksum 是
Steam++_macos_arm64_v2.8.6.dmg | 772CFB10035F5DC290AA6A1E6F373826DB4F45E8BD65E4D06083E4973B576DAD
-- | --

**Comment by Mossimos** [comment]
1. 打开 Steam++ 出现提示弹窗
2. 打开  系统设置 
3. 隐私与安全性
4. 看看最下面是否有 xxx 未知程序 然后有个任然打开
![image](https://user-images.githubusercontent.com/26396340/211253398-08291a36-66e0-468b-b485-911dcb383d78.png)
在这一块选项
mac 13.x 设置Ui都改了

**Comment by ShadowWaIker** [comment]
> 1. 打开 Steam++ 出现提示弹窗
> 2. 打开  系统设置
> 3. 隐私与安全性
> 4. 看看最下面是否有 xxx 未知程序 然后有个任然打开
>    ![image](https://user-images.githubusercontent.com/26396340/211253398-08291a36-66e0-468b-b485-911dcb383d78.png)
>    在这一块选项
>    mac 13.x 设置Ui都改了

  没有仍然打开的提示哦
![WX20230109-151010@2x](https://user-images.githubusercontent.com/10329893/211256564-112bbe08-2797-4456-b2bc-eae928eda848.png)

就算我打开“任何来源”的选项，也没有提示打开
![WX20230109-150904@2x](https://user-images.githubusercontent.com/10329893/211256646-ce2000d3-6c49-4489-8fd7-a23534ebfaec.png)

**Comment by ShadowWaIker** [comment]
解决了，执行下面这个命令之后就能打开了

`sudo xattr -rd com.apple.quarantine /Applications/Steam++.app`

**Comment by Mossimos** [comment]
![image](https://user-images.githubusercontent.com/26396340/211265454-b69eee95-ab81-417c-bb1b-1fc75a07685c.png)
正常应该提示这个。
我用来签发的证书 是在 2023年5月过期才对。
你这行命令是删除证书
