### ISSUE TITLE
内存占用过高🐛[BUG] 

### ISSUE THREAD

**Issue by flycran** [BeyondDimension/SteamTools#2423]
### 🐛 描述(Description)
内存占用过高，超过2GB，并且不是个例，而是经常出现。并且我仅使用了该软件的【网络加速】功能

### 📷 复现步骤(Steps to Reproduce)

无法复现/未知原因

### 📄 日志信息(Log Information)

[nlog-all-2023-01-09.log](https://github.com/BeyondDimension/SteamTools/files/10372227/nlog-all-2023-01-09.log)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):

<img width="290" alt="image" src="https://user-images.githubusercontent.com/86134803/211285919-2fd55509-28b4-4865-93ae-ea64fa0ce466.png">

- 系统版本号(OS Version): Windows 11 专业版 22H2

- 是否为应用商店版本(Whether it is a Store version): yes

### 🖼 截图(Screenshots)

描述已经很清楚了

**Comment by TheQYQ** [comment]
不知道，会不会是图形gui的原因

**Comment by flycran** [comment]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/86134803/226072248-51c35528-d3de-4dd5-8e0e-7a110d0b90f7.png">

**Comment by flycran** [comment]
这个bug不管了吗？

**Comment by rmbadmin** [comment]
这种bug不确定原因之前很难修复，现在推倒重来彻底重构新版本，看新版本之后是否会依然存在吧

**Comment by flycran** [comment]
> 这种bug不确定原因之前很难修复，现在推倒重来彻底重构新版本，看新版本之后是否会依然存在吧

好的好的

**Comment by David-Xian66** [comment]
期待！

> 这种bug不确定原因之前很难修复，现在推倒重来彻底重构新版本，看新版本之后是否会依然存在吧

**Comment by Roc136** [comment]
后台持续运行时间太久就会出现内存占用过高的情况，可能存在内存泄漏。另外，恢复前台后内存恢复，猜测可能是某些内存释放操作只在前台时才被执行。
