### ISSUE TITLE
整个加速界面消失🧐[Question] 

### ISSUE THREAD

**Issue by Namaste8537** [BeyondDimension/SteamTools#2441]
### 🧐 问题描述(Description)

从github下载，8月份使用正常，12月某天发现加速界面消失，此后再也没重新出现，卸载重装后依然没有解决，进入软件始终找不到加速界面

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/122426374/211724058-9ea5bf79-e391-4963-aab3-8d6bd8246fa9.png)

- 程序版本(Program Version): win_x64_v2.8.6
- 系统版本号(OS Version): Windows 10 Pro 21H2 19044.2364 Windows Feature Experience Pack 120.2212.4190.0
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by SuperChenSSS** [comment]
我也遇到了相同的问题

**Comment by nathanlcl** [comment]
我也出现过这个问题，我当时是把steam的语言和地区改到美国了，改回来就有出现了

**Comment by uzvg** [comment]
我也是

**Comment by Mossimos** [comment]
尝试下切换语言，或者设置 通用设置 打开 Appdata 文件夹删除其中 Config.mpo 尝试看是否解决（如有令牌等需要先备份下文件）

**Comment by Namaste8537** [comment]
> 尝试下切换语言，或者设置 通用设置 打开 Appdata 文件夹删除其中 Config.mpo 尝试看是否解决（如有令牌等需要先备份下文件）

已解决，非常感谢。
我改了语言，删除了Config.mpo，Config.mpo.bak，所有log和cache，最后退出程序重新打开就出现了加速界面。另外Appdata文件夹多出了一个LOCAL_ACCELERATE.json，其消失应该是问题出现的原因。
