### ISSUE TITLE
🧐[Question] Deepin系统下使用Watt Toolkit加速提示隐私错误

### ISSUE THREAD

**Issue by postyizhan** [BeyondDimension/SteamTools#2453]
### 🧐 问题描述(Description)
Deepin系统下使用Watt Toolkit加速 edge浏览器访问加速网站时弹出隐私错误

具体内容如下：
你的连接不是专用连接
攻击者可能试图从 discordapp.com 窃取你的信息(例如，密码、消息或信用卡)。
NET::ERR_CERT_AUTHORITY_INVALID

做过的尝试：
打开证书文件夹手动删除两个证书后点击安装证书并刷新，工具中仅有上行流量，无下行流量
此时edge浏览器页面提示 细节：此时证书文件夹中只有SteamTools.Certificate.cer
嗯… 无法访问此页面似乎 discordapp.com 关闭了连接

接着，关闭浏览器和Watt Toolkit 重新启动
在Watt Toolkit中重新安装证书并刷新，启动加速，访问Discord 爆出隐私错误
具体内容如下：
你的连接不是专用连接
攻击者可能试图从 discordapp.com 窃取你的信息(例如，密码、消息或信用卡)。
NET::ERR_CERT_AUTHORITY_INVALID
使用Deepin自带的证书查询工具加载不出
![image](https://user-images.githubusercontent.com/97342038/212532335-c40da7ca-8712-4755-aa07-cbecc977434b.png)
打开网页 https://myssl.com/cert_decode.html 进行证书查询
SteamTools.Certificate.cer 查询结果如下
![image](https://user-images.githubusercontent.com/97342038/212532575-3e31a824-24f8-4261-9b49-dd412f456c0d.png)
SteamTools.Certificate.pfx 查询结果如下
解析 PEM 证书文件失败

- 程序版本(Program Version):2.8.6β for linux
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by Mossimos** [comment]
https://steampp.net/liunxSetupCer

**Comment by postyizhan** [comment]
> 

您好，我仔细阅读了链接中的内容，貌似与我的问题并不符合？

**Comment by Mossimos** [comment]
pfx是windows iis使用的证书  
![image](https://user-images.githubusercontent.com/26396340/212533093-1229771d-3c7b-48f7-bf3d-0e932b2648b3.png)

**Comment by Mossimos** [comment]
导入浏览器受信任的颁发机构就行了
这是每台机器自己生成的证书

**Comment by postyizhan** [comment]
> 导入浏览器受信任的颁发机构就行了 这是每台机器自己生成的证书

抱歉又来打扰，我摸索了一会并没有搞明白，您是指让我使用openssl命令将cer转为pem然后在edge浏览器的设置-隐私、搜索和服务-管理证书 将这个证书导入吗？我导入的时候只有cer的那个可以选择，导入后尝试仍然是隐私错误

**Comment by Mossimos** [comment]
直接改文件后缀名就行了   导入后完全关闭后再开就会显示正常了。

**Comment by postyizhan** [comment]
> 直接改文件后缀名就行了 导入后完全关闭后再开就会显示正常了。

我按照您说的尝试导入，但是报错，内容如下

证书导入错误
此客户端证书的私钥缺失或无效

**Comment by Mossimos** [comment]
那你尝试下用 openssl 转换下试试

**Comment by postyizhan** [comment]
> 

尝试过也是不行的

**Comment by Mossimos** [comment]
那应该证书是有问题的吧。删除重新生成一个呢

**Comment by postyizhan** [comment]
> 那应该证书是有问题的吧。删除重新生成一个呢

重新生成也试过了，结果相同

**Comment by Mossimos** [comment]
那你吧证书压缩发我看看

**Comment by postyizhan** [comment]
[证书.zip](https://github.com/BeyondDimension/SteamTools/files/10419932/default.zip)

**Comment by Mossimos** [comment]
这个证书我导入浏览器 Macos 和 Linux 都是正常的

**Comment by Mossimos** [comment]
请问你使用的是什么浏览器

**Comment by postyizhan** [comment]
> 请问你使用的是什么浏览器

是微软的edge浏览器

**Comment by postyizhan** [comment]
> 这个证书我导入浏览器 Macos 和 Linux 都是正常的

我尝试了下Deepin自带的浏览器，虽然还是报链接不是安全的，但是我可以选择继续访问

**Comment by Mossimos** [comment]
![image](https://user-images.githubusercontent.com/26396340/212537386-fe3f3be5-62d8-4e15-bc1a-2ac3deb95918.png)

**Comment by Mossimos** [comment]
![image](https://user-images.githubusercontent.com/26396340/212537393-f0acf636-2ede-4339-84a2-1798b196c4d9.png)
是这样导入的吗

**Comment by postyizhan** [comment]
> ![image](https://user-images.githubusercontent.com/26396340/212537393-f0acf636-2ede-4339-84a2-1798b196c4d9.png) 是这样导入的吗

原来是我一直在犯傻！抱歉浪费您这么多时间，谢谢您，可以用了

**Comment by Mossimos** [comment]
![image](https://user-images.githubusercontent.com/26396340/212541397-043bc90a-b9d9-428d-ab95-02620e77fc9e.png)
给你的链接写明了是这样导入的啊。。。

**Comment by javatheaabackgroundbosses** [comment]
mac 需要怎么导入，我按照文档的提示将cer改成了pem，然后在密钥里面手动导入了一下，是这么操作吗
