### ISSUE TITLE
建议增加安全加密

### ISSUE THREAD

**Issue by sususgh** [BeyondDimension/SteamTools#2461]
游戏在加速过程当中没有安全加密
容易被其他人盗取账号
建议增加启动时的安全加密

**Comment by CodeMan-cmd** [comment]
已经被盗了我，感觉这是

**Comment by rmbadmin** [comment]
我不太明白你说的安全加密是指什么，加速过程的安全最重要的是保护好自己本机随机生成的ssl证书不要泄露
