### ISSUE TITLE
🐛[BUG] Mac版加速部分网站会出现https相关错误

### ISSUE THREAD

**Issue by xulu199705** [BeyondDimension/SteamTools#2464]
### 🐛 描述(Description)
Mac版加速部分网站会出现https相关错误
使用Chrome打开Pixiv和Github时，会出现如下错误提示，无法正常访问网站，Windows版本目前没有遇到相同问题。
```
NET::ERR_CERT_AUTHORITY_INVALID
Subject: www.pixiv.net
Issuer: SteamTools Certificate
Expires on: 2024年1月20日
Current date: 2023年1月20日
```

### 📷 复现步骤(Steps to Reproduce)

1. 加速Pixiv和Github
2. 使用Chrome打开相应网站

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): arm64 v2.8.6 $\beta$ macOS
- 系统版本号(OS Version): macOS Ventura 13
- 是否为应用商店版本(Whether it is a Store version): 否(No)

### 🖼 截图(Screenshots)

<img width="621" alt="image" src="https://user-images.githubusercontent.com/17242727/213678684-b2f895bf-54f8-4131-9de5-c38e5f0f4f78.png">

**Comment by Mossimos** [comment]
请看 #2376 这个问题中的回复。 下个版本会修复这个问题
将命令中的这段 `/Users/{Environment.UserName}/Library/Keychains/login.keychain-db` 替换成 `/Library/Keychains/System.keychain`  执行就能安装到系统证书目录了
