### ISSUE TITLE
🧐[Question] 请问如何下载Discord桌面应用？

### ISSUE THREAD

**Issue by lzy20091001** [BeyondDimension/SteamTools#2499]
### 🚑 其他信息(Other Information)

- 程序版本(Program Version): 2.8.6 for Windows Desktop Bridge (x64)
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by CDmking** [comment]
https://discord.onl/zh/discord%e4%b8%8b%e8%bc%89/

**Comment by lzy20091001** [comment]
万分感谢！
