### ISSUE TITLE
🐛[BUG] 上传下载图卡死

### ISSUE THREAD

**Issue by TianMengLucky** [BeyondDimension/SteamTools#2501]
### 🐛 描述(Description)
开始加速后，上传和下载中图不显示只有加速时间在跳动，也不加速的状态

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.6
- 系统版本号(OS Version): windows11
- 是否为应用商店版本(Whether it is a Store version): 是(Yes)

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/107238739/215317811-a76f7c77-6732-4c66-b74c-ea20c54d5b5e.png)

**Comment by CDmking** [comment]
此问题是否已解决？若否，请尝试更换其他版本（如将Store版本更换为安装版本或自解压版本）。
