### ISSUE TITLE
🐛[BUG] 开启加速后无法访问Mega

### ISSUE THREAD

**Issue by wyivz** [BeyondDimension/SteamTools#2516]
### 🐛 描述(Description)
启用steam++内的那几个加速Mega的选项后，网页访问mega，会卡在不停地转圈的界面。几个不同的加速模式都试过了，似乎都不行。

### 📷 复现步骤(Steps to Reproduce)
运行steam++，浏览器输入网址mega.nz

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): v2.8.6
- 系统版本号(OS Version): Win11 22H2
- 是否为应用商店版本(Whether it is a Store version): 否。官网版本

**Comment by AHKR-y** [comment]
同问，我这里是点击网址链接https://mega.nz/folder/xxxxxx，也是一样卡”正在请求网盘文件资源“转圈
计算机系统是win10，其他一样

**Comment by AHKR-y** [comment]
同问，我这里是点击链接https://mega.nz/folder/xxxxxx
也是一样卡”正在请求网盘文件资源“转圈
计算机系统是win10，其他一样

**Comment by rmbadmin** [comment]
已热更新修复
