### ISSUE TITLE
🧐[Question] 2.8.6 版本是否已经移除了二级代理这一功能？

### ISSUE THREAD

**Issue by TaoRone** [BeyondDimension/SteamTools#2523]
### 🧐 问题描述(Description)
今天发现steam++的脚本功能很好用……于是试了试，发现和V2冲突。
查看以往issue发现很久之前添加了二级代理功能。
但是2.8.6版本并未找到。
是不是已经移除了这一功能？
如果移除了这一功能，是否已有替代方案？
谢谢大大们~~~

**Comment by rmbadmin** [comment]
因为2.8.6修改了底层代理的库，所以二级代理需要重新实现以下，目前还未实现所以暂且移除了
