### ISSUE TITLE
能否加入加速google👑[Enhancement] 

### ISSUE THREAD

**Issue by TurtleLemon** [BeyondDimension/SteamTools#2524]
虽然国内对google的管控较严，但是有些程序员经常会用到google里的功能，就比如colab，colab可以提供免费的临时服务器以运行ipynb文件，每次使用时需要翻墙，极其麻烦，想通过修改hosts访问但网上找不到一个能用的，希望作者考虑一下

**Comment by HX-Technology-LLC** [comment]
Google这种直接封IP的方法除了靠代理服务器转发不然没法上把

**Comment by MIllI0N-IllUSI0N** [comment]
你可以ping得通软件内提供的那些网站的ip但绝对ping不通谷歌的，这就不是在本地处理一下就能解决的，想上去就只有梯子一种方法。梯子先不说服务器费用谁出，最主要的是，在CN你要是敢光明正大地提供梯子绝对是要被请去喝茶的。

**Comment by MangoGong** [comment]
我个人认为现在能加速pixiv啥的已经是极限了，在往上去就变成梯子了吧。

**Comment by UjuiUjuMandan** [comment]
```
142.250.27.90
142.251.0.90
142.251.1.90
142.251.111.90
142.251.112.90
142.251.117.90
142.251.12.90
142.251.120.90
142.251.160.90
142.251.161.90
```

扫描到类似上述的GWS IP之后把SNI改成类似 `www.google.cn` 这样的就行了。实现不了就是作者水平不够。
