### ISSUE TITLE
这是不是内存溢出了🐛[BUG] 

### ISSUE THREAD

**Issue by Katie-i** [BeyondDimension/SteamTools#2537]
### 🐛 描述(Description)
正常情况下占用也就几百MB，但这个属实不正常，程序是后台挂着的，前台打开看了下然后过会正常了

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 📄 日志信息(Log Information)
没有今天的日志

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.8.6 for Windows Desktop Bridge x64
- 系统版本号(OS Version): Windows 11 22623.1255
- 是否为应用商店版本(Whether it is a Store version): 是

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/76895191/218293982-67baa0d7-fcc5-4315-88ff-bed339293215.png)
<img width="740" alt="image" src="https://user-images.githubusercontent.com/76895191/218294060-bb47d4ba-3217-435c-9ea2-7515ba2616bd.png">

**Comment by rmbadmin** [comment]
重复 #2708
