### ISSUE TITLE
英文bug

### ISSUE THREAD

**Issue by Abel2333** [BeyondDimension/SteamTools#2658]
把语言切换为英文后，重启软件，就会发现加速选项消失了
![20230311094327](https://user-images.githubusercontent.com/45725694/224458320-c71eb334-2b8b-4019-93f5-e0921d754330.png)

同时，个人资料界面也不能正确排版，最下方的按钮无法显示在页面中，也没有滚轮
![QQ图片20230311094351](https://user-images.githubusercontent.com/45725694/224458331-020490d5-a45a-40f2-9fba-25e4fa44f55e.png)

**Comment by Mossimos** [comment]
加速选项消失 是除了简中区域需要加速功能 其他语言的区域基本都正常访问不需要加速功能所以屏蔽的
1. 非简中语言将默认隐藏加速和脚本功能，仅能通过切换语言并重启程序的方式还原被隐藏的功能

**Comment by Abel2333** [comment]
这样啊，好的，那没事了
