### ISSUE TITLE
ASF更新到最新版5.4.3.2后无法使用

### ISSUE THREAD

**Issue by inory121** [BeyondDimension/SteamTools#2659]
ASF版本：5.4.3.2
steam++版本：2.8.6
第一个问题是ASF检查不了更新
![image](https://user-images.githubusercontent.com/35392664/224524611-bf936371-d46c-414b-9046-39334fb337b0.png)
第二个无法挂卡
![image](https://user-images.githubusercontent.com/35392664/224524685-0498201f-0d97-4592-9b14-ddcbc9518af7.png)
尝试过重新安装证书无效，使用302工具不会出现上述问题

**Comment by AigioL** [comment]
2.8.6 中嵌入的 ASF 版本为 5.3.2.4
最近发布的几个版本也采用的单文件部署的形式，你是如何更新到 5.4.3.2 的？

现在的版本在 ASF 源码的基础上修改了一些内容嵌入进来的，所以也是不支持更新的
下一个大版本 3.0 中计划将 ASF 作为独立模块使用，这种方式才能使用 ASF 的更新功能

**Comment by inory121** [comment]
我用的独立ASF，不是steam++内嵌的
