### ISSUE TITLE
🧐[Question] 请问最近突然无法打开程序，启动程序后无反应

### ISSUE THREAD

**Issue by OreoProMax** [BeyondDimension/SteamTools#2687]
### 🧐 问题描述

打开程序后无反应，任务管理器也没有任何watt相关进程。重启无效，卸载重新安装无效。之前一直正常使用，也没什么操作。

- 处理器体系结构：x64
- 系统版本号：Win11 22H2 （22621.1413）
- 下载渠道：gitee仓库
- 程序版本：2.8.6
- 是否包含独立运行时：文件名中带有 with_runtime 或 不包含 fde

**Comment by rmbadmin** [comment]
尝试清除一下程序的config.mpo文件重启程序

**Comment by OreoProMax** [comment]
清除一下程序的config.mpo文件重启程序
