### ISSUE TITLE
网络被限制在3Mbps左右

### ISSUE THREAD

**Issue by wangdongdong9264** [BeyondDimension/SteamTools#2688]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

很奇怪 家里的网络是100M，拿手机测试也接近100M
电脑上就只要这一个加速器 想问一下你们有做限制过网络速率吗
有可能触发了bug

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：example Windows 10.19045.2728(see winver) 
- 下载渠道： 微软商店  
- 程序版本：2.8.6 
- 是否包含独立运行时：

**Comment by rmbadmin** [comment]
没有做过任何限制
