### ISSUE TITLE
希望加速可以对YouTube

### ISSUE THREAD

**Issue by ghost** [BeyondDimension/SteamTools#2691]
希望以后的版本可以对油管进行加速支持。

**Comment by Catiks** [comment]
> 希望以后的版本可以对油管进行加速支持。

还是翻墙吧

**Comment by localmt** [comment]
> 希望以后的版本可以对油管进行加速支持。

买翻墙软件吧，出了也是需要付费的。

**Comment by IzayoiAster** [comment]
> 希望以后的版本可以对油管进行加速支持。

要是这么简单，那还要机场干什么。而且现在这个项目还算是安全的，要是真能给油管加速了，作者在国内就不妥了

**Comment by wyivz** [comment]
https://github.com/URenko/Accesser 
https://github.com/URenko/Accesser/issues/115
可以尝试使用SNI-RST Accesser这个东西

**Comment by GentsunCheng** [comment]
这软件只支持加速被SNI阻断的网站，youtube这种直接拦截ip的加速不了

**Comment by PandaFiredoge** [comment]
你妈死了，傻逼，滚
