### ISSUE TITLE
希望增加对于Wikipedia 维基百科的支持

### ISSUE THREAD

**Issue by liamwu-workspace** [BeyondDimension/SteamTools#2697]
rt

**Comment by giegie12** [comment]
666,你想让作者坐牢？

**Comment by WindSakura** [comment]
不如去找央视拿个7890的端口冲XDD

**Comment by zxcv-12345** [comment]
你为什么不说如何送人家去喝茶得了........

**Comment by LSP0123** [comment]
wikipedia同样是SNI阻断，我不知道为什么楼上几位都在说想让作者坐牢。

**Comment by zxcv-12345** [comment]
> wikipedia同样是SNI阻断，我不知道为什么楼上几位都在说想让作者坐牢。

笑死，这已经不是什么类型的阻断问题和实现难度大不大的事了，好好的Steam store tools整这东西，是想让墙国粉红举报致死是吧？？？

**Comment by LSP0123** [comment]
> > wikipedia同样是SNI阻断，我不知道为什么楼上几位都在说想让作者坐牢。
> 
> 笑死，这已经不是什么类型的阻断问题和实现难度大不大的事了，好好的Steam store tools整这东西，是想让墙国粉红举报致死是吧？？？

快笑死建议去医院，如果不会友好评论和好好说话的话也请去医院挂脑科

**Comment by liamwu-workspace** [comment]
> wikipedia同样是SNI阻断，我不知道为什么楼上几位都在说想让作者坐牢。

所以是这一类的都构不成违法是吗？有没有类似的工具推荐下哈哈哈

**Comment by rmbadmin** [comment]
关于wiki是不会考虑添加的
