### ISSUE TITLE
🧐[Question] 请输入标题

### ISSUE THREAD

**Issue by cnbinwang** [BeyondDimension/SteamTools#2698]
## 请认真检查以下清单中的每一项
- [ ] 已经搜索过，没有发现类似的 issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🚑 其他信息

- 处理器体系结构：<!-- x64 >
- 系统版本号：- example Windows 25324.1000(see winver)
- 下载渠道：<!-- 微软商店 />
- 程序版本：- 2.8.6
- 是否包含独立运行时- 文件名中带有 with_runtime -

**Comment by cnbinwang** [comment]
在设置里网络重置后恢复了

**Comment by Mossimos** [comment]
系统代理模式  关闭程序  代理设置可能没有还原。其系统网络设置把代理关了就行了
