### ISSUE TITLE
🧐[Question] v3.x 分支无法完成编译

### ISSUE THREAD

**Issue by arenekosreal** [BeyondDimension/SteamTools#2701]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述
使用 v3.x 分支的源码，按照 [CI.yml](https://github.com/BeyondDimension/SteamTools/blob/v3.x/.github/workflows/CI.yml) 的步骤尝试编译，但出现错误：
```
CSC : error AXN0002: XamlX.XamlParseException: Unable to resolve type DebugPageViewModel from namespace https://steampp.net/ui Line 11, position 4. [/build/watt-toolkit-git/src/SteamTools/src/BD.WTTS.Client.Avalonia.App/BD.WTTS.Client.Avalonia.App.csproj::TargetFramework=net7.0]
/build/watt-toolkit-git/src/SteamTools/src/BD.WTTS.Client.Avalonia.App/UI/Views/Pages/DebugPage.axaml.cs(4,54): error CS0246: The type or namespace name 'DebugPageViewModel' could not be found (are you missing a using directive or an assembly reference?) [/build/watt-toolkit-git/src/SteamTools/src/BD.WTTS.Client.Avalonia.App/BD.WTTS.Client.Avalonia.App.csproj::TargetFramework=net7.0]

```
看起来是 https://steampp.net/ui 这个命名空间不可用导致的

### 🚑 其他信息

尝试使用这个 PKGBUILD 在 chroot 环境下完成构建：
[watt-toolkit-pkgbuild.tar.gz](https://github.com/BeyondDimension/SteamTools/files/11360588/watt-toolkit-pkgbuild.tar.gz)
因为看到了v3.x 分支再加上 watt-toolkit-git 这个 AUR 软件包的构建脚本需要修复，所以把两件事合并在一起来搞了

- 处理器体系结构： x64
- 系统版本号： ArchLinux
- 下载渠道： GitHub 源代码
- 程序版本： v3.x 分支源代码
- 是否包含独立运行时： N/A

**Comment by AigioL** [comment]
v3.x 分支还在开发中，目前还没有可用的预览版

**Comment by arenekosreal** [comment]
20230711 测试 de2faef6b 提交已经可以完成构建，因此关闭此 issue

**Comment by Neubulae** [comment]
`~/.cache/paru/clone/watt-toolkit-git/src/SteamTools/src/BD.WTTS.UnitTest/CertificateUnitTest.cs(1,14): error CS0234: 命名空间“System”中不存在类型或命名空间名“DirectoryServices”(是否缺少程序集引用?) [~/.cache/paru/clone/watt-toolkit-git/src/SteamTools/src/BD.WTTS.UnitTest/BD.WTTS.UnitTest.csproj::TargetFramework=net7.0]`
这个是当前最新提交的问题，有没有哪个提交适合构建
