### ISSUE TITLE
突然无法连接至Discord

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [BeyondDimension/SteamTools#2705]
### 请认真检查以下清单中的每一项
- [√] 已经搜索过，没有发现类似的 issue
- [√] 已经搜索过文档，没有发现相关内容
- [√] 已经尝试使用过最新版，问题依旧存在
- [√] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述
(使用加速模式： Hosts代理)
昨天之前都能直接用校园网开Watt连接到discord，昨天开始就突然不行了，本来以为是敏感日不让连，结果今天开了还是连不上，discord.com显示：
Request:Could not find any IP that can be successfully connected. (HTTP connection to 162.159.138.232 timed out.) (HTTP connection to 168.143.162.58 timed out.) (discord.com:443)
然后我昨天用我手机数据来开电脑端Watt，连接discord上去了，但是今天就突然不能连了，连手机端的Watt上discord也是基本上进不去

### 🚑 其他信息
![image](https://github.com/BeyondDimension/SteamTools/assets/22123964/37177ef3-b855-451a-8b7e-632bdb1ff6db)
![image](https://github.com/BeyondDimension/SteamTools/assets/22123964/9a239b9d-ed1e-4e75-914e-fe163ab73677)

- 处理器体系结构：x64
- 系统版本号：Windows 11 
- 下载渠道：微软商店 / Github 都试过了
- 程序版本：2.8.6
- 是否包含独立运行时：否

**Comment by Walker0501** [comment]
+1

**Comment by laopiao98** [comment]
我和我身边8个朋友同时都上不去   服务器出问题了？

**Comment by CXZom** [comment]
同

**Comment by laopiao98** [comment]
救命

**Comment by rmbadmin** [comment]
应该已经修复了，重新加速试一下
