### ISSUE TITLE
🐛[BUG] 内存泄漏 开启加速一天后，内存达到惊人的900M.

### ISSUE THREAD

**Issue by RemMai** [BeyondDimension/SteamTools#2708]
## 请认真检查以下清单中的每一项
- [ ] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
1. 软件在开启加速的情况下，放置一天，从最开始的200M内存占用到现在的900M内存占用，发现应该是内存泄漏。
2. 经过下方问题复现中描述的步骤操作后，发现每次启动加速，会发生内存逐步增加。应该是有内存没有释放的问题。

### 📷 复现步骤

1. 打开任务管理器，观察软件内存，200M
4. 打开加速 - 等待1~5s - 关闭加速    【重复这三步】
5. 发现内存偶尔增加5M，多次重复后，发现内存逐渐增加，

### 📄 日志信息
<!--
```
- 日志文件所在文件夹路径
    - Microsoft Store ```%USERPROFILE%\AppData\Local\Packages\4651ED44255E.47979655102CE_k6txddmbb6c52\LocalCache\Logs```
    - Windows ```\Logs``` or ```%Tmp%\Steam++\Logs```
    - macOS ```~/Library/Caches/Steam++/Logs```
    - Linux ```$XDG_CACHE_HOME/Steam++/Logs``` or ```$HOME/.cache/Steam++/Logs```
    - Android ```/data/data/net.steampp.app/cache/Logs```
你的日志内容


### 🖼 截图


### 🚑 其他信息

**Comment by RemMai** [comment]
测试，感觉和统计流量的二维折线图有关系，每次关闭的时候，也没有清理之前的折线图数据，

**Comment by rmbadmin** [comment]
> 测试，感觉和统计流量的二维折线图有关系，每次关闭的时候，也没有清理之前的折线图数据，

感谢告知，我之后会仔细检查下这部分

**Comment by kaxifakl** [comment]
![image](https://github.com/BeyondDimension/SteamTools/assets/63728902/12496925-ed62-40c9-8a52-bfa6f81c82f3)
这是我这的，内存一直变大

**Comment by QAQosuy** [comment]
![image](https://github.com/BeyondDimension/SteamTools/assets/41537133/42625530-0eb1-46c6-9208-57e3840acaf8)
应该是BUG，资源管理器没有流量统计，软件依旧有1mb的流量波动，折线统计图会调用显卡渲染，积增内存占用。

**Comment by wuwawo** [comment]
运行内存占用7G，恐怖

**Comment by kohroy** [comment]
一直挂在后台，没有开启任何加速，内存占用9G。

**Comment by rmbadmin** [comment]
目前看来原因应该与图表绘制有关 https://github.com/beto-rodriguez/LiveCharts2/issues/1080

**Comment by kaxifakl** [comment]
> 目前看来原因应该与图表绘制有关 [beto-rodriguez/LiveCharts2#1080](https://github.com/beto-rodriguez/LiveCharts2/issues/1080)

这个问题大概什么时候可以修复

**Comment by rmbadmin** [comment]
> > 目前看来原因应该与图表绘制有关 [beto-rodriguez/LiveCharts2#1080](https://github.com/beto-rodriguez/LiveCharts2/issues/1080)
> 
> 这个问题大概什么时候可以修复

3.0新版本应该已经解决此问题

**Comment by kaxifakl** [comment]
> > > 目前看来原因应该与图表绘制有关 [beto-rodriguez/LiveCharts2#1080](https://github.com/beto-rodriguez/LiveCharts2/issues/1080)
> > 
> > 
> > 这个问题大概什么时候可以修复
> 
> 3.0新版本应该已经解决此问题

有下载链接吗？还是说要自己build？

**Comment by f2m4** [comment]
希望解决。。。。 内存小的用起来体验不好。

**Comment by wyivz** [comment]
3.0版本什么时候能公开release？目前各下载渠道的最新版仍然是是2.8.6
