### ISSUE TITLE
👑[Enhancement] 64位版本安装目录仍为program files x86

### ISSUE THREAD

**Issue by swift-lee** [BeyondDimension/SteamTools#271]
### 🥰 需求描述(Description)
64位版本安装目录仍为program files x86

### 🚑 其他信息(Other Information)
![image](https://user-images.githubusercontent.com/57428138/120910657-21983180-c6b3-11eb-81f6-4fcf0d8f988c.png)

**Comment by AigioL** [comment]
因为之前可能有旧版本安装在这个目录上，所以改也不合适

**Comment by swift-lee** [comment]
> 因为之前可能有旧版本安装在这个目录上，所以改也不合适

但是吧，换安装目录好像大多数不能继承的设置都不是那么重要，最需要继承的设置是令牌，还需要手动导出。当然也不是什么大问题（可能问题都算不上），只是不太符合我的认识，所以来提一下，新用户的安装目录可以改成正确的目录

**Comment by AigioL** [comment]
@Mossimos 安装包应该有写注册表，之前安装的位置应该是写入某个值了，默认安装路径能改成 有旧版本则使用旧版本安装路径，无旧版本时默认路径 ```C:\Program Files``` 安装包能整成 64 位的么？

```Program Files``` 这个文件夹，好像 32 位的会重定向到 ```C:\Program Files (x86)```
只能通过字符串截取的方式改成 ```C:\Program Files``` ？

**Comment by jimstar06** [comment]
按照规范，用户数据是不能写入%ProgramFiles%的（这个变量自动适应32/64位），这个目录的内容在安装完成之后就应保持只读状态。生成的令牌数据、用户配置文件等应该放在%APPDATA%（单用户）或%ProgramData%（所有用户，推荐用这个）下。如果是CEF缓存那种可以随时丢弃的数据应该放在%TEMP%下。
如果希望同时支持portable应用模式，安装程序可以在安装时在%ProgramFiles%写一个配置将产生的数据放置到规范目录。

**Comment by AigioL** [comment]
因为安装程序是 32 位的所以这个目录默认是 ```Program Files (x86)```
有用户有便携版的需求，比如他安装在 U 盘上，然后在多台机子上使用的场景（不一定用 7z 包也许用 exe 的安装包）
所以目前将 AppData 与 Cache 目录放在根目录上

Android / iOS & macOS / WinStore 倒是用的 https://docs.microsoft.com/zh-cn/xamarin/essentials/file-system-helpers 这个 API 分开放了
Linux 上之前也是放在根目录上，后面改成 XDG 规范了

要彻底解决这个问题，安装程序得改用 64 位 版本
然后安装版要与便携版独立才能将这两个文件夹移入 LocalApplicationData 与 Temp
看 NSIS 安装后写注册表的安装路径与当前路径匹配就是安装版，读下注册表应该可行
