### ISSUE TITLE
🧐[Question] 向开发者问个好和一些问题

### ISSUE THREAD

**Issue by kikilloy** [BeyondDimension/SteamTools#2710]
算很久了吧版本停留在2.8的版本，不知道开发者是否还在开发这个项目，主要是steam手机版不是更新嘛，steam++也有手机版，但加速不了steamapp会显示（载入网页时出现问题），但可以用网页版。若支持加速app版，那直接起飞，因为我要想手机令牌，不挂东西很难进去，希望开发者可以对steam++手机版优化（换过加速模式vpn、本地无效，且VPN模式勾上steam，貌似就不能用别的软件和网站了）

**Comment by SongSongso** [comment]
感谢支持
我们目前正在持续开发V3版本
可以从代码的提交上看出来，我们很频繁的在提交新的代码。
