### ISSUE TITLE
[Enhancement] 官网对 GitHub 的拼写不规范

### ISSUE THREAD

**Issue by ymzhang-cs** [BeyondDimension/SteamTools#2713]
[官网](https://steampp.net/) 将 GitHub 错误拼写为 ```Github```。建议修改为 ```GitHub``` 更加严谨。

另推荐阅读 [sparanoid/chinese-copywriting-guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines)，以使排版更加精美。

**Comment by AigioL** [comment]
@Mossimos

**Comment by laopiao98** [comment]
你有强迫症？

**Comment by silascript** [comment]
哈哈，把markdown那个中文排版指北那货拿出来，就有点搞笑了。那东西本就只是个建议，又不是什么排版标准，严谨个毛！本来我还star那货的，看到有你这种推广者，现在可以取关了！

**Comment by ymzhang-cs** [comment]
> 哈哈，把markdown那个中文排版指北那货拿出来，就有点搞笑了。那东西本就只是个建议，又不是什么排版标准，严谨个毛！本来我还star那货的，看到有你这种推广者，现在可以取关了！

有没有一种可能，“GitHub”从来就没有"Github"的拼法？本身就是一个严不严谨的问题，就像我们在文内谈到“Google”不会写成“google”，不规范就是不规范，有什么好洗的？
