### ISSUE TITLE
🧐[Question] 能否添加左侧功能的自定义显示的选项及文字提醒

### ISSUE THREAD

**Issue by ZhuSunDev** [BeyondDimension/SteamTools#2717]
因本人只用切换账号与令牌功能，其他功能并不常用，而左侧的菜单图片非常地抽象，每次都无法快速找到自己要的功能，因此建议添加一个自定义侧边栏的功能：用户可在设置里将不常用的功能禁用，并且该功能会在侧边栏隐藏。
另外，因为图标比较抽象，建议在图标旁添加文字说明（而不是默认收起状态）。
![image](https://github.com/BeyondDimension/SteamTools/assets/112301592/8c808b15-5578-48ee-8a38-377f3e058795)

**Comment by rmbadmin** [comment]
3.0新版所有功能都会插件化，可以只装自己需要的插件达成同样目的
