### ISSUE TITLE
🐛[BUG] 没有加速功能

### ISSUE THREAD

**Issue by HamBearGer** [BeyondDimension/SteamTools#2728]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

![image](https://github.com/BeyondDimension/SteamTools/assets/121067236/c1eb295c-5b4c-4d64-9e5a-71e924a8ad73)

### 📷 复现步骤

1. 
2. 
3. 

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by rmbadmin** [comment]
#2441 #2048  重复

搜索时注意检查已关闭问题
