### ISSUE TITLE
🐛[BUG]软件语言为Auto，系统语言为法国法语的情况下网络加速和脚本配置页面消失

### ISSUE THREAD

**Issue by zse4t7i** [BeyondDimension/SteamTools#2729]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

软件语言为Auto，系统语言为法语的情况下网络加速页面消失。

### 📷 复现步骤

1. 系统信息：Windows 11 22H2 22621.1778 with Windows Feature Experience Pack 1000.22642.1000.0
2. 软件信息：微软商店版 Watt Toolkit 2.8.6
3. 软件语言设置为 Auto ，系统语言设置为法国法语（fr_FR）
4. 启动 Watt Toolkit ，网络加速和脚本配置页面完全消失
5. 将软件语言设置为 Chinese ( Simplified ) ，重启软件，网络加速和脚本配置页面再次出现

### 🖼 截图

![image](https://github.com/BeyondDimension/SteamTools/assets/51823222/729d80e8-4cdf-44d7-8db3-94645732e1fe)

![image](https://github.com/BeyondDimension/SteamTools/assets/51823222/d3477598-77c9-43bb-bf4f-744f3c99d24a)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 11 22H2 22621.1778 with Windows Feature Experience Pack 1000.22642.1000.0
- 下载渠道：微软商店
- 程序版本：2.8.6
- 是否包含独立运行时：看文件大小应该包含运行时

**Comment by Mossimos** [comment]
该问题与 #2048  相同
非中文语言下 隐藏了 加速功能
