### ISSUE TITLE
客户端错误-由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by ThingsWhy** [BeyondDimension/SteamTools#2731]
<img width="669" alt="image" src="https://github.com/BeyondDimension/SteamTools/assets/37958754/1e9eaa4b-3638-41c6-bac0-6936a7387fc0">
新电脑刚装就提示这个，win11的22h2，哪里设置没调好吗，防火墙也加进去了

**Comment by hu3rror** [comment]
+1

**Comment by ai-y-f** [comment]
+1

**Comment by tingyims** [comment]
+1

**Comment by ThingsWhy** [comment]
好家伙，这么多跟我一样报错的吗

**Comment by fskc42** [comment]
一样，steam更新页面以后就开始1006了，等更新解决问题吧

**Comment by Lazy-Rabbit-2001** [comment]
昨天晚上十二点就突然连不上了，今天一看报这个错

**Comment by fskc42** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Timeover7** [comment]
我也是，而且确认代理关了，防火墙关了都没用

**Comment by Mossimos** [comment]
是服务器错误，已经修复了
