### ISSUE TITLE
🧐[Question] 增加zip格式打包

### ISSUE THREAD

**Issue by CoolPlayLin** [BeyondDimension/SteamTools#2735]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述
增加zip格式打包

**Comment by rmbadmin** [comment]
是有什么需求要使用静默安装呢？
为什么不直接考虑用免安装版

**Comment by CoolPlayLin** [comment]
类似winget的包管理工具需要静默安装选项

**Comment by CoolPlayLin** [comment]
microsoft/winget-pkgs#109426

**Comment by CoolPlayLin** [comment]
@rmbadmin

**Comment by rmbadmin** [comment]
目前程序也有发布msix包，并且上架了微软商店， 这方面应该是已经支持了 winget 安装的

如果要提交给winget 也可以 提交msix appx的比我们这exe安装程序更合适

**Comment by CoolPlayLin** [comment]
可

**Comment by CoolPlayLin** [comment]
@rmbadmin msix具体在哪？

**Comment by rmbadmin** [comment]
目前因为msix已经发布了微软商店 所以直接是支持winget安装的
`winget install "Watt Toolkit"`
输入这条命令应该直接就可以

**Comment by CoolPlayLin** [comment]
![image](https://github.com/BeyondDimension/SteamTools/assets/96709586/de4997f9-899f-47eb-92ca-d5cc6f14590b)

**Comment by AigioL** [comment]
zip 格式压缩率太低了，Windows 之后也会原生支持 7z 等压缩格式
