### ISSUE TITLE
🐛[BUG] Ubuntu 23.04下无法信任证书

### ISSUE THREAD

**Issue by hidiyou** [BeyondDimension/SteamTools#2741]
### 🐛 描述
在Ubuntu 23.04中使用steam++（2.8.6、2.8.4、2.7.4均可复现）
点击加速中的信任证书没有反应
![image](https://github.com/BeyondDimension/SteamTools/assets/98258846/9ac72e39-d9bd-4483-bc19-1bc79df7abe3)
手动信任证书后无效

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Ubuntu23.04
- 下载渠道：github及镜像站
- 程序版本：
- 是否包含独立运行时：独立

**Comment by hidiyou** [comment]
如果是向我一样只是要用discord的话，可以离谱一点
``` bash
discord -ignore-certificate-errors #关闭electron的证书检查
```
那我的问题就解决了

**Comment by itsumi33** [comment]
我想问一下在哪里写入上方的代码禁用electron的证书检查
