### ISSUE TITLE
我忘记账号是哪个了，只知道UID，能不能根据UID告诉我绑定的手机号或者QQ？

### ISSUE THREAD

**Issue by Sunovn** [BeyondDimension/SteamTools#2743]
8de8b158-e0b3-49da-1938-08da24780696

**Comment by Sunovn** [comment]
发我邮件就行：nimingyx1@pm.me

**Comment by laopiao98** [comment]
我忘记我家地址了  能不能根据uid知道我住哪啊

**Comment by rmbadmin** [comment]
就算我可以根据uid找到你的手机号或者QQ 我也不能这样直接发给你，因为你并没有像我证明这号是你的证据，我不能随意泄露任何用户的隐私信息

**Comment by Sunovn** [comment]
> 就算我可以根据uid找到你的手机号或者QQ 我也不能这样直接发给你，因为你并没有像我证明这号是你的证据，我不能随意泄露任何用户的隐私信息

了解，那我怎么证明呢？
爱发电记录或者登陆设备记录？
