### ISSUE TITLE
discord上不去了  一直卡在加载界面 一直转圈 

### ISSUE THREAD

**Issue by laopiao98** [BeyondDimension/SteamTools#2744]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

**Comment by Anneliese1989** [comment]
6月24日整天都无法登录DC，请解决一下这个问题

**Comment by linlinglin** [comment]
i have this problem too.
thanks for check

**Comment by spicyczp** [comment]
一样，我和我朋友在24号开始也打不开discord，一直卡在更新界面后面的加载界面，希望能解决

**Comment by todoki21** [comment]
+1

**Comment by Pentalimbed** [comment]
有一段时间又可以上了，然而过一会又变成无限加载了

**Comment by acrowayian101** [comment]
me too, 昨天好用 今天出现问题 @rmbadmin

**Comment by Maskshine** [comment]
是的，流量统计有数据，但LOGO无限转圈圈

**Comment by acrowayian101** [comment]
![image](https://github.com/BeyondDimension/SteamTools/assets/115060994/9c8ea4da-bcc8-4798-a1b9-b2c831404cf1)
我太急了所以就

**Comment by nixgnot** [comment]
同样问题

**Comment by spicyczp** [comment]
还是打不开，哭死

**Comment by daycold1000** [comment]
原来都遇到了一样的问题

**Comment by spicyczp** [comment]
@rmbadmin

**Comment by Maskshine** [comment]
> 

可能steam++是卡在LOGO验证这一步了~~
刚又试了下，关闭steam++，改用其他网络代理登录成功后，再关闭代理，重新打开Steam++，Discrod的频道和图片都可以正常加载

**Comment by AlabasterStone** [comment]
我还以为只有我这样😦

**Comment by AlabasterStone** [comment]
@rmbadmin

**Comment by RawDiamondMC** [comment]
出现了同样的问题，开发者界面的报错如下：
`WebSocket connection to 'wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream' failed: `
一直在retry但是不成功所以会卡在加载界面

**Comment by acrowayian101** [comment]
同意.大家都是一样的问题，我已经爱发电上给作者捐了5块希望他能回复

**Comment by acrowayian101** [comment]
> 出现了同样的问题，开发者界面的报错如下： `WebSocket connection to 'wss://gateway.discord.gg/?encoding=json&v=9&compress=zlib-stream' failed: ` 一直在retry但是不成功所以会卡在加载界面

同样

**Comment by laopiao98** [comment]
> 同意.大家都是一样的问题，我已经爱发电上给作者捐了5块希望他能回复

你咋这么急

**Comment by laopiao98** [comment]
> 一样，我和我朋友在24号开始也打不开discord，一直卡在更新界面后面的加载界面，希望能解决

你咋天天来

**Comment by spicyczp** [comment]
> > 一样，我和我朋友在24号开始也打不开discord，一直卡在更新界面后面的加载界面，希望能解决
> 
> 你咋天天来
额？想来就来啊

**Comment by acrowayian101** [comment]
我有一堆事情要处理

**Comment by laopiao98** [comment]
> 我有一堆事情要处理
一定要discord吗

**Comment by laopiao98** [comment]
> 我有一堆事情要处理

用discord处理吗

**Comment by acrowayian101** [comment]
是的

**Comment by laopiao98** [comment]
> 

那咋办你有别的加速器吗

**Comment by acrowayian101** [comment]
没有

**Comment by laopiao98** [comment]
> 

这个加速器是不用服务器的  你觉得是哪里出问题了

**Comment by laopiao98** [comment]
> 

我感觉不是watt的问题

**Comment by laopiao98** [comment]
有可能是中间人被瓦格纳占领了 流量转发不了了

**Comment by laopiao98** [comment]
我打电话问问普京

**Comment by laopiao98** [comment]
普京说明天修好 @linlinglin @Anneliese1989 @nixgnot @Pentalimbed @daycold1000 @acrowayian101 @spicyczp @spicyczp

**Comment by acrowayian101** [comment]
你干嘛~嘿嘿·~呦~

**Comment by acrowayian101** [comment]
@rmbadmin

**Comment by Maskshine** [comment]
哈哈，你们......邮箱不停地跳邮件

**Comment by laopiao98** [comment]
Putin said he will deal with this problem @linlinglin

**Comment by acrowayian101** [comment]
这和普京有关系吗

**Comment by laopiao98** [comment]
> 

普京说他也上不去了

**Comment by laopiao98** [comment]
> 

怎么没关系哇，肯定有关系的， 瓦格纳一反叛，disocrd就上不去了

**Comment by laopiao98** [comment]
> i have this problem too. thanks for check

Do you support Putin or Zelensky

**Comment by AlabasterStone** [comment]
discord不在俄罗斯吧

**Comment by AlabasterStone** [comment]
应该是discord换服务器了，但是watt的代理没换

**Comment by laopiao98** [comment]
> 

watt是本地反代没有代理服务器

**Comment by rmbadmin** [comment]
问题已经修复，等待半小时左右缓存刷新后重开加速即可。

**Comment by laopiao98** [comment]
> 问题已经修复，等待半小时左右缓存刷新后重开加速即可。

谢谢大佬 咋修复的，是瓦格纳同意撤军了吗

**Comment by spicyczp** [comment]
> 问题已经修复，等待半小时左右缓存刷新后重开加速即可。

谢谢大佬

**Comment by laopiao98** [comment]
@linlinglin putin said he has already fixed this piece of shit

**Comment by laopiao98** [comment]
@linlinglin and you must donate money to app‘s author

**Comment by laopiao98** [comment]
then he will deal with problems ASAP in next time

**Comment by acrowayian101** [comment]
putin and zelensky are both stupid
putin doesn't know how to fight a war and zelensky is a literal actor

**Comment by gusx123** [comment]
问题解决了吗 怎么登陆 一直卡在登陆界面
