### ISSUE TITLE
🐛[BUG]  discord又双叒叕连不上了 这次问题不同

### ISSUE THREAD

**Issue by acrowayian101** [BeyondDimension/SteamTools#2751]
## 请认真检查以下清单中的每一项
- [v ] 已经搜索过，没有发现类似的 issue
- [ v] 已经搜索过文档，没有发现相关内容
- [v ] 已经尝试使用过最新版，问题依旧存在
- [v; ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
https://[discord.com/app](https://discord.com/app)
![image](https://github.com/BeyondDimension/SteamTools/assets/115060994/8619a970-4093-45f2-938b-b0be5afa6fe7)
反正就是连不上...

### 📷 复现步骤

1. 开启加速（hosts代理）
2. 访问discord
error 443/502 

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 11 最新版
- 下载渠道：官网
- 程序版本：2.8.6
- 是否包含独立运行时：包含

**Comment by acrowayian101** [comment]
@rmbadmin  爱发电上通知了您

**Comment by laopiao98** [comment]
> @rmbadmin 爱发电上通知了您

怎么又是你

**Comment by laopiao98** [comment]
> @rmbadmin 爱发电上通知了您

每次都有你?

**Comment by acrowayian101** [comment]
工作上的事都靠dc我能咋办

**Comment by woaiyaomimi** [comment]
@rmbadmin 大大 我也上不去辽555555

**Comment by ghost** [comment]
> @rmbadmin 爱发电上通知了您

希望紧急修复！

**Comment by spicyczp** [comment]
@rmbadmin 加一

**Comment by StevenChang1892** [comment]
我也一样啊😂,用什么代理和脚本也没用

**Comment by rmbadmin** [comment]
已经热更新修复  
cmd 输入 ` ipconfig /flushdns ` 刷新dns缓存后重开加速试试 
如果不行可能还需要等待一段时间缓存刷新

**Comment by laopiao98** [comment]
> 

爱你哦

**Comment by laopiao98** [comment]
> 已经热更新修复 cmd 输入 `ipconfig /flusdns` 刷新dns缓存后重开加速试试 如果不行可能还需要等待一段时间缓存刷新

爱你哦

**Comment by acrowayian101** [comment]
谢！！！如果一直这么活跃的话会继续在爱发电上支持的

**Comment by StevenChang1892** [comment]
太感谢辣
