### ISSUE TITLE
之前用微软商店下载到Windowsapp里面， 现在怎么给删除掉

### ISSUE THREAD

**Issue by obliviate1043** [BeyondDimension/SteamTools#2752]
## 请认真检查以下清单中的每一项
- [ ] 已经搜索过，没有发现类似的 issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by rmbadmin** [comment]
windows 应用管理里卸载，或者开始菜单内找到程序右键卸载

**Comment by gsxgmpkt9020** [comment]
正常方式我也卸载不掉，C:\Program Files\WindowsApps\4651ED44255E.47979655102CE_2.8.6.0_x64__k6txddmbb6c52里面有残留
