### ISSUE TITLE
🧐[Question] 何时能够恢复二级代理功能？

### ISSUE THREAD

**Issue by SakuraI-Nagakaze** [BeyondDimension/SteamTools#2753]
它在某一次更新中被移除，据说是因为修改了底层逻辑。能否恢复它？
ps：这个issue之前在2023年2月6日被其他人提出过，但作者似乎并未回应这个问题。并且作者已经很久没有更新这个应用了，于是我重新提出它。希望作者还活着并能够做出回应。 :-(

**Comment by rmbadmin** [comment]
目前一直在开发3.0分支，二级代理确实依然可以支持，但实际上在之前这个功能也是有一定问题的，得等新版本稳定后才会考虑再做一下这功能了

**Comment by lwb-2021** [comment]
@rmbadmin 借楼问一下，什么时候3.0会release，目前能自己下载构建吗
