### ISSUE TITLE
🧐[Question] 能否添加保持窗口最大化功能

### ISSUE THREAD

**Issue by Leyndell31** [BeyondDimension/SteamTools#2755]
当前Windows端最新版本2.8.6客户端，在将界面最小化至托盘后，从托盘再次打开，无论关闭前是否窗口最大化，重新打开都将以非窗口最大化的方式呈现界面，每次都要手动点击窗口最大化，不方便使用。
开发者能否添加保持窗口尺寸的功能，使每次启动和从托盘打开时，界面都能保持关闭前的窗口尺寸，方便使用，谢谢。

**Comment by rmbadmin** [comment]
有添加过保存窗口尺寸，但没有考虑过保存最大化的状态，之后修正一下
