### ISSUE TITLE
2023年.net7 3.x新版源码vs22打开sln有很多引用缺失，22年12月以前的2.x旧版源码没有，是否缺少新版源码要用的包或插件？

### ISSUE THREAD

**Issue by 44nl** [BeyondDimension/SteamTools#2776]
2023年.net7 3.x新版源码vs22打开sln有很多引用缺失，22年12月以前的2.x旧版源码没有，是否缺少新版源码要用的包或插件？

 x64  Windows 11, version 22H2  Github  3.x  无独立运行时

**Comment by rmbadmin** [comment]
自行参考CI编译方式拉取子模块和安装工作负载
