### ISSUE TITLE
🧐[Question] 添加令牌登录输入验证代码后失败

### ISSUE THREAD

**Issue by EndstoneV** [BeyondDimension/SteamTools#2781]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

添加令牌-新增-steam账号导入-输入账号密码登录，填写邮箱收到的代码之后，提示

### 🚑 其他信息

![image](https://github.com/BeyondDimension/SteamTools/assets/89293705/54d4d7d1-a8b0-4a4b-a84d-5d9b05628bd6)

- 处理器体系结构： x64
- 系统版本号： Windows 11
- 下载渠道： GitHub
- 程序版本： 2.8.6

**Comment by rmbadmin** [comment]
等3.0更新即可
