### ISSUE TITLE
🐛[BUG] 程序常驻后台会占用大量内存

### ISSUE THREAD

**Issue by Rea1-ms** [BeyondDimension/SteamTools#2782]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

如题，开启加速后，消耗的内存随时间增加而增加，若长时间未退出会吃掉好几个G

### 📷 复现步骤

1. 开启加速后不退出

### 📄 日志信息

[nlog-all-2023-07-29.log](https://github.com/BeyondDimension/SteamTools/files/12206941/nlog-all-2023-07-29.log)

### 🖼 截图

<img width="492" alt="5d735d869ddd089956032b52bf05aff7" src="https://github.com/BeyondDimension/SteamTools/assets/127638245/e7401a88-69bd-4e95-b722-93100889a5ce">

### 🚑 其他信息

- 处理器体系结构： x64  
- 系统版本号： Windows 10专业版 22h2 Build 19045.2728 
- 下载渠道： 微软商店 
- 程序版本： 2.8.6 
- 是否包含独立运行时：无

**Comment by rmbadmin** [comment]
重复 #2708
