### ISSUE TITLE
👑[Enhancement] 请停止对google.com的重定向

### ISSUE THREAD

**Issue by SteveXu9102** [BeyondDimension/SteamTools#2794]
### 🥰 需求描述(Description)

使用其他软件（懂的都懂）搭配steamtools使用的时候google.com无法正常加载，会重定向到一个意义不明的404网页。
问题是steamtools里还找不到把这项代理关掉的选项……
虽然确实挺乐的，但是，咱就是说，既然国内网络横竖都已经连不上google了，何必要加这么一条呢？（

### 🧐 解决方案(Solution)

在未来的版本里停止对google.com的重定向

### 🚑 其他信息(Other Information)

罪证.jpg
![{5C16D0F7-6196-4b28-B464-275DA9B88388}](https://github.com/BeyondDimension/SteamTools/assets/68725147/083356a7-2778-454b-932a-ad4220497093)

**Comment by AigioL** [comment]
因为一些网站中使用了 Google 的服务比如字体等一些内容，通常情况下虽然连不上但是会一直等待连接至超时。

对 Google 的重定向到 404 能让相关网站不用等待至超时才算网页加载完成，这也算是一种网络加速的方案。

**Comment by rmbadmin** [comment]
取消谷歌验证码的代理选项勾选即可，这是因为对谷歌验证码代理需要监听google域名
