### ISSUE TITLE
加速后会使chrome的谷歌搜索404,关闭加速后就好了不知道为啥

### ISSUE THREAD

**Issue by fatelove42** [BeyondDimension/SteamTools#2800]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by fatelove42** [comment]
开着clash tun模式

**Comment by AigioL** [comment]
参考 https://github.com/BeyondDimension/SteamTools/issues/2794

**Comment by fatelove42** [comment]
> 参考 #2794

感谢回复😊
