### ISSUE TITLE
🐛[BUG] 在非简体中文语言下，菜单的网络加速和脚本配置不显示

### ISSUE THREAD

**Issue by thiliapr** [BeyondDimension/SteamTools#2806]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
在设置的界面设置里，将语言一项更换成非`Chinese (Simplified)`项，如`Chinese (Traditional)`等，然后重启本程序，便可发现菜单中`网络加速`项和`脚本配置`没了。（比正常时少了两项功能）
且右键单击任务栏的本程序图标时，也会少两个功能。

### 📷 复现步骤

1. 打开本程序后，在菜单里找到设置，然后选择界面设置。
2. 将语言一项更改为非简体中文选项。
3. 重启本程序。

### 📄 日志信息
无产生的日志。

### 🖼 截图
![screenshot](https://github.com/BeyondDimension/SteamTools/assets/140580293/db5c4b12-999e-4c5f-8e61-c9f8d8c73671)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 10.19045.3324
- 下载渠道：Github
- 程序版本：2.8.6
- 是否包含独立运行时：是

**Comment by Cecilia-pj** [comment]
![截图_20230821113356](https://github.com/BeyondDimension/SteamTools/assets/55571881/bc92ff78-aff1-4f89-b5e8-3ac10157f313)

**Comment by thiliapr** [comment]
抱歉，我在发Issue未查看前面版本的通知。
