### ISSUE TITLE
🐛[BUG] 内存泄漏 8.5h-10Gb内存

### ISSUE THREAD

**Issue by wzqvip** [BeyondDimension/SteamTools#2813]
WIN11 21H2
i5-10400 32G ddr4 RTX3070M

运行了8.5h后发现了10-12Gb的内存使用。
仅开启加速，steam未运行

<img width="668" alt="image" src="https://github.com/BeyondDimension/SteamTools/assets/30136639/759602be-dbcb-4170-a433-14bf27c41c46">

<img width="450" alt="image" src="https://github.com/BeyondDimension/SteamTools/assets/30136639/27bc1820-1d64-4305-bd16-82e1d9c0fdcc">

**Comment by rmbadmin** [comment]
重复 #2708
