### ISSUE TITLE
如何构建v3版本

### ISSUE THREAD

**Issue by Mythos-404** [BeyondDimension/SteamTools#2816]
我使用 [CL.yml](https://github.com/BeyondDimension/SteamTools/blob/develop/.github/workflows/CI.yml) 脚本构建出来了一个v3版本但是打不开且没有任何报错
我该如何构建v3呢?

**Comment by adoin** [comment]
> 我使用 [CL.yml](https://github.com/BeyondDimension/SteamTools/blob/develop/.github/workflows/CI.yml) 脚本构建出来了一个v3版本但是打不开且没有任何报错 我该如何构建v3呢?

哥，有没有构建步骤啊，我想fork个把discord加上。。。

**Comment by Mythos-404** [comment]
看那个cl.yaml文件里的run命令就行
但是我感觉不可以加回来我现在用的v3rc1当时有discord加速结果现在打开直接没了
加速列表是请求网络的不好搞

**Comment by adoin** [comment]
> 看那个cl.yaml文件里的run命令就行 但是我感觉不可以加回来我现在用的v3rc1当时有discord加速结果现在打开直接没了 加速列表是请求网络的不好搞

作者是请求回来的规则里面过滤掉，还是不请求对应规则了。。。

**Comment by Mythos-404** [comment]
初步判断是请求服务器列表不是客户端屏蔽

找到[请求的代码](https://github.com/BeyondDimension/SteamTools/blob/4e2cfc23aededa40aa6a4a4faf0d7380f86a0123/src/BD.WTTS.Client.Plugins.Accelerator/Services/Mvvm/ProxyService.cs#L321-L322)了

我建议直接由社区fork v2版本进行维护开发

**Comment by adoin** [comment]
> 初步判断是请求服务器列表不是客户端屏蔽
> 
> 找到[请求的代码](https://github.com/BeyondDimension/SteamTools/blob/4e2cfc23aededa40aa6a4a4faf0d7380f86a0123/src/BD.WTTS.Client.Plugins.Accelerator/Services/Mvvm/ProxyService.cs#L321-L322)了
> 
> 我建议直接由社区fork v2版本进行维护开发

他这个请求是发去作者的另外的服务器吗

**Comment by Mythos-404** [comment]
是的，你把网断了打开steam++就会报错提示无法请求加速列表

**Comment by adoin** [comment]
> 是的，你把网断了打开steam++就会报错提示无法请求加速列表

那岂不是代码改了没用，手动规则合并才行，哪里有带discord的规则呢

**Comment by Mythos-404** [comment]
所以推荐fork v2版本进行维护开发

或者可以尝试将v2版本的加速移植到v3版本

**Comment by adoin** [comment]
> 所以推荐fork v2版本进行维护开发
> 
> 或者可以尝试将v2版本的加速移植到v3版本

V2是本地规则吗

**Comment by Mythos-404** [comment]
我测试了一下v2也是请求服务器来获得加速列表，所以寄，建议使用其他工具来代替

**Comment by adoin** [comment]
> 我测试了一下v2也是请求服务器来获得加速列表，所以寄，建议使用其他工具来代替

=。=

**Comment by adoin** [comment]
> 我测试了一下v2也是请求服务器来获得加速列表，所以寄，建议使用其他工具来代替

除了梯子 你有啥工具不

**Comment by Mythos-404** [comment]
自己部署的代理服务器呗，我现在所有上网用的就是这个

**Comment by adoin** [comment]
> 自己部署的代理服务器呗，我现在所有上网用的就是这个

发现个好玩的东西，你能不能帮调试一下获取的代理服务数据是什么格式

**Comment by Mythos-404** [comment]
额有qq吗，别再github上聊了

**Comment by adoin** [comment]
> 额有qq吗，别再github上聊了

QQ号发你邮件了

**Comment by anjilaqwq** [comment]
ヾ(≧▽≦*)o

**Comment by AdySnowflake** [comment]
我根据CI的步骤，在Windows上构建得到是便携版，没有安装版，是不是我构建出错了？
