### ISSUE TITLE
🐛[BUG] 3.0 功能菜单排序重启后失效

### ISSUE THREAD

**Issue by Dingzheng0615** [BeyondDimension/SteamTools#2830]
3.0 功能菜单排序每次软件重启后会失效，无法记录之前改过的菜单顺序

**Comment by AigioL** [comment]
rc.1 版本中仅起始页固定在首位，其他页面排序应是生效的，除开起始页之外的页面有失效的问题吗？

**Comment by Dingzheng0615** [comment]
其他正常，就是想打开软件就可以直接点加速，而不是需要切换一下侧边栏
