### ISSUE TITLE
3.0.0-rc1 MacOS 13.5.2 M2版本无法运行

### ISSUE THREAD

**Issue by synhaz** [BeyondDimension/SteamTools#2834]
直接打开：
“Steam++”已损坏，无法打开。 你应该将它移到废纸篓。
于 /Applications/Steam++.app/Contents/MacOS/Steam++ 打开，问题报告如下：

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Steam++ [10582]
Path:                  /Applications/Steam++.app/Contents/MacOS/Steam++
Identifier:            net.steampp.app
Version:               3.0.0 (3.0.0.0)
Code Type:             ARM-64 (Native)
Parent Process:        zsh [10571]
Responsible:           Terminal [1282]
User ID:               501

Date/Time:             2023-09-08 21:27:28.5927 +0800
OS Version:            macOS 13.5.2 (22G91)
Report Version:        12
Anonymous UUID:        348DF811-3E05-D191-2523-DD885B17922F

Sleep/Wake UUID:       75CBBE39-6382-43FE-A62B-B9C3FAEAA7A3

Time Awake Since Boot: 32000 seconds
Time Since Wake:       18317 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Codes:       UNKNOWN_0x32 at 0x0000000100d60000
Exception Codes:       0x0000000000000032, 0x0000000100d60000

Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page

VM Region Info: 0x100d60000 is in 0x100d60000-0x100d90000;  bytes after start: 0  bytes before end: 196607
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      mapped file                 100d54000-100d60000    [   48K] r--/rwx SM=COW  ...t_id=b98eb13b
--->  mapped file                 100d60000-100d90000    [  192K] r-x/rwx SM=COW  ...t_id=b64e533b
      VM_ALLOCATE (reserved)      100d90000-100df8000    [  416K] rw-/rwx SM=NUL  ...(unallocated)

Thread 0 Crashed:
0   dyld                          	       0x190f26e40 dyld3::MachOFile::isMachO(Diagnostics&, unsigned long long) const + 40
1   dyld                          	       0x190eef0e0 dyld4::Loader::mapSegments(Diagnostics&, dyld4::RuntimeState&, char const*, unsigned long long, dyld4::Loader::CodeSignatureInFile const&, bool, dyld3::Array<dyld4::Loader::Region> const&, bool, bool, dyld4::Loader::FileValidationInfo const&) + 984
2   dyld                          	       0x190ef794c invocation function for block in dyld4::JustInTimeLoader::makeJustInTimeLoaderDisk(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*) + 88
3   dyld                          	       0x190ef72e8 dyld4::JustInTimeLoader::withRegions(dyld3::MachOFile const*, void (dyld3::Array<dyld4::Loader::Region> const&) block_pointer) + 292
4   dyld                          	       0x190ef7890 invocation function for block in dyld4::JustInTimeLoader::makeJustInTimeLoaderDisk(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*) + 456
5   dyld                          	       0x190efe68c dyld4::SyscallDelegate::withReadOnlyMappedFile(Diagnostics&, char const*, bool, void (void const*, unsigned long, bool, dyld4::FileID const&, char const*) block_pointer) const + 132
6   dyld                          	       0x190ef7694 dyld4::JustInTimeLoader::makeJustInTimeLoaderDisk(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*) + 208
7   dyld                          	       0x190eee40c invocation function for block in dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&) + 1680
8   dyld                          	       0x190eed754 dyld4::Loader::forEachResolvedAtPathVar(dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, dyld4::ProcessConfig::PathOverrides::Type, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) + 776
9   dyld                          	       0x190edaf54 dyld4::ProcessConfig::PathOverrides::forEachPathVariant(char const*, dyld3::Platform, bool, bool, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) const + 488
10  dyld                          	       0x190eed28c dyld4::Loader::forEachPath(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) + 248
11  dyld                          	       0x190eed9e0 dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&) + 588
12  dyld                          	       0x190ef5730 invocation function for block in dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&) + 412
13  dyld                          	       0x190f287e8 invocation function for block in dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const + 148
14  dyld                          	       0x190ed42d8 dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 296
15  dyld                          	       0x190f28630 dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const + 172
16  dyld                          	       0x190ef5478 dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&) + 164
17  dyld                          	       0x190ed8a0c dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 1236
18  dyld                          	       0x190ed7e18 start + 1964

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000100d60000   x1: 0x000000016f9bdd20   x2: 0x0000000000030000   x3: 0x0000000000040012
    x4: 0x0000000000000003   x5: 0x000000000009c000   x6: 0x000000000009c000   x7: 0x0000000000000000
    x8: 0x00000001ec2b212c   x9: 0x00000001ec2b2030  x10: 0x000000016f9bd53c  x11: 0x0800000000040000
   x12: 0x0000000000000001  x13: 0x0000000000000001  x14: 0x0000000000056d20  x15: 0x000000016f9bea70
   x16: 0x00000000000000c5  x17: 0x0000000190ed5f60  x18: 0x0000000000000000  x19: 0x000000016f9bdd20
   x20: 0x0000000000000003  x21: 0x000000016f9bdd20  x22: 0x000000016f9bd7f8  x23: 0x0000000000098000
   x24: 0x000000000009c000  x25: 0x000000016f9bd56c  x26: 0x0000000000000000  x27: 0x0000000100d60000
   x28: 0x0000000000000040   fp: 0x000000016f9bd180   lr: 0x7d4a000190eef0e0
    sp: 0x000000016f9bd170   pc: 0x0000000190f26e40 cpsr: 0x20001000
   far: 0x0000000100d60000  esr: 0x92000007 (Data Abort) byte read Translation fault

Binary Images:
       0x100440000 -        0x100613fff net.steampp.app (3.0.0) <53b6e40d-362d-3893-a265-c270405be762> /Applications/Steam++.app/Contents/MacOS/Steam++
       0x190ed2000 -        0x190f60587 dyld (*) <e7a99595-e0f8-34af-be8b-9347d0d658a4> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 5
    thread_create: 0
    thread_set_state: 4

VM Region Summary:
ReadOnly portion of Libraries: Total=808.0M resident=0K(0%) swapped_out_or_unallocated=808.0M(100%)
Writable regions: Total=9248K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9248K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE (reserved)             784K        5         reserved VM address space (unallocated)
__DATA                             555K        3 
__DATA_CONST                        86K        2 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       805.6M        2 
__TEXT                            2444K        2 
dyld private memory                272K        2 
mapped file                       17.5M       41 
===========                     =======  ======= 
TOTAL                            891.2M       60 
TOTAL, minus reserved VM space   890.4M       60 

-----------
Full Report
-----------

{"app_name":"Steam++","timestamp":"2023-09-08 21:27:28.00 +0800","app_version":"3.0.0","slice_uuid":"53b6e40d-362d-3893-a265-c270405be762","build_version":"3.0.0.0","platform":1,"bundleID":"net.steampp.app","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.5.2 (22G91)","roots_installed":0,"name":"Steam++","incident_id":"D01044FE-6EB6-4191-8EA2-0910A9B64236"}
{
  "uptime" : 32000,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,6",
  "coalitionID" : 1000,
  "osVersion" : {
    "train" : "macOS 13.5.2",
    "build" : "22G91",
    "releaseType" : "User"
  },
  "captureTime" : "2023-09-08 21:27:28.5927 +0800",
  "incident" : "D01044FE-6EB6-4191-8EA2-0910A9B64236",
  "pid" : 10582,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-09-08 21:27:28.5887 +0800",
  "procStartAbsTime" : 791540344982,
  "procExitAbsTime" : 791540437905,
  "procName" : "Steam++",
  "procPath" : "\/Applications\/Steam++.app\/Contents\/MacOS\/Steam++",
  "bundleInfo" : {"CFBundleShortVersionString":"3.0.0","CFBundleVersion":"3.0.0.0","CFBundleIdentifier":"net.steampp.app"},
  "storeInfo" : {"deviceIdentifierForVendor":"EB9D10BE-9A37-5D5E-B577-5066C1C740F7","thirdParty":true},
  "parentProc" : "zsh",
  "parentPid" : 10571,
  "coalitionName" : "com.apple.Terminal",
  "crashReporterKey" : "348DF811-3E05-D191-2523-DD885B17922F",
  "responsiblePid" : 1282,
  "responsibleProc" : "Terminal",
  "codeSigningID" : "net.steampp.app",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 587203072,
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 18317,
  "sleepWakeUUID" : "75CBBE39-6382-43FE-A62B-B9C3FAEAA7A3",
  "sip" : "enabled",
  "vmRegionInfo" : "0x100d60000 is in 0x100d60000-0x100d90000;  bytes after start: 0  bytes before end: 196607\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      mapped file                 100d54000-100d60000    [   48K] r--\/rwx SM=COW  ...t_id=b98eb13b\n--->  mapped file                 100d60000-100d90000    [  192K] r-x\/rwx SM=COW  ...t_id=b64e533b\n      VM_ALLOCATE (reserved)      100d90000-100df8000    [  416K] rw-\/rwx SM=NUL  ...(unallocated)",
  "exception" : {"codes":"0x0000000000000032, 0x0000000100d60000","rawCodes":[50,4308992000],"type":"EXC_BAD_ACCESS","signal":"SIGKILL (Code Signature Invalid)","subtype":"UNKNOWN_0x32 at 0x0000000100d60000"},
  "termination" : {"flags":0,"code":2,"namespace":"CODESIGNING","indicator":"Invalid Page"},
  "vmregioninfo" : "0x100d60000 is in 0x100d60000-0x100d90000;  bytes after start: 0  bytes before end: 196607\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      mapped file                 100d54000-100d60000    [   48K] r--\/rwx SM=COW  ...t_id=b98eb13b\n--->  mapped file                 100d60000-100d90000    [  192K] r-x\/rwx SM=COW  ...t_id=b64e533b\n      VM_ALLOCATE (reserved)      100d90000-100df8000    [  416K] rw-\/rwx SM=NUL  ...(unallocated)",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":4,"task_for_pid":5},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":429765,"threadState":{"x":[{"value":4308992000},{"value":6167452960},{"value":196608},{"value":262162},{"value":3},{"value":638976},{"value":638976},{"value":0},{"value":8257216812,"symbolLocation":172,"symbol":"_main_thread"},{"value":8257216560,"symbolLocation":0,"symbol":"errno"},{"value":6167450940},{"value":576460752303685632},{"value":1},{"value":1},{"value":355616},{"value":6167456368},{"value":197},{"value":6726442848,"symbolLocation":56,"symbol":"fcntl"},{"value":0},{"value":6167452960},{"value":3},{"value":6167452960},{"value":6167451640},{"value":622592},{"value":638976},{"value":6167450988},{"value":0},{"value":4308992000},{"value":64}],"flavor":"ARM_THREAD_STATE64","lr":{"value":9028028409744126176},"cpsr":{"value":536875008},"fp":{"value":6167449984},"sp":{"value":6167449968},"esr":{"value":2449473543,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":6726774336,"matchesCrashFrame":1},"far":{"value":4308992000}},"frames":[{"imageOffset":347712,"symbol":"dyld3::MachOFile::isMachO(Diagnostics&, unsigned long long) const","symbolLocation":40,"imageIndex":1},{"imageOffset":119008,"symbol":"dyld4::Loader::mapSegments(Diagnostics&, dyld4::RuntimeState&, char const*, unsigned long long, dyld4::Loader::CodeSignatureInFile const&, bool, dyld3::Array<dyld4::Loader::Region> const&, bool, bool, dyld4::Loader::FileValidationInfo const&)","symbolLocation":984,"imageIndex":1},{"imageOffset":153932,"symbol":"invocation function for block in dyld4::JustInTimeLoader::makeJustInTimeLoaderDisk(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*)","symbolLocation":88,"imageIndex":1},{"imageOffset":152296,"symbol":"dyld4::JustInTimeLoader::withRegions(dyld3::MachOFile const*, void (dyld3::Array<dyld4::Loader::Region> const&) block_pointer)","symbolLocation":292,"imageIndex":1},{"imageOffset":153744,"symbol":"invocation function for block in dyld4::JustInTimeLoader::makeJustInTimeLoaderDisk(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*)","symbolLocation":456,"imageIndex":1},{"imageOffset":181900,"symbol":"dyld4::SyscallDelegate::withReadOnlyMappedFile(Diagnostics&, char const*, bool, void (void const*, unsigned long, bool, dyld4::FileID const&, char const*) block_pointer) const","symbolLocation":132,"imageIndex":1},{"imageOffset":153236,"symbol":"dyld4::JustInTimeLoader::makeJustInTimeLoaderDisk(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*)","symbolLocation":208,"imageIndex":1},{"imageOffset":115724,"symbol":"invocation function for block in dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&)","symbolLocation":1680,"imageIndex":1},{"imageOffset":112468,"symbol":"dyld4::Loader::forEachResolvedAtPathVar(dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, dyld4::ProcessConfig::PathOverrides::Type, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer)","symbolLocation":776,"imageIndex":1},{"imageOffset":36692,"symbol":"dyld4::ProcessConfig::PathOverrides::forEachPathVariant(char const*, dyld3::Platform, bool, bool, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) const","symbolLocation":488,"imageIndex":1},{"imageOffset":111244,"symbol":"dyld4::Loader::forEachPath(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer)","symbolLocation":248,"imageIndex":1},{"imageOffset":113120,"symbol":"dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&)","symbolLocation":588,"imageIndex":1},{"imageOffset":145200,"symbol":"invocation function for block in dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&)","symbolLocation":412,"imageIndex":1},{"imageOffset":354280,"symbol":"invocation function for block in dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const","symbolLocation":148,"imageIndex":1},{"imageOffset":8920,"symbol":"dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const","symbolLocation":296,"imageIndex":1},{"imageOffset":353840,"symbol":"dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const","symbolLocation":172,"imageIndex":1},{"imageOffset":144504,"symbol":"dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&)","symbolLocation":164,"imageIndex":1},{"imageOffset":27148,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":1236,"imageIndex":1},{"imageOffset":24088,"symbol":"start","symbolLocation":1964,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4299423744,
    "CFBundleShortVersionString" : "3.0.0",
    "CFBundleIdentifier" : "net.steampp.app",
    "size" : 1916928,
    "uuid" : "53b6e40d-362d-3893-a265-c270405be762",
    "path" : "\/Applications\/Steam++.app\/Contents\/MacOS\/Steam++",
    "name" : "Steam++",
    "CFBundleVersion" : "3.0.0.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6726426624,
    "size" : 583048,
    "uuid" : "e7a99595-e0f8-34af-be8b-9347d0d658a4",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6725763072,
  "size" : 3553361920,
  "uuid" : "40eab1ab-8b22-3dec-aa46-bb3136a05069"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=808.0M resident=0K(0%) swapped_out_or_unallocated=808.0M(100%)\nWritable regions: Total=9248K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9248K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE (reserved)             784K        5         reserved VM address space (unallocated)\n__DATA                             555K        3 \n__DATA_CONST                        86K        2 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       805.6M        2 \n__TEXT                            2444K        2 \ndyld private memory                272K        2 \nmapped file                       17.5M       41 \n===========                     =======  ======= \nTOTAL                            891.2M       60 \nTOTAL, minus reserved VM space   890.4M       60 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "863024a525691f8ebbd93248c8f763ac229c2d4b",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6425c75e4327780c10cc4252",
      "factorPackIds" : {
        "SIRI_HOME_AUTOMATION_INTENT_SELECTION_CACHE" : "642600a457e7664b1698eb32"
      },
      "deploymentId" : 240000004
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "a092db1b-c401-44fa-9c54-518b7d69ca61",
      "experimentId" : "64a844035c85000c0f42398a",
      "deploymentId" : 400000019
    },
    {
      "treatmentId" : "6dd670af-0633-45e4-ae5f-122ae4df02be",
      "experimentId" : "64406ba83deb637ac8a04419",
      "deploymentId" : 900000017
    }
  ]
}
}

Model: Mac14,6, BootROM 10151.0.305.0.1, proc 12:8:4 processors, 64 GB, SMC 
Graphics: Apple M2 Max, Apple M2 Max, Built-In
Display: Redmi 27 NU, 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition), Main, MirrorOff, Online
Display: Color LCD, 3456 x 2234 Retina, MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4388), wl0: Jun 11 2023 05:20:59 version 23.20.95.0.40.50.92 FWID 01-ec505a98
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Network Service: GoGoJumpVPN, VPN (cloud.centaur.goj), utun7
USB Device: USB31Bus
USB Device: USB3.1 Hub
USB Device: DataTraveler 3.0
USB Device: USB2.1 Hub
USB Device: IQUNIX Receiver
USB Device: USB Receiver
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by Mossimos** [comment]
目前 Arm 代码签名有问题 可以用 转义层 运行x64版本

**Comment by bcw222** [comment]
然而我在 Intel Mac 上也遇到了相同的问题

**Comment by synhaz** [comment]
我在安装 Rosetta  2转译层后，
执行sudo xattr -r -d com.apple.quarantine，允许任意来源，
再执行 sudo xattr -r -d com.apple.quarantine /Applications/Steam++.app 后，
在Steam++的简介中启用使用Rosetta打开，之后就能正常打开了。

**Comment by bcw222** [comment]
（在我的 Intel Mac 上）只需要拷贝出Steam++.app 后直接 sudo xattr -r -d com.apple.quarantine /path/to/Steam++.app 就可以正常打开。

**Comment by Mossimos** [comment]
请前往 [https://hk.mossimo.net/s/PLSG?path=%2F最新版本%2FMac](https://hk.mossimo.net/s/PLSG?path=%2F%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%AC%2FMac) 获取最新 dmg 尝试下 目前只替换了这里的包 其他地方的后续测试后会替换一下

**Comment by synhaz** [comment]
我这边（m2）可以原生正常运行了。
