### ISSUE TITLE
Steam🐛[BUG]库存无法显示

### ISSUE THREAD

**Issue by qxsm** [BeyondDimension/SteamTools#2838]
## 请认真检查以下清单中的每一项

- [ ] 已经尝试使用过最新版，问题依旧存在
-

### 🐛 描述
steam库进入后只有下载游戏，没有显示库中所有的游戏

### 📷 复现步骤

Clearly describe the reproduction steps so that others can see the problem
Ensure that the above steps can be reproduced 100% on most devices as far as possible in order to locate the cause of the problem
-->
1.打开steam后打开steam++之后只出现了几个已经下载的游戏，其他游戏无法调出。
2. 关闭steam后一个游戏也没有了
3. 电脑外星人win11

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by rmbadmin** [comment]
库存游戏-筛选，取消仅显示已安装游戏选项
