### ISSUE TITLE
🐛[BUG] 启动时最小化到托盘不生效！

### ISSUE THREAD

**Issue by HumanMus1c** [BeyondDimension/SteamTools#2840]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
启动时最小化到托盘不生效！

### 📷 复现步骤

1. 重启电脑/开机
2. 等待软件启动完毕
3. 软件依然显示窗口

### 📄 日志信息
<!--
在程序内 设置 - 通用设置 - 存储空间 - 打开Logs文件夹 找到当天的日志，将文件上传或将关键部分写在此处，在内容的开始与结束上加上 ``` 单独作为一行，如下所示
Set in the program - General Settings - storage space - open the logs folder to find the log of the day, upload the file or write the key part here, and add ``` to the beginning and end of the content as a separate line, as shown below

```
- 日志文件所在文件夹路径
    - Microsoft Store ```%USERPROFILE%\AppData\Local\Packages\4651ED44255E.47979655102CE_k6txddmbb6c52\LocalCache\Logs```
    - Windows ```\Logs``` or ```%Tmp%\Steam++\Logs```
    - macOS ```~/Library/Caches/Steam++/Logs```
    - Linux ```$XDG_CACHE_HOME/Steam++/Logs``` or ```$HOME/.cache/Steam++/Logs```
    - Android ```/data/data/net.steampp.app/cache/Logs```
你的日志内容
Your log content
-->
```
[Accelerator-nlog-all-2023-09-08.log](https://github.com/BeyondDimension/SteamTools/files/12564838/Accelerator-nlog-all-2023-09-08.log)
[nlog-all-2023-09-08.log](https://github.com/BeyondDimension/SteamTools/files/12564839/nlog-all-2023-09-08.log)

### 🖼 截图

![image](https://github.com/BeyondDimension/SteamTools/assets/46023154/06a61272-6d52-4056-8b30-16218b76bbfa)

### 🚑 其他信息

- 处理器体系结构： x64
- 系统版本号：Windows 11 专业版 22H2 22621.2215
- 下载渠道：Github
- 程序版本：[3.0.0-rc.1]Pre-release
- 是否包含独立运行时：不包含 fde

**Comment by CharlesHim** [comment]
遇到这个问题+1，我的情况大多与issue中提到的相同，不同之处是：如果电脑开机自动连校园网，开机时一定无法正常最小化；其他网络环境下多半正常。怀疑与校园网环境需要登录有关。

**Comment by CharlesHim** [comment]
补充我的环境：Win11家庭中文版22h2，版本3.0.0-rc.1，exe安装包，x64，下载自官网蓝奏云

**Comment by Eashinun** [comment]
+1

**Comment by ChenyangS** [comment]
同,可复现

**Comment by exaggerate-const** [comment]
我在群里面问过这个问题，开发者说已经注意到这个bug，下个版本就会修复

**Comment by rmbadmin** [comment]
已经再最新提交中修复
