### ISSUE TITLE
🧐[Question] 解锁游戏区域限制功能有部分游戏不能起作用

### ISSUE THREAD

**Issue by hzy132** [BeyondDimension/SteamTools#2848]
## 请认真检查以下清单中的每一项
- [√] 已经搜索过，没有发现类似的 issue
- [√] 已经搜索过文档，没有发现相关内容
- [√] 已经尝试使用过最新版，问题依旧存在
- [√] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述
解锁游戏区域限制功能确实有用，我低价区家庭共享到国区的Gal游戏都可以直接看到了，但低价区购买的最终幻想7重制版还是无法共享到国区账户，开启我自己的VPN后就可以在国区游戏库中看到最终幻想7了。所以这个问题能解决吗？

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 10.19045.3393
- 下载渠道：Github
- 程序版本：3.0.0-rc.1
- 是否包含独立运行时：

**Comment by rmbadmin** [comment]
目前解锁区域限制只可查看，没有办法购买

**Comment by hzy132** [comment]
抱歉，或许可能是我没表述清楚，不是购买，我已经在低价区购买好了，在未开启工具时无法家庭共享到国区的游戏中，开启工具后大部分都可以共享到国区然后使用国区账号游玩，但是存在部分游戏在开启工具后还是无法共享到国区使用国区账号游玩，但开启美国VPN后可以共享到国区使用国区账户游玩
