### ISSUE TITLE
🐛[BUG] steam启动后无法正常最小化到托盘

### ISSUE THREAD

**Issue by exaggerate-const** [BeyondDimension/SteamTools#2851]
## 请认真检查以下清单中的每一项

- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

我的设置

- [x] 启动时自动运行steam
- [ ] 以管理员权限运行steam
- [x] steam启动时最小化到托盘
- [x] steam启动时不检查更新

之后开机后steam依然无法正常最小化到托盘，而且老版本时就我就有这个问题，新版本还是没有得到解决

### 📷 复现步骤

1. 打开启动时自动运行steam
2. 打开Steam启动时最小化到托盘
3. 之后开机后steam没有正常最小化到托盘

### 📄 日志信息

我的日志内容

```
2023-09-11 08:39:06.3603|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
```

### 🚑 其他信息

- 处理器体系结构：64位
- 系统版本号：Win11  22H2
- 下载渠道：官网 
- 程序版本：3.0.0-rc.1
- steam版本：1690583737

**Comment by exaggerate-const** [comment]
我注意到3.0版本的开发任务中开发者也注意到了这个问题，描述为：不用管理员权限带参数启动steam失败, 应该有望在下一版本完成修复，另外开发任务中也加入了针对steamdeck的优化，希望到时候能出一个在steamdeck上易于安装的版本

**Comment by rmbadmin** [comment]
这个问题已经在最新提交中修复
