### ISSUE TITLE
🐛[BUG] m1无法启动

### ISSUE THREAD

**Issue by jingliancui** [BeyondDimension/SteamTools#2856]
## 请认真检查以下清单中的每一项
- [ ] 已经搜索过，没有发现类似的 issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 📷 复现步骤

1. 
2. 
3. 

### 📄 日志信息

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Steam++ [2139]
Path:                  /Applications/Steam++.app/Contents/MacOS/Steam++
Identifier:            net.steampp.app
Version:               3.0.0 (3.0.0.0)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-09-11 19:30:46.7180 +0800
OS Version:            macOS 13.5.2 (22G91)
Report Version:        12
Anonymous UUID:        BEA45DF8-A5C3-B4A7-6315-C31F48EA4F5B

Time Awake Since Boot: 390 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Codes:       UNKNOWN_0x32 at 0x00000001036d8000
Exception Codes:       0x0000000000000032, 0x00000001036d8000

Termination Reason:    Namespace CODESIGNING, Code 2 Invalid Page

VM Region Info: 0x1036d8000 is in 0x10363c000-0x103770000;  bytes after start: 638976  bytes before end: 622591
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      mapped file                 1035ac000-10363c000    [  576K] r--/rwx SM=COW  ...t_id=c519ca5d
--->  mapped file                 10363c000-103770000    [ 1232K] r--/rwx SM=COW  ...t_id=c519a85d
      GAP OF 0x5c000 BYTES
      mapped file                 1037cc000-1039c4000    [ 2016K] r-x/rwx SM=COW  ...t_id=c530d95d

Thread 0 Crashed:
0   dyld                          	       0x19d2c2e40 dyld3::MachOFile::isMachO(Diagnostics&, unsigned long long) const + 40
1   dyld                          	       0x19d2c2d1c dyld3::FatFile::isValidSlice(Diagnostics&, unsigned long long, unsigned int, unsigned int, unsigned int, unsigned long long, unsigned long long) const + 80
2   dyld                          	       0x19d2c303c dyld3::FatFile::forEachSlice(Diagnostics&, unsigned long long, bool, void (unsigned int, unsigned int, void const*, unsigned long long, bool&) block_pointer) const + 332
3   dyld                          	       0x19d29aed4 dyld4::SyscallDelegate::mapFileReadOnly(Diagnostics&, char const*, unsigned long*, dyld4::FileID*, bool*, char*) const + 704
4   dyld                          	       0x19d29a660 dyld4::SyscallDelegate::withReadOnlyMappedFile(Diagnostics&, char const*, bool, void (void const*, unsigned long, bool, dyld4::FileID const&, char const*) block_pointer) const + 88
5   dyld                          	       0x19d293694 dyld4::JustInTimeLoader::makeJustInTimeLoaderDisk(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*) + 208
6   dyld                          	       0x19d28a40c invocation function for block in dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&) + 1680
7   dyld                          	       0x19d289754 dyld4::Loader::forEachResolvedAtPathVar(dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, dyld4::ProcessConfig::PathOverrides::Type, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) + 776
8   dyld                          	       0x19d276f54 dyld4::ProcessConfig::PathOverrides::forEachPathVariant(char const*, dyld3::Platform, bool, bool, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) const + 488
9   dyld                          	       0x19d28928c dyld4::Loader::forEachPath(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) + 248
10  dyld                          	       0x19d2899e0 dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&) + 588
11  dyld                          	       0x19d291730 invocation function for block in dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&) + 412
12  dyld                          	       0x19d2c47e8 invocation function for block in dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const + 148
13  dyld                          	       0x19d2702d8 dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const + 296
14  dyld                          	       0x19d2c4630 dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const + 172
15  dyld                          	       0x19d291478 dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&) + 164
16  dyld                          	       0x19d274a0c dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 1236
17  dyld                          	       0x19d273e18 start + 1964

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x00000001036d8000   x1: 0x000000016d495a70   x2: 0x0000000000096d20   x3: 0x0000000000000001
    x4: 0x000000000100000c   x5: 0x0000000000000000   x6: 0x000000000009c000   x7: 0x0000000000096d20
    x8: 0x0000000000096d20   x9: 0x0000000000c00900  x10: 0x0000000000001020  x11: 0x0000000000000001
   x12: 0x000000016d496272  x13: 0x0000000000000000  x14: 0x000000023ec5cb82  x15: 0x0000000000008000
   x16: 0x00000002a7747724  x17: 0x6ae100016d495af8  x18: 0x0000000000000000  x19: 0x000000016d495a70
   x20: 0x000000000009c000  x21: 0x00000001036d8000  x22: 0x000000000100000c  x23: 0x0000000000000000
   x24: 0x000000010363c020  x25: 0x0000000000000001  x26: 0x0000000000096d20  x27: 0x000000000100000c
   x28: 0x0000000000000000   fp: 0x000000016d4959e0   lr: 0x5b1080019d2c2d1c
    sp: 0x000000016d4959d0   pc: 0x000000019d2c2e40 cpsr: 0x20001000
   far: 0x00000001036d8000  esr: 0x92000007 (Data Abort) byte read Translation fault

Binary Images:
       0x102968000 -        0x102b3bfff net.steampp.app (3.0.0) <53b6e40d-362d-3893-a265-c270405be762> /Applications/Steam++.app/Contents/MacOS/Steam++
       0x19d26e000 -        0x19d2fc587 dyld (*) <e7a99595-e0f8-34af-be8b-9347d0d658a4> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=808.0M resident=0K(0%) swapped_out_or_unallocated=808.0M(100%)
Writable regions: Total=8832K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8832K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE (reserved)             368K        4         reserved VM address space (unallocated)
__DATA                             555K        3 
__DATA_CONST                        86K        2 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       805.6M        2 
__TEXT                            2444K        2 
dyld private memory                272K        2 
mapped file                       17.4M       40 
===========                     =======  ======= 
TOTAL                            890.6M       58 
TOTAL, minus reserved VM space   890.3M       58 

-----------
Full Report
-----------

{"app_name":"Steam++","timestamp":"2023-09-11 19:30:47.00 +0800","app_version":"3.0.0","slice_uuid":"53b6e40d-362d-3893-a265-c270405be762","build_version":"3.0.0.0","platform":1,"bundleID":"net.steampp.app","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.5.2 (22G91)","roots_installed":0,"name":"Steam++","incident_id":"77959190-B145-4C62-AEAB-D898C2EE690F"}
{
  "uptime" : 390,
  "procRole" : "Default",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro17,1",
  "coalitionID" : 1270,
  "osVersion" : {
    "train" : "macOS 13.5.2",
    "build" : "22G91",
    "releaseType" : "User"
  },
  "captureTime" : "2023-09-11 19:30:46.7180 +0800",
  "incident" : "77959190-B145-4C62-AEAB-D898C2EE690F",
  "pid" : 2139,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-09-11 19:30:46.6912 +0800",
  "procStartAbsTime" : 9445153889,
  "procExitAbsTime" : 9445785617,
  "procName" : "Steam++",
  "procPath" : "\/Applications\/Steam++.app\/Contents\/MacOS\/Steam++",
  "bundleInfo" : {"CFBundleShortVersionString":"3.0.0","CFBundleVersion":"3.0.0.0","CFBundleIdentifier":"net.steampp.app"},
  "storeInfo" : {"deviceIdentifierForVendor":"F07B1F1C-6AB7-52D9-8E56-1EB949E86F40","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "net.steampp.app",
  "crashReporterKey" : "BEA45DF8-A5C3-B4A7-6315-C31F48EA4F5B",
  "codeSigningID" : "net.steampp.app",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 587203072,
  "codeSigningValidationCategory" : 0,
  "codeSigningTrustLevel" : 0,
  "sip" : "enabled",
  "vmRegionInfo" : "0x1036d8000 is in 0x10363c000-0x103770000;  bytes after start: 638976  bytes before end: 622591\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      mapped file                 1035ac000-10363c000    [  576K] r--\/rwx SM=COW  ...t_id=c519ca5d\n--->  mapped file                 10363c000-103770000    [ 1232K] r--\/rwx SM=COW  ...t_id=c519a85d\n      GAP OF 0x5c000 BYTES\n      mapped file                 1037cc000-1039c4000    [ 2016K] r-x\/rwx SM=COW  ...t_id=c530d95d",
  "exception" : {"codes":"0x0000000000000032, 0x00000001036d8000","rawCodes":[50,4352475136],"type":"EXC_BAD_ACCESS","signal":"SIGKILL (Code Signature Invalid)","subtype":"UNKNOWN_0x32 at 0x00000001036d8000"},
  "termination" : {"flags":0,"code":2,"namespace":"CODESIGNING","indicator":"Invalid Page"},
  "vmregioninfo" : "0x1036d8000 is in 0x10363c000-0x103770000;  bytes after start: 638976  bytes before end: 622591\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      mapped file                 1035ac000-10363c000    [  576K] r--\/rwx SM=COW  ...t_id=c519ca5d\n--->  mapped file                 10363c000-103770000    [ 1232K] r--\/rwx SM=COW  ...t_id=c519a85d\n      GAP OF 0x5c000 BYTES\n      mapped file                 1037cc000-1039c4000    [ 2016K] r-x\/rwx SM=COW  ...t_id=c530d95d",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":19795,"threadState":{"x":[{"value":4352475136},{"value":6128491120},{"value":617760},{"value":1},{"value":16777228},{"value":0},{"value":638976},{"value":617760},{"value":617760},{"value":12585216},{"value":4128},{"value":1},{"value":6128493170},{"value":0},{"value":9643084674},{"value":32768},{"value":11399362340},{"value":7701436843908750072},{"value":0},{"value":6128491120},{"value":638976},{"value":4352475136},{"value":16777228},{"value":0},{"value":4351836192},{"value":1},{"value":617760},{"value":16777228},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":6561885401499053340},"cpsr":{"value":536875008},"fp":{"value":6128490976},"sp":{"value":6128490960},"esr":{"value":2449473543,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":6931885632,"matchesCrashFrame":1},"far":{"value":4352475136}},"frames":[{"imageOffset":347712,"symbol":"dyld3::MachOFile::isMachO(Diagnostics&, unsigned long long) const","symbolLocation":40,"imageIndex":1},{"imageOffset":347420,"symbol":"dyld3::FatFile::isValidSlice(Diagnostics&, unsigned long long, unsigned int, unsigned int, unsigned int, unsigned long long, unsigned long long) const","symbolLocation":80,"imageIndex":1},{"imageOffset":348220,"symbol":"dyld3::FatFile::forEachSlice(Diagnostics&, unsigned long long, bool, void (unsigned int, unsigned int, void const*, unsigned long long, bool&) block_pointer) const","symbolLocation":332,"imageIndex":1},{"imageOffset":184020,"symbol":"dyld4::SyscallDelegate::mapFileReadOnly(Diagnostics&, char const*, unsigned long*, dyld4::FileID*, bool*, char*) const","symbolLocation":704,"imageIndex":1},{"imageOffset":181856,"symbol":"dyld4::SyscallDelegate::withReadOnlyMappedFile(Diagnostics&, char const*, bool, void (void const*, unsigned long, bool, dyld4::FileID const&, char const*) block_pointer) const","symbolLocation":88,"imageIndex":1},{"imageOffset":153236,"symbol":"dyld4::JustInTimeLoader::makeJustInTimeLoaderDisk(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, bool, unsigned int, mach_o::Layout const*)","symbolLocation":208,"imageIndex":1},{"imageOffset":115724,"symbol":"invocation function for block in dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&)","symbolLocation":1680,"imageIndex":1},{"imageOffset":112468,"symbol":"dyld4::Loader::forEachResolvedAtPathVar(dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, dyld4::ProcessConfig::PathOverrides::Type, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer)","symbolLocation":776,"imageIndex":1},{"imageOffset":36692,"symbol":"dyld4::ProcessConfig::PathOverrides::forEachPathVariant(char const*, dyld3::Platform, bool, bool, bool&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer) const","symbolLocation":488,"imageIndex":1},{"imageOffset":111244,"symbol":"dyld4::Loader::forEachPath(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&, void (char const*, dyld4::ProcessConfig::PathOverrides::Type, bool&) block_pointer)","symbolLocation":248,"imageIndex":1},{"imageOffset":113120,"symbol":"dyld4::Loader::getLoader(Diagnostics&, dyld4::RuntimeState&, char const*, dyld4::Loader::LoadOptions const&)","symbolLocation":588,"imageIndex":1},{"imageOffset":145200,"symbol":"invocation function for block in dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&)","symbolLocation":412,"imageIndex":1},{"imageOffset":354280,"symbol":"invocation function for block in dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const","symbolLocation":148,"imageIndex":1},{"imageOffset":8920,"symbol":"dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const","symbolLocation":296,"imageIndex":1},{"imageOffset":353840,"symbol":"dyld3::MachOFile::forEachDependentDylib(void (char const*, bool, bool, bool, unsigned int, unsigned int, bool&) block_pointer) const","symbolLocation":172,"imageIndex":1},{"imageOffset":144504,"symbol":"dyld4::JustInTimeLoader::loadDependents(Diagnostics&, dyld4::RuntimeState&, dyld4::Loader::LoadOptions const&)","symbolLocation":164,"imageIndex":1},{"imageOffset":27148,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":1236,"imageIndex":1},{"imageOffset":24088,"symbol":"start","symbolLocation":1964,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4338384896,
    "CFBundleShortVersionString" : "3.0.0",
    "CFBundleIdentifier" : "net.steampp.app",
    "size" : 1916928,
    "uuid" : "53b6e40d-362d-3893-a265-c270405be762",
    "path" : "\/Applications\/Steam++.app\/Contents\/MacOS\/Steam++",
    "name" : "Steam++",
    "CFBundleVersion" : "3.0.0.0"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6931537920,
    "size" : 583048,
    "uuid" : "e7a99595-e0f8-34af-be8b-9347d0d658a4",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6930874368,
  "size" : 3553361920,
  "uuid" : "40eab1ab-8b22-3dec-aa46-bb3136a05069"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=808.0M resident=0K(0%) swapped_out_or_unallocated=808.0M(100%)\nWritable regions: Total=8832K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8832K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE (reserved)             368K        4         reserved VM address space (unallocated)\n__DATA                             555K        3 \n__DATA_CONST                        86K        2 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       805.6M        2 \n__TEXT                            2444K        2 \ndyld private memory                272K        2 \nmapped file                       17.4M       40 \n===========                     =======  ======= \nTOTAL                            890.6M       58 \nTOTAL, minus reserved VM space   890.3M       58 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "7eade7e1fcf20a474146c15ad9732a25f693dd19",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "63582c5f8a53461413999550",
      "factorPackIds" : {

      },
      "deploymentId" : 240000002
    },
    {
      "rolloutId" : "62fe74515312cd4599bd3c80",
      "factorPackIds" : {
        "MYRIAD_BOOSTS" : "62fe74805312cd4599bd3c81"
      },
      "deploymentId" : 240000006
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "3a3cf641-8471-4e4e-9ad4-81d0ede970fd",
      "experimentId" : "64a84dae90d82611a0bd7d3d",
      "deploymentId" : 400000010
    },
    {
      "treatmentId" : "a092db1b-c401-44fa-9c54-518b7d69ca61",
      "experimentId" : "64a844035c85000c0f42398a",
      "deploymentId" : 400000019
    }
  ]
}
}

**Comment by Mossimos** [comment]
请前往 https://hk.mossimo.net/s/PLSG?path=%2F最新版本%2FMac 获取最新 dmg 尝试下 目前只替换了这里的包 其他地方的后续测试后会替换一下

**Comment by jingliancui** [comment]
@Mossimos 谢谢，你能否提供一个有速度的地址，上面那个link下50m就停了

**Comment by jingliancui** [comment]
刚刚试了，可用
