### ISSUE TITLE
👑[Enhancement] 启动时自动加速功能开关过于难找

### ISSUE THREAD

**Issue by Petard233** [BeyondDimension/SteamTools#2857]
### 🥰 需求描述(Description)
3.0版本的启动时自动加速功能开关过于难找，应像之前的版本一样放在加速设置的第一页中。

### 🧐 解决方案(Solution)
将启动时自动加速功能开关放在加速设置的第一页中。

### 🚑 其他信息(Other Information)
B站评论区已有网友提出相关问题。

**Comment by rmbadmin** [comment]
下个版本改进
