### ISSUE TITLE
🐛[BUG] 啊啊为什么我设置了启动时最小化到托盘还是会启动弹出啊啊啊啊啊

### ISSUE THREAD

**Issue by Xlongren** [BeyondDimension/SteamTools#2858]
## 请认真检查以下清单中的每一项
- [ ] 已经搜索过，没有发现类似的 issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 📷 复现步骤

1. 
2. 
3. 

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by rmbadmin** [comment]
这个问题已经不下三个人提过了，已经修复了，等更新
