### ISSUE TITLE
🐛[BUG] 启动时steam++无法最小化启动

### ISSUE THREAD

**Issue by luraminate** [BeyondDimension/SteamTools#2874]
## 请认真检查以下清单中的每一项
- [√ ] 已经搜索过，没有发现类似的 issue
- [√ ] 已经搜索过文档，没有发现相关内容
- [√ ] 已经尝试使用过最新版，问题依旧存在
- [ √] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

启动时steam++无法最小化启动
--

### 📷 复现步骤
1. 安装路径选择D:\Program Files\Watt Toolkit
2. 打开开机自启动和启动时最小化到托盘
3. 重启电脑

### 📄 日志信息

HiBit「启动管理器」报告
名称                                                                         说明                        命令行                                                                                                           发布者
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Steam                                                                        Steam                                  "d:\Program Files (x86)\Steam\steam.exe" -silent                                                                       Valve Corporation
Steam++_{S-1-5-21-1241297756-255518023-2993173338-1001}                                                             找不到文件:  Steam++.exe -clt c -silence                                                                                    

### 🖼 截图
暂无
### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：windows 11专业版 22621.2134 Revios定制游戏系统
- 下载渠道：官方（蓝奏云）
- 程序版本：3.0.0 rc .1
- 是否包含独立运行时：无

**Comment by rmbadmin** [comment]
已修复问题，等新版本更新

**Comment by luraminate** [comment]
感谢优化
