### ISSUE TITLE
🐛[BUG] Steam退出后软件崩溃

### ISSUE THREAD

**Issue by chenxiex** [BeyondDimension/SteamTools#2876]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

Steam退出后软件也一并崩溃。

### 📷 复现步骤

1. 启动watt-toolkit
2. 启动网络加速（Steam服务、公共CDN和国外验证码平台）
3. 启动Steam
4. 右键单击Steam托盘图标，退出Steam

### 📄 日志信息

[nlog-all-2023-09-16.log](https://github.com/BeyondDimension/SteamTools/files/12640821/nlog-all-2023-09-16.log)
### 🚑 其他信息
终端输出：
```
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe (pipe is disconnected).
src/common/pipes.cpp (883) : Fatal assert; application exiting
src/common/pipes.cpp (883) : Fatal assert; application exiting
assert_20230916214059_3.dmp[18649]: Uploading dump (out-of-process)
/tmp/dumps/assert_20230916214059_3.dmp
_ExitOnFatalAssert
assert_20230916214059_3.dmp[18649]: Finished uploading minidump (out-of-process): success = yes
assert_20230916214059_3.dmp[18649]: response: Discarded=1
assert_20230916214059_3.dmp[18649]: file ''/tmp/dumps/assert_20230916214059_3.dmp'', upload yes: ''Discarded=1''
```

- 处理器体系结构：x64 
- 系统版本号：Manjaro Linux Gnome Edition 
- 下载渠道：AUR 
- 程序版本：3.0.0-rc.1 
- 是否包含独立运行时：否

**Comment by AigioL** [comment]
log 文件中没有包含闪退的异常，src/common/pipes.cpp 这个疑似是 steamclient.so 中出现的，这个可能引发了非托管异常导致闪退，看上去是 Steam 在这个发行版上的 bug

https://github.com/ValveSoftware/steam-for-linux/issues/5899
https://github.com/sapphonie/StAC-tf2/issues/59

**Comment by chenxiex** [comment]
我这边现在也没法稳定复现这个bug。如果有新的线索再发上来吧。
