### ISSUE TITLE
win10设置了开机自启动和启动时最小化到托盘 ，但是我每次开机时，软件都不是最小化到托盘的

### ISSUE THREAD

**Issue by wantosleep3** [BeyondDimension/SteamTools#2896]
- 处理器体系结构： x64 
- 系统版本号：win10家庭22H2
- 下载渠道：官网 
- 程序版本：3.0.0 rc.1 for windows(x64)

**Comment by rmbadmin** [comment]
已经修复的问题，等更新就好了
