### ISSUE TITLE
👑[Enhancement] 希望其他网站增加 ‘https://hub.docker.com’

### ISSUE THREAD

**Issue by kksay2010** [BeyondDimension/SteamTools#2897]
查看docker镜像网络不方便，希望其他网站里增加 ‘https://hub.docker.com’

**Comment by xiaolan610** [comment]
@AigioL 来看看

**Comment by iDTer** [comment]
+1

**Comment by winerchan** [comment]
虽然访问不了dockerhub好像是因为其被加入了禁止名单，网站主动拒绝部分国家访问
详见服务条款20.8([https://www.docker.com/legal/docker-terms-service/](https://www.docker.com/legal/docker-terms-service/))
但却是还是希望能做到...单位不允许走代理（至少不能是代理目标境外的主动代理.....）之类想看个技术文档找个容器镜像啥的太难了

**Comment by 781011762** [comment]
+1

**Comment by akwangl** [comment]
好像现在只能挂梯子看镜像说明。。。。

**Comment by rmbadmin** [comment]
已热更新支持在github加速分组中
