### ISSUE TITLE
👑[Enhancement] 增加对 Wikipedia 的加速支持

### ISSUE THREAD

**Issue by Nightingale0504** [BeyondDimension/SteamTools#2909]
### 🥰 需求描述(Description)

由于我平常会在 Wikipedia 上查阅资料，而我所使用的VPN没有电脑版本，很不方便，所以请在 Watt Toolkit 中增加对 Wikipedia 的加速支持

**Comment by PandaFiredoge** [comment]
请参考https://zh.wikipedia.org/wiki/Help:%E5%A6%82%E4%BD%95%E8%AE%BF%E9%97%AE%E7%BB%B4%E5%9F%BA%E7%99%BE%E7%A7%91
