### ISSUE TITLE
win10证书出错

### ISSUE THREAD

**Issue by 1144766526** [BeyondDimension/SteamTools#2913]
### 🧐 问题描述

换固态把系统盘直接换了，重装完系统之后开启加速进入github和steam都提示证书出问题，移除证书再安装也不行，于是去下了最新版试试，但无变化，同时拳头平台账号无法检测

### 🚑 其他信息

github提示
![未连接：有安全风险 — Mozilla Firefox 2023_9_25 16_01_23](https://github.com/BeyondDimension/SteamTools/assets/122301488/147896f6-06f9-4a1d-b775-289f2e12bb5c)
证书页
![2023-09-25_161233](https://github.com/BeyondDimension/SteamTools/assets/122301488/2b098843-6e9a-4dc4-a294-aa97f4da0aab)
错误代码页
![2023-09-25_161315](https://github.com/BeyondDimension/SteamTools/assets/122301488/98544951-f124-4b5c-bbca-a888c91237e2)

steam提示
![2023-09-25_161844](https://github.com/BeyondDimension/SteamTools/assets/122301488/0af5fee7-c7cd-4d3a-a80c-b7b3cbc60233)
证书页
![2023-09-25_161952](https://github.comeyondDimension/SteamTools/assets/122301488/7071d14f-778e-4e5e-ae45-0dcea14ed999)
错误代码页
![2023-09-25_164524](https://github.com/BeyondDimension/SteamTools/assets/122301488/ad2ea56b-5502-4fad-8d61-cc5667b0c555)

无法检测拳头账号
![2023-09-25_161741](https://github.com/BeyondDimension/SteamTools/assets/122301488/dba9764b-a4ef-45c4-bd55-8d36e48fc8f5)

- 处理器体系结构和系统版本号：
![2023-09-25_163552](https://github.com/BeyondDimension/SteamTools/assets/122301488/8d879b5a-924e-4692-af3e-be9eb392694d)

- 下载渠道：官网 
- 程序版本：3.0.0-rc.1
- 是否包含独立运行时：否

**Comment by 1144766526** [comment]
补图
![2023-09-25_161952](https://github.com/BeyondDimension/SteamTools/assets/122301488/44417b23-1c26-4cbf-9635-a5acdfae5fc2)

**Comment by OldGodShen** [comment]
火狐浏览器走的是自己的证书信任，要在火狐浏览器里面单独导入一次

**Comment by 1144766526** [comment]
> 火狐浏览器走的是自己的证书信任，要在火狐浏览器里面单独导入一次

谢谢大佬，确实是这个问题，问题解决了
