### ISSUE TITLE
🐛[BUG] macos打开GitHub显示不安全

### ISSUE THREAD

**Issue by AMlhd** [BeyondDimension/SteamTools#2926]
## 每一次打开GitHub时, 都会显示“你使用的不是专用链接”
每一次都要输入“Thisisunsafe”, 及其麻烦,望官方解决此问题
![](https://cdn.luogu.com.cn/upload/image_hosting/074vku2z.png)

**Comment by Mossimos** [comment]
什么版本的 如果是 2.x 去钥匙串把证书取消信任然后重新信任一遍

**Comment by AMlhd** [comment]
> 什么版本的 如果是 2.x 去钥匙串把证书取消信任然后重新信任一遍
是3.0.0 r2 版本的

**Comment by AMlhd** [comment]
> 什么版本的 如果是 2.x 去钥匙串把证书取消信任然后重新信任一遍

怎么搞

**Comment by Mossimos** [comment]
去钥匙串访问把证书取消信任然后重新信任一遍 这就是方法 已经说的很明白了
https://github.com/BeyondDimension/SteamTools/issues/2376#issuecomment-1380107289
