### ISSUE TITLE
🐛[BUG] img-sketch.pixiv.net: 421 Misdirected Request

### ISSUE THREAD

**Issue by moi-si** [BeyondDimension/SteamTools#2938]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
访问[pixiv Sketch](https://sketch.pixiv.net)时，#Items>div:nth-child(2)处的图片无法显示，图片的域名是[img-sketch.pixiv.net](https://img-sketch.pixiv.net)，均 421 Misdirected Request

### 📷 复现步骤

1. 勾选加速其他网站->Pixiv Sketch, Pixiv 图片加载
2. 点击“一键加速”
3. 访问[sketch.pixiv.net](https://sketch.pixiv.net)并等待加载界面完成

### 📄 日志信息
（无有关部分）
[nlog-all-2023-10-03.log](https://github.com/BeyondDimension/SteamTools/files/12789762/nlog-all-2023-10-03.log)

### 🖼 截图

![网页捕获_3-10-2023_153427_sketch pixiv net](https://github.com/BeyondDimension/SteamTools/assets/111831296/c7b3bf56-beea-4726-9a14-d99e281a5ce1)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 10 专业版 22H2 19045.3448
- 下载渠道：Github
- 程序版本：2.8.6 Latest
- 是否包含独立运行时：

**Comment by moi-si** [comment]
原因可能是 [img-sketch.pixiv.net](https://img-sketch.pixiv.net) 的Hosts被指定到了 [www.pixivision.net](https://www.pixivision.net) 的IP段，但是此域名只能指定为：
210.140.131.144,
210.140.131.147,
210.140.131.153,
210.140.131.145
在另一个工具测试没有问题。

**Comment by hexadecimal233** [comment]
在 https://id.twitch.tv/ 上复现
