### ISSUE TITLE
🐛[BUG] hosts文件权限无法永久生效

### ISSUE THREAD

**Issue by xulu199705** [BeyondDimension/SteamTools#2940]
Version: `v3.0.0-rc.2` from Github
Platform: macOS 14.0 arm64

### 🐛 描述

``` shell
sudo chmod +a 'user:用户名:allow write' /etc/hosts
```

使用上述命令(用户名匿了)对hosts文件权限修改后，权限仅单次生效，无法永久生效；
`steam++`在开/关加速时会不间断跳转官网的[Host文件权限](https://steampp.net/unixhostaccess)帮助页面

**Comment by Mossimos** [comment]
我测试 是不会出现这种问题。 请检查下是否有 其他程序锁定了 Host 文件的权限。

**Comment by xulu199705** [comment]
> 我测试 是不会出现这种问题。 请检查下是否有 其他程序锁定了 Host 文件的权限。

感谢排查；
我这几天测试了，确实找到了有锁定host的程序。
