### ISSUE TITLE
🐛[BUG] WattToolkit修改hosts文件后导致杀毒软件报毒，不停将hosts删除

### ISSUE THREAD

**Issue by ghost** [BeyondDimension/SteamTools#2941]
操作系统：Windows 11 企业版 22H2（通过MSDN官方镜像安装，非盗版）
系统版本：22621.2361
软件版本：Watt Toolkit x64 v3.0.0-rc2 for Windows
杀毒软件与版本：ESET NOD32 Smart Security Premium 16.2.15.0

![WattToolkit](https://github.com/BeyondDimension/SteamTools/assets/84257664/ecd48e87-d3a1-4de6-9667-01ceb19d9e12)

问题描述：
全新安装的操作系统，从Github上下载的Watt Toolkit安装包。
安装Watt Toolkit并运行“一键加速”后，软件对系统hosts文件进行修改：

----- 以下为Watt Toolkit添加的内容 -----

# Steam++ Start
127.0.0.1 steam-chat.com
127.0.0.1 steamcdn-a.akamaihd.net
127.0.0.1 cdn.akamai.steamstatic.com
127.0.0.1 community.akamai.steamstatic.com
127.0.0.1 avatars.akamai.steamstatic.com
127.0.0.1 community.steamstatic.com
127.0.0.1 store.akamai.steamstatic.com
127.0.0.1 media.steampowered.com
127.0.0.1 steamcommunity.com
127.0.0.1 www.steamcommunity.com
127.0.0.1 store.steampowered.com
127.0.0.1 api.steampowered.com
127.0.0.1 help.steampowered.com
127.0.0.1 login.steampowered.com
127.0.0.1 checkout.steampowered.com
127.0.0.1 origin-a.akamaihd.net
127.0.0.1 fonts.gstatic.com
127.0.0.1 gravatar.com
127.0.0.1 secure.gravatar.com
127.0.0.1 www.gravatar.com
127.0.0.1 themes.googleusercontent.com
127.0.0.1 ajax.googleapis.com
127.0.0.1 fonts.googleapis.com
127.0.0.1 maxcdn.bootstrapcdn.com
127.0.0.1 google.com
127.0.0.1 www.google.com
127.0.0.1 hcaptcha.com
127.0.0.1 assets.hcaptcha.com
127.0.0.1 imgs.hcaptcha.com
127.0.0.1 www.hcaptcha.com
127.0.0.1 docs.hcaptcha.com
127.0.0.1 js.hcaptcha.com
127.0.0.1 newassets.hcaptcha.com
127.0.0.1 client-api.arkoselabs.com
127.0.0.1 epic-games-api.arkoselabs.com
127.0.0.1 cdn.arkoselabs.com
127.0.0.1 prod-ireland.arkoselabs.com
127.0.0.1 api.github.com
127.0.0.1 gist.github.com
127.0.0.1 raw.github.com
127.0.0.1 githubusercontent.com
127.0.0.1 raw.githubusercontent.com
127.0.0.1 camo.githubusercontent.com
127.0.0.1 cloud.githubusercontent.com
127.0.0.1 avatars.githubusercontent.com
127.0.0.1 avatars0.githubusercontent.com
127.0.0.1 avatars1.githubusercontent.com
127.0.0.1 avatars2.githubusercontent.com
127.0.0.1 avatars3.githubusercontent.com
127.0.0.1 user-images.githubusercontent.com
127.0.0.1 github.com
127.0.0.1 pages.github.com
127.0.0.1 githubapp.com
127.0.0.1 github.io
127.0.0.1 www.github.io
127.0.0.1 pinterest.com
127.0.0.1 www.pinterest.com
127.0.0.1 pinimg.com
127.0.0.1 sm.pinimg.com
127.0.0.1 s.pinimg.com
127.0.0.1 i.pinimg.com
127.0.0.1 artstation.com
127.0.0.1 www.artstation.com
127.0.0.1 cdn-learning.artstation.com
127.0.0.1 cdna.artstation.com
127.0.0.1 cdn.artstation.com
127.0.0.1 cdnb.artstation.com
127.0.0.1 aleksi.artstation.com
127.0.0.1 aroll.artstation.com
127.0.0.1 dya.artstation.com
127.0.0.1 yourihoek.artstation.com
127.0.0.1 rishablue.artstation.com
127.0.0.1 ww.artstation.com
127.0.0.1 magazine.artstation.com
127.0.0.1 v2ex.com
127.0.0.1 www.v2ex.com
127.0.0.1 cdn.v2ex.com
127.0.0.1 imgur.com
127.0.0.1 i.imgur.com
127.0.0.1 s.imgur.com
127.0.0.1 i.stack.imgur.com
127.0.0.1 m.imgur.com
127.0.0.1 api.imgur.com
127.0.0.1 p.imgur.com
127.0.0.1 www.imgur.com
127.0.0.1 fufufu23.imgur.com
127.0.0.1 thepoy.imgur.com
127.0.0.1 blog.imgur.com
127.0.0.1 cellcow.imgur.com
127.0.0.1 t.imgur.com
127.0.0.1 sketch.pixiv.net
127.0.0.1 pixivsketch.net
127.0.0.1 www.pixivsketch.net
127.0.0.1 pximg.net
127.0.0.1 i.pximg.net
127.0.0.1 s.pximg.net
127.0.0.1 img-sketch.pximg.net
127.0.0.1 source.pximg.net
127.0.0.1 booth.pximg.net
127.0.0.1 i-f.pximg.net
127.0.0.1 imp.pximg.net
127.0.0.1 public-img-comic.pximg.net
127.0.0.1 vercel.app
127.0.0.1 www.pixiv.net
127.0.0.1 touch.pixiv.net
127.0.0.1 source.pixiv.net
127.0.0.1 accounts.pixiv.net
127.0.0.1 imgaz.pixiv.net
127.0.0.1 app-api.pixiv.net
127.0.0.1 oauth.secure.pixiv.net
127.0.0.1 dic.pixiv.net
127.0.0.1 comic.pixiv.net
127.0.0.1 factory.pixiv.net
127.0.0.1 g-client-proxy.pixiv.net
127.0.0.1 payment.pixiv.net
127.0.0.1 sensei.pixiv.net
127.0.0.1 novel.pixiv.net
127.0.0.1 ssl.pixiv.net
127.0.0.1 times.pixiv.net
127.0.0.1 recruit.pixiv.net
127.0.0.1 pixiv.net
127.0.0.1 p2.pixiv.net
127.0.0.1 matsuri.pixiv.net
127.0.0.1 m.pixiv.net
127.0.0.1 iracon.pixiv.net
127.0.0.1 inside.pixiv.net
127.0.0.1 i1.pixiv.net
127.0.0.1 help.pixiv.net
127.0.0.1 goods.pixiv.net
127.0.0.1 genepixiv.pr.pixiv.net
127.0.0.1 festa.pixiv.net
127.0.0.1 en.dic.pixiv.net
127.0.0.1 dev.pixiv.net
127.0.0.1 chat.pixiv.net
127.0.0.1 blog.pixiv.net
127.0.0.1 embed.pixiv.net
127.0.0.1 comic-api.pixiv.net
127.0.0.1 pay.pixiv.net
127.0.0.1 pixon.ads-pixiv.net
127.0.0.1 link.pixiv.net
127.0.0.1 in.appcenter.ms
127.0.0.1 appcenter.ms
# Steam++ End

------------------------------

**hosts文件修改后导致杀毒软件不停报毒，并且不断将hosts文件删除（就算手动将hosts文件加入“排除”列表，只要有软件读取hosts文件，也会导致hosts文件被报毒查杀）。**

本人已做过多次测试，只要将Watt Toolkit添加进hosts文件的那些地址删除，杀毒软件就不会再报毒查杀，但会影响Watt Toolkit使用。
还请开发组的各位大佬核实一下，优化hosts文件的修改方式。

**Comment by rmbadmin** [comment]
你可以杀毒软件添加白名单或者使用其他加速模式
