### ISSUE TITLE
👑[Enhancement] 程序结束时/结束系统代理时将windows系统的局域网设置复原

### ISSUE THREAD

**Issue by ToKiNoBug** [BeyondDimension/SteamTools#2944]
### 🥰 需求描述(Description)

目前 SteamTools在windows平台下开启系统代理时，会修改局域网设置中的代理服务器设置（可以在`控制面板>网络和Internet>Internet选项>Internet属性>连接>局域网设置`中看到），但程序结束时或系统代理结束时并不会复原这部分设置，导致代理服务器指向一个无服务的端口，这会导致打开其他网页（尤其是各种wifi登录网页）时出现“代理服务器拒绝连接”的错误。

### 🧐 解决方案(Solution)

希望在开启代理前存储一下原先的代理服务器设置，在程序结束时或者系统代理结束时复原这部分设置。

### 🚑 其他信息(Other Information)

代理服务器拒绝连接的截图：
<img width="331" alt="屏幕截图 2023-10-08 100747" src="https://github.com/BeyondDimension/SteamTools/assets/62002934/116ea91b-3b5d-4cd2-9116-e3f8c70529f1">

未被复原的局域网（LAN）设置：
<img width="349" alt="屏幕截图 2023-10-08 100915" src="https://github.com/BeyondDimension/SteamTools/assets/62002934/9b07989c-cb09-41d9-ae08-27723ffd7fa2">

**Comment by rmbadmin** [comment]
请给出问题版本和加速使用的加速模式情况，这个问题应该是不存在的
