### ISSUE TITLE
🐛[BUG] 

### ISSUE THREAD

**Issue by xwxqwqpwpawa** [BeyondDimension/SteamTools#2999]
## 请认真检查以下清单中的每一项
- [/] 已经搜索过，没有发现类似的 issue
- [/] 已经搜索过文档，没有发现相关内容
- [/] 已经尝试使用过最新版，问题依旧存在
- [/] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

"此应用程序仅兼容Windows 11 与 Windows 10 版本 1809 （OS内部版本17763） 或更高版本"

### 📷 复现步骤

1. 在Windows 7运行Watt Toolkit v3.0.0-rc.2
2. 
3. 

### 🖼 截图

![image](https://github.com/BeyondDimension/SteamTools/assets/111604312/db058819-5378-41f3-b488-05ef240bb1da)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 7 7601
- 下载渠道：蓝揍云
- 程序版本：v3.0.0-rc.2
- 是否包含独立运行时：包含

**Comment by rmbadmin** [comment]
win7请使用3.0之前的版本
