### ISSUE TITLE
👑[Enhancement] 加速仅启用脚本

### ISSUE THREAD

**Issue by RottenSea** [BeyondDimension/SteamTools#3002]
### 🥰 需求描述(Description)

> 使用脚本(steamdb，也就是历史价格查询)时，有一个要求：需要启用steam商店加速。
> 我个人不是很理解为什么会有这个硬性要求，我全天挂clash，如果同时使用steampp的加速(hosts模式)，就会导致商店页面大概率加载不出来

### 🧐 解决方案(Solution)

> 希望能将这个硬性需求更改为建议

**Comment by rmbadmin** [comment]
因为脚本依赖加速对应的域名才能注入，代理设置中是有仅启用脚本功能的。

**Comment by RottenSea** [comment]
> 因为脚本依赖加速对应的域名才能注入，代理设置中是有仅启用脚本功能的。

我清楚设置中有仅启用脚本功能，就是不解为什么脚本还需要对应域名才能用?

**Comment by HAMAN23333** [comment]
> > 因为脚本依赖加速对应的域名才能注入，代理设置中是有仅启用脚本功能的。
> 
> 我清楚设置中有仅启用脚本功能，就是不解为什么脚本还需要对应域名才能用?

这应该是MITM中间人攻击的方式注入脚本，实际上不用加速域名，只需要解析就行了，Quantumult和Surge就是这样的原理，我也比较迷惑为什么会需要加速

而且我在开启**代理仅启用脚本功能**的情况下反而无法注入脚本，必须在勾选加速商店的情况下才能使用

以下是我自己的clash规则和watt toolkit配置，然后关闭watt的doh加密dns设置，直接让clash接管dns设置

![image](https://github.com/BeyondDimension/SteamTools/assets/80085265/7f9d6a74-0f30-4824-afad-d21616e683a0)
![image](https://github.com/BeyondDimension/SteamTools/assets/80085265/58c9e2d7-f049-4f3e-b2c0-9aad410dba49)
