### ISSUE TITLE
🧐[Question] 把discord的加速删了吗？

### ISSUE THREAD

**Issue by superteaa** [BeyondDimension/SteamTools#3024]
如果可以的话，求求把discord加回来吧，孩子不能没有它。

**Comment by juluoawa** [comment]
对啊，考虑考虑一些人的感受吧，只有这个加速器可以加速discord，现在都没了QAQ

**Comment by OldGodShen** [comment]
我也突然发现了没discord了

**Comment by Dshez1** [comment]
求求加回来吧

**Comment by seakoria** [comment]
请问，删掉discord加速的原因是？

**Comment by Ovo0ov** [comment]
呜呜加回来吧TvT

**Comment by whnoyt** [comment]
加回来吧QAQ

**Comment by juluoawa** [comment]
求求官方看看我们的建议吧，我认识的人都在等

**Comment by DrAkile** [comment]
discord怎么没了，求您快加回来，急用啊，我丢，加回来呗，现在咋还删加速选项啊

**Comment by Minecraft-YUN** [comment]
不仅discord没了，pixiv也没了

**Comment by qingyu308** [comment]
我不希望看到什么因政府要求什么什么的

**Comment by mikunameless** [comment]
别啊一直在用加速discord不想离开一分一秒

**Comment by who-care123** [comment]
加回来吧 多少人就是因为可以加速discord才用的

**Comment by HDD187** [comment]
为什么用不了discord，我好难过，呜呜呜呜呜呜

**Comment by DisguiserZERO** [comment]
回来吧QAQ

**Comment by rmbadmin** [comment]
不好意思，实际上就是因为大家想的原因，我也没有办法过多的说什么。这类相关的问题目前暂时是没有办法提供处理了，对各位说声抱歉。
