### ISSUE TITLE
🧐[Question] 11月24日星期五，怎么突然访问不了pixiv呢

### ISSUE THREAD

**Issue by Minecraft-YUN** [BeyondDimension/SteamTools#3025]
昨天还能访问的今天突然寄了，以前也有类似的情况

**Comment by wdsjgj** [comment]
我也是
不知道为什么

**Comment by 4887441** [comment]
现在连P站的加速选项都无了

**Comment by Minecraft-YUN** [comment]
> 现在连P站的加速选项都无了

手机上2.8.3也没了，不知道还搞不搞了

**Comment by wdsjgj** [comment]
估计是这几天官方入住B站了，为了正规化而删掉P站的吧

**Comment by Minecraft-YUN** [comment]
> 估计是这几天官方入住B站了，为了正规化而删掉P站的吧

高情商：为了正规化
低情商：寄

**Comment by klee13919909068** [comment]
加回来吧求求了

**Comment by rmbadmin** [comment]
不好意思，实际上就是因为大家想的原因，我也没有办法过多的说什么。这类相关的问题目前暂时是没有办法提供处理了，对各位说声抱歉。
