### ISSUE TITLE
🧐[Question] pixiv加速选项消失

### ISSUE THREAD

**Issue by 4887441** [BeyondDimension/SteamTools#3026]
### 🧐 问题描述

其他网站的图标仍是pixiv，但加速选项中没有pixiv的选项。
是遭遇BUG还是不支持pixiv加速了？

### 🚑 其他信息
<img width="655" alt="屏幕截图 2023-11-24 195958" src="https://github.com/BeyondDimension/SteamTools/assets/151929192/cfaccb2b-c700-416f-94dd-b3c9470f3186">

- 处理器体系结构：x64 
- 系统版本号：example Windows 10 22h2
- 下载渠道：微软商店
- 程序版本：2.8.6
- 是否包含独立运行时：不清楚

**Comment by YB-10032** [comment]
补充一下3.0.0rc2也没有了pixiv的加速项

**Comment by wdsjgj** [comment]
是不是以后不搞P站了？？
现在用不了？

**Comment by Minecraft-YUN** [comment]
正式版2.8.6也一样

**Comment by 4887441** [comment]
> 正式版2.8.6也一样
试了一下更早的2.6.2版本也不存在P站的选项。

**Comment by Minecraft-YUN** [comment]
> > 正式版2.8.6也一样
> > 试了一下更早的2.6.2版本也不存在P站的选项。

手机的2.8.3也没了，不会不搞了吧

**Comment by 4887441** [comment]
> > > 正式版2.8.6也一样
> > > 试了一下更早的2.6.2版本也不存在P站的选项。
> 
> 手机的2.8.3也没了，不会不搞了吧

可能是想正规化或者听到什么风声了？看别的问题貌似discord也给撤了。

**Comment by Minecraft-YUN** [comment]
> > > > 正式版2.8.6也一样
> > > > 试了一下更早的2.6.2版本也不存在P站的选项。
> > 
> > 
> > 手机的2.8.3也没了，不会不搞了吧
> 
> 可能是想正规化或者听到什么风声了？看别的问题貌似discord也给撤了。

用steam++就是为了上discord和pixiv的，这回撤了用屁啊，还不是得翻墙，免费的墙不好用，付费的又贵，现在steam++没了这些现在已经不知道咋搞了

**Comment by 4887441** [comment]
> > > > > 正式版2.8.6也一样
> > > > > 试了一下更早的2.6.2版本也不存在P站的选项。
> > > 
> > > 
> > > 手机的2.8.3也没了，不会不搞了吧
> > 
> > 
> > 可能是想正规化或者听到什么风声了？看别的问题貌似discord也给撤了。
> 
> 用steam++就是为了上discord和pixiv的，这回撤了用屁啊，还不是得翻墙，免费的墙不好用，付费的又贵，现在steam++没了这些现在已经不知道咋搞了

至少能用来上github和创意工坊。省一点魔法流量是好的。记得steam++普及之前P站就已经有反代理方案了。改天可以找找试试。

**Comment by Minecraft-YUN** [comment]
> > > > > > 正式版2.8.6也一样
> > > > > > 试了一下更早的2.6.2版本也不存在P站的选项。
> > > > 
> > > > 
> > > > 手机的2.8.3也没了，不会不搞了吧
> > > 
> > > 
> > > 可能是想正规化或者听到什么风声了？看别的问题貌似discord也给撤了。
> > 
> > 
> > 用steam++就是为了上discord和pixiv的，这回撤了用屁啊，还不是得翻墙，免费的墙不好用，付费的又贵，现在steam++没了这些现在已经不知道咋搞了
> 
> 至少能用来上github和创意工坊。省一点魔法流量是好的。记得steam++普及之前P站就已经有反代理方案了。改天可以找找试试。

佬，找到@我一声，谢谢

**Comment by 2590672259** [comment]
> > > > > > 正式版2.8.6也一样
> > > > > > 试了一下更早的2.6.2版本也不存在P站的选项。
> > > > 
> > > > 
> > > > 手机的2.8.3也没了，不会不搞了吧
> > > 
> > > 
> > > 可能是想正规化或者听到什么风声了？看别的问题貌似discord也给撤了。
> > 
> > 
> > 用steam++就是为了上discord和pixiv的，这回撤了用屁啊，还不是得翻墙，免费的墙不好用，付费的又贵，现在steam++没了这些现在已经不知道咋搞了
> 
> 至少能用来上github和创意工坊。省一点魔法流量是好的。记得steam++普及之前P站就已经有反代理方案了。改天可以找找试试。

佬 找到也麻烦帮帮我P站上不去太难受了

**Comment by ws2bhhh** [comment]
> 佬 找到也麻烦帮帮我P站上不去太难受了
 > 
移动端推荐PixEz，桌面端不知道PixEz是否可用

**Comment by 2590672259** [comment]
> > 佬 找到也麻烦帮帮我P站上不去太难受了
> 
> 移动端推荐PixEz，桌面端不知道PixEz是否可用

只有PC端的

**Comment by rmbadmin** [comment]
不好意思，实际上就是因为大家想的原因，我也没有办法过多的说什么。这类相关的问题目前暂时是没有办法提供处理了，对各位说声抱歉。

**Comment by lixin2009** [comment]
可以试一下早期版本，如1.x.x什么的，但苦于没有资源。不知道哪位大佬可以提供一下这个古董级别版本的存档，十分感谢。

**Comment by ws2bhhh** [comment]
> 可以试一下早期版本，如1.x.x什么的，但苦于没有资源。不知道哪位大佬可以提供一下这个古董级别版本的存档，十分感谢。

属于是骑驴找驴😂
[https://github.com/BeyondDimension/SteamTools/releases/tag/1.1.1](url)

**Comment by buleGX** [comment]
https://gitee.com/rmbgame/SteamTools/releases/tag/1.1.4

**Comment by buleGX** [comment]
这个新一点
https://gitee.com/rmbgame/SteamTools/releases/tag/1.1.4

**Comment by buleGX** [comment]
这个新一点
