### ISSUE TITLE
P站和discord链接怎么不见了

### ISSUE THREAD

**Issue by ZouNuoLan** [BeyondDimension/SteamTools#3028]
前两天还有的，今天突然没了，我下这个就是为了能访问P站和discord，Git偶尔也会加速一下但有时候直连也没问题，基本用不到这个。
现在各大加速器都能免费加速Steam了，包括雷神，而且还不用担心社区错误代码问题，如果以后也没加速P站和Discord那我也只能去找别的工具了

**Comment by FlashDragons** [comment]
是的，真要命。是不是逼着我用VPN？但找不到合适的啊。

**Comment by Minecraft-YUN** [comment]
估摸着上了b站为了正规化把这俩给砍了

**Comment by Minecraft-YUN** [comment]
> 前两天还有的，今天突然没了，我下这个就是为了能访问P站和discord，Git偶尔也会加速一下但有时候直连也没问题，基本用不到这个。 现在各大加速器都能免费加速Steam了，包括雷神，而且还不用担心社区错误代码问题，如果以后也没加速P站和Discord那我也只能去找别的工具了

佬，找到工具@我一声，谢谢

**Comment by ishamrla** [comment]
估计是有点风险才去掉的

**Comment by x1h0126** [comment]
可太突然了直接没了，哎算了，理解，理解

**Comment by MDeath** [comment]
动态更新的，不重启服务还能继续用

**Comment by cohhi** [comment]
唉，可惜了，一直用的这个免费的

**Comment by ghost** [comment]
找到可以访问dis的工具@我一声，谢谢

**Comment by rmbadmin** [comment]
#3060
