### ISSUE TITLE
🧐[Question] Kali虚拟机从官网下载出错

### ISSUE THREAD

**Issue by imagebuilder1837** [BeyondDimension/SteamTools#3029]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

Kali虚拟机中运行 curl -sSL https://steampp.net/Install/Linux.sh | bash ，提示下载出错

### 🚑 其他信息

![20231125121812737.png](https://raw.githubusercontent.com/image-builder-1837/ImageHost/main/20231125121812737.png)

- 处理器体系结构：x64
- 系统版本号：kali-linux-2023.3-vmware-amd64
- 下载渠道：官网
- 程序版本：3.0.0-rc.2
- 是否包含独立运行时：未知

**Comment by Mossimos** [comment]
可能无法连接 提供的下载服务器
虚拟机内能否访问  以下地址？
https://hk.mossimo.net/s/PLSG

**Comment by imagebuilder1837** [comment]
现在下载已经没问题了，但是证书配置完后加速仍然会报错
![](https://raw.githubusercontent.com/image-builder-1837/ImageHost/main/2023125214024444.png)
![](https://raw.githubusercontent.com/image-builder-1837/ImageHost/main/2023125214027102.png)

**Comment by Mossimos** [comment]
执行这段 后  echo $? 输出的返回代码是多少
`
CERT_NAME="SteamTools"
CERT_RESULT=$(certutil -L -d $HOME/.pki/nssdb | grep \"$CERT_NAME\")
if [ -n "$CERT_RESULT" ]; then
    echo "证书 '$CERT_NAME' 存在。"
    exit 200
else
    echo "证书 '$CERT_NAME' 不存在。"
    exit 10
fi
`

**Comment by imagebuilder1837** [comment]
如果我的操作没错的话返回代码是1
![2023126123150261.png](https://raw.githubusercontent.com/image-builder-1837/ImageHost/main/2023126123150261.png)

**Comment by imagebuilder1837** [comment]
而且我之前在下载安装阶段发现系统区域语言设置为zh_CN安装会报错，改成en_US后才正常

**Comment by imagebuilder1837** [comment]
> 而且我之前在下载安装阶段发现系统区域语言设置为zh_CN安装会报错，改成en_US后才正常

这是我在新虚拟机上复现输出的终端信息：
```shell
bash: 行 13: 警告：setlocale: LC_ALL: 无法改变区域设置 (en_US.UTF-8)：没有那个文件或目录
certutil 工具已安装。
zenity 工具已安装。
jq 工具已安装。
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
即将初始化 certutil sql:$HOME/.pki/nssdb
certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.
--2023-12-05 23:44:55--  https://api.steampp.net/basic/versions/8/16/1/2023/3/-1/0/
Resolving api.steampp.net (api.steampp.net)... 40.73.96.128, 2404:7940:300:2::10
Connecting to api.steampp.net (api.steampp.net)|40.73.96.128|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: '/home/kali/WattToolkit/WattToolkit.AppVer'

/home/kali/WattTool     [ <=>             ]   3.37K  --.-KB/s    in 0s      

2023-12-05 23:44:55 (59.5 MB/s) - '/home/kali/WattToolkit/WattToolkit.AppVer' saved [3448]

cat: AppVer: No such file or directory

(process:2837): Gtk-WARNING **: 23:44:56.267: Locale not supported by C library.
        Using the fallback 'C' locale.
This option is not available. Please see --help for all possible usages.

(process:2871): Gtk-WARNING **: 23:44:59.414: Locale not supported by C library.
        Using the fallback 'C' locale.
This option is not available. Please see --help for all possible usages.

(process:2924): Gtk-WARNING **: 23:45:04.897: Locale not supported by C library.
        Using the fallback 'C' locale.
This option is not available. Please see --help for all possible usages.

(process:2964): Gtk-WARNING **: 23:45:08.226: Locale not supported by C library.
        Using the fallback 'C' locale.
This option is not available. Please see --help for all possible usages.
```

**Comment by Mossimos** [comment]
LC_ALL 咋会没有 en_US.UTF-8 呢

**Comment by Mossimos** [comment]
![image](https://github.com/BeyondDimension/SteamTools/assets/26396340/3fa4a4be-b0ba-4a8e-ae3b-4590c819b0e3)
Github 为啥没换行很奇怪

**Comment by Mossimos** [comment]
CERT_NAME="SteamTools"
CERT_RESULT=$(certutil -L -d $HOME/.pki/nssdb | grep "$CERT_NAME")
if [ -n "$CERT_RESULT" ]; then
    echo "证书 '$CERT_NAME' 存在。"
    exit 200
else
    echo "证书 '$CERT_NAME' 不存在。"
    exit 10
fi

**Comment by imagebuilder1837** [comment]
`test.sh` 里面是测试代码，exit code应该是10
![2023126131032257.png](https://raw.githubusercontent.com/image-builder-1837/ImageHost/main/2023126131032257.png)

**Comment by imagebuilder1837** [comment]
> ![image](https://private-user-images.githubusercontent.com/26396340/288287145-3fa4a4be-b0ba-4a8e-ae3b-4590c819b0e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4Mzk0MzcsIm5iZiI6MTcwMTgzOTEzNywicGF0aCI6Ii8yNjM5NjM0MC8yODgyODcxNDUtM2ZhNGE0YmUtYjBiYS00YThlLWFlM2ItNDU5MGM4MTliMGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA1MDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZjY1YzYyNDM2MmQ0NzY1ODcwM2E2NjQwOWYzMDIzMTFmZDM5NGM2ZjVhNDQ3Y2RhMDgyNDFlM2I2ZGRiNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UtgeG8E5_UJeWyUV-hx8fMaO6HeR8_CabWT8kfgp550) Github 为啥没换行很奇怪

大概是因为Markdown中代码块是三个反引号包裹，一个反引号会被视为单行代码

**Comment by Mossimos** [comment]
$HOME/.pki/nssdb 这个目录存在不 下面有没有 文件夹

**Comment by Mossimos** [comment]
如果 
`certutil -d $HOME/.pki/nssdb -L`
还是输出 bad database 且  $HOME/.pki/nssdb 目录有文件 
尝试 
`rm -f $HOME/.pki/nssdb`
然后初始化 db
```
        mkdir -p $HOME/.pki/nssdb
        chmod 700 $HOME/.pki/nssdb
        certutil -d $HOME/.pki/nssdb -N --empty-password
```
再用程序加速

**Comment by imagebuilder1837** [comment]
不存在`~/.pki` 文件夹
![2023126132322256.png](https://raw.githubusercontent.com/image-builder-1837/ImageHost/main/2023126132322256.png)

**Comment by Mossimos** [comment]
安装脚本中 应该会初始化该数据库
```
        echo "即将初始化 certutil \$HOME/.pki/nssdb"
        mkdir -p $HOME/.pki
        mkdir -p $HOME/.pki/nssdb
        chmod 700 $HOME/.pki/nssdb
        certutil -d $HOME/.pki/nssdb -N --empty-password
```

**Comment by imagebuilder1837** [comment]
谢谢，运行脚本后问题已解决
