### ISSUE TITLE
加回pixiv的加速吧

### ISSUE THREAD

**Issue by Muelsyse1103** [BeyondDimension/SteamTools#3032]

**Comment by Minecraft-YUN** [comment]
感觉开发应该不会看

**Comment by klee13919909068** [comment]
一直都是用steam++上p站的

**Comment by pigrass** [comment]
希望加回去+1

**Comment by 2590672259** [comment]
加回去！加回去！

**Comment by FlashDragons** [comment]
别忘了还有discord！😥

**Comment by KeeKalm** [comment]
希望能重新支持

**Comment by HINOUMI** [comment]
我看P站就是用这个😓没了这个我还真不知道有哪个加速器可以免费加速p站了
求添加回来❤

**Comment by anyexingkongkefeng** [comment]
拜托加回去吧！

**Comment by daycold1000** [comment]
慢慢等吧，不知道发生了什么，现在我在discord上创建的伺服器也已经搬家到kook了，好不方便，不喜欢kook

**Comment by LyaQanYi** [comment]
+1

**Comment by x1h0126** [comment]
求你了QAQ把discord加回来吧

**Comment by MDeath** [comment]
D&P +1

**Comment by Alee867** [comment]
> 慢慢等吧，不知道发生了什么，现在我在discord上创建的伺服器也已经搬家到kook了，好不方便，不喜欢kook

可以用渡渡，我觉得比kook好用

**Comment by daycold1000** [comment]
> > 慢慢等吧，不知道发生了什么，现在我在discord上创建的伺服器也已经搬家到kook了，好不方便，不喜欢kook
> 
> 可以用渡渡，我觉得比kook好用

你说的这个，支援国外用户连接吗？还有港澳台

**Comment by FlashDragons** [comment]
家人们，我找到新的加速器，可以加速DC和P了！
叫steamcommunity，bing搜索第一条就可以下载。
下载后以管理员身份运行，同时在设置中把本地监听IP改为0.0.0.0就可以使用了。
可惜的是这个软件没steam++用起来方便。

**Comment by rmbadmin** [comment]
不好意思，实际上就是因为大家想的原因，我也没有办法过多的说什么。这类相关的问题目前暂时是没有办法提供处理了，对各位说声抱歉。

**Comment by MDeath** [comment]
> 不好意思，实际上就是因为大家想的原因，我也没有办法过多的说什么。这类相关的问题目前暂时是没有办法提供处理了，对各位说声抱歉。

那[docker](https://hub.docker.com/)的能加吗
