### ISSUE TITLE
所以官方把Pixiv加速删了？

### ISSUE THREAD

**Issue by googolplex35** [BeyondDimension/SteamTools#3035]
今天想访问没有pixiv加速了

**Comment by cixigangsai** [comment]
但愿只是维护，以后会再加入进来

**Comment by rmbadmin** [comment]
不好意思，实际上就是因为大家想的原因，我也没有办法过多的说什么。这类相关的问题目前暂时是没有办法提供处理了，对各位说声抱歉。

**Comment by googolplex35** [comment]
请问未来有可能添加回来这些加速吗？还是永久删除？

**Comment by googolplex35** [comment]
请问未来会恢复这些加速吗？还是永久删除？







                       
原始邮件
                       
                     

发件人："RMBGAME"< ***@***.*** &gt;;

发件时间：2023/11/29 10:24

收件人："BeyondDimension/SteamTools"< ***@***.*** &gt;;

抄送人："googolplex35"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [BeyondDimension/SteamTools] 所以官方把Pixiv加速删了？ (Issue #3035)




 
不好意思，实际上就是因为大家想的原因，我也没有办法过多的说什么。这类相关的问题目前暂时是没有办法提供处理了，对各位说声抱歉。
