### ISSUE TITLE
🧐[Question] Discord与P站已经无法使用

### ISSUE THREAD

**Issue by xianmovo** [BeyondDimension/SteamTools#3039]
如题

**Comment by JamiePW** [comment]
同问

**Comment by youling8051** [comment]
今天刚想登就都没了

**Comment by CodeingJack** [comment]
我这也没有加速Pixiv了
旧版也试过，一起没了
我觉得可能是考虑到P站一些图片不太符合国内法规，怕一些法律因素就下架P站加速了

**Comment by cafeawa** [comment]
同问，今天想登发现找不到pixiv了

**Comment by FlashDragons** [comment]
家人们，我找到新的加速器，可以加速DC和P了！
叫steamcommunity，bing搜索第一条就可以下载。
下载后以管理员身份运行，同时在设置中把本地监听IP改为0.0.0.0就可以使用了。
可惜的是这个软件没steam++用起来方便。

**Comment by youling8051** [comment]
> 家人们，我找到新的加速器，可以加速DC和P了！ 叫steamcommunity，bing搜索第一条就可以下载。 下载后以管理员身份运行，同时在设置中把本地监听IP改为0.0.0.0就可以使用了。 可惜的是这个软件没steam++用起来方便。

这个别的up也推荐过，和Steam++比可以说各有所长吧，就看什么时候没

**Comment by cixigangsai** [comment]
> 家人们，我找到新的加速器，可以加速DC和P了！ 叫steamcommunity，bing搜索第一条就可以下载。 下载后以管理员身份运行，同时在设置中把本地监听IP改为0.0.0.0就可以使用了。 可惜的是这个软件没steam++用起来方便。

这东西不好用，还不如edge浏览器搞个扩展

**Comment by xiaoniangaoh** [comment]
p站我能理解，但是为啥discord也没了啊！！！！！！

**Comment by DisguiserZERO** [comment]
昨天还能加速discord，今天就不行了，QAQ

**Comment by GettingCN** [comment]
今天刚发现，特地来看有没有类似的，出啥问题了

**Comment by nanjuekaien1** [comment]
@DisguiserZERO  你运气挺好的，我们前天discord就不能用了，你昨天还可以用。

**Comment by xianmovo** [comment]
彳亍了，就用steamcommunity302吧，GitHub再用steam++

**Comment by xianmovo** [comment]
steamcommunity302
V12.1.30:(该版本当前被微软WD定义为恶意软件,自行加白使用/介意请继续使用12.1.28版本)
[steamcommunity_302_V12.1.30_解压密码dogfight360]
https://www.dogfight360.com/blog/wp-content/uploads/2023/11/steamcommunity_302_V12.1.30_%E8%A7%A3%E5%8E%8B%E5%AF%86%E7%A0%81dogfight360.zip

**Comment by Ovo0ov** [comment]
> steamcommunity302 V12.1.30：（该版本当前被微软WD定义为恶意软件，自行加白使用/介意请继续使用12.1.28版本） [steamcommunity_302_V12.1.30_解压密码dogfight360] https://www.dogfight360.com/blog/wp-content/uploads/2023/11/steamcommunity_302_V12.1.30_%E8%A7%A3%E5%8E%8B%E5%AF%86%E7%A0%81dogfight360.zip

佬，为什么我用这个进dc黑屏呀呜呜，用了链接里面的解决措施也没成功

**Comment by wupgyu** [comment]
发现v2ex也没加速了

**Comment by GettingCN** [comment]
结合之前b站注册了官号，估计是彻底没了

**Comment by rmbadmin** [comment]
#3060

**Comment by as564335sa** [comment]
> 家人们，我找到新的加速器，可以加速DC和P了！ 叫steamcommunity，bing搜索第一条就可以下载。 下载后以管理员身份运行，同时在设置中把本地监听IP改为0.0.0.0就可以使用了。 可惜的是这个软件没steam++用起来方便。

好像不支持pixiv吧，我在里面没找到呢

**Comment by FlashDragons** [comment]
> > 家人们，我找到新的加速器，可以加速DC和P了！ 叫steamcommunity，bing搜索第一条就可以下载。下载后以管理员身份运行，同时在设置中把本地监听IP改为0.0.0.0就可以使用了。可惜的是这个软件没steam++用起来方便。
> 
> 好像不支持pixiv吧，我在里面没找到呢

从12.1.31开始的新版本不支持了，那个软件的作者在更新日志中明确指出将永久取消对pixiv的支持，之前的版本是可以的，这也是最近几天的事，作者已删除旧版本的下载链接。
