### ISSUE TITLE
🐛[BUG] 何时能够修复P站的加速？

### ISSUE THREAD

**Issue by 2590672259** [BeyondDimension/SteamTools#3045]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 📷 复现步骤

1. 打开Watt toolkit
2. 点击网络加速
3. 其他网页内并无P站加速方法（无论何种版本）

**Comment by ZZBSMJ** [comment]
还在这做梦会修复呢，明显是和灰色地带搞切割，打算上岸了呗。对蓝P有刚需的话，早点老老实实换东西用吧

**Comment by rmbadmin** [comment]
不好意思，实际上就是因为大家想的原因，我也没有办法过多的说什么。这类相关的问题目前暂时是没有办法提供处理了，对各位说声抱歉。
