### ISSUE TITLE
🐛[BUG] 本地令牌锁定后仍可通过菜单托盘栏获取5位数验证码

### ISSUE THREAD

**Issue by zhongerjunze** [BeyondDimension/SteamTools#3052]
## 请认真检查以下清单中的每一项
- [ √ ] 已经搜索过，没有发现类似的 issue
- [ √ ] 已经搜索过文档，没有发现相关内容
- [ √ ] 已经尝试使用过最新版，问题依旧存在
- [ √ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
在本地令牌锁定后，可以通过托盘图标中的“本地令牌”复制5位数验证码。

### 📷 复现步骤
1. 打开 “本地令牌” ，并输入令牌保护密码；
2. 点击 “令牌设置” 后，点击 “锁定令牌” ；
3. 右击托盘栏中的图标，点击 “本地令牌” ，并点击一个令牌名称，成功复制验证码。

### 🚑 其他信息
- 处理器体系结构：x64
- 系统版本号：
   Windows 10 家庭中文版
   版本号 22H2 
   操作系统内部版本 19045.3693 
   体验 Windows Feature Experience Pack 1000.19053.1000.0
- 下载渠道：Github
- 程序版本：3.0.0-rc.2 for Windows (x64) （7z压缩包）
- 是否包含独立运行时：不包含 fde

**Comment by Heporis** [comment]
1.第一次使用软件时，打开本地令牌，会显示“您的令牌具有密码保护，请先进行密码验证”，然而我还没有导入任何令牌。
2.未锁定的令牌，打开软件后，托盘右键没有本地令牌的选项，需要在软件主界面进入本地令牌栏目后，托盘右键才有本地令牌选项
3.文本错误
![image](https://github.com/BeyondDimension/SteamTools/assets/51895154/85068e52-fb41-45ef-b45d-b24c15fa1815)
