### ISSUE TITLE
🧐[Question] 具体哪些网站停止支持？

### ISSUE THREAD

**Issue by wuyilingwei** [BeyondDimension/SteamTools#3059]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

听说DC和P停止支持了，还有哪些吗？
#3039

**Comment by rmbadmin** [comment]
#3060
