### ISSUE TITLE
🧐[Question] 请对下架的服务进行说明，这是对用户基本的尊重

### ISSUE THREAD

**Issue by XuCpeng** [BeyondDimension/SteamTools#3060]
## 请认真检查以下清单中的每一项
- [x ] 已经搜索过，没有发现类似的 issue
- [x ] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

当前 Discord 与 Pixiv 加速已不可用，虽然对我个人而言这没有什么影响，我还有很多其他的方法；
但是不可否认有很多用户是该功能的强依赖者，毫无征兆的下架该功能势必会对其产生负面的影响；

首先，肯定要感谢相关作者们推出了符合大家需求的、好用的产品；
但是，用户与产品也是相互成就的过程，在用户中积累的良好口碑才是Steam++能在一众加速工具中脱颖而出的关键；

无论是处于什么原因，都应该有义务把事情讲明白说清楚，不要对某些不可抗力有过于“害怕”或“包庇”的心理。如果是自身原因，更有必要说明。

作者和用户必须认识到一个共识：国内互联网，不只是互联网，总是通过一些搪塞的话术进行整改和下架是十分错误的操作。用户的需求应该得到尊重，需不需要该功能的评判标准应该由用户决定，产品理念不该与用户相悖。当因为某些原因或规划导致产品理念发生变化，特别是一些底层逻辑的变化时，势必会对已有用户产生影响。

"用户是“无辜”的，受益者只有你"，起码在没有说明时只能得到如此的结论。

就我个人而言，下架这些功能的原因我只能自己进行揣测，结果自然是负面的。简单说：**一味的这样“顺从”下去也就失去的作为“加速器”的意义**。这是令人悲观和失望的，不只是对于Steam++更是对“环境”，这也是我提这个Issue的原因。比起功能的缺失，理念上的残疾更令人心痛。

但总的来说，还是感谢带来好的作品。

**Comment by Wswjcl** [comment]
I think you are right.

**Comment by EarOfWheat** [comment]
I agree with you.

**Comment by rmbadmin** [comment]
有些原因是不方便讨论的，我没有办法，我可以简单的说一下就是收到了警告，并明确表明了这是违法犯罪事实，所以不得不改。
也因为这样的原因我更不希望过多的人对此讨论，这只会让讨论的话题偏移造成更多问题。

**Comment by PumpkinXD** [comment]
看来只能坚守旧版本或者fork了 哎

_要是有具体的commit就更好了_

**Comment by UjuiUjuMandan** [comment]
> 看来只能坚守旧版本或者fork了 哎
> 
> _要是有具体的commit就更好了_

加速器的配置是远程下发的，和代码库没有任何关系。

可不敢乱讨论，今天你就想上 pixiv ，明天要上什么我都不敢想。

**Comment by NoneVector** [comment]
理解理解😎

**Comment by MartianReunion** [comment]
理解
这个issues要载入watt toolkit史册了属于是

**Comment by xitieshiz2** [comment]
> 有些原因是不方便讨论的，我没有办法，我可以简单的说一下就是收到了警告，并明确表明了这是违法犯罪事实，所以不得不改。 也因为这样的原因我更不希望过多的人对此讨论，这只会让讨论的话题偏移造成更多问题。

或许可以开放反代的自定义配置接口？既可以规避风险也可以保证体验
而且反代从技术上来说和法律中提到的“提供国际互联网信道”应该是没有关系的

**Comment by MinecraftEarthVillage** [comment]
> > 看来只能坚守旧版本或者fork了 哎
> > _要是有具体的commit就更好了_
> 
> 加速器的配置是远程下发的，和代码库没有任何关系。
> 
> 可不敢乱讨论，今天你就想上 pixiv ，明天要上什么我都不敢想。

不用想都知道是CPC干的（

**Comment by MinecraftEarthVillage** [comment]
> 有些原因是不方便讨论的，我没有办法，我可以简单的说一下就是收到了警告，并明确表明了这是违法犯罪事实，所以不得不改。 也因为这样的原因我更不希望过多的人对此讨论，这只会让讨论的话题偏移造成更多问题。

独立了，变成“境外”就能讨论了
