### ISSUE TITLE
👑[Enhancement] pixiv

### ISSUE THREAD

**Issue by HuaJiKing402** [BeyondDimension/SteamTools#3075]
### 🥰 需求描述(Description)
增加个pixiv的反代加速项呗

**Comment by TianMengLucky** [comment]
做梦吧你,翻翻以前的issues先 #3060

**Comment by PumpkinXD** [comment]
这个我感觉还是得自行查找解决方案，唉…

真就…

**Comment by HuaJiKing402** [comment]
> 这个我感觉还是得自行查找解决方案，唉...
> 
> 真就...

我尝试了自建nginx反代和替换图片镜像源 
感觉良好

ps:pixiv反代就可以解决大部分问题，提出这个方案的人认为这是合法的，steam++不是基于这个原理的吗

**Comment by XuCpeng** [comment]
> 做梦吧你,翻翻以前的issues先 #3060

“做梦吧你”这个态度是不对的，虽然现状可能是真的无能为力，但用户提出这个需求是完全合理的，也不是什么“做梦”，应该尽量通过各种努力达成（包括但**不限于**技术方法）。很多“规定”是一直是变化的，只要变化就会有方向，方向是人们努力的结果。即使现阶段达不到也应该保持尊重。

**Comment by PumpkinXD** [comment]
> > 这个我感觉还是得自行查找解决方案，唉...
> > 
> > 真就...
> 
> 我尝试了自建nginx反代和替换图片镜像源 
> 感觉良好
> 
> ps:pixiv反代就可以解决大部分问题，提出这个方案的人认为这是合法的，steam++不是基于这个原理的吗

不好说那些“《》”是怎么想的，有可能Github和steam在他们心目中也是“《》”只是碍于玩家和开发者所以没敢提
