### ISSUE TITLE
Discord的加速呢?

### ISSUE THREAD

**Issue by hzr12** [BeyondDimension/SteamTools#3080]

**Comment by Ad-closeNN** [comment]
![image](https://github.com/BeyondDimension/SteamTools/assets/103355026/7023e9b4-3c91-4595-87d5-e1e7209c076d)

**Comment by kukukumiko-git** [comment]
pixiv也没了

**Comment by TianMengLucky** [comment]
懂得都懂，翻下以前的问题，不过我是觉得 p 关了正常，d 倒是想不到

**Comment by hzr12** [comment]
什么时候能恢复
