### ISSUE TITLE
🐛[BUG] 3.0.0rc3的流量统计图动画在运行1分钟后变得很“果冻”

### ISSUE THREAD

**Issue by castorwong** [BeyondDimension/SteamTools#3088]
刚运行一分钟内，没有平移时曲线正常 （下图是gif动图）

![20231216_145814.gif](https://github.com/BeyondDimension/SteamTools/assets/58938467/6c34fb77-1c3b-4107-9b5f-c640ed823369)

在运行满1分钟后，整体开始向左平移后，曲线开始变得奇怪，很“果冻”（下图是GIF动图）
![20231216_144937.gif](https://github.com/BeyondDimension/SteamTools/assets/58938467/92ea7e76-4217-4aef-ab14-1510005580d1)

- 处理器体系结构：amd64(x86_64)
- 系统版本号：Windows 10 19045.3803
- 下载渠道： Github 
- 程序版本： 3.0.0rc3 

发行版2.8.6则无此问题 （下图为动图）
![20231216_210544.gif](https://github.com/BeyondDimension/SteamTools/assets/58938467/0db6e01b-89e1-42d6-9145-c8045b725a54)

**Comment by rmbadmin** [comment]
这应该是在3.0中升级了图标绘制库导致的一个有趣现象，我也不认为这是bug所以并不打算处理
