### ISSUE TITLE
👑[Enhancement] 更换安装包制作方案

### ISSUE THREAD

**Issue by Lutra-Fs** [BeyondDimension/SteamTools#310]
### 🐛 描述(Description)

卸载程序被Windows Defender报毒

### 📷 复现步骤(Steps to Reproduce)

1. 安装Steam++
2. 报毒

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): The latest
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/36790218/124012850-f213e500-da24-11eb-95d0-1a42fa8cddad.png)

**Comment by AigioL** [comment]
看图中是 Steam++.exe 主程序被多个杀毒软件误报，这个问题除了交保护费之外也没啥办法了。

**Comment by Lutra-Fs** [comment]
不是的 只有卸载程序才会报毒 从文件大小也能看出来

**Comment by AigioL** [comment]
> 不是的 只有卸载程序才会报毒 从文件大小也能看出来

那就是 uninst.exe，现在这安装包方案确实不太行

**Comment by Lutra-Fs** [comment]
> > 不是的 只有卸载程序才会报毒 从文件大小也能看出来
> 
> 那就是 uninst.exe，现在这安装包方案确实不太行

有计划更换封包方案吗

**Comment by AigioL** [comment]
一直想换方案，但是没啥方案可选，之前想用 WinFroms 做，但是体积太大了
