### ISSUE TITLE
🧐[Question] 电脑小白关于安全性的疑问

### ISSUE THREAD

**Issue by issunset** [BeyondDimension/SteamTools#3112]
## 请认真检查以下清单中的每一项
- [√ ] 已经搜索过，没有发现类似的 issue
- [ √] 已经搜索过文档，没有发现相关内容
- [ √] 已经尝试使用过最新版，问题依旧存在
- [ √] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

各位大佬好 我知道此软件是开源的 也通过百度大概了解了下反代理  通过查找issue了解到了github和steam是dns污染 和完全被墙的youtube不一样 上github和steam是合法的 那么不知道我们这样理解此软件对吗：
    就是要信任一个中间人 这个中间人会经手你访问github/steam的数据 把其中一些会被gfw检测到且做出dns污染操作的信息加密处理 然后能让你的数据安全到达你想去的网站 那我的问题是：
    理论上讲 使用此软件访问steam和github时 到底有没有数据泄露的风险 比如中间人会获取你的steam账号密码/获取你github访问的内容等

再次声明下 真的是在学习中的电脑小白 所以会有这样的疑问 如果冒犯到您 非常欢迎您宝贵的批评 非常感谢

**Comment by rmbadmin** [comment]
软件的原理是本地反代，中间人是你自己，只要不泄露你本机随机生成的https证书，就不会有你出现的担忧状况。
