### ISSUE TITLE
🐛[BUG] 浏览器的bing搜索，自动跳转到github页面。

### ISSUE THREAD

**Issue by GlanceQwQ** [BeyondDimension/SteamTools#3115]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 📷 复现步骤

1. 
2. 
3. 

### 🖼 截图

[](url)

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by Magnushy** [comment]
我的manjora firefox也出现同样的问题

**Comment by hhxy11** [comment]
我怀疑是系统代理这个功能出现了问题，如果不是这个模式，其实正常搜索没什么问题

**Comment by songxingling1** [comment]
我的也是

**Comment by lhy-cn** [comment]
我用的system，清除浏览器的“缓存的图像和文件”能解决问题
