### ISSUE TITLE
🐛[BUG] 在未安装过的Ubuntu上使用官网脚本安装出错

### ISSUE THREAD

**Issue by lsxuan12138** [BeyondDimension/SteamTools#3116]
## 请认真检查以下清单中的每一项
- [ ] 已经搜索过，没有发现类似的 issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

在使用官网上提供的命令'curl -sSL https://steampp.net/Install/Linux.sh | bash'安装时（之前没有安装过），会出问题。
![image](https://github.com/BeyondDimension/SteamTools/assets/74349318/4d7e8b2d-fbf1-425c-a95d-b52990402812)
脚本的这一部分，貌似没有对没有'AppVer'的情况进行处理，最后导致安装失败。
![image](https://github.com/BeyondDimension/SteamTools/assets/74349318/68ed68e4-2b1e-4aad-be13-b9999b4237af)

### 📷 复现步骤

1. 在未安装过的Ubuntu上使用命令'curl -sSL https://steampp.net/Install/Linux.sh | bash'安装

### 🖼 截图

![image](https://github.com/BeyondDimension/SteamTools/assets/74349318/2f2408fe-e354-4787-ad08-46b3279f728c)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Ubuntu 20.04.6 LTS

**Comment by lsxuan12138** [comment]
刚才发现就算安装过了（使用deb双击安装），还是会出错

**Comment by Mossimos** [comment]
报错正常 检测到 文件不存在或者 版本号不对就会执行 下载的 逻辑  
因为 提供下载的服务器 在国外 所以可能有连接失败的情况
https://hk.mossimo.net/

**Comment by lsxuan12138** [comment]
这样的吗，感谢
