### ISSUE TITLE
🐛[BUG] GITHUB加速会出现SSL连不上，GITHUB.com 443报警

### ISSUE THREAD

**Issue by Lennonleslie** [BeyondDimension/SteamTools#3142]
使用github加速时，打开github网站显示以下内容
```Request:The SSL connection could not be established, see inner exception. (github.com:443)```
关闭也打不开github。
使用网上找的配置内容可以打开。
配置如下
```# GitHub Start
140.82.114.4 github.com
199.232.69.194 github.global.ssl.fastly.net
# GitHub End```

**Comment by rmbadmin** [comment]
证书信任问题，自行参考如何信任第三方证书
