### ISSUE TITLE
🧐[Question] 个人数据存放路径

### ISSUE THREAD

**Issue by eramicro** [BeyondDimension/SteamTools#3146]
## 请认真检查以下清单中的每一项
- 已经搜索过，没有发现类似的 issue
-  已经搜索过文档，没有发现相关内容
- 已经尝试使用过最新版，问题依旧存在
- 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

个人数据存放路径具体在哪里？

### 🚑 其他信息
![image](https://github.com/BeyondDimension/SteamTools/assets/44019323/faea9b64-4637-4342-bdf2-d68f679bbdf9)

**Comment by gbostock** [comment]
<img width="723" alt="屏幕截图 2024-01-22 120556" src="https://github.com/BeyondDimension/SteamTools/assets/94212663/16eedf5f-235e-4424-b3fe-57316f86fe81">
这里可以找到
