### ISSUE TITLE
🐛[BUG] git pull(ssh) 在22号端口报错：Connection refused

### ISSUE THREAD

**Issue by HairlessVillager** [BeyondDimension/SteamTools#3151]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

加速 Github 时无法执行`git pull`命令，但是能在浏览器访问网站。

### 📷 复现步骤

1. 打开 SteamTools
2. 启动 Github 加速功能
3. 在命令行执行命令 `git pull`，报错：
```bash
$ git pull
ssh: connect to host github.com port 22: Connection refused
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

### 📄 日志信息

[nlog-all-2024-01-24.log](https://github.com/BeyondDimension/SteamTools/files/14046315/nlog-all-2024-01-24.log)
### 🖼 截图

无

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 10.19045.3930
- 下载渠道：Gitee
- 程序版本：3.0.0-rc.3 for Windows (x64)
- 是否包含独立运行时：不包含

**Comment by HairlessVillager** [comment]
已解决，解决方案为在hosts文件中手动添加github.com的域名ip映射。

**Comment by H-Hui2277** [comment]
Steam++使用的hosts代理模式，hosts文件中github.com已经映射到127.0.0.1，手动添加映射指的是什么呢？
![Snipaste_2024-02-08_21-05-19](https://github.com/BeyondDimension/SteamTools/assets/82951812/c52b4131-a48b-4f90-bcdd-f62636a5a7c2)

**Comment by HairlessVillager** [comment]
@H-Hui2277 我说的手动添加映射，是指先关闭 Steam++，然后通过其他手段获取 github.com 的 IP，添加到 hosts 文件中。此时由于 Steam++ 已关闭，所以 hosts 文件中不会有 127.0.0.1 的映射。

**Comment by yyyytawa** [comment]
> ## 请认真检查以下清单中的每一项
> * [x]  已经搜索过，没有发现类似的 issue
> * [x]  已经搜索过文档，没有发现相关内容
> * [x]  已经尝试使用过最新版，问题依旧存在
> * [x]  使用的是官方版本（未替换及修改过安装目录程序文件）
> 
> ### 🐛 描述
> 加速 Github 时无法执行`git pull`命令，但是能在浏览器访问网站。
> 
> ### 📷 复现步骤
> 1. 打开 SteamTools
> 2. 启动 Github 加速功能
> 3. 在命令行执行命令 `git pull`，报错：
> 
> ```shell
> $ git pull
> ssh: connect to host github.com port 22: Connection refused
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```
> 
> ### 📄 日志信息
> [nlog-all-2024-01-24.log](https://github.com/BeyondDimension/SteamTools/files/14046315/nlog-all-2024-01-24.log)
> 
> ### 🖼 截图
> 无
> 
> ### 🚑 其他信息
> * 处理器体系结构：x64
> * 系统版本号：Windows 10.19045.3930
> * 下载渠道：Gitee
> * 程序版本：3.0.0-rc.3 for Windows (x64)
> * 是否包含独立运行时：不包含

换成PAC模式即可
