### ISSUE TITLE
👑[Enhancement] Github中在线VSC功能相关支持 

### ISSUE THREAD

**Issue by nageih** [BeyondDimension/SteamTools#3153]
### 🥰 需求描述(Description)

加速Github服务中似乎并不包含Github自带的那个在线VSC，即github.dev，希望可以支持

### 🧐 解决方案(Solution)
似乎进入之后还有登录aoi相关的，主要是这个部分容易失败

**Comment by rmbadmin** [comment]
已热更新支持
