### ISSUE TITLE
🧐[Question] 这个工具打开后可以访问Google或者YouTube吗？？？

### ISSUE THREAD

**Issue by Brady-X** [BeyondDimension/SteamTools#3161]
## 请认真检查以下清单中的每一项
- [ ] 已经搜索过，没有发现类似的 issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ ] 已经尝试使用过最新版，问题依旧存在
- [ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

🔴🔴🔴这个工具打开后可以访问Google或者YouTube吗？？？

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by yyyytawa** [comment]
你想啥呢？

**Comment by S-1-5-21-1726115** [comment]
谷歌翻译可以，不过只能使用一次，之后就要同意/拒绝Cookie,然后跳转到consent.google.com就打不开了（）其他的就别想了
