### ISSUE TITLE
🧐[Question]IPV6状况显示异常

### ISSUE THREAD

**Issue by hugsyf** [BeyondDimension/SteamTools#3163]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

有IPV6网络、加速后可以正常进行社区留言的情况下，程序显示不支持IPV6访问。

### 🚑 其他信息
![image](https://github.com/BeyondDimension/SteamTools/assets/40665263/33655a01-d6ae-4eae-9853-d8b31716fb36)

- 处理器体系结构：x64
- 系统版本号：Windows 11 22631.3085
- 下载渠道：官网
- 程序版本：3.0.0-rc.3
- 是否包含独立运行时：否

**Comment by yyyytawa** [comment]
+1
我这边也是有公网IP 但是还是显示不支持IPv6访问

**Comment by AigioL** [comment]
最近迁移到华为云上，虚拟机里没有公网 IPv6，所以这个检测失效了

**Comment by yyyytawa** [comment]
> 最近迁移到华为云上，虚拟机里没有公网 IPv6，所以这个检测失效了

很好奇为啥不用test-ipv6或者是6.ipw.cn test6.ustc.edu.cn等一些纯ipv6网站来检测？
