### ISSUE TITLE
🧐[Question] The lowest price plugin issue

### ISSUE THREAD

**Issue by ghost** [BeyondDimension/SteamTools#3172]
This plugin some how broken down. I REALLY need this,and **i know that there has other mods available just right there runs in a browser environment. But i want to use steam app ONLY**. 

Hope to be fixed soon.Is very ez,pls

**Comment by Alengying** [comment]
加+1

**Comment by Mossimos** [comment]
After upgrading to API V2, the subsequent update plan for IsThereAnyDeal is scheduled for at least after March.

**Comment by Mossimos** [comment]
The "lowest price plugin" has been upgraded to V2 API, which can be used by updating to version 1.2. If any bugs are found, please open a new issue to provide feedback.
