### ISSUE TITLE
🐛[BUG]  Steam挂卡会出现无法挂卡的bug。

### ISSUE THREAD

**Issue by GTX-6300** [BeyondDimension/SteamTools#3184]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
电脑重新启动之后会报出
LoadBadges Error
'<' is an invalid start of a value. LineNumber: 01
BytePositionInLine: 0.

### 📷 复现步骤

1. 
2. 
3. 

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号： Windows Feature Experience Pack1000.19053.1000.0(see winver) 
- 下载渠道：  官网 
- 程序版本：
- 是否包含独立运行时：

**Comment by zgwsww** [comment]
Steam挂卡无法挂卡

**Comment by zgwsww** [comment]
Steam挂卡无法挂卡 并且获取不到挂卡游戏数据，我本身有steam卡牌数据。
