### ISSUE TITLE
🧐[Question] Arch Linux无法导入证书，提示p11-kit: couldn't create object: 该字段为只读

### ISSUE THREAD

**Issue by Neutron3529** [BeyondDimension/SteamTools#3191]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

按照官网导入证书的教程
https://steampp.net/liunxSetupCer
```
sudo trust anchor --store SteamTools.Certificate.cer
```
执行后报错
```
# trust anchor /etc/nginx/ca/SteamTools.Certificate.cer
p11-kit: couldn't create object: 该字段为只读
p11-kit: 1 error while processing
# LC_ALL=C trust anchor /etc/nginx/ca/SteamTools.Certificate.cer 
p11-kit: couldn't create object: The field is read-only
p11-kit: 1 error while processing
```

搜索The field is read-only只能得到一些不相关的结果

https://bugzilla.redhat.com/show_bug.cgi?id=2024927

> Note that there are two ways of installing private certificate:
> 1. put the PEM (or any supported format) file under /etc/pki/ca-trust/source/anchors/ and optionally run update-ca-trust to propagate the change to external stores (e.g., Java keystore)
> 2. use the trust anchor command pointing to a certificate _outside_ of that directory

但我的cer甚至不在/usr和/etc

之前我导入证书的方法是方法1，转pem之后扔进/etc/ca-certificates/trust-source/anchors，之后sudo update-ca-trust
在做完这一切之后firefox是认这个证书的
但不知道为什么steam不认

或许官网应该提供另一种Arch系导入证书的方法

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：`Linux 3060 6.7.6-arch1-2 #1 SMP PREEMPT_DYNAMIC Thu, 29 Feb 2024 19:08:51 +0000 x86_64 GNU/Linux`

**Comment by Neutron3529** [comment]
我测出能用的解法是这个：
```
certutil -d "sql:$HOME/.pki/nssdb" -A -i SteamTools.Certificate.pem  -n "SteamTools CA" -t C,,
```
这是从https://wiki.archlinux.org/title/User:Grawity/Adding_a_trusted_CA_certificate 查到的，修改chrome的信任CA的方法

（暂时保留这个issue，官网修正之后把这个issue关掉就好了）

**Comment by Mossimos** [comment]
你用的是2.8.6把你去官网看看 Linux下载界面就懂了
