### ISSUE TITLE
🐛[BUG] win11 3.00-rc4开机自启动无效

### ISSUE THREAD

**Issue by DishboZHY** [BeyondDimension/SteamTools#3213]
## 请认真检查以下清单中的每一项
- [ ] 已经搜索过，没有发现类似的 issue
- [ ] 已经搜索过文档，没有发现相关内容
- [ √] 已经尝试使用过最新版，问题依旧存在
- [ √]使用的是官方版本（未替换及修改过安装目录程序文件）**

### 📷 复现步骤

1. 
2. 
3. 

### 🚑 其他信息

- 处理器体系结构：<13th Gen Intel(R) Core(TM) i9-13900KF   3.00 GHz>
- 系统版本号：<版本	Windows 11 专业版
版本	23H2
安装日期	‎2024/‎2/‎14
操作系统版本	22631.3235
体验	Windows Feature Experience Pack 1000.22687.1000.0
>
- 下载渠道：<微软商店>
- 程序版本：
- 是否包含独立运行时：

**Comment by AigioL** [comment]
rc.5 已修复
