### ISSUE TITLE
🐛[BUG] 微软商店渠道无法正常开机自启

### ISSUE THREAD

**Issue by ZnCookie** [BeyondDimension/SteamTools#3214]
### 🐛 描述

通过微软商店渠道下载的版本，设置”开机自启动“无效
卸载后，安装Github下载的安装包，设置“开机自启动”后，可以正常的开机自启
在 计算机管理->系统工具->任务计划程序->任务计划程序库 中发现，如果是微软商店渠道下载的应用程序，不能正常创建自启任务

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 11 23H2 Beta (22635.3276)
- 下载渠道：微软商店 
- 程序版本：3.0.0-rc.4

**Comment by cleverpigeb** [comment]
我也是这样，微软商店下的无法开机自启

**Comment by AigioL** [comment]
rc.5 已修复

**Comment by XHF1954** [comment]
还是不可以
