### ISSUE TITLE
🐛[BUG] 请输入标题 github的3.0开机自启有问题

### ISSUE THREAD

**Issue by WSMTBG** [BeyondDimension/SteamTools#3217]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
github的3.0开机自启有问题，开机会卡住，就黑屏
WIN11最新版，3.0最新版

### 📷 复现步骤

1. 安装
2. 重启
3. 卡住了

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by AigioL** [comment]
https://github.com/BeyondDimension/SteamTools/issues/3213 https://github.com/BeyondDimension/SteamTools/issues/3214
