### ISSUE TITLE
👑[Enhancement] 强烈建议精简一下账号切换的操作

### ISSUE THREAD

**Issue by catnap826** [BeyondDimension/SteamTools#3224]
### 🥰 需求描述(Description)
优化一下账号切换的操作，原版的watt工具箱是可以直接一键切换的，现在的测试版还需要点开账号然后才有切换账号的选项

### 🧐 解决方案(Solution)
可以把“最近登录”的文本去掉，改成“切换到此账号”的功能

### 🚑 其他信息(Other Information)

如截图等其他信息可以贴在这里
<img width="732" alt="屏幕截图 2024-03-08 224423" src="https://github.com/BeyondDimension/SteamTools/assets/114160227/127d7630-5937-4a2c-9f87-c21f78748a7a">

**Comment by truthlovefaith** [comment]
直接双击

**Comment by AigioL** [comment]
下一个版本将会加入创建桌面快捷方式功能简化操作

![image](https://github.com/BeyondDimension/SteamTools/assets/24450093/4434fbe1-ccdc-47b0-a709-8249b6315f38)
