### ISSUE TITLE
🐛[BUG] github 上传失败

### ISSUE THREAD

**Issue by awut-star** [BeyondDimension/SteamTools#3233]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

在「网络加速」中勾选并启动「Github Api」，然后使用「PicGo」往「github」上传图片会失败

### 📷 复现步骤

1. 在「网络加速」中勾选并启动「Github Api」
2. 使用「PicGo」往「github」上传图片

### 📄 日志信息

Steam++没有今天的日志，只有「PicGo」的日志
```
2024-03-09 14:30:38 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/awut-star/",
  "statusCode": 0,
  "message": "unable to verify the first certificate",
  "stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\n    at TLSSocket.emit (node:events:394:28)\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
2024-03-09 14:30:38 [PicGo ERROR] {
  "method": "PUT",
  "url": "https://api.github.com/repos/awut-star/",
  "statusCode": 0,
  "message": "unable to verify the first certificate",
  "stack": "Error: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (node:_tls_wrap:1530:34)\n    at TLSSocket.emit (node:events:394:28)\n    at TLSSocket._finishInit (node:_tls_wrap:944:8)\n    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12)",
  "response": {
    "status": 0,
    "statusCode": 0,
    "body": ""
  }
} 
```
### 🖼 截图

![image](https://github.com/BeyondDimension/SteamTools/assets/90757590/f60aff39-fdf4-4197-9dff-503e7fc0b38f)
![image](https://github.com/BeyondDimension/SteamTools/assets/90757590/5616aa40-6487-4077-9b12-a43bcfad8dd3)
![image](https://github.com/BeyondDimension/SteamTools/assets/90757590/ecaa3484-d52a-4f82-8366-ab06b233a385)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 10 企业版 LTSC 1809 17763.3469
- 下载渠道：Github
- 程序版本：3.0.0-rc.5
- 是否包含独立运行时：

**Comment by rmbadmin** [comment]
这是因为picgo不信任steam++的第三方证书导致的，自行寻找下picgo如何信任第三方证书
