### ISSUE TITLE
🐛[BUG] 在PAC模式下加速github时，访问github文档站会被重定向至github.com

### ISSUE THREAD

**Issue by harry-xi** [BeyondDimension/SteamTools#3240]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
如题

### 📷 复现步骤

1. 启动watttoolkit 勾选github的全部加速选项，选择pac模式并启动加速
2. 访问https://docs.github.com/

### 📄 日志信息

未发现相关日志

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：win10 22H2 19045.4046
- 下载渠道：微软商店
- 程序版本：3.0.0-rc.5 for windows desktop bridge
- 是否包含独立运行时：

**Comment by YU-7** [comment]
![image](https://github.com/BeyondDimension/SteamTools/assets/58320198/40558e01-fcde-4fb1-ac03-cba1bd05b4d6)
我有一个类似的问题，用 git clone 的时候无法克隆项目到本地。关掉加速之后就行了。

**Comment by rmbadmin** [comment]
已添加docs加速项热更新修复
