### ISSUE TITLE
🐛[BUG] MEGA网盘网站无法访问

### ISSUE THREAD

**Issue by lyf67175817** [BeyondDimension/SteamTools#3252]
![屏幕截图 2024-03-13 130800](https://github.com/BeyondDimension/SteamTools/assets/26183540/4757946b-3ada-4014-9068-c5f37733361f)
![屏幕截图 2024-03-13 130840](https://github.com/BeyondDimension/SteamTools/assets/26183540/9fb6bd16-4aec-4a5f-aa29-4385c82ef946)
![屏幕截图 2024-03-13 130912](https://github.com/BeyondDimension/SteamTools/assets/26183540/09cb931e-7c05-4cd9-866f-7734922ea1eb)
网站无法处理请求的脚本文件，疑似代理的链接所指向的JAVA文件”受损“或”不存在“。

所有加速模式都错误。

**Comment by rmbadmin** [comment]
已热更新修复
