### ISSUE TITLE
🧐[Question] 默认配置加速后，商店加载不全，steam离线

### ISSUE THREAD

**Issue by ch3NzZxM** [BeyondDimension/SteamTools#3270]
## 请认真检查以下清单中的每一项
- [√] 已经搜索过，没有发现类似的 issue
- [√] 已经搜索过文档，没有发现相关内容
- [√] 已经尝试使用过最新版，问题依旧存在
- [√] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by bin2516** [comment]
![image](https://github.com/BeyondDimension/SteamTools/assets/164449300/061e5cf6-7873-4956-8c89-5dd7c49631ff)
我也是这个问题遇到了，加速Steam会报错

**Comment by ch3NzZxM** [comment]
报错倒是不会，你这个应该是模式或者dns选择的不对，我的是steam离线

**Comment by ch3NzZxM** [comment]
> ![image](https://private-user-images.githubusercontent.com/164449300/315870373-061e5cf6-7873-4956-8c89-5dd7c49631ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzY4MjEsIm5iZiI6MTcxMTA3NjUyMSwicGF0aCI6Ii8xNjQ0NDkzMDAvMzE1ODcwMzczLTA2MWU1Y2Y2LTc4NzMtNDk1Ni04Yzg5LTVkZDdjNDk2MzFmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwMzAyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzNhYzk2MzcxZDk5NWI5OTc0NDIwNzk0YzdjNGE1MjZlN2ZkMmQ0MDU4MWU1Mzc0MzA3NzMzODMyMGExOTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zYs55XABlgfafmqASiScqpQg5D336JLgDzM_7AUebJQ) 我也是这个问题遇到了，加速Steam会报错

报错倒是不会，你这个应该是模式或者dns选择的不对，我的是steam离线

**Comment by bin2516** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/164449300/315870373-061e5cf6-7873-4956-8c89-5dd7c49631ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzY4MjEsIm5iZiI6MTcxMTA3NjUyMSwicGF0aCI6Ii8xNjQ0NDkzMDAvMzE1ODcwMzczLTA2MWU1Y2Y2LTc4NzMtNDk1Ni04Yzg5LTVkZDdjNDk2MzFmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMlQwMzAyMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MzNhYzk2MzcxZDk5NWI5OTc0NDIwNzk0YzdjNGE1MjZlN2ZkMmQ0MDU4MWU1Mzc0MzA3NzMzODMyMGExOTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zYs55XABlgfafmqASiScqpQg5D336JLgDzM_7AUebJQ)我也是这个问题遇到了，加速Steam会报错
> 
> 报错倒是不会，你这个应该是模式或者dns选择的不对，我的是steam离线
那你知道这种情况怎么办吗？没更新还好的，更新了最新版的就不能用了

**Comment by rmbadmin** [comment]
检查加速服务 证书 dns hosts 挨个检查下
