### ISSUE TITLE
Mac版本的本地配置文件夹在哪？

### ISSUE THREAD

**Issue by a994849598** [BeyondDimension/SteamTools#3287]
## Please check each item in the following list carefully
- [x] I have searched and found no similar issues
- [x] Have searched the documentation and found no relevant content
- [x] I have tried to use the latest version, but the problem still exists
- [x] The official version is used (no replacement and modification of the installation directory program files)

我不小心在设置中取消了“在顶部栏显示”，现在我想找到配置文件夹进行删除还原。
（无法从Dock栏打开主界面，我知道这是待解决的问题）

- Processor architecture: 
- System version number: 
- Download channels: 
- Program version: 
- Does it contain a standalone runtime:

**Comment by Mossimos** [comment]
在设置中勾选托盘显示i就行了

**Comment by Mossimos** [comment]
~/Library/Steam++
