### ISSUE TITLE
👑[Enhancement] 无GUI LINUX版本支持

### ISSUE THREAD

**Issue by yyyytawa** [BeyondDimension/SteamTools#3293]
### 🥰 需求描述(Description)

LINUX SERVER环境下有安装软件的需求,但是软件在Github上,很难连接,又不方便安装桌面

### 🧐 解决方案(Solution)
支持无GUI启动和命令行操作

**Comment by TheCCMT** [comment]
或者出个 webui

**Comment by TyxTang** [comment]
有同样的需求
