### ISSUE TITLE
👑[Enhancement] Linux installation script: don't put the .desktop file on the Desktop

### ISSUE THREAD

**Issue by xiaoshihou514** [BeyondDimension/SteamTools#3294]
### 🥰 需求描述(Description)

Many linux users don't use the `~/Desktop`, it would make more sense to put the .desktop file in `~/.local/share/applications`, which is almost always present and users can drag and drop it to the desktop if they so wish.

### 🧐 解决方案(Solution)

Change the installation script:
```bash
# previous code omitted
rm -rf "$HOME/.local/share/applications/Watt Toolkit.desktop" 2>/dev/null
mkdir -p "$HOME/.local/share/applications"
echo "#!/usr/bin/env xdg-open
[Desktop Entry]
Name=Watt Toolkit
Exec=$base_path/$exec_name.sh
Icon=$base_path/Icons/Watt-Toolkit.png
Terminal=false
Type=Application
StartupNotify=false" >"$HOME/.local/share/applications/Watt Toolkit.desktop"
chmod +x "$HOME/.local/share/applications/Watt Toolkit.desktop"
# update-desktop-database ~/.local/share/applications
#运行程序
Show_Run "下载安装完成，是否启动程序？"
exit 0
```

**Comment by Mossimos** [comment]
Sure, adding it to the desktop by default makes it convenient for Steamdeck touchscreen operation. I'll also include in the script the option to choose whether or not to add it to the desktop later on.

**Comment by xiaoshihou514** [comment]
I see, in my case I did not have the `~/Desktop` directory and I had to check the script to find out how to launch the app.

**Comment by Mossimos** [comment]
The script has been updated to support installation to a specified directory. Users can now choose between installing to $HOME/.local/share/applications/ or $HOME/Desktop/
![image](https://github.com/BeyondDimension/SteamTools/assets/26396340/dbbffa24-70ac-4074-a9e1-cb0dd480de99)
![image](https://github.com/BeyondDimension/SteamTools/assets/26396340/48450077-7dcf-4c44-b3ad-9c0b41b3fe21)

**Comment by xiaoshihou514** [comment]
Thanks for your great work!
