### ISSUE TITLE
🐛[BUG] (MacOS) 更新软件后 Steam 报错 - Invalid SSL Certificate

### ISSUE THREAD

**Issue by schtonn** [BeyondDimension/SteamTools#3295]
## 请认真检查以下清单中的每一项
- [ ] 已经搜索过，没有发现类似的 issue （见下）
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

此前有类似 Issue，然而系统均为 Linux，其中的解决方案也对 MacOS 无效，为避免挖坟提出新 Issue。

### 🐛 描述

某次版本更新后 Steam 加速失效（报 Invalid SSL Certificate），由于此后多次回退和更新，这个失效版本已无法找到。
已在 Keychain Access 中确认 `SteamTools Certificate` 证书存在且被所有用户信任。尝试了重装、重启、重置证书等办法，无果。
这个问题在我的设备上持续复现，无从解决。

### 📷 复现步骤

1. 启动 Steam 加速
2. 打开任一 Steam 页面
3. 报错：The SSL certificate for https://store.steampowered.com/... is invalid and the page will not be loaded (error:-202 status:4).

### 🚑 其他信息

- 处理器体系结构：M2
- 系统版本号：macOS Sonoma 14.3
- 下载渠道：百度网盘
- 程序版本：现有可下载版本均存在问题
- 是否包含独立运行时：

**Comment by 8yr0n-J** [comment]
Windows 11 23H2下出现同样问题。开启加速后，无法登陆Steam。登陆Steam后开启加速，出现“无效的SSL证书”提示。

**Comment by Mossimos** [comment]
钥匙串访问中彻底删除证书 且在 程序中打开AppData 删除里面的 SteamTools Certificate 证书文件 然后重开软件  开始加速  然后去钥匙串访问手动取消信任然后再信任

**Comment by schtonn** [comment]
不错，问题解决了。感谢！

**Comment by 8yr0n-J** [comment]
雀食，原来是证书过期了。Windows操作系统参考如下。进入证书管理器，在可信任的根证书颁发机构中找到SteamTool Certificate，删除后，重新运行Steam++，证书就更新好了。

**Comment by SuXYIO** [comment]
同样问题，操作后未解决，Steam仍然报错，证书未过期，且浏览器在导入后并无报错，求解

> 钥匙串访问中彻底删除证书 且在 程序中打开AppData 删除里面的 SteamTools Certificate 证书文件 然后重开软件 开始加速 然后去钥匙串访问手动取消信任然后再信任
