### ISSUE TITLE
库存游戏增加已安装筛选项👑[Enhancement] 

### ISSUE THREAD

**Issue by ShineZcx** [BeyondDimension/SteamTools#3301]
### 🥰 需求描述(Description)
1.现库存游戏是加载账号/家庭/共享的所有游戏，需要增加筛选项已安装游戏
2.增加其他平台游戏管理
### 🧐 解决方案(Solution)
1.类似steam库中的已安装选项，一键筛选出本地下载游戏并快速启动

**Comment by rmbadmin** [comment]
库存游戏已有已安装筛选
