### ISSUE TITLE
👑[Enhancement] 同人账号无法相互绑定

### ISSUE THREAD

**Issue by tecsm** [BeyondDimension/SteamTools#3308]
我用QQ和手机号分别创建了一个账号，无法相互绑定
![{5EA37835-AB23-4165-8D51-11F4D5C89314}](https://github.com/BeyondDimension/SteamTools/assets/50205866/baf38b76-ffb9-4e5a-96c4-5be2fa279ad0)

**Comment by rmbadmin** [comment]
你需要注销一个
