### ISSUE TITLE
arm64安装失败

### ISSUE THREAD

**Issue by cuicanmengxing** [BeyondDimension/SteamTools#3309]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

./Steam++.sh: 行 16: ./Steam++: 无法执行二进制文件：可执行文件格式错误
![image](https://github.com/BeyondDimension/SteamTools/assets/157385609/ab70a8d9-dc94-4c91-812e-539c5298ac4b)
![image](https://github.com/BeyondDimension/SteamTools/assets/157385609/f3478017-df51-46d0-b326-be36e7919443)

### 📷 复现步骤

1. 
2. 
3. 

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by Mossimos** [comment]
Linux 目前没有发布 arm版本 报名都写的 x64 目前仅有 macos 完全支持 arm
