### ISSUE TITLE
账号切换功能无法添加ubisoft和epic games

### ISSUE THREAD

**Issue by Leyndell31** [BeyondDimension/SteamTools#3311]
选择对应的exe路径，提示“平台路径没有正确选择”
![微信截图_20240421175217](https://github.com/BeyondDimension/SteamTools/assets/42005605/68e7a355-af71-47f5-94f9-10d737d452e5)
![微信截图_20240421175238](https://github.com/BeyondDimension/SteamTools/assets/42005605/3ec474cd-9085-4954-bed4-bcf340acf2e8)

**Comment by rmbadmin** [comment]
你能告知一下你路径中的 %23 Tools是什么样的文件夹名称吗

**Comment by Leyndell31** [comment]
> 你能告知一下你路径中的 %23 Tools是什么样的文件夹名称吗

D:\Games\#Tools\Ubisoft Game Launcher
D:\Games\#Tools\Epic Games\Launcher\Portal\Binaries\Win64

是因为watt toolkit识别的路径中不能有#号吗
![1714312482618](https://github.com/BeyondDimension/SteamTools/assets/42005605/76f62bc8-241c-4787-b268-203719496e7d)
