### ISSUE TITLE
（question）一点击网络加速就卡住崩溃Linux端

### ISSUE THREAD

**Issue by Poss-Studio** [BeyondDimension/SteamTools#3331]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by Poss-Studio** [comment]
你好，我用的是Archlinux,我用的是kde wayland会话，我下载了aur中的watt-toolkit-bin之后，打开软件点击网络加速程序就会卡住，动也动不了，点击其他部分就正常(最新3.0.0rc8)而我手动下载官网的压缩包打开steam++.sh就没有这样的问题，请问这是为什么呢？如果有时间能帮我解答以下吗？谢谢

**Comment by Mossimos** [comment]
他是直接使用 
```
#!/usr/bin/env bash

dotnet /usr/lib/watt-toolkit/Steam++.dll "$@"

```
执行的 Steam++.sh  设置了 内置的 dotnet  环境变量
你需要参考 Steam++.sh 修改下 Aur仓库中的执行脚本
```
#!/bin/bash
run_path=$(dirname "$0")
dotnet_path="$run_path/dotnet"
dotnet_exec="$dotnet_path/dotnet"
export DOTNET_ROOT="$dotnet_path"
link_exec="$run_path/Steam++"
# 判断符号链接是否存在
if [ -L "$link_exec" ]; then
    echo "符号链接 $link_exec 已存在"
else
    rm -rf "$link_exec"  2>/dev/null
    echo "创建符号链接 $dotnet_exec 到 $link_exec"
    ln -s "$dotnet_exec" "$link_exec"
    chmod +x "$link_exec"
fi
"$link_exec" "$run_path/assemblies/Steam++.dll" "$@"
exit
```

**Comment by Poss-Studio** [comment]
谢谢已经解决

**Comment by arenekosreal** [comment]
我是 aur/watt-toolkit-bin 的维护者。虽然这个 issue 已经关闭但我还是写一句以供后来人查阅：
如果在终端运行 watt-toolkit 的时候出现问题时的输出有类似 `文件具有执行权限。 Failure processing application bundle; possible file corruption. Arithmetic overflow while reading bundle. A fatal error occurred while processing application bundle` 的话，那是因为加速器主程序是通过 `-p:PublishSingleFile=true` 构建的单文件，被 makepkg strip 之后导致 .net 运行时校验不通过，在 `3.0.0.rc.8-2` 这个版本已经通过关闭自动 strip 而手动 strip 其它部分来绕过这个问题。

大概可以参考 https://github.com/Ombi-app/Ombi/issues/3916#issuecomment-742070961 这个回复，它也是一个 .net 的应用并且出现的问题和这个一样。

关于 dotnet 的问题，因为 aur/watt-toolkit-bin 自带的文件结构实在是比较不拘一格，所以我选择的是拆出程序部分使用系统的 dotnet 运行时来运行它，这也是为啥我没在 aur 的启动脚本里面使用和 Steam++.sh 一样的复杂逻辑的原因。

**Comment by arenekosreal** [comment]
![image](https://github.com/BeyondDimension/SteamTools/assets/17194552/a4c1c168-2ffa-469f-8028-c2df589c9f1a)
另外你们这个 `$link_exec` 指向的是压缩包顶层的一个叫 Steam++ 的文件？如果是这样的话我在压缩包里未发现，所以我实在是很怀疑它能否通过 Steam++.sh 正常启动？
这里仅仅是个人猜想，如有错误还请大佬指正。
