### ISSUE TITLE
🧐[Question] 启动加速后iCloud异常

### ISSUE THREAD

**Issue by alovelydoge** [BeyondDimension/SteamTools#3332]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

勾选全部加速项目+使用系统方式代理后，Windows系统下的MS Store版本iCloud表现不正常：提示需要用户输入苹果账号的密码，继续登录的iCloud，但是iCloud点击登录后会显示无法连接苹果服务器

### 🚑 其他信息

iCloud报错如图：
![image](https://github.com/BeyondDimension/SteamTools/assets/156295679/7fa240c5-e77c-4bb8-9a45-7f56c59b9eac)

系统详细信息：
版本	Windows 11 家庭中文版
版本	23H2
安装日期	‎2024/‎2/‎3
操作系统版本	22631.3527
体验	Windows Feature Experience Pack 1000.22700.1003.0

- 处理器体系结构：x64
- 系统版本号：Windows 11 23H2 22631.3527
- 下载渠道：从官网跳转的蓝奏云网盘
- 程序版本：3.0.0-rc.8 for Windows(x64)
- 是否包含独立运行时：否

**Comment by Mossimos** [comment]
UWP 需要 执行一个直接 允许访问 本地 127.0.0.1

**Comment by alovelydoge** [comment]
> ###
> **[Mossimos](/Mossimos) ** commented [May 6, 2024](#issuecomment-2095367908)

谢谢告知！
