### ISSUE TITLE
🧐[Question] 无法编译

### ISSUE THREAD

**Issue by goblock2021** [BeyondDimension/SteamTools#3333]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

尝试拉取最新版的develop仓库并编译，有大量错误
![image](https://github.com/BeyondDimension/SteamTools/assets/114788565/273485fe-bc0d-41a4-84d3-cbc07c19860a)
是我打开方式不对还是本来就没法正常编译

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 11 专业版 23H2 22631.3447
- 下载渠道：Github
- 程序版本：[542b528](https://github.com/BeyondDimension/SteamTools/commit/542b528b933b022cc2e6ec36da5af8e5efbafc31)
- 是否包含独立运行时：--

**Comment by Mossimos** [comment]
```
git submodule update --recursive
```
克隆子模块

**Comment by goblock2021** [comment]
已经克隆了所有子模块
下载了vscode弹窗让我下载的所有组件。
已经下载 .NET SDK

依然出现该问题，所以才提的这个issue

有自己构建该项目的帮助文档吗？
或者是我遗漏了什么？

**Comment by goblock2021** [comment]
问题基本解决，仍有一些模块无法正常编译，不知道搞错了什么
