### ISSUE TITLE
👑[Enhancement] 两个小建议

### ISSUE THREAD

**Issue by mxancl** [BeyondDimension/SteamTools#335]
### 🥰 需求描述(Description)

1、加速hCaptcha效果不理想，在discord登录进行该验证的过程中显示“速率受限或网络错误”，导致无法成功登录
2、可否支持对wikipedia的加速
### 🚑 其他信息(Other ### Information)

<img width="364" alt="QQ浏览器截图20210712105445" src="https://user-images.githubusercontent.com/70007204/125224274-e0bdb900-e2ff-11eb-9ee7-9b2f6cd3eb3d.png">

**Comment by Rems501** [comment]
小bug建议修复
![动画](https://user-images.githubusercontent.com/84369004/146557590-92c5be27-4c7a-4460-b99e-efc818ad7a3e.gif)

**Comment by Ra2-IFV** [comment]
建议试试现在的版本
Wikipedia就别想了，重点关注对象

**Comment by mxancl** [comment]
> 建议试试现在的版本 Wikipedia就别想了，重点关注对象

现在版本可以了
