### ISSUE TITLE
🐛[BUG] Steam++最小化后通过任务栏打开后不会回到原来位置

### ISSUE THREAD

**Issue by ghost** [BeyondDimension/SteamTools#3360]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

窗口无法正常显示在原来位置

### 📷 复现步骤

1. 打开steam ++ 点击加速
2. 最小化steam++，打开Steam，或者进行一些其他操作
3. 通过任务栏，点击最小化的steam++图标，发现窗口左上角对其了，并且竖直方向被拉长了

### 📄 日志信息

2024-06-03 19:56:59.1965|Error|SteamworksLocalApiS|Initialize fail. | SAM.API.ClientInitializeException: failed to create pipe
   at SAM.API.Client.Initialize(Int64 appId)
   at BD.SteamClient.Services.Implementation.SteamworksLocalApiServiceImpl.Initialize()

### 🖼 截图
应该上传了吧？为什么preview看不到？

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 11 beta channel 23H2 22635.3646
- 下载渠道：官网
- 程序版本：3.0.0-rc8 
- 是否包含独立运行时：不知道

**Comment by muqian2022** [comment]
![Uploading 屏幕截图 2024-06-03 200835.png…]()

**Comment by ghost** [comment]
![屏幕截图 2024-06-03 200835](https://github.com/BeyondDimension/SteamTools/assets/97910545/bfd97a29-84e4-4f02-8552-3e8a80f61222)
![屏幕截图 2024-06-03 200948](https://github.com/BeyondDimension/SteamTools/assets/97910545/db714e29-4b26-444c-92df-a948c6d8da62)

**Comment by Alengying** [comment]
这个版本就是狗屎一坨，用老版本吧

**Comment by xiamuban** [comment]
![image](https://github.com/user-attachments/assets/973dec8c-383f-4c3a-9e85-a14f07adf518)
请问解决了么，我这版本好像还是有这个问题，最小化再重新打开，它会自动固定到左上角

**Comment by Alengying** [comment]
> ![图像](https://private-user-images.githubusercontent.com/61500917/383850037-973dec8c-383f-4c3a-9e85-a14f07adf518.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwNDgxNzIsIm5iZiI6MTczMTA0Nzg3MiwicGF0aCI6Ii82MTUwMDkxNy8zODM4NTAwMzctOTczZGVjOGMtMzgzZi00YzNhLTllODUtYTE0ZjA3YWRmNTE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA4VDA2Mzc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYzYyNDQyZWMwMTk4ZGY3MzZmM2MyNjI5MzJkODc1MjJhNWI0ZTVhYmU4OTVmZTAzZTkzYmY1ZDk4NzU4MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a5P5q7_8i5yhLSQCZvdt_cMPqgas16XSvWChE92HaNE)请问解决了么，我这版本好像还是有这个问题，最小化再重新打开，它会自动固定到左上角

作者不会
