### ISSUE TITLE
🐛[BUG] 双BUG-1、修改名称导致steam 部分游戏显示分类错误———2、Watt Toolkit库存游戏不显示

### ISSUE THREAD

**Issue by yymiDream** [BeyondDimension/SteamTools#3371]
## 请认真检查以下清单中的每一项
- [√] 已经搜索过，没有发现类似的 issue
- [√] 已经搜索过文档，没有发现相关内容
- [√] 已经尝试使用过最新版，问题依旧存在
- [√] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

1、修改游戏名称导致steam 部分游戏显示分类错误，显示无此分类并且steam卡死
2、人工重新分类后，Watt Toolkit库存游戏不显示

### 📷 复现步骤

1.打开Watt Toolkit库存游戏-库
2.修改游戏名称-修改极限竞速：地平线4 和 5 ，由英文改为中文
3.打开Watt Toolkit库存游戏-编辑-保存全部更改到 steam
4.出现steam 部分游戏分类错误，部分游戏分类打开并且无法点击-号收回，点击分类名称就会在steam上方显示此分类不存在+错误代码，并且steam会卡死（忘记截图）
5.人工修改游戏分类，把游戏移除当前分类，在未分类里将该游戏重新分类时发现，右键点击游戏-添加至-里有该游戏的原有分类
6.人工修改完游戏分类有strem分类恢复正常使用
7.打开Watt Toolkit-库存游戏-库——发现无法读取到游戏库存
![Steam++_V6UlCb1dfr](https://github.com/BeyondDimension/SteamTools/assets/132929109/74dd1144-fb2e-4702-8311-28e27b5c7374)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 10-21H2
- 下载渠道：官网
- 程序版本：3.0.0-rc.8
- 是否包含独立运行时：

**Comment by Overlapper** [comment]
我也是库存加载不了

**Comment by HuaYunFX** [comment]
我的也是，而且我加速后，登录steam，会出现这个
![image](https://github.com/BeyondDimension/SteamTools/assets/126221964/d7ed5051-54b6-4eb2-8673-fcdbae0c4974)
看之前作者解释说是受信任证书的问题，我导入证书依然不行

**Comment by kaneeies** [comment]
我也加载不了

**Comment by tsukiyoz** [comment]
我也是，如何解决这个问题？
"appinfo.vdf" magic code is not supported: 0x07564429
库存游戏加载不了

**Comment by yyfmaster** [comment]
我都没有修改游戏名字，有一天突然就加载不了库存了，而且重新安装最新版软件也没用

**Comment by FastChen** [comment]
原因是 Steam Beta 更新了游戏文件数据，所以读取不了

目前解决方案：
1. 取消参与任何 Beta 测试计划，包括 Steam Beta Update 与 Steam Families Beta
2. 等待更新

官方网站发布说明：[Steam Beta 客户端 6 月 27 日更新](https://steampp.net/Article/Detail?id=6aa563b9-ded2-41a2-ac86-e9621ccc2f4f)

@yyfmaster 、 @lazywoo 、 @kaneeies 、 @HuaYunFX 、 @Overlapper 、 @yymiDream

**Comment by HuaYunFX** [comment]
已经解决，我昨天晚上从家庭beta版改为取消参与任何 Beta 测试计划，重启电脑后，问题解决可以读取库存信息。
但网络加速按指南加速重置后，没有出现SSL问题，但无法访问任何steam服务器，steam无法载入网页，查询网络问题报错：502 Bad Gateway

**Comment by rmbadmin** [comment]
> 已经解决，我昨天晚上从家庭beta版改为取消参与任何 Beta 测试计划，重启电脑后，问题解决可以读取库存信息。 但网络加速按指南加速重置后，没有出现SSL问题，但无法访问任何steam服务器，steam无法载入网页，查询网络问题报错：502 Bad Gateway

加速问题提供 设置 存储空间 Logs文件夹 Accelerator 文件夹内日志

**Comment by HuaYunFX** [comment]
请问是这个吗 @rmbadmin

![image](https://github.com/BeyondDimension/SteamTools/assets/126221964/8a2aaeb1-4fa5-4d52-9be3-8e58af7a4789)

2024-06-30 10:10:07.7988|Error|BD.WTTS.Services.Implementation.RequestLoggingMiddleware|GET https://store.steampowered.com/ responded 502 in 218.7939 ms
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. (store.steampowered.com:443)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) ......

**Comment by tallpeekaboo** [comment]
希望优化这个功能,以便在家庭版本中使用

**Comment by rmbadmin** [comment]
> 请问是这个吗 @rmbadmin
> 
> ![image](https://private-user-images.githubusercontent.com/126221964/344439756-8a2aaeb1-4fa5-4d52-9be3-8e58af7a4789.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDQ1NDksIm5iZiI6MTcyMTA0NDI0OSwicGF0aCI6Ii8xMjYyMjE5NjQvMzQ0NDM5NzU2LThhMmFhZWIxLTRmYTUtNGQ1Mi05YmUzLThlNThhZjdhNDc4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxMTUwNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGYzZjI4MGNiMmY2Y2NmMTgwZDE0ZTM3MTkzMzI2OWM5MTA0ODliY2U5MWQyNDY4YjkzNzJjOWIxNzhhNmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._K_wP2cPodkNN62QFdFBjExjgVGa2rtnzksjfiQNacU)
> 
> 2024-06-30 10:10:07.7988|Error|BD.WTTS.Services.Implementation.RequestLoggingMiddleware|GET https://store.steampowered.com/ responded 502 in 218.7939 ms System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. (store.steampowered.com:443) ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。. ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。 --- End of inner exception stack trace --- at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) ......

尝试关闭doh或者切换下doh地址以及dns地址
