### ISSUE TITLE
🐛[BUG] 库存游戏页面报错

### ISSUE THREAD

**Issue by gakkiyomi** [BeyondDimension/SteamTools#3374]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [ ] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
点击库存页面不显示，点击刷新按钮报错

### 📷 复现步骤
1. 点击库存页面不显示
2. 点击刷新按钮报错

### 🖼 截图
![image](https://github.com/BeyondDimension/SteamTools/assets/41406557/abaa1073-9c73-43f2-a5e3-87d1d0261fd8)

### 🚑 其他信息
- 系统版本号：Windows 10
- 程序版本：3.0.0-rc.8

**Comment by aqua1016** [comment]
一样 应该是软件bug了

**Comment by 844374939** [comment]
![屏幕截图 2024-06-28 133521](https://github.com/BeyondDimension/SteamTools/assets/38110533/ac63a469-5591-4782-a33f-cc8ae562e495)
一样的问题

**Comment by rmbadmin** [comment]
steam beta版更新改了游戏数据文件，可以还原不用beta版或者等软件更新即可
