### ISSUE TITLE
🐛[BUG] 获取不到游戏库存信息，提示"appinfo.vdf" magic code is not supported: Ox07564429

### ISSUE THREAD

**Issue by yamero233** [BeyondDimension/SteamTools#3376]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 📷 复现步骤

1. 
2. 
3. 

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by ohotto** [comment]
附议，问题一致

**Comment by devnakx** [comment]
+1

**Comment by juliy819** [comment]
+1

**Comment by Nanako464** [comment]
+1

**Comment by lo-77** [comment]
+1

**Comment by rmbadmin** [comment]
重复 #3374

**Comment by RickS153** [comment]
![Snipaste_2024-06-29_00-58-14](https://github.com/BeyondDimension/SteamTools/assets/167489496/29dcc743-c59d-4951-812a-11b0695482c3)
+1

**Comment by StarlingLin** [comment]
![image](https://github.com/BeyondDimension/SteamTools/assets/139955759/b3318ebd-b7a9-4361-b897-88c0dab509f1)
同样的问题

**Comment by ssssbb1122** [comment]
!['appinfo vdf magic code is not supported 0x07564429](https://github.com/BeyondDimension/SteamTools/assets/169594624/59a5f6f0-dfe8-4206-b7ec-82455c197d3b)

**Comment by ssssbb1122** [comment]
![Uploading 'appinfo.vdf magic code is not supported 0x07564429.png…]()

**Comment by ssssbb1122** [comment]
![QQ截图20240629100053](https://github.com/BeyondDimension/SteamTools/assets/169594624/8396a2b2-110d-41e9-aaae-0a0dff58a80a)

**Comment by ssssbb1122** [comment]
![QQ截图20240629100150](https://github.com/BeyondDimension/SteamTools/assets/169594624/4ef8cbb7-db8d-43a7-affb-16731d210eb3)

**Comment by wang-ziyin1997** [comment]
same issue

**Comment by ixLeTh3E** [comment]
same++
![image](https://github.com/BeyondDimension/SteamTools/assets/29089296/5632e926-4243-481e-809f-093ff2b40823)

**Comment by 1i9htning** [comment]
已经知道原因了，STAEM BETA版本就会出现这个BUG，可能是STEAM更改了API。切换回正式版STEAM就正常了
