### ISSUE TITLE
🐛[BUG] 绿色版无法干净卸载

### ISSUE THREAD

**Issue by cadexI9wUR7** [BeyondDimension/SteamTools#3377]
下载的是官网的Steam++_v3.0.0-rc.8_win_x64.7z，解压后运行，删除文件夹后，每次重启还是有Steam++的开机提示（多少秒，哪个区。。。）。

整个硬盘都搜过了，没有任何Steam++的文件了。
再解压一次Steam++，解压后运行，删除文件夹后，开机提示反而又多了一个。

按照这个操作后问题还在
https://answers.microsoft.com/zh-hans/windows/forum/all/%E5%A6%82%E4%BD%95%E5%8E%BB%E9%99%A4%E5%B7%B2/a2f57986-0735-4949-bb09-92b96897c5cf

-->

![steam](https://github.com/BeyondDimension/SteamTools/assets/121579484/b477843f-36b1-439a-a02a-e22b4da50424)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 10
- 下载渠道：官网
- 程序版本：v3.0.0-rc.8
- 是否包含独立运行时：

**Comment by rmbadmin** [comment]
这个记录是 windows 存的，与 steam++ 没关系，任何弹出过 windows 通知的程序都会被自动添加记录进这个列表，
具体位置在 Windows 注册表
 `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Notifications\Settings`
你可以在这个路径下检索对应项，或者直接清空此注册表文件夹，反正只要有应用再次弹出 Windows 通知时，依然会被 Windows 自动添加进来的
