### ISSUE TITLE
🐛[BUG] 挂时长界面图标重叠

### ISSUE THREAD

**Issue by tarabyee** [BeyondDimension/SteamTools#3379]
## 请认真检查以下清单中的每一项
- [√] 已经搜索过，没有发现类似的 issue
- [√] 已经搜索过文档，没有发现相关内容
- [√] 已经尝试使用过最新版，问题依旧存在
- [√] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
在挂时长——挂机界面。

当挂时长状态为暂停时，
将鼠标悬停在某游戏上方会同时出现“开始”和“暂停”图标

### 📷 复现步骤

1. 打开左侧“库存游戏”
2. 点击右上方的“挂机”板块
3. 点击“全部暂停”
4. 将鼠标悬停在游戏标志上方

### 📄 日志信息
无相关日志

### 🖼 截图

![屏幕截图 2024-06-29 232201](https://github.com/BeyondDimension/SteamTools/assets/167688985/8b52ed00-8891-4ab8-8a11-2e3bbea80110)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Microsoft Windows 11 版本 23H2（OS内部版本：22631.3737）
- 下载渠道：官网
- 程序版本：3.0.0-rc8 for Windows (x64)
- 是否包含独立运行时：

**Comment by rmbadmin** [comment]
已修复问题
