### ISSUE TITLE
🐛[BUG] 库存游戏无法获取到游戏数据

### ISSUE THREAD

**Issue by xiayuexuxian** [BeyondDimension/SteamTools#3380]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

打开软件点击库存游戏无法获取到游戏数据

### 📷 复现步骤

1. 打开软件
2. 点击库存游戏

### 🖼 截图

![image](https://github.com/BeyondDimension/SteamTools/assets/111733371/9123b29a-5229-46c1-ba02-65ab5dcc6b68)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：版本	Windows 11 家庭中文版
版本号	23H2
安装日期	‎2023/‎3/‎15
操作系统版本	22631.3737
序列号	PF30K8EB
体验	Windows Feature Experience Pack 1000.22700.1009.0

- 下载渠道：官网
- 程序版本：3.0.0-rc.8 for windows (x64)
- 是否包含独立运行时：

**Comment by HuaYunFX** [comment]
1.取消参与任何 Beta 测试计划，包括 Steam Beta Update 与 Steam Families Beta
2.重启电脑

**Comment by rmbadmin** [comment]
重复 #3376 #3370
