### ISSUE TITLE
🐛[BUG] ubuntu24.04 用提供的脚本安装打不开界面

### ISSUE THREAD

**Issue by dxzhan** [BeyondDimension/SteamTools#3382]
用官网提供的Linux.sh脚本在ubuntu24.04上安装后，打不开主面板。点了没反应。

**Comment by Mossimos** [comment]
经过测试 于 deepin 上能正常打开  ubuntu24.04 等待我晚点继续测试

**Comment by dxzhan** [comment]
昨天更新了下系统，现在可以打开了
