### ISSUE TITLE
🐛[BUG] 请输入标题 本地令牌 Steam App共存令牌无法导入

### ISSUE THREAD

**Issue by 372377909** [BeyondDimension/SteamTools#3388]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 📷 复现步骤

手机ios，电脑windows10，导入共存令牌时，电脑端无法正常登录，会卡到最后一步，手机端能收到登录请求，但是批准之后也无法使得电脑端登陆成功。

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by yingpanwang** [comment]
移动端网络请求 Steam 网络是正常的吗 ? 
使用令牌验证码登录是否正常?

**Comment by 372377909** [comment]
> 移动端网络请求 Steam 网络是正常的吗 ? 使用令牌验证码登录是否正常?

移动端（ios）可以正常接收到watt的登录请求，但是批准之后，仍然卡在watt绑定令牌登陆界面，其他都没有问题，只是共存令牌无法实现。

**Comment by yingpanwang** [comment]
> > 
> 
> 移动端（ios）可以正常接收到watt的登录请求，但是批准之后，仍然卡在watt绑定令牌登

什么意思,卡在哪个界面?

目前共存令牌的逻辑

前提是 ***未绑定令牌的账号*** (目前不支持替换令牌的逻辑)

在Watt 客户端 中初始化获取令牌数据

Steam App 中完成令牌绑定的动作

绑定的步骤是在 Steam App 完成的 ( 所以无法支持替换令牌逻辑 )

**Comment by 372377909** [comment]
不好意思，我刚开始没弄明白共存令牌的操作流程，目前已经解决了。
