### ISSUE TITLE
🐛[BUG] 双重图标

### ISSUE THREAD

**Issue by LeiDellTech** [BeyondDimension/SteamTools#3392]
## 请认真检查以下清单中的每一项
- [ yes] 已经搜索过，没有发现类似的 issue
- [yes] 已经搜索过文档，没有发现相关内容
- [yes ] 已经尝试使用过最新版，问题依旧存在
- [ yes] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 📷 复现步骤

1. 一进就是暗黑模式
2. 指针在右上角
3. 图标就双重了
 

### 🚑 其他信息

- 处理器体系结构：11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz   2.69 GHz        (X64)
- 系统版本号：Windows 11 专业版 22631.3737
- 下载渠道：微软商店
- 程序版本：3.0.908.0

**Comment by LeiDellTech** [comment]
![屏幕截图 2024-07-08 121530](https://github.com/BeyondDimension/SteamTools/assets/153336711/630b4eb4-ebfd-48c6-bd68-504125c187ae)
![屏幕截图 2024-07-08 121543](https://github.com/BeyondDimension/SteamTools/assets/153336711/0df0ac4a-fc9d-4adf-ae3c-43d71c591798)
![屏幕截图 2024-07-08 121600](https://github.com/BeyondDimension/SteamTools/assets/153336711/a2e85a9a-7c23-4293-9c73-18643c1ac2f7)
![屏幕截图 2024-07-08 121607](https://github.com/BeyondDimension/SteamTools/assets/153336711/68f47961-985d-46dd-935e-90bdf4b94862)
![屏幕截图 2024-07-08 121638](https://github.com/BeyondDimension/SteamTools/assets/153336711/407a8f17-9e01-4626-a732-cb229a275e4a)

**Comment by rmbadmin** [comment]
调整背景透明度或者透明材质即可
