### ISSUE TITLE
👑[Enhancement] 在 启动Steam时 自动启动加速 

### ISSUE THREAD

**Issue by 23286440** [BeyondDimension/SteamTools#3399]
### 🥰 需求描述(Description)

+ 在 启动Steam时 自动启动加速 或 启动加速顺便启动Steam，简化启动流程 ( 在托盘图中加一个组合命令的小按钮？

### 🧐 解决方案(Solution)

+ 在托盘图标中加一个“加速启动Steam”（雾？）的选项，然后顺序调用加速代码然后Sleep或者等待返回后调用启动Steam部分代码

### 🚑 其他信息(Other Information)

+ 无

**Comment by rmbadmin** [comment]
已有此功能
