### ISSUE TITLE
👑[Enhancement] 希望可以实现两个watt toolkit共存

### ISSUE THREAD

**Issue by eden-chen3** [BeyondDimension/SteamTools#3400]
### 🥰 需求描述(Description)

现有两个watt toolkit（steam++），版本分别是1.1.4和3.0.0，一个用来实现pixiv加速，一个实现spotify加速，现欲实现双版本共存，以实现两个网页同时加速

### 🧐 解决方案(Solution)

-

### 🚑 其他信息(Other Information)

-

**Comment by rmbadmin** [comment]
加速是冲突的没有办法支持
