### ISSUE TITLE
🐛[BUG] 被腾讯电脑管家报毒——修改host文件，且无法添加至信任名单

### ISSUE THREAD

**Issue by CaiDangt** [BeyondDimension/SteamTools#3405]
![QQPCTray exe_20240715_172933](https://github.com/user-attachments/assets/89332bbf-413a-4e4e-8544-0ff105f77b1b)
![QQPCTray exe_20240715_172954](https://github.com/user-attachments/assets/079039a5-e5e8-4831-8fbc-05f13bcd1d6d)
每次打开加速都会弹出

**Comment by rmbadmin** [comment]
这个问题与steam++无关
