### ISSUE TITLE
🧐[Question] ajax.googleapis.com 无法使用

### ISSUE THREAD

**Issue by xuanxuan1231** [BeyondDimension/SteamTools#3409]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

ajax.googleapis.com 无法使用。测试时使用 `https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js` 报错：
```
Request:Could not find any IP that can be successfully connected. (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (ajax.loli.net:443)
```
或
```
Request:Could not find any IP that can be successfully connected. (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert:'HandshakeFailure'.) (Authentication failed because the remote party sent a TLS alert: 'HandshakeFailure'.) (ajax.loli.net:443)
```

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 11 Pro for Workstation 24H2 (内部版本 26100.1150)
- 下载渠道：Github
- 程序版本：3.0.0-rc.8

Hosts/PAC/System (使用 Firefox 128)：
![image](https://github.com/user-attachments/assets/c64716a4-affe-4ae4-b0d8-0da0b6da7922)

DNSIntercept/PAC (使用 Edge 126)：
![image](https://github.com/user-attachments/assets/75c495b0-2521-4b36-b6cf-a8deafe5f0e3)

**Comment by rmbadmin** [comment]
已热更新修复
