### ISSUE TITLE
🧐[Question] linux环境下开启加速后使用curl等工具时无法验证证书,是否有方法可支持

### ISSUE THREAD

**Issue by littlebananafish** [BeyondDimension/SteamTools#3417]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

linux环境下开启加速后使用curl等工具时无法验证证书，使用--cacert指定steamtools.cer依然无效
### 🚑 其他信息

![微信图片_20240729094838](https://github.com/user-attachments/assets/8bb5d994-7864-4199-84a1-669998657a52)

- 处理器体系结构：x64
- 系统版本号：ubuntu24.04
- 下载渠道：gitee
- 程序版本：3.00-rc9
- 是否包含独立运行时：

**Comment by Mossimos** [comment]
请在程序 加速设置 打开证书文件夹 手动导入证书到系统信任根证书 ，Linux 发行众多 自动安装仅尝试适配几个发行版本 ubuntu 按理说适配了的 但是可能安装不成功需要手动导入

**Comment by blqdswkl** [comment]
id.twitch.tv提示502？

**Comment by littlebananafish** [comment]
问题已通过手动导入证书解决，以ubuntu24.04为例，将证书重命名为.crt格式，cp证书到/usr/local/share/ca-certificates，通过update-ca-certificates更新证书库即可，部分网址可能依然存在访问问题，可尝试关闭加速时的脚本注入

**Comment by littlebananafish** [comment]
另，使用证书自动安装脚本时若终端报setlocale:LC_ALL错误，可能是因为系统并未安装英文语言包，而脚本需要设置该变量，桌面系统可通过”语言支持“进行安装
