### ISSUE TITLE
人机开奖

### ISSUE THREAD

**Issue by snhyy2q1** [BeyondDimension/SteamTools#3424]
几把送不起就别尼玛送，搞个尼玛活动看人数不够硬生生拖尼玛两个礼拜？你妈死了老子支持一波给你点愿望单，活动结束前一天2000多人一看人少了送不起你个没妈的东西就硬延长活动开奖和公示日期？硬生生找尼玛3000个机器人把你奖池分完是吧，内幕狗不得好死，连尼玛是什么人或者说不是人的东西把奖分走你是真几把牛逼，送不起别送，小丑！
送不起别送，送不起别送，送不起别送，送不起别送，送不起别送，送不起别送，送不起别送，送不起别送，送不起别送，送不起别送，送不起别送，送不起别送，送不起别送，送不起别送，送不起别送

**Comment by a123456-abcd** [comment]
你好，我是本次活动的运营，这次活动给你带来了疑问首先说个抱歉，也对你没有中奖的沮丧和愤怒心情表示理解。
对于你的质疑我可以做出以下简单回复：
1、我们抽奖活动一直都是真实不作假的，当然目前也确实有一些做的不好的地方，因为目前的抽奖算法确实只是取随机数，这样有点黑盒了被产生怀疑也是正常。
2、延期是因为活动开始后，7月15日又对活动做了升级追加了一个参与奖活动，确实想让更多人参与到活动中而忽视了已参与用户的利益。对此我深表歉意
针对以上两点反馈问题做出如下改动
1、会改进使用公开算法进行抽奖并且完善抽奖规则和开奖页面，让各位都可以自证抽奖结果。
2、充分考虑各方利益，今后对已上线的活动，不再做有损已参与用户利益的临时修改。
同时，也欢迎你继续监督

**Comment by a123456-abcd** [comment]
此外，Github 是反馈软件问题的地方，活动运营问题到官网商务合作反馈可以更快速的获得回复。
