### ISSUE TITLE
🐛[BUG] 解析总是导致评论无法发出

### ISSUE THREAD

**Issue by zhaowenjunan** [BeyondDimension/SteamTools#3426]
### 🐛 描述

加速steam社区，社区内评论区发言会显示【发言过于频繁已禁止】，切换梯子恢复

### 📷 复现步骤

1. 
2. 
3. 

### 🖼 截图

![image](https://github.com/user-attachments/assets/635a2b62-b6fe-4261-b873-91a0a8dd8ddd)

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by rmbadmin** [comment]
如果你的网络环境有ipv6的话，在steam加速项中去掉 steam 讨论留言/IPV4的 勾选应该就可以解决
