### ISSUE TITLE
🧐[Question] 库存功能似乎无法使用

### ISSUE THREAD

**Issue by wybzdqs** [BeyondDimension/SteamTools#3430]
## 请认真检查以下清单中的每一项
- [✓] 已经搜索过，没有发现类似的 issue
- [?] 已经搜索过文档，没有发现相关内容
- [✓] 已经尝试使用过最新版，问题依旧存在
- [✓] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述
在使用库存功能时出现了如图所示的问题，不知道要如何解决
在文档中的解决方法已经使用了，并没有解决此问题

### 🚑 其他信息
![屏幕截图 2024-08-05 163458](https://github.com/user-attachments/assets/5342e10a-64f6-4b38-849b-e1224dafb0be)

- 处理器体系结构： x64 
- 系统版本号：Windows 11.22631.3958
- 下载渠道： 微软商店 
- 程序版本：3.0.0-rc.8 
- 是否包含独立运行时：不确定

**Comment by Mossimos** [comment]
更新RC9 微软商店现在被卡审核 卡了快一个月了

**Comment by rmbadmin** [comment]
已更新修复
