### ISSUE TITLE
🐛[BUG] R8更新R9后DNSIntercept加速模式无法使用

### ISSUE THREAD

**Issue by Avenger233** [BeyondDimension/SteamTools#3435]
## 请认真检查以下清单中的每一项
- [√] 已经搜索过，没有发现类似的 issue
- [√] 已经搜索过文档，没有发现相关内容
- [√] 已经尝试使用过最新版，问题依旧存在
- [√] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述
测试版R8更新测试版R9后，用DNSIntercept显示0KB，停止加速时报错。
![image](https://github.com/user-attachments/assets/a3aaf9e8-90ce-41d7-86de-5a74064219f2)
![3762a6a46c9ebf7b611d70ec76da950c](https://github.com/user-attachments/assets/31dab706-ab6e-4085-a07d-4d32ac143b7b)
### 📷 复现步骤
1. 使用测试版R8版本
2. 安装测试版R9版本
3. 使用DNSIntercept加速模式
### 📄 日志信息
[nlog-all-2024-08-10.log](https://github.com/user-attachments/files/16570060/nlog-all-2024-08-10.log)
[nlog-all-2024-08-10.log](https://github.com/user-attachments/files/16570061/nlog-all-2024-08-10.log)
### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows10 22H2(19045.3693)
- 下载渠道： github
- 程序版本：3.0.0-rc.9
- 是否包含独立运行时：无

**Comment by rmbadmin** [comment]
已知问题，暂时使用其他模式，后续更新解决

**Comment by Avenger233** [comment]
> 已知问题，暂时使用其他模式，后续更新解决

好吧
