### ISSUE TITLE
🐛[BUG] Ubuntu Microsoft Edge GitHub无法访问

### ISSUE THREAD

**Issue by Enderman-TPing** [BeyondDimension/SteamTools#3437]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 📷 复现步骤

1. 正常运行watt toolkit加速（加速选项包含GitHub）
2. 使用Edge浏览器访问GitHub，发现无法加载，流量统计的图像也是直线
3. 用导入过证书的火狐浏览器可以正常访问GitHub并且像我这样发Issue
4. 尝试在Edge导入证书，发现无法导入

### 📄 日志信息
[nlog-all-2024-08-11.log](https://github.com/user-attachments/files/16573726/nlog-all-2024-08-11.log)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Ubuntu 22.04.4 LTS
- 下载渠道：Gitee
- 程序版本：3.0.0-rc 9 for Ubuntu (x64)
- 是否包含独立运行时：

**Comment by Enderman-TPing** [comment]
补张图
![图片](https://github.com/user-attachments/assets/84119162-c809-4035-80bc-b43e26d9c46b)
![图片](https://github.com/user-attachments/assets/fffd2615-ed29-4335-b82f-a90bb4118748)

**Comment by Enderman-TPing** [comment]
证书应该是有的，但是还是访问不了

**Comment by rmbadmin** [comment]
流量统计是直线表示你的网络访问没有正常走到程序代理内，尝试更换代理模式或者检查hosts是否对浏览器有正常生效

**Comment by Enderman-TPing** [comment]
现设置加速模式为System
![图片](https://github.com/user-attachments/assets/e7911ea8-71ce-4f8f-815b-b4754dd5640d)
![图片](https://github.com/user-attachments/assets/72a79e7f-7eec-4874-a4ad-5657b7179b41)
![图片](https://github.com/user-attachments/assets/eb44eb22-9ae5-4cc9-9b14-69158095365e)

**Comment by Enderman-TPing** [comment]
甚至...
![图片](https://github.com/user-attachments/assets/eb797acc-8c81-4e81-ba8e-839c13aa8863)
但是火狐浏览器就不受影响

**Comment by rmbadmin** [comment]
你没有正确信任程序的证书

**Comment by Enderman-TPing** [comment]
我的ubuntu系统坏掉了 换了一个parrot OS 现在github可以随便上 没有这个问题了（不过好像watt仍然有问题，但是我的issue已经没有参考价值了 所以close了）
