### ISSUE TITLE
🐛[BUG] 加速证书与安全性问题

### ISSUE THREAD

**Issue by SuXYIO** [BeyondDimension/SteamTools#3454]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🐛 描述

在开启`Github`加速服务后(没有开别的脚本), `LibreWolf`显示`未连接, 有潜在风险`(详见截图), `Safari`则显示`无法建立安全连接`, 并且二者都不提供忽略风险选项. 
证书安装并信任了, 这个电脑装过好多版本, 所以我发现时已经好几个重复证书了, 在钥匙串里也删不掉, 点右键-删除没反应. 

### 📷 复现步骤

暂时不知道能否复现. 
1. 正常流程安装steamtools(版本已在其他项目中提到)
2. 打开`Github加速`, 并根据提示安装证书
3. 打开浏览器(`LibreWolf`与`Safari`, 其他的没测试过), 并访问`github.com`

### 📄 日志信息

```
2024-08-22 22:07:02.8435|Error|CertificateManager|Please manually install the CA certificate /Users/myuser/Library/Steam++/SteamTools.Certificate.pfx to a trusted root certificate authority. | System.Security.Cryptography.CryptographicException: Access is denied.
   at Internal.Cryptography.Pal.StorePal.AppleTrustStore.OpenStore(StoreName storeName, StoreLocation location, OpenFlags openFlags)
   at Internal.Cryptography.Pal.StorePal.FromSystemStore(String storeName, StoreLocation storeLocation, OpenFlags openFlags)
   at System.Security.Cryptography.X509Certificates.X509Store.Open(OpenFlags flags)
   at System.Application.Services.Implementation.YarpCertificateManagerImpl.SharedTrustRootCertificate()
```
这个日志感觉在说证书没安装好, 但是我在钥匙串里看到已经安装并信任了, 也不知道是哪个版本的日志了. 

### 🖼 截图

> LibreWolf提示安全风险
![Screen Shot](https://github.com/user-attachments/assets/bc5c2d19-8064-47e3-b103-0857c4130fcd)

### 🚑 其他信息

系统: x64, MacOS 12.7.5, 官网下载
版本: 在2.8.6, 3.0.0-rc.1,3,9皆有出现, 推测其他版本也会有

**Comment by SuXYIO** [comment]
哦, 加速后即使停止加速, 使用`git`进行远程相关操作(如`push`), 会显示
```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the EDXXXXX key sent by the remote host is
SHA256:XXXX/XXXXXXXXXXXXXXXXXXXXXXX.
Please contact your system administrator.
Add correct host key in /Users/myuser/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /Users/myuser/.ssh/known_hosts:3
Host key for github.com has changed and you have requested strict checking.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by rmbadmin** [comment]
证书每次重新安装时都会重新生成一份新的，确保安装的是最新的软件使用的证书，不然只是名字相同实际上证书是对不上的，旧证书全都可以直接删了，没有任何作用的

**Comment by SuXYIO** [comment]
不知道为啥之前的证书删不掉，用macos自带的`Keychain Access`，<kbd>右键</kbd>-<kbd>删除</kbd>，没反应。
当然，证书的问题可以先不管（我没有特别强的赛博洁癖），主要问题还是 __浏览器不允许访问__。

**Comment by Mossimos** [comment]
用macos自带的Keychain Access，右键-删除，没反应。 估计是你系统设置了啥系统保护还是啥
看日志 Access is denied. 是权限被拒绝了 程序使用 系统安全 提权安装也被拒绝了

**Comment by SuXYIO** [comment]
好了，解决方案是把证书添加进`Firefox/Librewolf`的`设置-安全-证书`中，并信任

**Comment by KangLin** [comment]
@SuXYIO 具体如何设置？

**Comment by KangLin** [comment]
@SuXYIO 具体如何设置？
