### ISSUE TITLE
👑 [增强]能成功打开Steam讨论区

### ISSUE THREAD

**Issue by QianNianHZ** [BeyondDimension/SteamTools#346]
### 🥰 需求描述(Description)
到现在，Steam++还不能打开讨论区
到现在，Steam++不能打开Steam讨论区。
我在chongqing,china电信。

### 🧐 解决方案(Solution)

我不是很会编程。
但是可能这个方法需要VPN。你可以尝试做一个开关。

**Comment by rmbadmin** [comment]
目前已支持ipv6网络加速steam 讨论和留言 相关功能
