### ISSUE TITLE
👑[Enhancement] 挂卡列表支持来源于家庭共享的游戏

### ISSUE THREAD

**Issue by SeeleVolleri** [BeyondDimension/SteamTools#3473]
### 🥰 需求描述(Description)

目前挂卡列表不展示家庭成员的游戏，希望能挂来自家庭成员的游戏。

**Comment by rmbadmin** [comment]
家庭库共享的游戏也不会让你掉卡，这样做的意义是？

**Comment by SeeleVolleri** [comment]
> 家庭库共享的游戏也不会让你掉卡，这样做的意义是？

了解，我以为家庭共享会掉卡。
