### ISSUE TITLE
🧐[Question] clash开启代理的情况下，将stema++和steam设置直连，脚本没有生效，关闭代理后，脚本又可以生效了

### ISSUE THREAD

**Issue by cysx07** [BeyondDimension/SteamTools#3474]
## 请认真检查以下清单中的每一项
- [ √ ] 已经搜索过，没有发现类似的 issue
- [ √ ] 已经搜索过文档，没有发现相关内容
- [ √ ] 已经尝试使用过最新版，问题依旧存在
- [ √ ] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 
在clash里设置了  - PROCESS-NAME,Steam++.exe,DIRECT和  - PROCESS-NAME,steamwebhelper.exe.exe,DIRECT
然后勾选启用脚本后，加速steam，steam可以正常使用商店社区等功能，但是脚本查询价格和解锁访问限制没有生效，关闭clash系统代理后，重新打开steam，脚本可以正常使用了，请问，我应该怎么操作，才可以在clash开启代理的情况下，正常使用脚本

### 🚑 其他信息

- 处理器体系结构： x64
- 系统版本号：win11 专业版 23h2   22631.4112
- 下载渠道： 官网 
- 程序版本：3.0.O-rc-7 for Windows (x64)

**Comment by Rikan-Lordship** [comment]
只要clash开启系统代理就会抢Steam++的代理导致js无法注入，所以你clash写的分流规则也无法使脚本生效，你能进steam商店也是走的clash分流。如果需要clash和脚本同时使用可以启用clash的虚拟网卡（Tun）模式并关闭系统代理，同时Steam++ “加速设置”-“代理设置”中关闭DoH，启用脚本并使用Hosts模式加速steam

**Comment by Rikan-Lordship** [comment]
补充一下此现象的原因：steam++通过加速服务拦截网络请求将JS脚本注入Steam内置浏览器网页，所以只能让clash使用虚拟网卡模式运行在网络最外层，steam+加速服务运行在中间层注入js，最后steam内置浏览器就得到处理好的页面（非计算机专业，如果用词有错误请谅解）

**Comment by rmbadmin** [comment]
> 只要clash开启系统代理就会抢Steam++的代理导致js无法注入，所以你clash写的分流规则也无法使脚本生效，你能进steam商店也是走的clash分流。如果需要clash和脚本同时使用只能使用clash的虚拟网卡（Tun）模式并关闭系统代理，同时Steam++启用脚本并加速steam

其实也可以clash监听后 转发至steam++即可，注意转发的ip和端口是steam++的本地端口和ip就行，
亦或者也可以
![image](https://github.com/user-attachments/assets/c4d29cf8-c562-45c7-8a60-c9b69d60ef31)
由steam++监管监听后配合这几个选项转发至clash，都可以

**Comment by cysx07** [comment]
> > 只要clash开启系统代理就会抢Steam++的代理导致js无法注入，所以你clash写的分流规则也无法使脚本生效，你能进steam商店也是走的clash分流。如果需要clash和脚本同时使用只能使用clash的虚拟网卡（Tun）模式并关闭系统代理，同时Steam++启用脚本并加速steam
> 
> 其实也可以clash监听后 转发至steam++即可，注意转发的ip和端口是steam++的本地端口和ip就行， 亦或者也可以 ![image](https://private-user-images.githubusercontent.com/12234359/365361853-c4d29cf8-c562-45c7-8a60-c9b69d60ef31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3Njk5NzAsIm5iZiI6MTcyNTc2OTY3MCwicGF0aCI6Ii8xMjIzNDM1OS8zNjUzNjE4NTMtYzRkMjljZjgtYzU2Mi00NWM3LThhNjAtYzliNjlkNjBlZjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA4VDA0Mjc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0YmFkMDY3OTc1ZjkyMWQ3YzkwNDRmMWVmNDRlMmI5ODIxYWNkZjZlNDYwYzhiYTVlYjdjMDdhZjIzOGVkZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2xA2vV3mi9nJizPF42NmzixdWJa4uh-baVWwB4llJXk) 由steam++监管监听后配合这几个选项转发至clash，都可以

谢谢大佬指点

**Comment by cysx07** [comment]
> 补充一下此现象的原因：steam++通过加速服务拦截网络请求将JS脚本注入Steam内置浏览器网页，所以只能让clash使用虚拟网卡模式运行在网络最外层，steam+加速服务运行在中间层注入js，最后steam内置浏览器就得到处理好的页面（非计算机专业，如果用词有错误请谅解）

谢谢大佬指点

**Comment by E1nzbern** [comment]
分享一下我的配置方法，我使用的是Mihomo party，既要保留Mihomo对其他流量的代理功能，也要让steam的流量只被watt toolkit加速并启用脚本功能
只需要添加代理规则"PROCESS-NAME,Steam++.Accelerator.exe,DIRECT"，再如下图所示，打开“使用系统Hosts”，将watt toolkit改为“Hosts代理模式”即可
![image](https://github.com/user-attachments/assets/3e8c3a4e-0b0c-4ed2-bcde-998ad3aba8c9)
目前还没有发现别的问题，在Mihomo的系统代理和虚拟网卡模式下都能正常工作，watt toolkit的DoH开不开都不影响

**Comment by lolisix** [comment]
如果使用的是Clash Verge, 可以在全局扩展脚本里添加我写的这个脚本.
```
function main(config, profileName) {
  新增规则函数(config);
  return config;
}

function 新增规则函数(原本配置){
  const 新增规则 = ["PROCESS-NAME,Steam++.Accelerator.exe,DIRECT"];
  原本配置["rules"] = 新增规则.concat(原本配置["rules"]);
  return 原本配置;
}
```
在虚拟网卡下, 也能让steam++的注入脚本功能正常使用>
