### ISSUE TITLE
🐛[BUG] 无法加速，网页乱码

### ISSUE THREAD

**Issue by AirNoze** [BeyondDimension/SteamTools#3479]
### 🐛 描述
加速后打开steam只有一行报错：
Request:鐢变簬杩炴帴鏂瑰湪涓€娈垫椂闂村悗娌℃湁姝ｇ‘绛斿鎴栬繛鎺ョ殑涓绘満娌℃湁鍙嶅簲锛岃繛鎺ュ皾璇曞け璐ャ€� (1.12.12.12:443) (store.steampowered.com:443)

### 📷 复现步骤

1. 打开加速
2. 打开steam
(之前都ok今天才出问题)

### 🖼 截图
![Uploading 屏幕截图 2024-09-09 143150.png…]()

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows10家庭版 19045.4780
- 下载渠道：微软商店
- 程序版本：3.0.0-rc.10
- 是否包含独立运行时：不包含

**Comment by AirNoze** [comment]
[log.txt](https://github.com/user-attachments/files/16926436/log.txt)

**Comment by elarbor** [comment]
没加速GitHubd打不开，启动加速打开了。好用啊
![image](https://github.com/user-attachments/assets/4cf251ca-6fb3-4617-9e64-e725731c4c76)

**Comment by rmbadmin** [comment]
加速设置 代理设置  换一个其它doh地址即可

**Comment by HX7743** [comment]
我直接把代理设置里面的 启用DoH 给关了,莫名其妙就又好了。

**Comment by AirNoze** [comment]
解决了！！感谢！！！
