### ISSUE TITLE
🐛[BUG] 加速服务出现问题

### ISSUE THREAD

**Issue by viIzzz** [BeyondDimension/SteamTools#3496]
最近两天开启加速反而打不开网页 N网停止加速后才能正常下载mod steam商城也打不开 个人主页报错代码-118 使用的校园网WiFi连接

**Comment by A-Dirt** [comment]
最近我升级了macos15，网络加速也出了问题，是不是升级macos系统导致的？ @rmbadmin

**Comment by rmbadmin** [comment]
> 最近我升级了macos15，网络加速也出了问题，是不是升级macos系统导致的？ @rmbadmin

是的，等待.NET 8.0.10发布将会修复

**Comment by A-Dirt** [comment]
> > 最近我升级了macos15，网络加速也出了问题，是不是升级macos系统导致的？ @rmbadmin
> 
> 是的，等待.NET 8.0.10发布将会修复

这个问题解决了吗？ @rmbadmin

**Comment by rmbadmin** [comment]
> > > 最近我升级了macos15，网络加速也出了问题，是不是升级macos系统导致的？ @rmbadmin
> > 
> > 
> > 是的，等待.NET 8.0.10发布将会修复
> 
> 这个问题解决了吗？ @rmbadmin

已解决，重新下载一下最新版即可
