### ISSUE TITLE
Mac无法安装证书

### ISSUE THREAD

**Issue by VeiaiLH** [BeyondDimension/SteamTools#3498]
Mac无法安装证书
系统版本: macOS 15.0 (24A335)  M1芯片
软件版本: Steam++_v3.0.0-rc.11_macos.dmg
异常信息:CheckRootCertificate,ErrCode: GenerateCerFilePathFail

**Comment by Mossimos** [comment]
公告有说明 macOS 15.0 等待 10月份的新版本
