### ISSUE TITLE
🐛[BUG] 使用Watt Tookit加速Github时，在Visual Studio上无法操作Github储存库

### ISSUE THREAD

**Issue by WillowTree1184** [BeyondDimension/SteamTools#3514]
### 🐛 描述
我在使用Watt Tookit的Github加速时，可以在浏览器中访问Github，但是无法在Visual Studio中操作储存库（如推送、拉取等），会出现问题。

### 📷 复现步骤
1. 启用Watt Tookit的Github加速并运行；
2. 打开Visual Studio上的任一托管在Github上的项目；
3. 在Visual Studio中推送或拉取Github储存库；
4. 可以看到，如截图所示，加速服务运行正常，但拉取或推送失败。

> ps: 关闭Watt Tookit且Github不被墙时，可以正常拉取或推送。

### 🖼 截图
![可以看到，加速服务运行正常，但拉取失败](https://github.com/user-attachments/assets/b1758c48-f777-4ac9-8263-aebe0ba90c32)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 11 专业版 23H2 22631.4169
- 下载渠道：微软商店
- 程序版本：3.0.0-rc.11 for Windows Desktop Bridge (x64)
- 是否包含独立运行时：不清楚

**Comment by rmbadmin** [comment]
#1960
git添加证书信任即可
