### ISSUE TITLE
🐛[BUG] 战网账号切换后自动启动战网客户端，则炉石插件火石（Firestone）无法正常工作

### ISSUE THREAD

**Issue by Sunshine40** [BeyondDimension/SteamTools#3519]
### 🐛 描述

使用战网账号切换功能，账号本身能够正常切换，但是切换后自动启动战网客户端并从中启动炉石传说后，炉石插件火石记牌器无法正常读取内存以提供记牌器功能。

关闭 Watt Toolkit 打开的战网并以常规方式重新启动战网平台（此时账号已成功切换）则火石插件恢复正常。

### 📷 复现步骤

1. 安装（网易国服）[战网+炉石传说](https://hs.blizzard.cn/home.html)、[Firestone](https://www.firestoneapp.com/)（火石）
2. 启动炉石客户端，确认记牌器功能正常工作（使用借用套牌或预组核心套牌进入休闲对战，或进入竞技场选牌看右侧是否有插件**额外展示**的卡组栏目即可检验）
3. 在 Watt Toolkit 中设置好战网路径，保存多个待切换的账号
4. 点击想要登陆的账号，进行切换
5. 在自动打开的战网客户端中启动炉石传说
6. Firestone 记牌器提示内存读取错误，部分功能不可用（记牌器功能无法工作，任务进度提示气泡可以工作）
7. 关闭 Watt Toolkit、战网、炉石传说
8. 通过正常方式启动战网并进入炉石传说（此时账号已成功切换）
9. Firestone 没有报错，记牌器功能恢复正常工作

### 📄 日志信息

无相关异常日志

### 🖼 截图

![image](https://github.com/user-attachments/assets/8b35355f-597a-49cc-a37c-6a4aa5a2c912)

### 🚑 其他信息

- 处理器体系结构：x64
- 系统版本号：Windows 11.22631.4169
- 下载渠道：微软商店
- 程序版本：3.0.0-rc.11
- 是否包含独立运行时：微软应用商店安装的，不清楚怎么检查

**Comment by rmbadmin** [comment]
应该是管理员权限问题，现阶段因为程序以管理员方式启动了所以启动平台时也变成了管理员权限

**Comment by Sunshine40** [comment]
那能否把「切换账号后启动战网客户端」做成一个可以关闭的选项？

**Comment by rmbadmin** [comment]
> 那能否把「切换账号后启动战网客户端」做成一个可以关闭的选项？

我会修改成默认不在以管理员权限启动的方式，应该就可以解决
