### ISSUE TITLE
🐛[BUG] 脚本读取异常

### ISSUE THREAD

**Issue by cccsssam** [BeyondDimension/SteamTools#3537]
![屏幕截图 2024-11-06 015719](https://github.com/user-attachments/assets/3565bc56-7381-48c0-b796-8dfc18a74c3e)
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 📷 复现步骤

1. 
2. 
3. 

### 🚑 其他信息

- 处理器体系结构：
- 系统版本号：
- 下载渠道：
- 程序版本：
- 是否包含独立运行时：

**Comment by rmbadmin** [comment]
已修复
