### ISSUE TITLE
👑[Enhancement] 希望支持 MDN 的加速

### ISSUE THREAD

**Issue by FreeAndFrei** [BeyondDimension/SteamTools#3549]
### 🥰 需求描述(Description)
最近用Edge上不去 MDN Webdocs 了
毕竟也算是 Web dev 中举足轻重的网站了, 希望能支持

![image](https://github.com/user-attachments/assets/ff376a1a-db78-4cbd-bbcb-f7b900d7122e)

**Comment by lingbopro** [comment]
![image](https://github.com/user-attachments/assets/0d655170-7131-40eb-82f6-fded019755b0)

但是我可以上去

也没开加速器或者VPN，就是国内正常网络环境

**Comment by FreeAndFrei** [comment]
好吧, 我回来再试试. 
其实我在天津, 这个地儿的网络监管比别的地儿要严.
