### ISSUE TITLE
🧐[Question] 开启 github 加速后，使用 curl 时，报“吊销功能无法检查证书是否吊销”的错误

### ISSUE THREAD

**Issue by dreampasssser** [BeyondDimension/SteamTools#3555]
## 请认真检查以下清单中的每一项
- [√] 已经搜索过，没有发现类似的 issue
- [√] 已经搜索过文档，没有发现相关内容
- [√] 已经尝试使用过最新版，问题依旧存在
- [√] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述
win11 上使用本软件开启 github 加速后，使用 curl 访问 github 时，报如下错误：
```sh
* Host github.com:443 was resolved.
* IPv6: (none)
* IPv4: 127.0.0.1
*   Trying 127.0.0.1:443...
* Connected to github.com (127.0.0.1) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - 吊销功能无法检查证书是否吊销。
* closing connection #0
curl: (35) schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - 吊销功能无法检查证书是否吊销。
```
查了一些资料，看到能用 --ssl-no-revoke 参数来避免报错。但这是跳过吊销检查的方法，感觉不太好。
想知道这是系统的问题、curl 的问题、还是本软件的问题，还有没有其他的解决办法。

### 🚑 其他信息
- 处理器体系结构：x64
- 系统版本号：Windows 11 家庭中文版  23H2  22631.4460
- 下载渠道：微软商店
- 程序版本：3.0.0-rc.11
- 是否包含独立运行时：没看懂，不知道

**Comment by rmbadmin** [comment]
因为证书没有被 curl 信任，你可以寻找 curl 信任系统证书的办法或者 --ssl-no-revoke ，这是加速原理必然导致的问题
