### ISSUE TITLE
🧐[Question] macOS系统的最低版本是15+了吗 

### ISSUE THREAD

**Issue by chenyulzhh** [BeyondDimension/SteamTools#3556]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [X] 已经搜索过文档，没有发现相关内容
- [X] 已经尝试使用过最新版，问题依旧存在
- [X] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

网站上写的“适用于 10.15 Catalina+” 我系统macOS Monterey 12.2.1，运行提示要求15+

### 🚑 其他信息

都是提示这个信息
<img width="260" alt="WX20241128-205108@2x" src="https://github.com/user-attachments/assets/fbbb428b-b7db-414e-b957-79d4c8208c0c">

- 处理器体系结构：x64
- 系统版本号：macOS Monterey 12.2.1
- 下载渠道： Github
- 程序版本：试过 Steam++_macos_x64_v2.8.6.dmg 和 Steam++_v3.0.0-rc.12_macos.dmg
- 是否包含独立运行时：

**Comment by rmbadmin** [comment]
从 rc12 开始 最低要求是 15+了 因为 升级了 .NET 9.0

**Comment by AigioL** [comment]
3.0.0-rc.13 已修复，现在最低应该兼容 12+
