### ISSUE TITLE
🧐[Question] macos intel 无法运行这个程序

### ISSUE THREAD

**Issue by kurt-steiner** [BeyondDimension/SteamTools#3563]
## 请认真检查以下清单中的每一项
- [ x] 已经搜索过，没有发现类似的 issue
- [ x] 已经搜索过文档，没有发现相关内容
- [ x] 已经尝试使用过最新版，问题依旧存在
- [ x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

![image](https://github.com/user-attachments/assets/d74417e5-b245-483d-8606-efb31335f2ea)

### 🚑 其他信息
![image](https://github.com/user-attachments/assets/368d6198-31e8-4a0b-9818-548e54df7381)

**Comment by kurt-steiner** [comment]
![image](https://github.com/user-attachments/assets/98052b26-d565-4018-ac58-02c2a87778c7)

**Comment by rmbadmin** [comment]
https://support.apple.com/zh-cn/102445

**Comment by kurt-steiner** [comment]
卧槽，谢谢大哥
