### ISSUE TITLE
🧐[Question] 为什么会占用80端口

### ISSUE THREAD

**Issue by MoLeft** [BeyondDimension/SteamTools#3564]
### 🧐 问题描述
为什么在steam++运行的时候会有一个Steam++.Accelerator.exe占用80端口，可以把这个端口改成其他的吗，80端口还是挺常用的，被steam++占用了之后其他的进程就无法使用了。

### 🚑 其他信息

![image](https://github.com/user-attachments/assets/11b0feee-d99b-4de4-afc7-857e175aea60)

**Comment by rmbadmin** [comment]
你可以在加速设置 代理设置中自行选择是否监听80端口
![image](https://github.com/user-attachments/assets/dd1d2ad1-f89a-43f1-a2df-56d93b6558a8)
