### ISSUE TITLE
👑[Enhancement] 希望3.0版本增加对于苹果M芯片(ARM架构)的支持

### ISSUE THREAD

**Issue by cx-xingchuan** [BeyondDimension/SteamTools#3573]
### 🥰 需求描述(Description)

目前3.0版本没有对于苹果M芯片的支持，arm架构最新版本的是v2.8.6，希望3.0版本增加对于苹果M系列芯片的支持

**Comment by AigioL** [comment]
目前的 dmg 包是支持 Intel+Apple Silicon 的

**Comment by cx-xingchuan** [comment]
> 目前的 dmg 包是支持 Intel+Apple Silicon 的

好的，感谢
