### ISSUE TITLE
🧐[Question] CheckRootCertificate,ErrCode:TrustRootCertificateFail

### ISSUE THREAD

**Issue by zichenstudio** [BeyondDimension/SteamTools#3580]
## 请认真检查以下清单中的每一项
- [x] 已经搜索过，没有发现类似的 issue
- [x] 已经搜索过文档，没有发现相关内容
- [x] 已经尝试使用过最新版，问题依旧存在
- [x] 使用的是官方版本（未替换及修改过安装目录程序文件）

### 🧐 问题描述

我正常安装了此软件，按照`sudo trust anchor --store SteamTools.Certificate.cer` 导入了证书。但是点击一键加速时会报错`CheckRootCertificate,ErrCode:TrustRootCertificateFail`，我的Firefox也导入了证书。

我目前没有找到问题所在。我尽力在ISSUE和网上寻找解决办法均无效。

我的另一台Manjaro也出现了这种状况，但是莫名其妙就好了，加速功能没有问题。但是在其他系的Linux上没有发生过这种状况，仅仅是Arch系的Linux出现问题。

### 🚑 其他信息

- Arch
- i3wm

**Comment by Mossimos** [comment]
该错误为证书文件损坏或者读取失败 删除证书文件重新生成即可

**Comment by Mossimos** [comment]
或者你可以检查 你的  certutil 指令以及 certutil -L -d $HOME/.pki/nssdb | grep "SteamTools" 证书正不正常

**Comment by zichenstudio** [comment]
目前看来，问题已经解决了。
我删除了安装好的证书文件，之后重新通过`yay`安装。再使用时就一切正常了。
希望可以添加一个官方镜像源，随时同步Github上的更新。因为这可以让无法访问Github的人更方便的使用`yay`安装。
感谢
