### ISSUE TITLE
🐛[BUG] OSX 几个功能问题需要修复

### ISSUE THREAD

**Issue by EinProfispieler** [BeyondDimension/SteamTools#369]
OSX Bigsur Latest

Chipset: M1 apple silicon

16GB+512GB

程序在dock里面点击无法显示UI，无法退出。必须从title bar操作。
添加令牌会报错
<img width="719" alt="截屏2021-08-18 下午6 11 35" src="https://user-images.githubusercontent.com/86020571/129880793-919ff66a-3825-46d6-9aa2-f72b83df461c.png">

**Comment by AigioL** [comment]
这些问题不能在 X86 的设备上复现，我们这边目前没有 M1 的硬件，而且在 macOS 上调试不太方便，所以暂时没有解决方案。

**Comment by AigioL** [comment]
AvaloniaUI 是支持 ARM64 了，之前测试的时候 ARM64 编译输出的 dylib 好像还是 x86 的，下一个版本发布 ARM64 版本的可以再试试还有没有这些问题。

**Comment by AigioL** [comment]
AvaloniaUI 0.10.7 osx-arm64 发布的 dylib 和 x64 上的文件是一致的，所以还是不支持 arm64。
