### ISSUE TITLE
🐛[BUG]我用的是Mac，但加速和库存游戏都用不了

### ISSUE THREAD

**Issue by KirikageT** [BeyondDimension/SteamTools#401]
### 📷 复现步骤(Steps to Reproduce)

1. 2.4.9 β for macOS (X64)
2. 成就用不了，steam加速不上
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)

<img width="1031" alt="iShot2021-08-23 01 41 11" src="https://user-images.githubusercontent.com/89354406/130364825-cac0438a-e58c-497d-be64-59ea1c8262f4.png">

**Comment by KirikageT** [comment]
<img width="1031" alt="iShot2021-08-23 01 41 11" src="https://user-images.githubusercontent.com/89354406/130364757-9eb11ac6-515c-497d-865f-7a7828c3a847.png">

**Comment by Mossimos** [comment]
系统版本能提供下吗， 管理成就是仅windows的 挂机只有后面ASF方式出来才能使用
