### ISSUE TITLE
🐛[BUG] Twitch的聊天室无法连接

### ISSUE THREAD

**Issue by MigorG** [BeyondDimension/SteamTools#470]
### 🐛 描述(Description)
最近在看wow天团开荒ff的乐子 但是聊天室加载不出来总是少了些味道
一直显示的是正在连接聊天 进房间时能加载出之前的聊天记录 但无法显示后续聊天 其他功能没有问题
挂梯的话一切正常

### 📷 复现步骤(Steps to Reproduce)
点开任意一个直播间

### 📄 [异常/日志]信息([Exception/Log] Information)
无
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.12 for Windows (X64)
- 系统版本号(OS Version): 

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/91320213/134660802-1edb62ff-f300-4afc-9032-f5b766c57d95.png)
![image](https://user-images.githubusercontent.com/91320213/134660916-4b6fe470-4b5a-4a55-94f8-4ddc21395fbf.png)

**Comment by rmbadmin** [comment]
已热更新修复
