### ISSUE TITLE
👑[Enhancement] 建议在加速服务里增加YouTube

### ISSUE THREAD

**Issue by AimlessKitten** [BeyondDimension/SteamTools#479]

**Comment by buiawpkgew1** [comment]
再添加一个Telegram(电报)

**Comment by aydzw** [comment]
再添加一个P站

**Comment by Xmug** [comment]
还不如让作者推荐一个收费VPN……

**Comment by xiaowuap** [comment]
反代又不是梯子。。。。。这些玩意还是打不开的

**Comment by govmoe** [comment]
兄弟，你这是要玩死steam++啊？

**Comment by Illustar0** [comment]
有些东西碰不得...玩火自焚

**Comment by XCwosjw** [comment]
如果不挂梯子直连Ytb就必须要修改TCP包来干扰GFW，使其无法正常对连接进行RST，而这已经不是反代能解决的了。

**Comment by Illustar0** [comment]
> 再添加一个Telegram(电报)

反代没法实现加速Telegram.Telegram 使用 IP 而不是域名进行连接，唯一的办法就是代理
