### ISSUE TITLE
[Bug]二级代理按钮作用不稳定，有时起作用，有时不起作用

### ISSUE THREAD

**Issue by nowing** [BeyondDimension/SteamTools#488]
设置中打开二级代理，填写正确配置，启动加速后访问steam，steam网络异常。
然后在设置中关闭二级代理的按钮，保持二级代理的地址不变，再次启动加速后访问steam，steam可正常访问，可从代理的log中看出二级代理发挥作用了

**Comment by rmbadmin** [comment]
二级代理启用时，如果你依然使用hosts代理将只会代理被修改hosts的文件，
使用二级代理时最好在steam++内使用系统代理模式，但如果你开的代理也设置了系统代理则可能产生冲突。

**Comment by DCxDESIGN** [comment]
我这里也重现了，Windows绿色版2.6.4，Hosts模式，二级代理按钮关闭，开启加速后走二级代理；二级代理按钮打开，开启加速后不走二级代理，且所有不加速就无法访问的网页都报错（ERR_EMPTY_RESPONSE）

**Comment by DCxDESIGN** [comment]
> 我这里也重现了，Windows绿色版2.6.4，Hosts模式，二级代理按钮关闭，开启加速后走二级代理；二级代理按钮打开，开启加速后不走二级代理，且所有不加速就无法访问的网页都报错（ERR_EMPTY_RESPONSE）

此时，再次停止加速并关闭二级代理按钮，然后开始加速，可以正常运行（走二级代理），若停止加速并退出程序，再次运行程序并在不修改设置的前提下直接开始加速，则二级代理不生效（此时只要不改变设置则反复停止/运行结果均不变）；若停止加速然后打开代理设置，可看到此时二级代理按钮为关闭状态，此时打开按钮并运行，则又回到上一条的状态，问题重现

**Comment by YohoYang** [comment]
我也遇到了一样的问题，测试了2.4.12和2.6.7两个版本。

具体表现为，使用host模式，先打开本地代理，随便设置一个未被占用端口，再打开二级代理，设置好二级代理的端口为本地梯子的端口，然后启动加速，这时候steam网络异常，梯子无网络log；
然后关掉加速，关闭二级代理开关，然后再次启动加速，这时steam网络正常，梯子能看见steam的请求log；
在这个情况下，不关闭软件的情况下，开关加速都是正常的；
一旦关闭软件，重新启动后，二级代理就变成了关闭状态，加速就不正常了。

按如下操作进行后，二级加速才正确生效：
启动软件，将二级加速开关打开，启动加速，关闭加速，将二级加速开关关闭，启动加速。 即可正常使用。

**Comment by zzqxztc** [comment]
恩 我到现在都没搞清楚二级代理的机制

**Comment by DCxDESIGN** [comment]
2.6.9 问题依旧，临时解决方法依然是先打开二级开关然后加速，再把加速关掉，把二级开关关闭，再开启加速，此时可以正常走二级代理，也不会出现 EMPTY_RESPONSE 错误

所以这个 bug 还会修吗。。

**Comment by rmbadmin** [comment]
> 2.6.9 问题依旧，临时解决方法依然是先打开二级开关然后加速，再把加速关掉，把二级开关关闭，再开启加速，此时可以正常走二级代理，也不会出现 EMPTY_RESPONSE 错误
> 
> 所以这个 bug 还会修吗。。

会修，不过还在找原因

**Comment by DCxDESIGN** [comment]
试用了 2.7.0 ，问题似乎依然存在

**Comment by etnAtker** [comment]
2.7.2问题依旧
