### ISSUE TITLE
🐛[BUG] 反代github.com, firefox打开提示证书错误

### ISSUE THREAD

**Issue by letterk** [BeyondDimension/SteamTools#490]
### 🐛 描述(Description)

firefox会出现这个问题
cent浏览器不会

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.4.12
- 系统版本号(OS Version): 
Win10 2004
Win11 21H2
firefox 93
### 🖼 截图(Screenshots)

![Snipaste_2021-10-10_16-17-21](https://user-images.githubusercontent.com/9822709/136689205-72dc0b3f-5eb9-4eb4-bbc9-95bc805dba17.png)

**Comment by Mossimos** [comment]
[https://steampp.net/faq#CommunityAccelerate](https://steampp.net/faq#CommunityAccelerate)
参考这里需要手动导入

**Comment by letterk** [comment]
![Snipaste_2021-10-10_23-38-50](https://user-images.githubusercontent.com/9822709/136702994-d359d5b5-83e2-4b30-873c-f7f23c59a80a.png)
![Snipaste_2021-10-10_23-39-23](https://user-images.githubusercontent.com/9822709/136703002-3e0191bf-1290-422d-a8e4-116311eccfe0.png)

@Mossimos 并不可行

**Comment by rmbadmin** [comment]
我这边火狐测试勾选后是可以正常使用的，
那你得检查下cer证书与windows添加信任的证书是否一致了，如果添加了错误的证书也不会生效。

**Comment by letterk** [comment]
![Snipaste_2021-10-11_00-13-23](https://user-images.githubusercontent.com/9822709/136704221-ea2063bd-d93a-4909-9588-5d22cbf3fba2.png)
![Snipaste_2021-10-11_00-13-37](https://user-images.githubusercontent.com/9822709/136704226-b93005b4-86b9-4efb-8013-39338a5c76ca.png)
这是不一致吗

**Comment by letterk** [comment]
谢谢, 应该是的, 好像是系统里没有证书的时候, 点加速弹出那个安装证书对话框会重新生成一个新的证书?
不知道为啥要搞两个证书在哪里
还有个`.pfx`后缀的证书, 也没办法在安装前看到序列号, 我这次是两边都用的`.cer`证书, 安装之前能看到序列号

**Comment by rmbadmin** [comment]
> 谢谢, 应该是的, 好像是系统里没有证书的时候, 点加速弹出那个安装证书对话框会重新生成一个新的证书? 不知道为啥要搞两个证书在哪里 还有个`.pfx`后缀的证书, 也没办法在安装前看到序列号, 我这次是两边都用的`.cer`证书, 安装之前能看到序列号

是的，没有安装时每次都会重新生成，.pfx的才是程序一直需要的证书，cer是为了方便导入生成的。

**Comment by letterk** [comment]
也就是说,  .pfx每次都生成一个新序列号? 然后导出一个cer证书, 是这样吗
