### ISSUE TITLE
🐛[BUG] Windows商店版本无Uplay加速选项

### ISSUE THREAD

**Issue by radiation-chan** [BeyondDimension/SteamTools#686]
### 🐛 描述(Description)

Windows商店版本没有Uplay加速选项

### 📷 复现步骤(Steps to Reproduce)

1. 下载Windows商店中的Steam++，发现没有Uplay加速

### 📄 [异常/日志]信息([Exception/Log] Information)
无

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.4.13 β
- 系统版本号(OS Version): Windows11.22000.282
- 是否为应用商店版本(Store Version): Yes

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/41768215/141322623-9343197c-2f8f-469a-83f3-0cff2894e067.png)

**Comment by rmbadmin** [comment]
这个所有版本目前都暂时屏蔽了该加速选项，因为有一些问题。
