### ISSUE TITLE
🐛[BUG] 段错误(核心已转储)

### ISSUE THREAD

**Issue by Riceneeder** [BeyondDimension/SteamTools#704]
### 🐛 描述(Description)

无法正常打开
控制台输出如下
```
段错误(核心已转储)
```

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):X64_v2.6.0
- 系统版本号(OS Version): Pop!_OS 20.04 LTS

**Comment by Mossimos** [comment]
你好请问是安装的哪个包呢？
![QQ截图20211124173117](https://user-images.githubusercontent.com/26396340/143212071-84c34206-8033-436a-9159-8b2050103fbe.png)

**Comment by Riceneeder** [comment]
> 你好请问是安装的哪个包呢？
> ![QQ截图20211124173117](https://user-images.githubusercontent.com/26396340/143212071-84c34206-8033-436a-9159-8b2050103fbe.png)
> 

今天放出的 Steam++_linux_x64_v2.6.0deb

**Comment by Mossimos** [comment]
我这使用的也是
Steam++_linux_x64_v2.6.0.deb
这个包安装的
文件：Z:\Steam++_linux_x64_v2.6.0.deb
大小：55.1 兆字节(MB) / 57,772,456 字节(B)
创建时间：2021/11/24 17:40:00
修改时间：2021/11/24 17:29:17
访问时间：2021/11/24 17:29:17
MD5：96BD7F99B75634E0E32A083069373686
SHA1：CBD8C898787E28626306E0024FE137CDCAF1D326
SHA256：43CC3440D08A0FC67867B17C1AF48E84F878CC0C4021A14E5C7F6F1D52733681
CRC32：C5B15811
这是我使用的deb包hash
请问是安装时报错还是运行报错

**Comment by Riceneeder** [comment]
> 我这使用的也是
> Steam++_linux_x64_v2.6.0.deb
> 这个包安装的
> 文件：Z:\Steam++_linux_x64_v2.6.0.deb
> 大小：55.1 兆字节(MB) / 57,772,456 字节(B)
> 创建时间：2021/11/24 17:40:00
> 修改时间：2021/11/24 17:29:17
> 访问时间：2021/11/24 17:29:17
> MD5：96BD7F99B75634E0E32A083069373686
> SHA1：CBD8C898787E28626306E0024FE137CDCAF1D326
> SHA256：43CC3440D08A0FC67867B17C1AF48E84F878CC0C4021A14E5C7F6F1D52733681
> CRC32：C5B15811
> 这是我使用的deb包hash
> 请问是安装时报错还是运行报错

是运行时报错
刚开始我点图标没有反应，然后就从命令行启动
安装包我已经删除了，比对不了hash😅

**Comment by OliverYmy** [comment]
Microsoft Store 里面的也打不开

**Comment by AigioL** [comment]
> Microsoft Store 里面的也打不开

应用商店之前上传了一个有问题的版本，新修复的版本目前在审核中。

**Comment by OliverYmy** [comment]
> 

好滴，感谢！

**Comment by OliverYmy** [comment]
> > Microsoft Store 里面的也打不开
> 
> 应用商店之前上传了一个有问题的版本，新修复的版本目前在审核中。

好嘞，感谢！

**Comment by AigioL** [comment]
移动到 #827 进行跟踪
