### ISSUE TITLE
🐛[BUG] Win7 Http2 不支持

### ISSUE THREAD

**Issue by IOnlyA** [BeyondDimension/SteamTools#776]
### 🐛 描述(Description)
显示页面有bug 且无法加速 有报错
新版本 无法加速 而且加速页面无任何显示 且显示 客户端错误1006

### 📷 复现步骤(Steps to Reproduce)

1. 直接进入即可 
2. 无其余步骤
3. 

### 📄 [异常/日志]信息([Exception/Log] Information)
[nlog-all-2021-12-12.log](https://github.com/BeyondDimension/SteamTools/files/7697950/nlog-all-2021-12-12.log)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.6.2
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): Y

### 🖼 截图(Screenshots)

![图片](https://user-images.githubusercontent.com/95988237/145696186-06b342b1-4ab7-4a69-b2a5-2654758971a1.png)
![图片](https://user-images.githubusercontent.com/95988237/145696198-71c997a6-0bbd-4338-aea6-62741038eeef.png)
![图片](https://user-images.githubusercontent.com/95988237/145696209-96d69db4-f156-450f-b854-577af62b0cdc.png)

**Comment by AigioL** [comment]
这个问题目前应该仅发生在 Win7 上，下个版本修复
