### ISSUE TITLE
👑[Enhancement] 本地令牌有多个令牌，希望可以手动调整令牌的排序

### ISSUE THREAD

**Issue by CCneorg** [BeyondDimension/SteamTools#777]

**Comment by AigioL** [comment]
你可以在令牌卡片上右键，上移或下移

**Comment by CCneorg** [comment]
> 你可以在令牌卡片上右键，上移或下移

我使用的是微软商店的steam++，右键令牌卡片无反应

**Comment by rmbadmin** [comment]
> > 你可以在令牌卡片上右键，上移或下移
> 
> 我使用的是微软商店的steam++，右键令牌卡片无反应

更新到最新的2.6.3版本在尝试
