### ISSUE TITLE
🐛[BUG] Archlinux无法使用

### ISSUE THREAD

**Issue by plokid** [BeyondDimension/SteamTools#778]
### 🐛 描述(Description)
Archlinux 在升入2.6.1和2.6.2后无法使用
2.4.12版本可以正常使用

### 📷 复现步骤(Steps to Reproduce)

正常使用即可
### 📄 [异常/日志]信息([Exception/Log] Information)
~/.cache/Steam++/Logs目录下只有ASF文件夹，且都为空
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.6.*
- 系统版本号(OS Version): Archlinux

### 🖼 截图(Screenshots)
![图片](https://user-images.githubusercontent.com/72876162/145698265-56345f5b-091a-4c02-900d-610503c3675f.png)
![图片](https://user-images.githubusercontent.com/72876162/145698273-7c0bacf4-3584-442f-aa45-b1bc51d621cc.png)

虽然没有支持Archlinux，但之前可以用后来不能用就挺奇怪的，来说一下，希望能修复。

**Comment by AigioL** [comment]
@Mossimos 也许与 2.6.1 中 更改了文件夹目录，遵循 XDG Base Directory Specification，导致 AppData 文件夹不同，重新创建了证书文件。

这一步骤更改应该是兼容的，可能由于某些原因没有执行成功
https://github.com/BeyondDimension/SteamTools/blob/2.6.1/src/ST.Client.Desktop.Linux/FileSystemDesktopXDG.cs#L32

**Comment by AigioL** [comment]
@plokid 将程序根目录下的 AppData 文件夹内容 复制到 ```$XDG_DATA_HOME/Steam++``` 目录下可以正常使用吗？

**Comment by plokid** [comment]
> @plokid 将程序根目录下的 AppData 文件夹内容 复制到 `$XDG_DATA_HOME/Steam++` 目录下可以正常使用吗？

你是指将2.4.12的AppData文件夹复制过去吗？

**Comment by AigioL** [comment]
> > @plokid 将程序根目录下的 AppData 文件夹内容 复制到 `$XDG_DATA_HOME/Steam++` 目录下可以正常使用吗？
> 
> 你是指将2.4.12的AppData文件夹复制过去吗？
对的

**Comment by plokid** [comment]
> > > @plokid 将程序根目录下的 AppData 文件夹内容 复制到 `$XDG_DATA_HOME/Steam++` 目录下可以正常使用吗？
> > 
> > 
> > 你是指将2.4.12的AppData文件夹复制过去吗？
> > 对的

依然无法运行

**Comment by Mossimos** [comment]
是能正常打开程序吧。
用的是什么代理模式呢？
Linux推荐系统代理模式  之前的版本 hosts代理模式会随机端口无法监听443 需要映射
![@Q3RAZG~$F~FFNBA0B}C_B3](https://user-images.githubusercontent.com/26396340/145783190-78f721f2-1c9d-47f3-9fbe-376645e296a7.png)

**Comment by plokid** [comment]
选择系统代理模式后已可以正常使用，十分感谢。
