### ISSUE TITLE
GPU 占用率很高

### ISSUE THREAD

**Issue by MayaolongMa** [BeyondDimension/SteamTools#797]
更新最新版本后GPU占用率很高
![image](https://user-images.githubusercontent.com/50213376/145922293-1252d64f-3c8a-4dab-8d27-c0481ee335c4.png)
![image](https://user-images.githubusercontent.com/50213376/145922372-2062578d-774c-494b-8f76-850cd7f1794e.png)

**Comment by AigioL** [comment]
关闭窗口后 GPU 的占用率应该会降低至 0%

**Comment by rmbadmin** [comment]
如果你不希望程序使用gpu你可以选择在设置中关闭硬件加速，
占用问题我这边测试是正常的，并且程序在后台时也不会有GPU占用。
