### ISSUE TITLE
🐛[BUG]官网请求存在问题

### ISSUE THREAD

**Issue by cyb233** [BeyondDimension/SteamTools#814]
### 🐛 描述(Description)
当在官网执行会导致URL变化的操作时(如下载, 更新日志等), 是获取请求动态修改, 但如果直接访问或刷新页面则会错误地加载Github, 因而导致返回Github的404页

### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): 

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/39186981/146214217-e61926be-89ba-4aa4-b52b-a17dd07d90e4.png)

**Comment by Mossimos** [comment]
这 Github Pages 不支持 gitee 那种  try_files $uri $uri.html /index.html $uri/ =404; 全指向 index.html 
只能新建 404.html 和 index.html 内容一样好麻烦

**Comment by cyb233** [comment]
> 

之所以发现这个问题，是因为从软件中点击更新日志是全新访问而直接404

**Comment by AigioL** [comment]
@Mossimos 开启 预渲染 能解决这个问题吧

https://umijs.org/zh-CN/docs/ssr#%E4%BD%BF%E7%94%A8%E9%A2%84%E6%B8%B2%E6%9F%93
https://zhuanlan.zhihu.com/p/141988506

**Comment by Mossimos** [comment]
开这个 会多很多不必要的文件 实际上都是 index.html 复制命名多份 而且多一堆目录 多一个路由就多一个目录
