### ISSUE TITLE
👑[Enhancement] 深色模式时, 部分文字/按钮颜色需要修改以增加阅读性

### ISSUE THREAD

**Issue by cyb233** [BeyondDimension/SteamTools#815]
### 🥰 需求描述(Description)
如题

### 🚑 其他信息(Other Information)
这是个人信息编辑前, 按钮不可点击的样子
![image](https://user-images.githubusercontent.com/39186981/146215357-c0daeb29-5b1c-43f1-81f6-76d7b0e109ef.png)
这是个人信息编辑后, 按钮可以点击的样子
![image](https://user-images.githubusercontent.com/39186981/146215434-8d7ba19b-82fd-43df-b57b-76ab4396294d.png)
检查更新等几个按钮为深色调几乎看不清
![image](https://user-images.githubusercontent.com/39186981/146215261-b83fe7cd-e726-4e67-a034-aaa4c17eac76.png)

**Comment by rmbadmin** [comment]
这与你设置的主题色有关，默认取自系统的主题色可能与背景色有些冲突，你可以自定义主题色来解决。
