### ISSUE TITLE
🐛[BUG] 无法使用Steam登录

### ISSUE THREAD

**Issue by gingerbreap** [BeyondDimension/SteamTools#821]
### 🐛 描述(Description)

点击使用Steam账号登录后，会跳转至steam++的返回页面，但是返回内容是乱码（见截图）。通过乱码恢复得到结果是“目前 Steam 登录的请求过多请刷新页面重试或稍后再试”。

对于这个bug，想要解决的是报错页面中UTF-8未被正确显示的问题，建议网页端稍做处理。

### 📷 复现步骤(Steps to Reproduce) / 📄 异常信息(Exception Information)

描述中已经写明。

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/27958821/146678370-63baaab2-d7e8-46e8-8e1e-890b30440f61.png)

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): v2.6.3
- 系统版本号(OS Version): Windows 10 21H2 (19044.1415)
- 是否为应用商店版本(Whether it is a Store version): 是(Yes)

**Comment by AigioL** [comment]
今天晚些时候发布服务端解决这个问题。
