### ISSUE TITLE
🐛[BUG] 编辑并刷新脚本导致含GM函数脚本无法执行

### ISSUE THREAD

**Issue by lyzlyslyc** [BeyondDimension/SteamTools#822]
### 🐛 描述(Description)

在编辑完内嵌脚本后进行开关和刷新缓存操作，有小概率会**使脚本先于GM框架嵌入页面，导致含有GM函数的脚本因为函数未定义而无法执行。**
当问题发生以后，重启steam后问题仍然存在，刷新脚本、开关脚本、重新加速等操作均无法解决问题。
只有重新导入脚本才可能解决问题。

### 📷 复现步骤(Steps to Reproduce)

1. 编辑并保存脚本
2. 开关脚本或刷新脚本
3. 开关加速
4. 打开页面，小概率脚本无法加载

### 📄 [异常/日志]信息([Exception/Log] Information)
页面控制台：
Uncaught ReferenceError: GM_getValue is not defined
    at 349b1760-7e62-43c2-ad77-1c968851a21a:46
    at 349b1760-7e62-43c2-ad77-1c968851a21a:222
    at 349b1760-7e62-43c2-ad77-1c968851a21a:392
    at 349b1760-7e62-43c2-ad77-1c968851a21a:392

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.6.3 for Windows (x64)
- 系统版本号(OS Version): Windows 10.19042.1415
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/62510112/146682131-ca81309c-cd52-4797-942f-5e27de013f01.png)

**Comment by AigioL** [comment]
fix https://github.com/BeyondDimension/SteamTools/commit/aa20d3d19c0b570ad17512987b882f6a71973946
