### ISSUE TITLE
👑[Enhancement] 已添加 git 版本的AUR软件包

### ISSUE THREAD

**Issue by zhanghua000** [BeyondDimension/SteamTools#825]
### 🥰 需求描述(Description)

我这里自行打包了 SteamTools 到 AUR 上，地址是 https://aur.archlinux.org/packages/steamtools-git/ 
两位dalao作为Maintainer标签
dalao可以把这个加到 Readme 里面吗？如果还需要什么额外修改，请让我修改。
#### 给后来人的太长不看版：
添加了两个位于 AUR 的软件包 `steam++-git` 和 `steam++-bin`，Linux 版目前已知的问题都有，可使用您的AUR助手或者手动下载安装。git 版本是克隆源代码完成编译打包，bin 版本是直接下载 Release 的文件完成打包，各位可按需取用。

**Comment by AigioL** [comment]
目前版本应该不支持源码构建，因为需要一些私有内容才能与服务端通信
且在 Linux 上编译比较困难，目前发行版都是在 Windows 上编译的

我们目前使用的是 https://github.com/quamotion/dotnet-packaging 这个项目进行打包 rpm 与 deb
目前还不支持 ArchLinux package format
不过有一个 issue 的功能请求
https://github.com/quamotion/dotnet-packaging/issues/105

zstd的支持有
https://github.com/skbkontur/ZstdNet

如果有打包的脚本或者源码支持的话可以添加到 https://github.com/BeyondDimension/SteamTools/tree/develop/src/ST.Tools.Publish
上，就像 deb 包的命令
https://github.com/BeyondDimension/SteamTools/blob/develop/src/ST.Tools.Publish/Steps/Step_deb.cs

**Comment by zhanghua000** [comment]
目前为止我按照dalao们在[CI配置](https://github.com/BeyondDimension/SteamTools/blob/develop/.github/workflows/publish.yml)里面的步骤，在使用 `dotnet-sdk` 版本为 `6.0.1.sdk101` 的情况下在 Arch Linux 上可以完成编译，但启动时会提示”非官方客户端“。另外dalao们使用的打包过程更适用于正式发行，Arch Linux 对带 `-git` 的软件包定位是“通过版本控制系统获取源代码并完成编译的开发阶段的软件包“。这种带私有内容的正式版可以通过直接下载 Release 里面的压缩包并且创建一个后缀为 `-bin` 的软件包来实现 Arch Linux 版本的构建，就像 [visual-studio-code-bin](https://aur.archlinux.org/packages/visual-studio-code-bin/) 一样。所以我倒是觉得不用专门让 .NET 去支持 Arch Linux 的软件包格式

**Comment by AigioL** [comment]
CI 中的这两步骤 仓库换成下面的 https://github.com/BeyondDimension/SteamTools/blob/develop/.github/workflows/publish.yml#L61-L74
https://github.com/BeyondDimension/Credentials-Public
应该就不会提示 非官方客户端了

目前  Arch Linux 上有一些反馈，无法运行程序的 https://github.com/BeyondDimension/SteamTools/issues/371 https://github.com/BeyondDimension/SteamTools/issues/372 https://github.com/BeyondDimension/SteamTools/issues/373

疑似与字体有关，这个问题目前也没什么进展，应该与上游的 skia 有关
@Mossimos 测试的时候也遇到了有几率能打开，有几率又不能运行，目前版本似乎不太稳定

**Comment by AigioL** [comment]
这些证书文件都是一些二进制数据，并不是真正的证书
另外 steamtools 这个名字应该已经弃用了，因为域名也没拿下来，这个域名有被另一个 Steam 工具持有了
如果支持符号的话还是保留 ```Steam++``` 或 ```SteamPP``` 合适

**Comment by zhanghua000** [comment]
好的，感谢dalao提供数据。为了一般使用稳定性，我另外打包了位于 Release 的官方二进制文件制作的软件包 [steam++-bin](https://aur.archlinux.org/packages/steam%2B%2B-bin/)，git 版本的改名我会尽快完成。

**Comment by memorydream** [comment]
> 目前 Arch Linux 上有一些反馈，无法运行程序的 #371 #372 #373
> 
> 疑似与字体有关，这个问题目前也没什么进展，应该与上游的 skia 有关 @Mossimos 测试的时候也遇到了有几率能打开，有几率又不能运行，目前版本似乎不太稳定

https://github.com/BeyondDimension/SteamTools/issues/791#issuecomment-995284584 
我在此处提供了一个解决方案


通过设置LANG=en_US.UTF-8，我这里可以百分百规避掉字体问题

编辑：
附上Steam++.sh
```
chmod 755 ./Steam++
LANG=en_US.UTF-8
rm $HOME/.local/share/Steam++/Config.mpo
./Steam++
```

第三行rm指令，是因为在我这里非第一次启动，加载到主窗口是就会异常崩掉，经过瞎排查，发现删掉这个文件就没问题了，但是每次也得重新设置

_Originally posted by @memorydream in https://github.com/BeyondDimension/SteamTools/issues/791#issuecomment-995284584_

**Comment by zhanghua000** [comment]
我这里字体倒没什么问题，就是也是出现第二次启动会炸主窗口，只要删掉Config.mpo就可以正常启动了。但下次肯定会继续炸，因此每次启动前都得去删一遍（

**Comment by memorydream** [comment]
> 我这里字体倒没什么问题，就是也是出现第二次启动会炸主窗口，只要删掉Config.mpo就可以正常启动了。但下次肯定会继续炸，因此每次启动前都得去删一遍（

我是直接改了Steam++.sh，然后跑脚本运行的，除了每次都要重新设置以外使用都很顺畅

**Comment by AigioL** [comment]
@rmbadmin @Mossimos 看一下这部分
https://github.com/BeyondDimension/SteamTools/blob/develop/src/ST.Client/Settings/UISettings.Avalonia.cs#L26
https://github.com/BeyondDimension/SteamTools/blob/develop/src/ST.Client/Services/IFontManager.cs#L18
https://github.com/BeyondDimension/SteamTools/blob/develop/src/ST.Client.Desktop.Avalonia/Application/Services/Implementation/AvaloniaFontManagerImpl.cs#L233

可能  GetSkTypefaceByFontFamily 也要加上 Default 硬编码字符串的判断
CreateGlyphTypefaceBySkia 中 FontFamily.DefaultFontFamilyName 和  KEY_Default 可能不一致
https://github.com/BeyondDimension/SteamTools/blob/develop/src/ST.Client.Desktop.Avalonia/Application/Services/Implementation/AvaloniaFontManagerImpl.cs#L177

**Comment by zhanghua000** [comment]
> 这些证书文件都是一些二进制数据，并不是真正的证书 另外 steamtools 这个名字应该已经弃用了，因为域名也没拿下来，这个域名有被另一个 Steam 工具持有了 如果支持符号的话还是保留 `Steam++` 或 `SteamPP` 合适

steamtools-git 已被更名为 [steam++-git](https://aur.archlinux.org/packages/steam%2B%2B-git/)

**Comment by AigioL** [comment]
尝试修复了字体的问题，疑似默认字体的key硬编码错误导致的闪退
https://github.com/BeyondDimension/SteamTools/actions/runs/1600794212 这个 action 执行完可下载 linux 的包

**Comment by AigioL** [comment]
@zhanghua000 Readme 也加上了，如果还有什么遗漏缺失的内容，你可以建一个PR提交上来。
