### ISSUE TITLE
👑[Enhancement] 为什么不能够拖拽Steam++的页面，以及能否添加Steam++的最小化功能

### ISSUE THREAD

**Issue by petermark66** [BeyondDimension/SteamTools#843]

**Comment by rmbadmin** [comment]
请在详情里详细描述问题？ 拖拽什么页面？ 最小化是指最小化到托盘？ 目前已有此功能

**Comment by petermark66** [comment]
在win7的64位系统下无法拖拽Steam++的程序（程序只能定格在桌面中央，鼠标无法拖拽），最小化主要是Steam++的右上角遮住了x键（鼠标光标移到程序右上角x键一直闪烁，但能关闭程序页面）

**Comment by AigioL** [comment]
https://user-images.githubusercontent.com/24450093/147813324-a06fb24a-8987-4c01-9da6-b4d59d98d7f2.mp4

你是没有开启 Aero 吗？

**Comment by petermark66** [comment]
没开aero，解决了谢谢
