### ISSUE TITLE
👑[Enhancement] 在程序的市场交易确认框窗口中添加账号ID

### ISSUE THREAD

**Issue by blankws** [BeyondDimension/SteamTools#844]
### 🥰 需求描述(Description)

在steam++程序中导入了多个账号的令牌并且需要同时确实市场交易的时候发现确认窗口不显示是哪个账号的，所以希望在程序的市场交易确认框窗口中添加账号ID便于区分

### 🧐 解决方案(Solution)

在如图所示的位置加上账号的ID
![1](https://user-images.githubusercontent.com/26181512/147756782-22e1aa0c-fa91-46fe-9587-9e304aa7c7e5.png)

**Comment by AigioL** [comment]
已发布 v2.6.4
