### ISSUE TITLE
👑[Enhancement] 需不需要增加对视频的加速？

### ISSUE THREAD

**Issue by zzqxztc** [BeyondDimension/SteamTools#847]
### 🥰 需求描述(Description)

steam的社区里有很多视频是转载的YouTube等视频网站的视频。
点击社区里的全部状态就能看到有很多视频无法加载。

### 🧐 解决方案(Solution)

添加对YouTube等视频网站的支持

### 🚑 其他信息(Other Information)

软件不支持，个人觉得是不是考虑到视频的流量比较大，可能会给代理服务器比较大的压力。
这样是不是可以只对启用本地反代，有自己的代理服务器用户增加添加对视频类网站的支持？

或者，直接开放自定义接口，用户可以自己添加网址或者程序，进行反代。
当然我看到，有人说，避免沦为翻墙工具，引起关注。

**Comment by AigioL** [comment]
目前的加速方式没有使用境外服务器做中转，是通过你本地的网络直接访问，有自己的代理服务器的用户可以全部走自己的服务器这样。

**Comment by zzqxztc** [comment]
> 

但是 开了二级代理，填写了自己的服务器以后，目前版本好像无法代理视频？

**Comment by zzqxztc** [comment]
> 目前的加速方式没有使用境外服务器做中转，是通过你本地的网络直接访问，有自己的代理服务器的用户可以全部走自己的服务器。

恩 我又了解了下，steam++的反代原理。原来是用的cdn 服务商Akamai，作为内容中转。我看到说全球很多知名企业都有用。貌似YouTube也有。。。

不知道未来考不考虑，自定义添加。
还有当前版本的二级代理用起来很不方便，经常报错。另外一个问题也提过。
想用steam++作代理，主要是脚本功能很方便。
