### ISSUE TITLE
🧐[Question] Hosts代理模式 + 二级代理 = steam错误 -324

### ISSUE THREAD

**Issue by mrwjh** [BeyondDimension/SteamTools#848]
如题，2.6.2商店版本 “Hosts代理模式 + 二级代理 = steam错误 -324或105”，好像只有”系统代理模式 + 二级代理"才有用，
那改Windows系统代理的话 还不如直接用fq软件自带的系统代理模式

**Comment by zzqxztc** [comment]
我也是这样。324错误
而且，有时候关掉二级代理以后，还是324错误

**Comment by mc-doge666** [comment]
+1

**Comment by rmbadmin** [comment]
可能重复 #488
