### ISSUE TITLE
🧐[Question] Github Desktop使用

### ISSUE THREAD

**Issue by NewbieXvwu** [BeyondDimension/SteamTools#849]
### 🧐 问题描述(Description)

我现在想使用Github Desktop，同时打开了Steam++的社区加速功能，clone操作成功，但是push不行，提示fatal: unable to access 'https://github.com/NewbieXvwu/占位符-这里是我的项目地址.git/': SSL certificate problem: unable to get local issuer certificate，我应该怎么办？

### 🚑 其他信息(Other Information)

我找到了[疑似解决方案](https://blog.csdn.net/qq_33349365/article/details/101514412)，但是我不知道端口号……

- 程序版本(Program Version):2.6.3
- 系统版本号(OS Version): Windows 10.22000.376（Windows 11）
- 是否为应用商店版本(Whether it is a Store version): No

**Comment by AigioL** [comment]
访问 github 的话你可以试试 https://github.com/dotnetcore/FastGithub/releases 用这个

**Comment by rmbadmin** [comment]
其实解决方案已经在这里发过了 #234   让git信任本地证书即可

**Comment by NewbieXvwu** [comment]
谢谢！
