### ISSUE TITLE
🧐[Question] 绑定账号时提示手机号已经被使用。Binding the account, it prompts that the mobile phone number has been used.

### ISSUE THREAD

**Issue by ZiuChen** [BeyondDimension/SteamTools#855]
### 🧐 问题描述(Description)

在`v1.1.4`版本的`Steam++`中，我使用手机号登录了`Steam++`，在我更新到`v2.6.3`版本后，我使用QQ登录了`Steam++`，此时我想要把我之前的手机号绑定到当前账号时，提示：该手机号已经被绑定。
**请问是否可以添加将已被绑定的手机号添加到其它方式绑定的账号中去的方法？**

In the `Steam++` version of `v1.1.4`, I used my mobile phone number to log in to `Steam++`. After I updated to the `v2.6.3` version, I used QQ to log in to `Steam++`. At this time, I want to When my previous mobile phone number is bound to the current account, it prompts: the mobile phone number has already been bound.
**Is it possible to add a method to add a bound mobile phone number to an account bound in other ways?**

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/64892985/147936308-1ce09feb-430e-4e52-afa7-eeb0625069ab.png)

- 程序版本(Program Version): `v2.6.3`
- 系统版本号(OS Version): `Windows 10.19042.1415`
- 是否为应用商店版本(Whether it is a Store version): `否(No)`

**Comment by rmbadmin** [comment]
在关于中注销一个账号就行

**Comment by ZiuChen** [comment]
> 在关于中注销一个账号就行

感谢！已经成功改过来了 😄
