### ISSUE TITLE
🐛[BUG] firefox的证书问题

### ISSUE THREAD

**Issue by jerry460** [BeyondDimension/SteamTools#856]
### 🐛 描述
Firefox导入证书时提示”此证书已在此前安装为一个证书颁发机构”，但打开github后Firefox依然认为证书有安全风险无法进入，此时github的证书序列号与系统的证书不一样，在证书颁发机构列表中寻找，并没有发现证书的名字（以上证书均指steamtools这个证书）
### 📷 复现步骤(Steps to Reproduce)

1. 
2. 
3. 

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.6.3
- 系统版本号(OS Version):Windows 10 
- 是否为应用商店版本(Whether it is a Store version): 不是

**Comment by andywang1011** [comment]
安装证书安全吗?
那不和裸奔一个样?

**Comment by AigioL** [comment]
> 安装证书安全吗? 那不和裸奔一个样?

安全的，本地跑了个代理服务器进行加速，证书是因为要修改一些数据包内容才能访问目标网站，客户端与服务端都在本机上，不存在中间人攻击。

火狐的证书问题 @Mossimos 看看

**Comment by rmbadmin** [comment]
> 每个证书都是在客户端上随机生成的，，不要泄露自己的证书就好。

**Comment by jerry460** [comment]
@andywang1011 我稍微提醒一下，如果你想提问，应该开一个新的issue而不是在我的issue下提问，这样得到回答的可能性更高（没有批评的意思）

**Comment by jerry460** [comment]
> 安装证书安全吗?
> 那不和裸奔一个样?
 我稍微提醒一下，如果你想提问，应该开一个新的issue而不是在我的issue下提问，这样得到回答的可能性更高（没有批评的意思）

**Comment by rmbadmin** [comment]
火狐打开 `about:certificate` 在证书机构中无法查询到 `SteamTools Certificate` 证书吗？
我测试只要添加过应该是存在的。

**Comment by jerry460** [comment]
> 火狐打开 `about:certificate` 在证书机构中无法查询到 `SteamTools Certificate` 证书吗？
> 我测试只要添加过应该是存在的。
> 
> 或者你可以参考 https://www.cnblogs.com/oliver-yt/p/9375609.html

不是不存在，而是提示已存在但是我在证书列表里找不到，这导致我没有办法导入证书

**Comment by Mossimos** [comment]
火狐的貌似在个人证书列中存在
![image](https://user-images.githubusercontent.com/26396340/148190086-f54b30bf-8580-4a86-8e80-4535fd6466fc.png)

**Comment by rmbadmin** [comment]
> > 火狐打开 `about:certificate` 在证书机构中无法查询到 `SteamTools Certificate` 证书吗？
> > 我测试只要添加过应该是存在的。
> > 或者你可以参考 https://www.cnblogs.com/oliver-yt/p/9375609.html
> 
> 不是不存在，而是提示已存在但是我在证书列表里找不到，这导致我没有办法导入证书，并且我没添加过之前就存在了

可以尝试参考链接中的网页删除证书的数据缓存重新导入

**Comment by jerry460** [comment]
> 火狐的貌似在个人证书列中存在
> ![image](https://user-images.githubusercontent.com/26396340/148190086-f54b30bf-8580-4a86-8e80-4535fd6466fc.png)
> 

是的，但是这解决不了安全报错问题

**Comment by AigioL** [comment]
那你删了重新导入呢？

**Comment by Mossimos** [comment]
测试发现是这个模块导致无法导入 可以卸载此模块  然后导入。 （模块会在下次重启 firefox 又自动安装）
![image](https://user-images.githubusercontent.com/26396340/148192001-de3d7ef4-5e3c-4fc5-b505-0a9ab822f3fd.png)

**Comment by jerry460** [comment]
> 那你删了重新导入呢？

没有效果

**Comment by jerry460** [comment]
> 测试发现是这个模块导致无法导入 可以卸载此模块  然后导入。 （模块会在下次重启 firefox 又自动安装）
> ![image](https://user-images.githubusercontent.com/26396340/148192001-de3d7ef4-5e3c-4fc5-b505-0a9ab822f3fd.png)

删除该模块后，停止加速以后会出问题吗？

**Comment by Mossimos** [comment]
不会的这个是 火狐 的证书模块  加载了系统的证书然后 证书选择出错了没选到新的证书

**Comment by jerry460** [comment]
> 不会的这个是 火狐 的证书模块  加载了系统的证书然后 证书选择出错了没选到新的证书

谢谢大佬，解决了乾杯 []~（￣▽￣）~*

**Comment by jerry460** [comment]
> 测试发现是这个模块导致无法导入 可以卸载此模块  然后导入。 （模块会在下次重启 firefox 又自动安装）
> ![image](https://user-images.githubusercontent.com/26396340/148192001-de3d7ef4-5e3c-4fc5-b505-0a9ab822f3fd.png)

依旧提示”此证书已在此前安装为一个证书颁发机构”

**Comment by Mossimos** [comment]
你卸载后 直接查看证书导入还是这样提示吗？

**Comment by jerry460** [comment]
> 你卸载后 直接查看证书导入还是这样提示吗？

是的

**Comment by Mossimos** [comment]
卸载后不要关火狐 直接查看证书去 证书办法机构导入 是可以导入的除非 里面像这样 导入过了吧这个给删除了就是好的
![image](https://user-images.githubusercontent.com/26396340/148198235-32447f36-333f-4744-8874-3dce9cb0cbb0.png)
确定下 这个选项卡下是空的
![image](https://user-images.githubusercontent.com/26396340/148198376-2fa70899-e8b4-4558-86ed-403b95050b93.png)

**Comment by jerry460** [comment]
是我在“您的证书”那里没有删除原来的证书的原因😂，非常不好意思，再次谢谢大佬

**Comment by Mossimos** [comment]
不是没有删除的原因  ， 卸载了这个模块这个 列表会变成空的。

**Comment by jerry460** [comment]
> 不是没有删除的原因  ， 卸载了这个模块这个 列表会变成空的。

唔，我这里并没有变成空的，是手动删的

**Comment by Mossimos** [comment]
也可能是先查看证书 加载了列表 导致有缓存 卸载模块 后缓存还在

**Comment by jerry460** [comment]
> ![image](https://user-images.githubusercontent.com/26396340/148199525-58b49704-6358-4e90-ab2e-c51c6a4b3959.png)
> 是选中的这个卸载的吧。我这卸载后列表就变空了

对的

**Comment by Mossimos** [comment]
能导入正常用吧？如果能导入那也行

**Comment by jerry460** [comment]
> 能导入正常用吧？如果能导入那也行

可以的，手动删除以后就可以了

**Comment by Mossimos** [comment]
看起来新版本 支持自动识别系统证书了，之后研究下他怎么选择证书的 估计后面不需要手动操作了。

**Comment by ZeroAurora** [comment]
Firefox 120 已经支持自动导入系统级证书
https://support.mozilla.org/zh-CN/kb/automatically-trust-third-party-certificates

**Comment by Mossimos** [comment]
![image](https://github.com/BeyondDimension/SteamTools/assets/26396340/d7cd3610-eddc-4fd8-8d22-9e1b709cabd9)
并没有在 120.0 上找到此选项 也未从 系统证书库加载证书

**Comment by ZeroAurora** [comment]
这边的 Firefox 120.0.1 有这一选项
![图片](https://github.com/BeyondDimension/SteamTools/assets/25359455/f71b0c44-65cf-4724-adbb-aeb8c4fbca7d)
