### ISSUE TITLE
有最新的安卓安装包吗？🧐[Question] 

### ISSUE THREAD

**Issue by GLORYFeonix** [BeyondDimension/SteamTools#859]
### 🧐 问题描述(Description)

看见更新历史里面有安卓相关的内容，但在release和官网都没有找到最新的安卓安装包。

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by AigioL** [comment]
在编译了，晚些时候发布。

**Comment by AigioL** [comment]
apk包已发布。
