### ISSUE TITLE
👑[Enhancement] 希望增加加速关闭后自动将host文件恢复原状的功能

### ISSUE THREAD

**Issue by jerry460** [BeyondDimension/SteamTools#860]
### 🥰 需求描述(Description)

停止加速以后，程序并没有把host文件改成原来的（火绒检测异常），希望可以自动改回来
### 🧐 解决方案(Solution)

太菜了，没有
### 🚑 其他信息(Other Information)

无

**Comment by rmbadmin** [comment]
程序是会自动还原的，你可以检查下是否是被拦截了操作，或者是否是程序非正常退出导致没有还原。
