### ISSUE TITLE
🐛[BUG] mega网盘加速无限刷新、OneDrive空数据

### ISSUE THREAD

**Issue by YuxiangWang0525** [BeyondDimension/SteamTools#873]
mega网盘加速无限刷新、OneDrive空数据,
![image](https://user-images.githubusercontent.com/66881174/148635174-1f3bb08c-cf23-4fa6-b51b-85a41e9ec181.png)
![image](https://user-images.githubusercontent.com/66881174/148635180-625adf62-ec87-4827-a9fd-2fe833a99ac0.png)

**Comment by YuxiangWang0525** [comment]
PS.我没找到log里的任何内容

**Comment by rmbadmin** [comment]
已热更新修复
