### ISSUE TITLE
🧐[Question] 请问可以在开机程序自启之后，自动开启网络加速功能吗

### ISSUE THREAD

**Issue by codesensi** [BeyondDimension/SteamTools#874]
如题，可以在开机程序自启之后，自动开启网络加速功能吗
电脑系统如图
![image](https://user-images.githubusercontent.com/66196408/148649170-0e6cc714-1ec2-4dcf-938a-2fa20464eea0.png)
Steam++版本如图
![image](https://user-images.githubusercontent.com/66196408/148649208-0731e5e9-74ba-48fc-8feb-69481365382d.png)

**Comment by AigioL** [comment]
在网络加速的页面上，右上角 ... 中 点击 ```程序启动时自动启动加速```

**Comment by codesensi** [comment]
> 在网络加速的页面上，右上角 ... 中 点击 `程序启动时自动启动加速`

多谢~一时没注意看到
