### ISSUE TITLE
🐛[BUG] Windows 7 TaskBar 上点击 Icon 没有最小化

### ISSUE THREAD

**Issue by 1078249029** [BeyondDimension/SteamTools#889]
### 🐛 描述(Description)

win7运行2.6.4版本steam++时，最小化只能通过点击app上的最小化按钮或屏幕其他区域，点击底栏steam++图标没反应

### 📄 [异常/日志]信息([Exception/Log] )
无日志文件

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.6.4
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): github release

**Comment by AigioL** [comment]
确实点击之后没有最小化，这应该是 UI 库的 Bug，可能要在 Window 上处理窗口消息

https://docs.microsoft.com/en-us/archive/msdn-magazine/2009/brownfield/windows-7-taskbar-apis
https://stackoverflow.com/questions/963201/using-wndproc-in-c-sharp-to-minimize-form-on-leftclick-of-taskbar
