### ISSUE TITLE
🐛[BUG] ASF 在线配置文件生成器链接错误

### ISSUE THREAD

**Issue by wordlesswind** [BeyondDimension/SteamTools#890]
### 📷 复现步骤(Steps to Reproduce)

1. 切换到“自动挂卡”标签页
2. 点开配置菜单
3. 点击“在线配置文件生成器”条目

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.6.4
- 系统版本号(OS Version): Windows 11 Version 21H2 (Build 22000.434)
- 是否为应用商店版本(Whether it is a Store version): 是

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/9050713/149304878-0931d1f0-3cff-4cdb-ba27-0ecee37cb211.png)

**Comment by AigioL** [comment]
URL 应为 ```https://justarchinet.github.io/ASF-WebConfigGenerator```，已修复
