### ISSUE TITLE
🧐[Question] 社区加速 Invalid URL

### ISSUE THREAD

**Issue by Dearanlan** [BeyondDimension/SteamTools#893]
加速其他网站，例如pixiv、github等url都编程这样了，怎么解决

![image](https://user-images.githubusercontent.com/50802482/149348802-a99a51b5-baba-4fee-a58e-625a7a3d368a.png)

**Comment by DCxDESIGN** [comment]
我这里也同样，只有开二级代理才能正常使用

**Comment by Rems501** [comment]
![屏幕截图 2022-01-14 143113](https://user-images.githubusercontent.com/84369004/149462148-c0039cd0-e618-4021-b198-9707ab53fe54.png)
Pixiv 网页加载功能和自己头像出来了 但 图片和自己的关注无法显示

**Comment by Mossimos** [comment]
尝试更换代理设置中的 自定义DNS 试试

**Comment by Rems501** [comment]
已经搞定了 但 我想看的内容无法显示
![屏幕截图(9)](https://user-images.githubusercontent.com/84369004/149471052-8ad01d20-4fc4-4a2e-8553-751c41bb86af.png)

**Comment by Mossimos** [comment]
这种加载慢也可以尝试换其他dns解析。

**Comment by Rems501** [comment]
我已经尽力了 但 想看的内容无法同时还整了任务管理器
![屏幕截图 2022-01-14 161838](https://user-images.githubusercontent.com/84369004/149475466-0b5254fe-e98f-4c42-94af-d5b0e9477f9c.png)
![屏幕截图 2022-01-14 162344](https://user-images.githubusercontent.com/84369004/149475471-b1e9b991-56c7-4d01-94b1-e724e15a590c.png)
![屏幕截图 2022-01-14 162428](https://user-images.githubusercontent.com/84369004/149475473-7237751f-c8f1-4aef-96e5-595a2d43203a.png)

**Comment by Dearanlan** [comment]
我上一个版本还能完美运行来着，结果前几天更新了一下就不行了

**Comment by Rems501** [comment]
啥时候有更新
