### ISSUE TITLE
🐛[BUG] 账号绑定qq错误

### ISSUE THREAD

**Issue by 497662068** [BeyondDimension/SteamTools#895]
### 🐛 描述(Description)
绑定qq，登录我的qq之后，提示此账号已被绑定
uid：b2e9ed8c-dca5-49e4-b6ba-08d9d5c4348c
已成功绑定steam和xbox microsoft账号
操作时间大致为2022/1/14 16:00-18:30之间

### 📷 复现步骤(Steps to Reproduce)
1. 头像->个人资料->账号绑定->qq绑定
2. 跳转至qq网页，登录我的qq账号
3. 提示绑定成功，关闭网页
4. 我的账号绑定中qq仍然提示未绑定
5. 再次重复绑定步骤，登录qq，提示此qq已被绑定

### 📄 [异常/日志]信息([Exception/Log] Information)
错误url
https://api.steampp.net/ExternalLoginCallback?port=65077&sKey=bJc6oX0lBYA4MvUwExGbPZMkzjbpRlrMgPk_eY2B5Up9HihHFuayUrnX1CHB6l_nu1zWJi0Xdp4yxT8BR_IFZHzpmccMZngUruAXVBldEyVG9zNsQ1ofLOjzcNoxrNdxGyl-DfD83Gz7zSssvz7dIdClL0REDGJEuYOmOZjLRK57tOzNMLx2gXzZMVMEF7pX68Dky0--KNiA2mbgS4NELY64fiuN5tTStnwlTrJjbrUBGUdPStLZaO3RUlz4cL5y-N6Izb-pvPtm-nZ5HN0YV_Va3e7QtEuhRwJ7GdqzRdcxqqw1_qZ-ejJ3EgPRA1-WUy2zut_n9T043x5--DKgQg&sKeyPadding=SHA256&ver=Mi42LjQ&isBind=True

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version) :2.6.4 for Windows Desktop Bridge (x64)
- 系统版本号(OS Version): Windows 10.19044.1415
- 是否为应用商店版本(Whether it is a Store version): 是(Yes)

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/53845142/149501454-4feced0a-79cc-42f8-bb44-cd7c37b51058.png)
![image](https://user-images.githubusercontent.com/53845142/149501569-2ae0c4b4-a84d-47a5-8050-6375161d6eab.png)

**Comment by Mossimos** [comment]
提供下QQ号 我去数据库看看是不是已经注册过了

**Comment by AigioL** [comment]
> 提供下QQ号 我去数据库看看是不是已经注册过了

QQ号 应该在图中显示了，且 QQ 渠道没有返回 QQ 号的值

**Comment by AigioL** [comment]
可以先退出登录，再使用 Xbox 或 Steam 渠道快速登录，可能是绑定账号成功的结果没有从网页端传递到应用程序内导致的。
重新登录能同步一遍数据。

**Comment by 497662068** [comment]
qq绑定已经可以正常显示了，感谢大佬们
