### ISSUE TITLE
🧐[Question] 如何吧steampp上面的本地令牌转移到手机上

### ISSUE THREAD

**Issue by lspiritcoderl** [BeyondDimension/SteamTools#896]
### 🧐 问题描述(Description)
1. 手机是安卓系统，具体来说是小米的手机；
2. 由于没有root，选择了移除手机上令牌，在steampp上面添加本地令牌；
3. 但是添加后发现手机app上面并不会显示手机令牌；
3. 目前我想在手机app上也能够显示我的手机令牌，也就是本地和app上面都显示令牌，有什么解决办法么；
4. 如果无法做到，我想移除steampp上面的本地令牌，仍然使用手机app上面的令牌，可是我在steampp上面好像没找到取消令牌的按钮。

- 程序版本(Program Version):Windows 2.6.4版本
- 系统版本号(OS Version):  win10 20H2 专业版 内部版本 19042.1415
- 是否为应用商店版本(Whether it is a Store version):  github上直接下载

**Comment by rmbadmin** [comment]
小米手机用备份导出既可以保留原本手机令牌同时也导出到电脑一份，不需要用账号导入。
也可以选择用steam++手机版来手机电脑都同时有令牌。
解绑令牌只需要去steam网页端解绑令牌即可，不要先在本地移除

**Comment by lspiritcoderl** [comment]
感谢，目前已经解决问题。
不过还有一个疑惑，如果我想更换电脑，是否将旧电脑上的文件夹复制到新电脑，就能够实现所有数据的转移功能？

**Comment by cyb233** [comment]
> 感谢，目前已经解决问题。 不过还有一个疑惑，如果我想更换电脑，是否将旧电脑上的文件夹复制到新电脑，就能够实现所有数据的转移功能？

在未勾选本机加密的前提下可行，不过推荐导出备份文件

**Comment by lspiritcoderl** [comment]
呃，备份文件夹是哪个，appdata文件夹么
