### ISSUE TITLE
👑[能让网络加速支持主页留言或者讨论区] 

### ISSUE THREAD

**Issue by linsnowmm** [BeyondDimension/SteamTools#897]
### 🥰 需求描述(Description)
我是steam国区账号，无法使用主页留言和讨论区
希望网络加速之后可以使用讨论区或者主页留言板

**Comment by cyb233** [comment]
反代并不影响你的IP地址，无法解决Steam服务器端的行为

**Comment by Rems501** [comment]
外网加速以后会有改进吗

**Comment by linsnowmm** [comment]
> 反代不影响你的IP地址，无法解决Steam服务器端的行为

原来是这样的啊，谢谢
