### ISSUE TITLE
🐛[BUG] DLsite 网络加速出错

### ISSUE THREAD

**Issue by wordlesswind** [BeyondDimension/SteamTools#907]
### 🐛 描述(Description)

访问 [DLsite](https://www.dlsite.com/) 会被跳转至 [にじGAME](https://www.nijiyome.jp/)。
根据 SSL Labs 的[信息](https://www.ssllabs.com/ssltest/analyze.html?d=www.dlsite.com)来看，它必须启用 SNI 才能访问。

### 📷 复现步骤(Steps to Reproduce)

1. 网络加速勾选 DLsite
2. 开启网络加速
3. 访问 https://www.dlsite.com/

### 📄 [异常/日志]信息([Exception/Log] Information)
```
curl -v --ssl-no-revoke -I https://www.dlsite.com/
*   Trying 127.0.0.1:443...
* Connected to www.dlsite.com (127.0.0.1) port 443 (#0)
* schannel: disabled automatic use of client certificate
* schannel: ALPN, offering http/1.1
* ALPN, server did not agree to a protocol
> HEAD / HTTP/1.1
> Host: www.dlsite.com
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
HTTP/1.1 302 Found
< Content-Type: text/html; charset=iso-8859-1
Content-Type: text/html; charset=iso-8859-1
< Date: Wed, 19 Jan 2022 10:40:30 GMT
Date: Wed, 19 Jan 2022 10:40:30 GMT
< Location: https://www.nijiyome.jp/
Location: https://www.nijiyome.jp/
< Server: Apache
Server: Apache
< Connection: keep-alive
Connection: keep-alive
```

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.6.4
- 系统版本号(OS Version): Windows 11 Version 21H2 (Build 22000.466)
- 是否为应用商店版本(Whether it is a Store version): 是

### 🖼 截图(Screenshots)

![image](https://user-images.githubusercontent.com/9050713/150114916-1bb884b1-8f9b-4364-a8bf-4a84347b8908.png)
![image](https://user-images.githubusercontent.com/9050713/150115185-242dd001-2c8c-4d4e-a01b-4f04fc4b32aa.png)

**Comment by basket-ball** [comment]
我也有这个bug，我还以为我电脑中病毒自己跳转了呢。。

**Comment by cherinyy** [comment]
Steam++ 在新版本已移除支持
