### ISSUE TITLE
👑[Enhancement] 监听 IPv6 和支持 IPv6

### ISSUE THREAD

**Issue by wordlesswind** [BeyondDimension/SteamTools#908]
### 🥰 需求描述(Description)

鉴于 IPv6 部署持续推进，且 DNS 污染同样存在于 AAAA 记录，建议 Steam++ 监听 IPv6 和支持 IPv6。

### 🧐 解决方案(Solution)

1. hosts 除了`127.0.0.1`，还应该添加`::1`。
2. 支持转发流量至 IPv6 服务器。

**Comment by rmbadmin** [comment]
目前是支持转发到ipv6地址服务器的，监听地址也支持ipv6，
但hosts修改 ::1 感觉没有必要，其目的都只是为了将指定域名指向本机，加不加都是一样的。

这一块后续需要完善的是支持使用ipv6的dns进行dns解析和支持一下DNS over HTTPS
