### ISSUE TITLE
👑[Enhancement] 更改 deb 包信息中的软件类别

### ISSUE THREAD

**Issue by StarOnTheSky** [BeyondDimension/SteamTools#909]
### 🥰 需求描述(Description)
目前 Steampp Linux 版本使用 deb 安装以后，会在开始菜单中被分类到“未知分类”(KDE)下，建议将分类改为“游戏”或者“工具”。

### 🧐 解决方案(Solution)
暂无（我在源代码树中没找到 debian 打包控制文件）。

### 🚑 其他信息(Other Information)
![Screenshot_20220120_090216](https://user-images.githubusercontent.com/51866924/150243448-fe878003-a606-445d-806d-fb5e7618c307.png)

**Comment by AigioL** [comment]
DebSection 已改为 ```utils```

https://github.com/BeyondDimension/SteamTools/blob/develop/src/ST.Tools.Publish/Steps/Step_deb.cs#L130
