### ISSUE TITLE
🐛[BUG] steam++打开，然后启动steam，发现steam状态是在游戏中

### ISSUE THREAD

**Issue by maodouzi123** [BeyondDimension/SteamTools#910]
### 🐛 描述(Description)
 steam++打开，然后启动steam，发现steam状态是在游戏中，但是我本地都没有下载该游戏，导致我无法自动挂卡。

### 📷 复现步骤(Steps to Reproduce)

1. 打开steam++，启动加速，启动AFS
2. 启动steam
3. steam状态自动出现在游戏中

**Comment by rmbadmin** [comment]
检查一下你是否启用了程序启动时自动挂时长功能

**Comment by liper** [comment]
应该就是启动了挂时长的功能，我之前就是，纳闷为啥有一个游戏总在运行，但是我本地明明没有启动

**Comment by maodouzi123** [comment]
确实是打开了自动挂时长。。。这个功能貌似不太显眼，不小心点到了，藏在“库存游戏”这个菜单里
