### ISSUE TITLE
🧐[Question] 启用 Microsoft Store 的网络加速后，Xbox 应用的图片等资源无法正常加载

### ISSUE THREAD

**Issue by wordlesswind** [BeyondDimension/SteamTools#912]
### 🧐 问题描述(Description)

启用 Microsoft Store 的网络加速后，Xbox 应用的图片等资源无法正常加载

### 🚑 其他信息(Other Information)

![image](https://user-images.githubusercontent.com/9050713/150537235-a7ca9cb2-3c18-4a3a-b0c4-c97865a1b02d.png)
![image](https://user-images.githubusercontent.com/9050713/150537332-65a5ef5e-b5f4-4e90-b568-1acfee7da86b.png)

- 程序版本(Program Version): 2.6.4
- 系统版本号(OS Version): Windows 11 Version 21H2 (Build 22000.466)
- 是否为应用商店版本(Whether it is a Store version): 是

**Comment by final-pigrider** [comment]
这好像是因为微软对自己的uwp版应用添加了本地代理的屏蔽导致的，我是用clash的uwp loopback功能勾选上xbox应用后解决了
![image](https://user-images.githubusercontent.com/57496324/151694201-dfebcf07-0a34-4433-ba57-d831a42b5e67.png)
