### ISSUE TITLE
🐛[BUG] UI 布局错乱

### ISSUE THREAD

**Issue by zhangchi19** [BeyondDimension/SteamTools#915]
### 🐛 描述(Description)

点击左下角的关于后，再去点击网络加速，会出现UI错乱。
### 📷 复现步骤(Steps to Reproduce)

1. 点击左下角的关于
2. 点击网络加速
3. 大概率会出现错乱

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.6.4
- 系统版本号(OS Version): Windows 11 22000.466
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)

]
<img width="761" alt="1" src="https://user-images.githubusercontent.com/93179489/150622827-870916e6-927b-4b47-a535-8fa618ee89d8.png">

**Comment by AigioL** [comment]
这个问题有一段时间了，一直没找到原因，疑似与 DPI 缩放或无障碍有关
