### ISSUE TITLE
🧐[Question] 史低查询脚本无法使用

### ISSUE THREAD

**Issue by Awencf** [BeyondDimension/SteamTools#918]
### 🧐 问题描述(Description)
史低脚本无法使用，一直显示：正在读取历史最低价格，要么干脆什么也不显示，该开的加速都开了

### 🚑 其他信息(Other Information)

- 程序版本(Program Version):2.6.4
- 系统版本号(OS Version): windows10 1909
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by Awencf** [comment]
已解决，删除所有插件， 只装了史低  居然好了，有点奇怪。话说该怎么删帖啊。。。

**Comment by Mossimos** [comment]
脚本是没问题的 因为请求的外部API可能是API请求失败了
