### ISSUE TITLE
🧐[Question] Android Foreground Service

### ISSUE THREAD

**Issue by USTHzhanglu** [BeyondDimension/SteamTools#923]
### 🧐 问题描述(Description)
安卓端无法正常加速

当steam++加速处于后台时，会出现time out错误
只有使用小窗模式使steam++处于前台时才能正常加速
### 🚑 其他信息(Other Information)
后台运行权限已经打开，并且关闭了省电优化

此时处于后台，无法加速

![Screenshot_20220123_152514_com huawei browser](https://user-images.githubusercontent.com/56349457/150668857-7b34cdbb-7943-435c-bfe8-9568956f59b3.jpg)

置于前台后正常

![Screenshot_20220123_151927_net steampp app](https://user-images.githubusercontent.com/56349457/150668885-42e72058-95bf-41c7-b4c2-31426ba8131d.jpg)

- 程序版本(Program Version):2.6.4
- 系统版本号(OS Version): 安卓11/鸿蒙2.0
- 是否为应用商店版本(Whether it is a Store version): 否

**Comment by AigioL** [comment]
看起来加速开启的时候得开一个通知栏常驻来使应用在前台中运行
https://developer.android.google.cn/guide/components/foreground-services?hl=zh_cn

**Comment by AigioL** [comment]
fix adf1bf0d97680e02a65e6007bd3bfcbbcf4ec85a
