### ISSUE TITLE
🧐[Question] 切换到加速页面时出错

### ISSUE THREAD

**Issue by DCG-Xiulong** [BeyondDimension/SteamTools#925]
### 🧐 问题描述(Description)
切换到加速页面时出错，需要切换到其他页面再切换回加速页面才能正常使用
### 🚑 其他信息(Other Information)
![image](https://user-images.githubusercontent.com/61415058/150677206-a33d91c3-1106-4363-b8c5-f03bd3e4e858.png)
- 程序版本: v2.6.4
- 系统版本号: Windows 11 21H2 (OS内部版本 22000.438)

**Comment by AigioL** [comment]
与 #915 相同
