### ISSUE TITLE
🧐[Question] 历史最新低价格查询没办法使用怎么办？

### ISSUE THREAD

**Issue by Hamuda233** [BeyondDimension/SteamTools#926]
### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by WeNeedChinese** [comment]
加一，最近一直正在读取历史价格，没有显示。

**Comment by UltimateLin** [comment]
+1,一直显示正在读取历史最低价格。

**Comment by UltimateLin** [comment]
问题描述(Description)
使用Steam++中“Steam历史最低查询价格”脚本，在Steam中一直显示“正在读取历史最低价格...”

其他信息(Other Information)
程序版本(Program Version): v2.7.2
系统版本号(OS Version):21H1
是否为应用商店版本(Whether it is a Store version):

截图：
![A5@W%2Q$0VW%GB{(58JIN(P](https://user-images.githubusercontent.com/50756305/174277334-7a15a5c8-887c-47c0-881a-48f15fbfcd22.png)

**Comment by Mossimos** [comment]
https://api.augmentedsteam.com/v01/prices/?bundleids=&subids=631804,710689&appids=1761390&stores=steam&cc=cn&coupon=true
检查是否能正常访问此API

**Comment by UltimateLin** [comment]
访问以后显示如下：
![ET1 Y@TJX8$E}E}`7Q% WO](https://user-images.githubusercontent.com/50756305/174466564-a0ceae36-26d7-4396-9014-0944f809b51d.png)
请问是否算正常访问？

**Comment by Mossimos** [comment]
这样显示正常应该会正常显示才对

**Comment by rmbadmin** [comment]
> 这样显示正常应该会正常显示才对

之前有过类似的情况，就是因为GM没更新，跨域导致加载失败那个，你应该询问下他的控制台异常输出记录

**Comment by Mossimos** [comment]
@UltimateLin  请在  设置 -》 储存空间 -》 打开 Cache 文件夹 -》 Scripts 删除 然后重启 Steam++ 试试

**Comment by UltimateLin** [comment]
@Mossimos 你好，并没有用。

**Comment by UltimateLin** [comment]
你好，目前更新到2.8.1之后，我可以正常使用。

**Comment by XBY38426** [comment]
> 这样显示正常应该会正常显示才对

![image](https://github.com/BeyondDimension/SteamTools/assets/69497125/b4b24ec7-2b73-44a0-8cbf-139b17cda9b0)
您好，我这里显示这个怎么办啊QAQ

**Comment by XBY38426** [comment]
> 这样显示正常应该会正常显示才对

![image](https://github.com/BeyondDimension/SteamTools/assets/69497125/af92e327-bc4c-462a-8d8b-63e86bc5183b)
您好，我这里显示404no found怎么办啊QAQ
