### ISSUE TITLE
🐛[BUG] mega盘在steam++加速后并不能正常使用

### ISSUE THREAD

**Issue by fsoceityC** [BeyondDimension/SteamTools#931]
### 🐛 描述(Description)

使用steam++加速mega盘后，mega网站可以打开，但是文件分享链接不能正确被打开/下载
### 📷 复现步骤(Steps to Reproduce)

1.使用steam++加速mega 
2. 随便打开一个mega分享链接，比如这个https://mega.nz/file/XAFi3BpQ#s-s194zX-AC8I6Ov6yqAGL1bwCkyh6BIP1KrlBY0DX4
3. mega进度条卡住，多刷新几次后显示“MEGA failed to load .....”
4. 用翻墙软件可以正常访问此链接

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.6.4
- 系统版本号(OS Version): win10 20h2 19042.1466
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)
![image](https://user-images.githubusercontent.com/89299632/150737540-c77863e4-d42a-43ad-b512-9116b1a3ef40.png)
![image](https://user-images.githubusercontent.com/89299632/150737510-6e20f806-cd4c-4f21-babc-4f448a59074f.png)

**Comment by rmbadmin** [comment]
已热更新修复
