### ISSUE TITLE
🐛[BUG] Steam 账号切换失效

### ISSUE THREAD

**Issue by ArcherGilgam3sh** [BeyondDimension/SteamTools#955]
### 🐛 描述(Description)

2月1日steam更新后 steam++的一键登录账号出现了问题，
想要切换账号的时候仍会一键登录上一次登录的账号

### 📷 复现步骤(Steps to Reproduce)

1. 先正常登录一个steam账号
2. 然后一键登录另一个steam账号
3. 会发现登录的仍是前一个steam账号

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by shibuyameltdown** [comment]
我也这样

**Comment by Mossimos** [comment]
Steam Bate版会这样 ，因为新增了参数 需要修改 将在下次版本更新修复。
切换回正式版目前没问题。

**Comment by AigioL** [comment]
v2.6.5 已发布
