### ISSUE TITLE
使用本软件加速后steam社区能访问但讨论区还是进不去🧐[Question] 

### ISSUE THREAD

**Issue by zyzf233** [BeyondDimension/SteamTools#956]
### 🚑 其他信息(Other Information)

- 程序版本(Program Version):
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version):

**Comment by AigioL** [comment]
讨论区是根据 IP 判断的地区屏蔽，本地加速并不能改变 IP。
