### ISSUE TITLE
🐛[BUG] [待补充] 界面BUG 阵发性 可自行恢复

### ISSUE THREAD

**Issue by Ra2-IFV** [BeyondDimension/SteamTools#968]
# 注意！该issue仍亟待探索和补充！
### 🐛 描述(Description)
界面错乱，功能完全不可用，详情请见截图

### 📷 复现步骤(Steps to Reproduce)
1. 随意切换几次菜单即可触发（例：加速->设置->脚本->XXX），与切换速度似乎无关
2. 要恢复正常可再切换几次

### 📄 [异常/日志]信息([Exception/Log] Information)
无报错
重装Steam++无效，怀疑是系统问题
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): 2.6.4 64bit
- 系统版本号(OS Version): Windows 10 2004 专业工作站版
- 是否为应用商店版本(Whether it is a Store version):  No

### 🖼 截图(Screenshots
![屏幕截图 2022-02-03 190612](https://user-images.githubusercontent.com/96299096/152331335-af3944b2-4212-455d-8620-a6f0317a5333.png)
![屏幕截图 2022-02-03 190640](https://user-images.githubusercontent.com/96299096/152331337-c88d6125-1ff2-468f-a866-90573eba98ab.png)
![屏幕截图 2022-02-03 190545](https://user-images.githubusercontent.com/96299096/152331331-cc633803-0180-4c2d-85c1-304ffa58a71e.png)

**Comment by Ra2-IFV** [comment]
#915 已有的类似issue

**Comment by Ra2-IFV** [comment]
Update:与设置中的硬件加速选项有关，关了以后虽然卡的离谱，但没遇到过了

**Comment by AigioL** [comment]
> Update:与设置中的硬件加速选项有关，关了以后虽然卡的离谱，但没遇到过了

如果与硬件加速有关的话，可以更新显卡驱动之后在尝试

可以提供你的**显卡设备型号**与**驱动版本**以及 **DPI 缩放** 数据吗？

**Comment by Ra2-IFV** [comment]
> 可以提供你的**显卡设备型号**与**驱动版本**以及 **DPI 缩放** 数据吗？

Nvidia 七彩虹 2060s 
驱动511.23
DPI缩放是什么？

**Comment by AigioL** [comment]
> > 可以提供你的**显卡设备型号**与**驱动版本**以及 **DPI 缩放** 数据吗？
> 
> Nvidia 七彩虹 2060s 驱动511.23 DPI缩放是什么？

![image](https://user-images.githubusercontent.com/24450093/152756300-5d3cd656-5ce6-4a64-80de-3fa499431b44.png)
这个值

**Comment by Ra2-IFV** [comment]
> 这个值

100%
更新至2.6.5版本后此问题暂未出现，暂时关闭issue
