### ISSUE TITLE
关闭主窗口时首次询问退出或隐藏到托盘

### ISSUE THREAD

**Issue by Yang-qwq** [BeyondDimension/SteamTools#970]
### 🐛 描述(Description)

Ubuntu 20.04 点击关闭按钮后无法自动关闭窗口
必须使用`pkill -9 Steam++`强制关闭
### 📷 复现步骤(Steps to Reproduce)

1. 打开steam++（点击desktop文件）
2. 打开加速（代理模式），然后停止加速
3. 点击关闭按钮

ps: 在终端使用`Steam++`命令启动的时候，点击关闭按钮后窗口会自动消失，但是终端仍然处于阻塞状态，无法主动释放

```bash
yang@PC-Yang:~$ Steam++
(no output)

```

### 📄 [异常/日志]信息([Exception/Log] Information)
无
### 🚑 基本信息(Basic Information)

- 程序版本(Program Version): v2.6.4 a for Linux
- 系统版本号(OS Version): Ubuntu 20.04.2 LTS
- 是否为应用商店版本(Whether it is a Store version):  No

### 🖼 截图(Screenshots)

无

**Comment by AigioL** [comment]
主窗口关闭并不会退出程序，在托盘上右键退出才行

**Comment by Yang161941** [comment]
抱歉，之前没有注意到托盘上的图标
那可不可以考虑一下制作默认关闭策略？
比如说关闭主窗口的时候询问是直接关闭还是后台
