### ISSUE TITLE
显卡占用率过高

### ISSUE THREAD

**Issue by nvwangloli** [BeyondDimension/SteamTools#971]
![image](https://user-images.githubusercontent.com/31061624/152627367-8a00dfc8-e5f8-449e-956b-8fc57e7daa08.png)

虽然使用的是AMD 3500U的核显，但是这种GPU占用率还是太高了，建议优化显示界面GPU占用

**Comment by AigioL** [comment]
关闭主窗口后，GPU 占用率应该降至 0%，目前还没有解决方案可优化占用率，可以关闭界面设置中的透明效果，或使用 Mica 代替 亚克力效果。

也可禁用硬件加速，使用 CPU 渲染，这样就不会占用 GPU，但应该会卡顿掉帧。
