### ISSUE TITLE
是否会升级到.net 7？

### ISSUE THREAD

**Issue by wuliangtdi** [BeyondDimension/SteamTools#982]
.net 7 pre已经发布，且已经支持Native AOT,Avalonia是不包含com组件,会有计划进行Native AOT的工作嘛?

**Comment by AigioL** [comment]
还是有一些 COM+ 的组件的，且 COM+ 也有 Native 的方案，之前也发布过 AOT 版本的，但体积太大了，在裁剪功能还不太行的情况下，AOT 的方案还是不太好。

.NET 7 等接近 RC 了会考虑升级
