### ISSUE TITLE
🐛🐛[BUG] 2.6.5版本有重大bug，请勿更新（含解决方法）🐛🐛🐛🐛🐛

### ISSUE THREAD

**Issue by batvbs** [BeyondDimension/SteamTools#984]
### 🐛 描述(Description)

新版本**只能在C盘运行**，安装到其他位置无法运行，且可能导致**文件丢失**

### 📷 复现步骤A(Steps to Reproduce)

1. 下载2.6.5版本
2. 安装/解压到D盘
3. 双击steam++.exe，**无任何反应**，无窗口无进程无报错

### 📷 复现步骤B(Steps to Reproduce)

1. 安装2.6.4版本到D盘，打开
2. 点击更新2.6.5版，等待下载完成
3. 程序闪退，**steam++\AppData**文件夹以外的所有文件全部消失

### 📄 [异常/日志]信息([Exception/Log] Information)
logs文件夹无任何日志

### 🚑 基本信息(Basic Information)
- 程序版本(Program Version):2.6.5
- 系统版本号(OS Version): 
- 是否为应用商店版本(Whether it is a Store version): NO

### 🚑 临时解决方法
1. 复制**steam++**文件夹到C盘任意位置
2. 官网下载2.6.5版，安装到相同位置

**Comment by AigioL** [comment]
已发布 2.6.6 修复
