### ISSUE TITLE
🐛[BUG] 更新2.6.5版本后程序无法打开

### ISSUE THREAD

**Issue by flZeroQAQ** [BeyondDimension/SteamTools#987]
### 🐛 描述(Description)
在更新2.6.5版本后，程序出现打开后没有任何画面即崩溃的反应

### 📄 [异常/日志]信息([Exception/Log] Information)
.NET Runtime报告
Application: Steam++.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException: Source and destination path must have identical roots. Move will not work across volumes.
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at System.IOPath.FileSystemBase.InitFileSystemWithMigrations(String destAppDataPath, String destCachePath, String sourceAppDataPath, String sourceCachePath)
   at System.Application.FileSystemDesktopWindows.InitFileSystem()
   at System.Application.UI.Program.Main(String[] args)

Application Error报告
错误应用程序名称: Steam++.exe，版本: 2.6.5.0，时间戳: 0x61954b73
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.1503，时间戳: 0xb2acaea9
异常代码: 0xe0434352
错误偏移量: 0x0000000000034f69
错误进程 ID: 0x65b4
错误应用程序启动时间: 0x01d81cb39afd0221
错误应用程序路径: D:\Program Files\Steam++\Steam++.exe
错误模块路径: C:\WINDOWS\System32\KERNELBASE.dll
报告 ID: 2e0f28b2-750f-47b0-be1a-5da633f4ff7e
错误程序包全名: 
错误程序包相对应用程序 ID: 

Windows Error Reporting报告
故障存储段 1678778401399850844，类型 4
事件名称: APPCRASH
响应: 不可用
Cab ID: 0

问题签名:
P1: Steam++.exe
P2: 2.6.5.0
P3: 61954b73
P4: KERNELBASE.dll
P5: 10.0.19041.1503
P6: b2acaea9
P7: e0434352
P8: 0000000000034f69
P9: 
P10: 

附加文件:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE820.tmp.mdmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE8BE.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE8EE.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE8FB.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERE93B.tmp.txt

可在此处获取这些文件:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Steam++.exe_cd8ef290bc205ce663f1efff12adcc9160cca81d_eb71cb24_e5974546-36b5-499a-9719-790af5bcdfbf

分析符号: 
重新检查解决方案: 0
报告 ID: 2e0f28b2-750f-47b0-be1a-5da633f4ff7e
报告状态: 268435456
哈希存储段: 70ac5c6e3d81a08d174c380fc009475cnCab GUID: 0

### 🚑 基本信息(Basic Information)

- 程序版本(Program Version):2.6.5
- 系统版本号(OS Version): Windows 10 Professional 21H2 操作系统内部版本 19044.1503
- 是否为应用商店版本(Whether it is a Store version): 否

### 🖼 截图(Screenshots)

]
![QQ截图20220208142244](https://user-images.githubusercontent.com/94091036/152930092-27897d20-3296-4bdc-b31c-78250a603b3b.png)
![QQ截图20220208142403](https://user-images.githubusercontent.com/94091036/152930196-fb3221bc-6f50-46b3-9db3-41ab710f56a5.png)
![QQ截图20220208142414](https://user-images.githubusercontent.com/94091036/152930212-09a94a9a-738f-4616-85ac-ee280057864f.png)

**Comment by AigioL** [comment]
已在 2.6.7 中修复
对于之前版本启动过需要使用以下步骤手动修复，不然可能存在 丢失数据（可能发生在第二次启动程序时），比如登录状态，设置项，已下载的脚本，缓存的图片文件等

1. 升级至 2.6.7
2. 按 Win + R 键打开运行，输入 %LocalAppData%\Steam++ 回车，将此文件夹备份到其他目录后删除该目录
3. 输入 %Tmp%\Steam++ 同上操作

如果这两个文件夹为空文件夹就不会发生丢失数据的问题，可直接删除这两个空文件夹
